### ISSUE TITLE
emtrends() for interaction betweeen factors

### ISSUE THREAD

**Issue by rpmady** [rvlenth/emmeans#103]
I am looking to compare the slopes in an interaction between treatment and location. Treatment has 4 factor levels and location has 2. I found emtrends(), but this only seems to work for when a numerical predictor interact with another. I'm at a loss for how to compare the slopes of the treatment*location interaction.

**Comment by rvlenth** [comment]
Please see `vignette("interactions")`, or its online rendering https://cran.r-project.org/web/packages/emmeans/vignettes/interactions.html

**Comment by rpmady** [comment]
Thanks for that link, but I did look there and I can't seem to find anything about comparing the slopes of the interaction between 2 categorical variables.

**Comment by rvlenth** [comment]
The word "slope" has to do with a relationship between numeric variables. So technically, your question needs to be reworded into something about differences of differences. I suggest you actually read the vignette. Look in particular at the section on interaction contrasts.

**Comment by rpmady** [comment]
I was not thinking about slope correctly, thank you for steering me in the right direction. And as someone very new to this, that section on interaction contrasts is hard for me to understand. Like you said, I'm interested in in the difference of differences (great to know now!) and I'm still struggling to figure that out. 

I produced this figure, 
![image](https://user-images.githubusercontent.com/42630011/56505869-cd3d9200-64ea-11e9-9b40-91d9b0ef5bb1.jpg)

using the emmip function:
```
emmip(mod5, trtmt~location)
```
The plot helps me see what is going on, but I want to be able to say whether the differences of differences are actually different. 

When I use the contrast() function and try to get the "difference of differences." The most recent code I've come up with is: 
```
tl.emm <- contrast(mod5.emm, interaction = c("poly","consec"), by = NULL)
```
that produces: 
```
 location_poly trtmt_consec                estimate    SE  df t.ratio p.value
 linear        constant - control              2.52 0.742 189  3.400  0.0008 
 linear        pulsed_food - constant          0.71 0.507 189  1.400  0.1631 
 linear        pulsed_nofood - pulsed_food    -1.71 0.623 189 -2.742  0.0067 

Results are given on the log (not the response) scale. 
```
I don't understand why the constant - pulsed_nofood was left out.

**Comment by rvlenth** [comment]
Well, let's look at the logic behind this. I don't see the code that produced `mod5.emm`, but evidently it produces the EMMs for `location` and `trtmt`. So in your `contrast()` call, the argument `interaction = c("poly","consec")` specifies polynomial constasts for `location` and comparisons of consecutive levels of `trtmt` -- so that's what it did, and it omitted `constant - pulsed_nofood` because those levels aren't consecutive.

If you do `? consec.emm` you will see documentation on all the built-in contrast families. You can choose other options, for example `"pairwise"`. What I'd have suggested would be
```
contrast(mod5.emm, interaction = "revpairwise")
```
which would do pairwise comparisons in reverse order for both factors. (I don't think you needed `by = NULL`, unless there was a `by` variable in effect when you created `mod5.emm`.) I believe that if you think carefully about what each argument in these R calls is for, you will be better able to obtain the results you need. Examples are helpful, but often you can't just copy them verbatim.

**Comment by rpmady** [comment]
Okay, that makes sense. I couldn't figure out what "consec" stood for. And thank you for directing me to ?consec.emm that helps to see all of the options. 

I think your suggestion is just what I need! I originally also incorrectly had ```trtmt|location``` when it should be ```trtmt:location```. 

 This is my code that produced ```mod5.emm```
```
mod5.emm <- emmeans(mod5, trtmt: location)
```
And now, using the code ```contrast(mod5.emm, interaction = "revpairwise")``` I get: 
```
 trtmt_revpairwise           location_revpairwise estimate    SE  df t.ratio p.value
 constant - control          near - far              2.524 0.742 189  3.400  0.0008 
 pulsed_food - control       near - far              3.234 0.808 189  4.001  0.0001 
 pulsed_food - constant      near - far              0.710 0.507 189  1.400  0.1631 
 pulsed_nofood - control     near - far              1.525 0.827 189  1.844  0.0667 
 pulsed_nofood - constant    near - far             -0.999 0.535 189 -1.866  0.0635 
 pulsed_nofood - pulsed_food near - far             -1.709 0.623 189 -2.742  0.0067 

Results are given on the log (not the response) scale.
```
This changes to be:
```
trtmt_revpairwise           location_revpairwise  ratio     SE  df t.ratio p.value
 constant / control          near / far           12.482  9.266 189  3.400  0.0008 
 pulsed_food / control       near / far           25.383 20.518 189  4.001  0.0001 
 pulsed_food / constant      near / far            2.034  1.031 189  1.400  0.1631 
 pulsed_nofood / control     near / far            4.596  3.801 189  1.844  0.0667 
 pulsed_nofood / constant    near / far            0.368  0.197 189 -1.866  0.0635 
 pulsed_nofood / pulsed_food near / far            0.181  0.113 189 -2.742  0.0067 

Tests are performed on the log scale 
```
when I revise the code to be : ```mod5.emm <- emmeans(mod5, ~ trtmt:location, type = "response", adjust = "mvt")```

So, it looks like the interaction treatment*location is only significantly different between 
constant and control, pulsed_food and control, and pulsed_nofood and pulsed_food. the others are not significant.

**Comment by rvlenth** [comment]
OK, though I really, really don't like the tradition of declaring things of "significant" or not based on a seemingly magical threshold of P < .05. There really isn't a law of nature saying that P = .0667 is unimportant. And it certainly doesn't mean that there is no difference.

**Comment by rpmady** [comment]
I agree, that threshold p <0.5 isn't magical. That's more just preliminary take on the data. I will take biological significant and effect size into account when reporting the results. 

I don't think that's "real" because I have no idea what the error bars around those look like and I'm not sure about the scale on the y-axis for that plot.

**Comment by rvlenth** [comment]
You *do* know what the scale is. It's the log of the response variable. And the error bars don't tell you the story about how those location differences compare; the tests you just did serve that purpose.

**Comment by rpmady** [comment]
Okay, the scale of the y-axis is the log(response variable). The results of the tests, I think, didn't indicate there was any real difference between the two.

**Comment by rpmady** [comment]
@rvlenth I've appreciated all of your help with this. To solidify this, I'm trying to understand just what is going on to when I run the code that produces the estimates in the output below. I've tried to locate the answer before posting here, but there isn't any documentation that I can find that explains what is going on in the backend when the code ```contrast(object, interaction="revpairwise")``` is run. 
```
mod3.emm <- emmeans(mod3, ~ trtmt:location, adjust = "mvt")
contrast(mod3.emm, interaction="revpairwise")

trtmt_revpairwise           location_revpairwise estimate    SE  df t.ratio p.value
 pulsed_food - constant      near - far              0.781 0.801 125  0.975  0.3314 
 pulsed_nofood - constant    near - far             -1.323 0.750 125 -1.765  0.0801 
 pulsed_nofood - pulsed_food near - far             -2.104 1.010 125 -2.084  0.0392 

```

**Comment by rvlenth** [comment]
I think one source of confusion is in not looking at the estimates whose contrasts are being computed. So I suggest going one step at a time: 

First, get the changes due to treatment (slopes of the lines in your plot) (BTW, what happened to `control` -- no longer present?)
```
emm= emmeans(mod3, ~ location | treatment)
emm ### look at the estimates. These are what the model predicts

locdiffs = contrast(emm, "revpairwise")
locdiffs ### look at the estimates. These are the changes.
```
These used `treatment` as a `by` variable which is remembered. I want to compare these differences, so I need to disable the `by`:
```
contrast(locdiffs, "revpairwise", by = NULL)
```
These last results are the same as the interaction contrasts.

I am going to close this issue, as I feel that I have maxed out on these questions. I do have vignettes with lots of examples, and those are intended to help users navigate the features of the package. I know that some users are more statistically experienced than others, but there's a point I need to ask people to find some other person, e.g., a statistical consulting service on their campus, when they need additional help.

**Comment by rpmady** [comment]
Thank you for elaborating and I understand the closing of the issue. Thank you for your help and breaking down those steps, it does help a lot. For some reason, using the examples in the vignettes didn't help me see that the above steps would be the most appropriate. 

Just so that you are aware, when I do it the way you just did it, my p-values increase compared to when I used the interaction contrast. I wonder if that is because constrast() is run twice in the way above, so the p-values get corrected more.

**Comment by rpmady** [comment]
@rvlenth in case you don't get notifications, I wanted to make sure you saw my last comment.
