### ISSUE TITLE
Error with brms ordinal model

### ISSUE THREAD

**Issue by PhoenixB** [rvlenth/emmeans#104]
Dear Russell

I fitted a ordinal model with three fixed factors with interactions and one random factor with brms cumulative family:

> summary(model)
>  Family: cumulative
>   Links: mu = logit; disc = identity
> Formula: answer ~ 1 + face + disfigurement + situation + situation:disfigurement + situation:face + face:disfigurement + face:situation:disfigurement + (1 | participant_id)

When I'm trying to do `emmeans(model, "disfigurement")`, it yields the following error:

> Error in vcov(object)[nm, nm, drop = FALSE] : subscript out of bounds
> In addition: Warning message:
> In model.matrix.default(trms, m, contrasts.arg = contr) :
>   variable 'answer' is absent, its contrast will be ignored

Can I do something about this?

Kindest regards,
Pascal

**Comment by rvlenth** [comment]
**brms** is a complex package, and **emmeans** support for it is pretty rudimentary. And ordinal models require special coding to account for thresholds and an implied multivariate response. I think, in terms of **emmeans** support, your best bet is to try fitting the equivalent model using `ordinal::clmm()`. There are options provided for whether you want the results in terms of the latent variable, probabilities for the ordinal response, etc.

FYI I am looking at expanding **MCMCglmm** support in a way that may help with this kind of model, and would provide a Bayesian option. But I am not there yet.

**Comment by rvlenth** [comment]
I'm closing this issue as it is unlikely that I will be able to support **brms** more fully than it is now. It'd help a lot of the developer of that package had an interest in adding **emmeans** and supporting functionality. I'd be happy to help facilitate that.
