### ISSUE TITLE
Consider supporting negative deltas in test of noninferiority

### ISSUE THREAD

**Issue by wdkrnls** [rvlenth/emmeans#106]
I would like to test that one treatment is better than another treatment by more than some practical amount. If I could use a negative delta, it seems as though this would be a noninferiority test. But it appears delta always uses the absolute value.

**Comment by rvlenth** [comment]
What you describe is not a non-inferiority test. It may be termed a "super-superiority test" or some such. It is still possible to do in **emmeans**. For example, if you want to test that a difference exceeds zero by at least 0.6, use something like this:
```r
(emm <- emmeans(my model, "treatment"))
comps <- pairs(emm)
test(comps, side = ">", null = 0.6)
```
I think this is less confusing than would be allowing negative `delta`.

That's how you do it. However, I question the value of such a super-superiority test. I have seen some literature (primarily in the social sciences) suggesting things like this, on the premise that "of course we know that the true difference can't be exactly zero, so it's silly to test that. Instead, the null hypothesis should be composite." 

I equate this with "shooting yourself in the foot." A hypothesis is just a hypothetical statement. If the null hypothesis is not rejected, it is really important to understand that that does *not* mean it is accepted; it simply means we can't prove it wrong. It is a mistake to take hypotheses literally, and by insisting on testing super-superiority, you are unnecessarily sacrificing power.

I believe I have answered the question, so am closing this issue. However, that does not keep you from commenting, and it can be re-opened if appropriate.
