### ISSUE TITLE
The pairs function doesn't explicitly state tukey adjustment 

### ISSUE THREAD

**Issue by dshelldhillon** [rvlenth/emmeans#110]
I'm running into another issue with Tukey!  Till yesterday everything was working fine, but for some other reasons, I had to re-install R and R studio (I was trying to develop a package and it kept failing). 

I came back to my project and re-installed emmeans (version 1.3.4), and when I run a simple linear model and try to run tukey comparisons, it now doesn't explicitly state which adjustment was done.  

Even when I change it to 'bonferroni', I don't get a message saying bonferroni adjustmnet is being used.  

```r
library(tidyverse)
library(emmeans)
outcome <- rnorm(12,0,1)
fac1 <- c("A","A","A","B","B","B","A","A","A","B","B","B")
fac2 <- c(rep("0",6),rep("25",6))


df <- cbind(fac1, fac2) %>% tbl_df %>%
  cbind(outcome)


## Run model  
m <- lm (outcome ~ fac1*fac2, data = df)

emm <- emmeans :: emmeans(m, ~fac1*fac2)
pairs(emm, simple = "each", adjust = "tukey")
#> $`simple contrasts for fac1`
#> fac2 = 0:
#>  contrast estimate    SE df t.ratio p.value
#>  A - B        1.56 0.851  8  1.833  0.1041 
#> 
#> fac2 = 25:
#>  contrast estimate    SE df t.ratio p.value
#>  A - B       -1.08 0.851  8 -1.265  0.2413 
#> 
#> 
#> $`simple contrasts for fac2`
#> fac1 = A:
#>  contrast estimate    SE df t.ratio p.value
#>  0 - 25       1.35 0.851  8  1.581  0.1525 
#> 
#> fac1 = B:
#>  contrast estimate    SE df t.ratio p.value
#>  0 - 25      -1.29 0.851  8 -1.517  0.1676
pairs(emm, simple = "each", adjust = "bonferroni")
#> $`simple contrasts for fac1`
#> fac2 = 0:
#>  contrast estimate    SE df t.ratio p.value
#>  A - B        1.56 0.851  8  1.833  0.1041 
#> 
#> fac2 = 25:
#>  contrast estimate    SE df t.ratio p.value
#>  A - B       -1.08 0.851  8 -1.265  0.2413 
#> 
#> 
#> $`simple contrasts for fac2`
#> fac1 = A:
#>  contrast estimate    SE df t.ratio p.value
#>  0 - 25       1.35 0.851  8  1.581  0.1525 
#> 
#> fac1 = B:
#>  contrast estimate    SE df t.ratio p.value
#>  0 - 25      -1.29 0.851  8 -1.517  0.1676


sessionInfo()
#> R version 3.5.3 (2019-03-11)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 16299)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] emmeans_1.3.4   forcats_0.4.0   stringr_1.4.0   dplyr_0.8.1    
#>  [5] purrr_0.3.2     readr_1.3.1     tidyr_0.8.3     tibble_2.1.1   
#>  [9] ggplot2_3.1.1   tidyverse_1.2.1
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.1       cellranger_1.1.0 pillar_1.4.0     compiler_3.5.3  
#>  [5] highr_0.8        plyr_1.8.4       tools_3.5.3      digest_0.6.19   
#>  [9] lubridate_1.7.4  jsonlite_1.6     evaluate_0.13    nlme_3.1-137    
#> [13] gtable_0.3.0     lattice_0.20-38  pkgconfig_2.0.2  rlang_0.3.4     
#> [17] cli_1.1.0        yaml_2.2.0       mvtnorm_1.0-10   haven_2.1.0     
#> [21] xfun_0.7         withr_2.1.2      xml2_1.2.0       httr_1.4.0      
#> [25] knitr_1.23       hms_0.4.2        generics_0.0.2   grid_3.5.3      
#> [29] tidyselect_0.2.5 glue_1.3.1       R6_2.4.0         readxl_1.3.1    
#> [33] rmarkdown_1.13   modelr_0.1.4     magrittr_1.5     backports_1.1.4 
#> [37] scales_1.0.0     htmltools_0.3.6  rvest_0.3.4      assertthat_0.2.1
#> [41] xtable_1.8-4     colorspace_1.4-1 estimability_1.3 stringi_1.4.3   
#> [45] lazyeval_0.2.2   munsell_0.5.0    broom_0.5.2      crayon_1.3.4
```

**Comment by dshelldhillon** [comment]
Interestingly, when I run this 
```r
summary(pairs(ref_grid(m)))
```
The output says tukey adjusmtment.  However, this is adjusting for more comparisons than I want to.  
I want to adjust for each pairwise comparison of one factor, at each level of the other factors.

**Comment by dshelldhillon** [comment]
Aha! I think I know why, there's just one comparison at each level so no need for an adjustment!

**Comment by rvlenth** [comment]
Hmmm, I responded to this earlier, via e-mail but I don't see it here... Anyway, you figured it out.

**Comment by rvlenth** [comment]
There’s only one comparison in each set, so there is no multiplicity to adjust for!

Sent from my iPhone

On May 30, 2019, at 2:39 PM, Dilsher Singh Dhillon <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm running into another issue with Tukey! Till yesterday everything was working fine, but for some other reasons, I had to re-install R and R studio (I was trying to develop a package and it kept failing).

I came back to my project and re-installed emmeans (version 1.3.4), and when I run a simple linear model and try to run tukey comparisons, it now doesn't explicitly state which adjustment was done.

Even when I change it to 'bonferroni', I don't get a message saying bonferroni adjustmnet is being used.

library(tidyverse)
library(emmeans)
outcome <- rnorm(12,0,1)
fac1 <- c("A","A","A","B","B","B","A","A","A","B","B","B")
fac2 <- c(rep("0",6),rep("25",6))


df <- cbind(fac1, fac2) %>% tbl_df %>%
  cbind(outcome)


## Run model
m <- lm (outcome ~ fac1*fac2, data = df)

emm <- emmeans :: emmeans(m, ~fac1*fac2)
pairs(emm, simple = "each", adjust = "tukey")
#> $`simple contrasts for fac1`
#> fac2 = 0:
#>  contrast estimate    SE df t.ratio p.value
#>  A - B      -0.677 0.919  8 -0.737  0.4824
#>
#> fac2 = 25:
#>  contrast estimate    SE df t.ratio p.value
#>  A - B      -0.435 0.919  8 -0.473  0.6487
#>
#>
#> $`simple contrasts for fac2`
#> fac1 = A:
#>  contrast estimate    SE df t.ratio p.value
#>  0 - 25     -0.855 0.919  8 -0.930  0.3795
#>
#> fac1 = B:
#>  contrast estimate    SE df t.ratio p.value
#>  0 - 25     -0.613 0.919  8 -0.667  0.5237
