### ISSUE TITLE
Error when generating marginal effects from brms model of the form y ~ 0 + intercept + x

### ISSUE THREAD

**Issue by Kriaese** [rvlenth/emmeans#113]
Dear Russell,

I am trying to obtain marginal effects using `emmeans` and `tidybayes` from a `brms` model with a prior on the real intercept and thus a model of the form `y ~ 0 + intercept + x`. However, this results in the following error:

```
Error in vcov(object)[nm, nm, drop = FALSE] : subscript out of bounds
Called from: emm_basis.brmsfit(object, trms, xlev, grid, ...)
```
Here’s a quick example (with mostly unchanged defaults) using the `warpbreaks` data set.

```
library(emmeans)
library(tidybayes)
library(magrittr)
library(brms)

set.seed(123)

# All seems to works here:
Model1 <- brm(breaks ~ tension,
              data = warpbreaks)

Model1 %>%
  emmeans(~ tension) %>%
  gather_emmeans_draws() %>%
  mean_qi()

# A tibble: 3 x 7
# tension .value .lower .upper .width .point .interval
# <fct>    <dbl>  <dbl>  <dbl>  <dbl> <chr>  <chr>    
# L         36.4   30.9   42.0   0.95 mean   qi       
# M         26.2   20.6   31.7   0.95 mean   qi       
# H         21.6   16.1   27.2   0.95 mean   qi 
 
# Error occurs here:
Model2 <- brm(breaks ~ 0 + intercept + tension,
              data = warpbreaks)

Model2 %>%
  emmeans(~ tension) %>%
  gather_emmeans_draws() %>%
  mean_qi()

#Error in vcov(object)[nm, nm, drop = FALSE] : subscript out of bounds
#Called from: emm_basis.brmsfit(object, trms, xlev, grid, ...)
```

It seems the error has to do with how the internally generated variable `intercept` is handled, which might require special coding (similar to #104 ).

**Comment by rvlenth** [comment]
Actually, it is an oddity in the names assigned by `brm` vis a vis those used later:
```r
# In the code:
    nm = eval(parse(text = "brms:::rename(colnames(X))"))
    V = vcov(object)[nm, nm, drop = FALSE]

# what we get:
Browse[2]> nm
[1] "intercept" "tensionL"  "tensionM"  "tensionH" 

Browse[2]> vcov(object)
          intercept  tensionM  tensionH
intercept  7.954110 -7.931893 -7.787033
tensionM  -7.931893 15.631325  7.807514
tensionH  -7.787033  7.807514 15.885689
```
So you see that I ask the package to tell me the names and to return the variance-covariance matrix, but the package is inconsistent with itself. That's kinda annoying.

I think I should probably just use the empirical cavariance of the posterior sample anyway, since we realkly don't need this result at all except in a frequestist summary.

I am traveling as I write and will not be able to do anything more with this until late June 2019.

**Comment by Kriaese** [comment]
Aha I see - many thanks for your prompt reply! Looking forward to your fix and happy traveling!

**Comment by rvlenth** [comment]
I'm closing this issue as it is unlikely that I will be able to support **brms** more fully than it is now. It'd help a lot of the developer of that package had an interest in adding **emmeans** and supporting functionality. I'd be happy to help facilitate that.
