### ISSUE TITLE
adding colors to plot in function of the fixed effects levels

### ISSUE THREAD

**Issue by diegogradosb** [rvlenth/emmeans#117]
First of all, thanks for such a nice package. I wonder if it is possible to change the colors of the points in function of the fixed effects levels?

This is my comparison:
`output<- emmeans(nonlinear.mixed.model, pairwise~treatment, adjust = "Dunnett", param="parameter1")`

I was trying this:
`plot1 <- plot(output, adjust = "Dunnett", intervals = TRUE, colour=aes(treatment)) + coord_flip() `
`plot1 <- plot(output, adjust = "Dunnett", intervals = TRUE, colour=aes(pri.fac)) + coord_flip() `

I read this issue https://github.com/rvlenth/emmeans/issues/28 but could find a solution yet.

**Comment by rvlenth** [comment]
The `color` or `colour` specification has to go *outside* of the `plot()` call:
```
g <- plot(output, adjust = "Dunnett", intervals = TRUE)
g + aes(color = pri.fac) + coord_flip()
```
Better yet, give the name of the actual primary factor (`treatment` or whatever it is.

**Comment by diegogradosb** [comment]
Thanks! It worked perfectly.
