### ISSUE TITLE
emmeans 1.3.5 throws crossprod error with gls corSymm

### ISSUE THREAD

**Issue by tcb2** [rvlenth/emmeans#119]
[TTE-v2.xlsx](https://github.com/rvlenth/emmeans/files/3322722/TTE-v2.xlsx)

```
`require('nlme')
require('emmeans')

gdata <- read.csv("TTE-v2.xlsx")

cat("\nm1\n")
m1 <- gls(score~group+visit+group*visit, data=gdata,
correlation=corCAR1(form=~visit|subject))
lsmeans(m1, pairwise~group,adjust="none")

cat("\nm2\n")
m2 <- gls(score~group+visit+group*visit, data=gdata,
correlation=corCompSymm(form=~visit|subject))
lsmeans(m2, pairwise~group,adjust="none")

cat("\nm3\n")
m3 <- gls(score~group+visit+group*visit, data=gdata,
correlation=corSymm(form=~1|subject))
lsmeans(m3, `pairwise~group,adjust="none")``
```

Running the above code (will need to convert attached xlsx file to csv) yields the following from emmeans version 1.3.5:

m1
NOTE: Results may be misleading due to involvement in interactions
$lsmeans
 group lsmean    SE   df lower.CL upper.CL
 p       1.23 0.186 51.1    0.857     1.60
 q       1.77 0.190 51.1    1.385     2.15

Results are averaged over the levels of: visit 
d.f. method: satterthwaite 
Confidence level used: 0.95 

$contrasts
 contrast estimate    SE   df t.ratio p.value
 p - q      -0.537 0.266 51.1 -2.018  0.0489 

Results are averaged over the levels of: visit 

m2
NOTE: Results may be misleading due to involvement in interactions
$lsmeans
 group lsmean    SE   df lower.CL upper.CL
 p       1.23 0.206 39.1    0.813     1.65
 q       1.77 0.211 39.1    1.339     2.19

Results are averaged over the levels of: visit 
d.f. method: satterthwaite 
Confidence level used: 0.95 

$contrasts
 contrast estimate    SE   df t.ratio p.value
 p - q      -0.537 0.295 39.1 -1.817  0.0768 

Results are averaged over the levels of: visit 

m3
NOTE: Results may be misleading due to involvement in interactions
Error in crossprod(x, y) : 
  requires numeric/complex matrix/vector arguments
Calls: <Anonymous> ... apply -> FUN -> <Anonymous> -> tcrossprod -> crossprod

But with emmeans 1.3.2, the following:

$lsmeans
 group lsmean    SE  df lower.CL upper.CL
 p       1.23 0.186 234    0.864     1.60
 q       1.77 0.190 234    1.392     2.14

Results are averaged over the levels of: visit 
Confidence level used: 0.95 

$contrasts
 contrast estimate    SE  df t.ratio p.value
 p - q      -0.537 0.266 234 -2.018  0.0448 

Results are averaged over the levels of: visit 

m2
NOTE: Results may be misleading due to involvement in interactions
$lsmeans
 group lsmean    SE  df lower.CL upper.CL
 p       1.23 0.206 234    0.824     1.64
 q       1.77 0.211 234    1.350     2.18

Results are averaged over the levels of: visit 
Confidence level used: 0.95 

$contrasts
 contrast estimate    SE  df t.ratio p.value
 p - q      -0.537 0.295 234 -1.817  0.0704 

Results are averaged over the levels of: visit 

m3
NOTE: Results may be misleading due to involvement in interactions
$lsmeans
 group lsmean    SE  df lower.CL upper.CL
 p       1.23 0.158 234    0.919     1.54
 q       1.77 0.162 234    1.448     2.09

Results are averaged over the levels of: visit 
Confidence level used: 0.95 

$contrasts
 contrast estimate    SE  df t.ratio p.value
 p - q      -0.537 0.226 234 -2.371  0.0186 

Results are averaged over the levels of: visit

**Comment by rvlenth** [comment]
The difference is that the Satterthwaite method for df was added and became the default. You may reproduce the results from the earlier version via
```r
lsmeans(m3, pairwise ~ group, adjust="none", mode = "df.error")
```
See https://cran.r-project.org/web/packages/emmeans/vignettes/models.html, section K.

I will see if I can make the code more robust or try to trap whatever is causing the error.

**Comment by rvlenth** [comment]
The problem is that `m3` has no `apVar` member:
```r
> m2$apVar
           corStruct      lSigma
corStruct 0.06146714 0.017123004
lSigma    0.01712300 0.006904627
attr(,"Pars")
corStruct    lSigma 
0.9657762 0.1044992 
attr(,"natural")
[1] TRUE

> m3$apVar
[1] "Non-positive definite approximate variance-covariance"
```
`apVar` is the covariance matrix of the random effects, and is needed for the Satterthwaite calculations. I don't fully understand why it is missing for `m3`, other than I guess it just can't estimate that matrix.
Apparently I will have to check for whether there is a valid `apVar` member when in Satterthwaite mode. I'll let you know if I find a fix.

**Comment by rvlenth** [comment]
Turned out to be a very easy repair. I was already testing `is.null(object$apVar)`; just changed it to `!is.matrix(object$apVar)`.

**Comment by tcb2** [comment]
TY
