### ISSUE TITLE
emmeans with variables not in a data.frame

### ISSUE THREAD

**Issue by mgondan** [rvlenth/emmeans#12]
Dear maintainers of emmeans,

This is working:

> dv = rnorm(100)
> iv = rbinom(100, 1, 0.5)
> d = data.frame(dv, iv) 
> m = lm(dv ~ iv, data=d) 
> emmeans(m, ~iv)
    iv      emmean       SE df   lower.CL  upper.CL
  0.56 -0.09024097 0.102466 98 -0.2935815 0.1130996  
Confidence level used: 0.95

However, this fails:

> dv = rnorm(100)
> iv = rbinom(100, 1, 0.5)
> m = lm(dv ~ iv)
> emmeans(m, ~iv)
Error in recover_data.call(fcall, delete.response(terms(object)), object$na.action,  : 
  object 'possibly.random' not found
Error in ref_grid(object, ...) : 
  Perhaps a 'data' or 'params' argument is needed

It seems that emmeans wants all the data in a data.frame. I see that the data.frame variant covers 
probably 99% of the use cases, though, but maybe it is only a small thing to fix...

Best regards,

Matthias

**Comment by rvlenth** [comment]
Thanks. I am aware of this (see Issue #11) and the version now on github has this bug fixed. It was simply an uninitialized logical variable. I will be sending an update to CRAN in the next week or two.

**Comment by mgondan** [comment]
Ah, good, thanks!

Best wishes,

Matthias


Von: Russell V. Lenth<mailto:notifications@github.com>
Gesendet: Montag, 8. Januar 2018 21:03
An: rvlenth/emmeans<mailto:emmeans@noreply.github.com>
Cc: Matthias Gondan<mailto:matthias.gondan@psy.ku.dk>; Author<mailto:author@noreply.github.com>
Betreff: Re: [rvlenth/emmeans] emmeans with variables not in a data.frame (#12)


Thanks. I am aware of this (see Issue #11<https://github.com/rvlenth/emmeans/issues/11>) and the version now on github has this bug fixed. It was simply an uninitialized logical variable. I will be sending an update to CRAN in the next week or two.
