### ISSUE TITLE
The `mvt` adjustment for adjusted least square means   

### ISSUE THREAD

**Issue by dshelldhillon** [rvlenth/emmeans#120]
This is not an issue, but more of a question regarding the mvt adjustment.   I would like to get adjusted confidence intervals for individual factor levels when running a one-way ANOVA.  I know we can't get tukey intervals because those are for pairwise comparisons.   

I'm convinced by the mvt method of adjustment, however my manager being not a R user isn't quite aware of that.   

My question is, is there a good reference to justify the use of mvt method?  Currently she uses statgraphics which has a `tukey adjusted` interval but honestly I don't know how it does that.   

Is there a good reference/justification i can use for the mvt?  Bonferroni would be another option but that becomes too conservative with more levels.    

Thank you!!

**Comment by rvlenth** [comment]
The `"mvt"` adjustment is exact when the joint distribution of the estimates is multivariate normal and the appropriately scaled *t* statistics are multivariate *t*. But it is pretty taxing computationally and the algorithm involves randomization, so the results will vary slightly if repeated. The Bonferroni-corrected intervals would indeed be conservative, and that conservatism gets worst as the number of levels increases. If the correlations are not high among the estimates, the `"scheffe"` option might be a better choice.

For details, one place to look is the vignette "Simultaneous Inference in General Parametric Models" provided in the **multcomp** package: https://cran.r-project.org/web/packages/multcomp/vignettes/generalsiminf.pdf. 

See also the references in the documentation for `mvtnorm::pmvt`. Most are about computation but Kotz and Narajah is a methodology reference.

**Comment by rvlenth** [comment]
I believe this issue is resolved.
