### ISSUE TITLE
Check for additional funtions in recover_data() results in failed all(...) comparisons in presence of missing data

### ISSUE THREAD

**Issue by tobadia** [rvlenth/emmeans#121]
Hi,

In `recover_data()`, whenever the call that is evaluated contains "funny" stuffs (in my case some dplyr `%>%`as well as functions e.g. `filter`, which were part of my `data` argument from `glm()`), this turns to `TRUE` the `possibly.random` flag.

Afterwards, if the dataset contains missing values, the all(chk == tbl) will fail because NA can't be compared to each other.

I'm guessing that can be fixed fairly easily by changing the `all()` statement, or introducing some NA sanitization first?

Best,
Thomas

**Comment by rvlenth** [comment]
I can't possibly account for all the fancy things users will do in their `data` arguments. The `possibly.random` flag is based on seeing if the first few rows of data can be reproduced, and I think it is working reasonably well now. I don't think it would be assuring enough that the data can be reproduced if I get `NA`s both times, so I'm unwilling to make such a change to the existing code.

I think the right thing to do in your application is to save the result of your filtering or whatever manipulation is done in a variable named, say, `thedata`; then fit the model with `data = thedata`. Finally, in the `emmeans()` or `ref_grid()` call, `thedata` will be recoverable if evaluated in the same environment, or if not, devise a way to save `thedata` and pass it explicitly as the `data` argument in `emmeans()` or `ref_grid()`.
