### ISSUE TITLE
Feature Request: Support for lm_robust in estimatr package

### ISSUE THREAD

**Issue by DeFilippis** [rvlenth/emmeans#123]
I was wondering if you could please enable compatibility for `lm_robust` in the `estimatr` package.  If not, could you suggest the steps necessary to manually get the`emmeans` to work with `lm_robust`?  

`lm_robust` cleanly allows for fast clustered standard errors and suppressed fixed effects, but, as of current, the only post-estimation tool that is compatible with it is `linearHypothesis` in the `car` library, which is insufficient for the complex contrasts that I use.  

I would be enormously grateful.

**Comment by rvlenth** [comment]
I am not sure how easily that can be done, or when I might be able to get around to investigating it, as I have some of the things going at this time. More and more, I am going to have to rely on package developers incorporating **emmeans** support for their model classes in their own packages. It might be worth contacting the package developer and mentio n that **emmeans** includes a vignette on how to do this.

Have you looked at the documentation for the `qdrg()` function? It might be possible to use that as a quick temporary measure.

**Comment by rvlenth** [comment]
It seems that the `qdrg()` function does indeed work:
```r
> library(estimatr)
> library(emmeans)
> warp.rlm = lm_robust(breaks ~ wool*tension, data = warpbreaks)

> rg = qdrg(object = warp.rlm, data = warpbreaks)
> emmeans(rg, ~tension | wool)
wool = A:
 tension emmean   SE df lower.CL upper.CL
 L         44.6 6.03 48     32.4     56.7
 M         24.0 2.89 48     18.2     29.8
 H         24.6 3.42 48     17.7     31.4

wool = B:
 tension emmean   SE df lower.CL upper.CL
 L         28.2 3.29 48     21.6     34.8
 M         28.8 3.14 48     22.5     35.1
 H         18.8 1.63 48     15.5     22.1

Confidence level used: 0.95
```

**Comment by DeFilippis** [comment]
You're amazing.  Thanks for looking into this... I couldn't quite figure out how to get it to work.

**Comment by rvlenth** [comment]
Resolved by contributing the needed code (https://github.com/DeclareDesign/estimatr/issues/309). Seems to work pretty well.
