### ISSUE TITLE
Latest CRAN Version (1.3.5.1): No more test statistics and P values in the output of contrast(), as expected

### ISSUE THREAD

**Issue by atrolle** [rvlenth/emmeans#128]
Hi Russell,

I've just downloaded the latest version of `emmeans` available from the CRAN (v. 1.3.5.1).

Just like the older version I had, with this latest version, `contrast()` should give, by default, test statistics and P values (according to your vignette: [(https://cran.r-project.org/web/packages/emmeans/vignettes/confidence-intervals.html]), but it is not the case anymore. In the ouptut, I get HPD Intervals instead.
I 've tried to use `summary()` with option `infer = c(FALSE, TRUE)`, but still, HPD Intervals.

Why can't I get test statistics and P values anymore?

**Comment by rvlenth** [comment]
The behavior you observed has been the case for the past several versions of **emmeans**. The difference is that evidently, the model you are studying was fitted using MCMC methods, and many Bayesians object to having a frequentist analysis as the default; hence the HPD intervals. 

For a Bayesian model, you may use `summary(..., frequentist = TRUE)` to obtain P values and such. For a non-Bayesian model, the default for `contrast()` results is still what you expected.

**Comment by rvlenth** [comment]
PS I added a clarifying statement about this in the vignette you mention.
