### ISSUE TITLE
Covariance matrix for EMM

### ISSUE THREAD

**Issue by xidongdxi** [rvlenth/emmeans#129]
How to extract the variance-covariance matrix of the EMM?
For example,
`pigs.lm <- lm(log(conc) ~ source + factor(percent), data = pigs)`
`pigs.emm <- emmeans(pigs.lm, "source", weights = "proportional")`
Then I can get the mean and SE of the "source". In addition, I want to extract the variance-covariance matrix of the estimates (might be different for different "weights"). Is there a quick way to do it? Many thanks

**Comment by rvlenth** [comment]
Try `vcov(pigs.emm)`
