### ISSUE TITLE
emmeans on an lme model created from a formula variable inside a function fails

### ISSUE THREAD

**Issue by bengowan** [rvlenth/emmeans#13]
Hello, 

Huge fan of lsmeans/emmeans! Noticed this issue today and thought I would pass along a reprex. 

I have a function which creates lme models using an assembled formula. Emmeans works fine on such models when they are assembled in the global space, but appear to fail inside functions. Does not occur with lm functions, appears to be specific to lme, perhaps because of the 'fixed = ' portion of the formula? 

Here is my attempt at a reprex using mtcars:

```r
#outside of a function an lme model with a variable in the call works fine
lme_formula <- as.formula("mpg ~ as.factor(cyl)")
lme_formula_model <- lme(lme_formula, random =~1|disp, data = mtcars)
emmeans(lme_formula_model, ~ cyl)
lme_formula_model$call

#inside of a function the emmeans cannot seem to find the formula variable in the model call
lme_formula_in_fn <- function(formula_string){  
  
  formula_inside_fn <- as.formula(formula_string)
  model_inside_fn <- lme(formula_inside_fn, random =~1|disp, data = mtcars)
  try(emmeans(model_inside_fn, ~ cyl))
  return(model_inside_fn)
  
}

#call the above function and see resulting error
model_outside_fn <- lme_formula_in_fn("mpg ~ as.factor(cyl)")

#model itself seems ok otherwise just has the variable in the call
model_outside_fn$call
summary(model_outside_fn)

```

The error text for the inside the function emmeans is: 
Error in eval(x$call$fixed) : object 'formula_inside_fn' not found
Error in ref_grid(object, ...) : 
  Perhaps a 'data' or 'params' argument is needed

I just found this morning, still toying around with it, will update if I find anything further/workarounds. 

Cheers,
Ben

**Comment by rvlenth** [comment]
Ben,

Thanks for the report. It appears that the error comes in the `terms` method for `lme` objects:
```
> terms(model_outside_fn)
Error in eval(x$call$fixed) : object 'formula_inside_fn' not found
```
whereas if I just pull the `terms` member, I'm OK:
```
> model_outside_fn$terms
mpg ~ as.factor(cyl)
attr(,"variables")
list(mpg, as.factor(cyl))
attr(,"factors")
               as.factor(cyl)
mpg                         0
as.factor(cyl)              1
attr(,"term.labels")
[1] "as.factor(cyl)"
attr(,"order")
[1] 1
attr(,"intercept")
[1] 1
attr(,"response")
[1] 1
attr(,".Environment")
<environment: 0x000000001c2da888>
attr(,"predvars")
list(mpg, as.factor(cyl))
attr(,"dataClasses")
           mpg as.factor(cyl) 
     "numeric"       "factor" 
```
I changed `recover_data.lme()` to use `object$terms` instead of `terms(object)`, and it now works:
```
> new_lme = lme_formula_in_fn("mpg ~ as.factor(cyl)")

> emmeans(new_lme, "cyl")
 cyl   emmean       SE df lower.CL upper.CL
   4 26.66364 1.022376 26 24.56211 28.76516
   6 19.74052 1.476179 24 16.69384 22.78721
   8 14.80218 1.007317 24 12.72317 16.88118

Confidence level used: 0.95    
```
The next update will have that, or some other fix. I'd really rather use `terms()` as it is *supposed* to be the best way to access internal stuff; maybe there's an extra argument I should be including or something.

**Comment by rvlenth** [comment]
Hmmm. It doesn't even use its own namespace:

```
> getS3method("terms", "lme")
function (x, ...) 
terms(formula(x), ...)
<bytecode: 0x00000000052ea2d0>
<environment: namespace:MASS>
```

**Comment by bengowan** [comment]
Wow, quick work! :) 

I had come up with a hacky work around in my function like so:

` model_inside_fn$call$fixed <- substitute(formula_inside_fn)`

Thanks again for emmeans, such a great package!

Cheers, 
Ben
