### ISSUE TITLE
plot prediction intervals?

### ISSUE THREAD

**Issue by mattansb** [rvlenth/emmeans#131]
Would it be possible to enable plotting prediction intervals in `emmip`? Perhaps adding a `PIs` argument in addition to `CIs` (maybe allow for the plotting of both simultaneously?)?

**Comment by rvlenth** [comment]
I'll consider. If I do this, then your next request would be adding that to `plot.emmGrid()` as well; so it's both or none. In `plot.emmGrid()`, it's dicier because I also allow comparison arrows, and I just don't know how many intervals we'd want to over-print...

**Comment by rvlenth** [comment]
OK, I did it. Let me know what you think.

**Comment by rvlenth** [comment]
Here's a demo
```r
> warp.lm = lm(breaks ~ wool * tension, data = warpbreaks)
> warp.emm = emmeans(warp.lm, ~ tension | wool)
> emmip(warp.lm, wool ~ tension, CIs = TRUE, PIs = TRUE)
```
![image](https://user-images.githubusercontent.com/26777519/61756588-3ea70e00-ad82-11e9-8085-85299e277a09.png)

```r
plot(warp.emm, PIs = TRUE)
```
![image](https://user-images.githubusercontent.com/26777519/61756651-8e85d500-ad82-11e9-9cc6-92fe5a40a929.png)

The latter do come across a bit l*My Little Pony* - themed, so I welcome suggestions for another color. The magenta PIs look better than my first attempt (cyan).

**Comment by rvlenth** [comment]
I changed it to just lighter blue (lower alpha). This is more consistent with what `emmip()` does and to me is much more tasteful.

![image](https://user-images.githubusercontent.com/26777519/61757407-073a6080-ad86-11e9-8e5c-d59a5fb1c683.png)

**Comment by mattansb** [comment]
Sure, more tasteful, but I think you just lost a lot of potential Bronie users...

This is fantastic! Thanks so much!

**Comment by rvlenth** [comment]
This is the first I have heard of bronies -- where was I? Anyway, it appears that this could be a vast number of users, so I should support them. Actually, I should provide a way to change colors of the plot elements, so I added a `colors` argument.
```r
plot(warp.emm, PIs = TRUE, comp = TRUE, colors = c("red", "blue", "magenta", "cyan"))
```
![image](https://user-images.githubusercontent.com/26777519/61812658-8e7ce800-ae09-11e9-8e04-1d2fa9a073f2.png)

Those changes will be in the next push. I'll close this issue as I think it's all done.
