### ISSUE TITLE
error in installing the package "emmeans''

### ISSUE THREAD

**Issue by clara1989** [rvlenth/emmeans#136]
install.packages("emmeans")

it reports
Installing package into ‘C:/Users/45063125/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  dependency ‘mvtnorm’ is not available

  There is a binary version available but the source version is later:
        binary source needs_compilation
emmeans  1.3.4    1.4             FALSE

installing the source package ‘emmeans’

trying URL 'https://cran.rstudio.com/src/contrib/emmeans_1.4.tar.gz'
Content type 'application/x-gzip' length 929207 bytes (907 KB)
downloaded 907 KB

ERROR: dependency 'mvtnorm' is not available for package 'emmeans'
* removing 'C:/Users/45063125/Documents/R/win-library/3.4/emmeans'
In R CMD INSTALL
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" CMD INSTALL -l "C:\Users\45063125\Documents\R\win-library\3.4" C:\Users\45063125\AppData\Local\Temp\RtmpUlyFq1/downloaded_packages/emmeans_1.4.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘emmeans’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\45063125\AppData\Local\Temp\RtmpUlyFq1\downloaded_packages’

 library("emmeans")
Error in library("emmeans") : there is no package called ‘emmeans’

**Comment by myerscl** [comment]
I am getting the same error, below. I started seeing this error on 8/20.

> install.packages("emmeans")
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
Warning: dependency ‘mvtnorm’ is not available
trying URL 'https://cran.cnr.berkeley.edu/src/contrib/emmeans_1.4.tar.gz'
Content type 'application/x-gzip' length 929207 bytes (907 KB)
==================================================
downloaded 907 KB

ERROR: dependency ‘mvtnorm’ is not available for package ‘emmeans’
* removing ‘/usr/lib64/R/library/emmeans’

The downloaded source packages are in
        ‘/tmp/RtmpX9wti2/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("emmeans") :
  installation of package ‘emmeans’ had non-zero exit status
>

**Comment by rvlenth** [comment]
I am traveling and without a PC. It is true that mvtnorm is a required package, but no particular version of it is needed. My suggestion is to install mvtnorm and make sure it works before installing emmeans. Then you won’t have this hurdle to pass when installing emmeans.

Hope it works

Russ

Sent from my iPad

On Sep 4, 2019, at 6:50 AM, Chris Myers <notifications@github.com<mailto:notifications@github.com>> wrote:


I am getting the same error, below. I started seeing this error on 8/20.

install.packages("emmeans")
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
Warning: dependency ‘mvtnorm’ is not available
trying URL 'https://cran.cnr.berkeley.edu/src/contrib/emmeans_1.4.tar.gz'
Content type 'application/x-gzip' length 929207 bytes (907 KB)
==================================================
downloaded 907 KB

ERROR: dependency ‘mvtnorm’ is not available for package ‘emmeans’

  *   removing ‘/usr/lib64/R/library/emmeans’

The downloaded source packages are in
‘/tmp/RtmpX9wti2/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("emmeans") :
installation of package ‘emmeans’ had non-zero exit status

**Comment by rvlenth** [comment]
Back home. Were you able to resolve this by installing **mvtnorm** separately?

**Comment by myerscl** [comment]
We were able to get it working based on your suggestion. Thanks for your help.
