### ISSUE TITLE
Unexpected indexing of `summary_emm` object.

### ISSUE THREAD

**Issue by Ax3man** [rvlenth/emmeans#14]
`summary_emm` objects also have class data.frame. `$` and `[[` indexing work as expected, and result in a single column. It's not clear to me, however, what `[` indexing does, since it usually just returns an error. I also can't find documentation of a `[.summary_emm` method. Is this intentional?

```
library(emmeans)
warp.lm <- lm(breaks ~ wool * tension, data = warpbreaks)
warp.emmGrid <- emmeans(warp.lm, ~ tension | wool)

summary(warp.emmGrid)
# wool = A:
#   tension   emmean       SE df lower.CL upper.CL
# L       44.55556 3.646761 48 37.22325 51.88786
# M       24.00000 3.646761 48 16.66769 31.33231
# H       24.55556 3.646761 48 17.22325 31.88786
# 
# wool = B:
#   tension   emmean       SE df lower.CL upper.CL
# L       28.22222 3.646761 48 20.88992 35.55453
# M       28.77778 3.646761 48 21.44547 36.11008
# H       18.77778 3.646761 48 11.44547 26.11008

# these both work
summary(warp.emmGrid)$emmean
summary(warp.emmGrid)[['emmean']]

# errors:
summary(warp.emmGrid)['emmean']

# Error in .subset2(x, i, exact = exact) : 
#   attempt to select less than one element in get1index
```

**Comment by rvlenth** [comment]
The error is not where it seems. Observe:
```
> smry <- summary(warp.emmGrid)

> smry['emmean']
 Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index 

> foo <- smry['emmean']   
> ### No error yet!
> foo
 Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index 

> class(foo)
[1] "summary_emm" "data.frame" 

> as.data.frame(foo)
    emmean
1 44.55556
2 24.00000
3 24.55556
4 28.22222
5 28.77778
6 18.77778

> as.data.frame(smry)['emmean']
    emmean
1 44.55556
2 24.00000
3 24.55556
4 28.22222
5 28.77778
6 18.77778
```
That is, the error occurs not in extracting the result, but in the fact that the subset is still of class `summary_emm` and there is an error in calling its print method, `print.summary_emm`

I suppose the cure would be to define a `[` method. Given that you can wrap it in `as.data.frame` and then use `[` to get the desired elements, do you think this is an important enough issue to warrant deploying a `[` method?

**Comment by rvlenth** [comment]
By the way, I should have mentioned a related matter. Starting with CRAN version 1.1, there is now an `as.data.frame` method for class `"emmGrid"`. Thus, if your goal is to extract elements, that's a better way to do it:
```
> as.data.frame(warp.emmGrid)['emmean']
    emmean
1 44.55556
2 24.00000
3 24.55556
4 28.22222
5 28.77778
6 18.77778
```

**Comment by Ax3man** [comment]
Thanks! That does clarify my confusion. I think the `as.data.frame` method is great, and I was indeed using `summary` after attempting data.frame coercion (that was a while ago). I think that is the preferable way to go.

I think the relevant question then becomes, is there still a need for the `summary_emm` to inherit from `data.frame`? As it stands I would expect subsetting to confirm to data.frame subsetting (and I expect this may confuse others).

Alternatively, should `print.summary_emm` detect the issue and print correctly?

**Comment by rvlenth** [comment]
I decided to ad a `[.summary_emm` method. Yes, I think `summary_emm` should still inherit from `data.frame`; I'm sure somebody out there has a script that depends on that; plus it really is a data frame, with extra attributes and a special `print` method.

I thought of adding `$` and `[[` methods for `emmGrid` objects, until I remembered that there already is a `[` method that does *not* return a `data.frame`, and shouldn't. So adding those would just create confusion.

**Comment by rvlenth** [comment]
PS - I discovered an unpleasant side-effect of my `[.summary_emm` method. The function `cld.emmGrid` relied on still having a `summary_emm`, object after subsetting (actually reordering it). So I added an optional argument `as.df` that defaults to `TRUE`. It will be in the next push to github.
