### ISSUE TITLE
Cannot get `pwpp` to work 

### ISSUE THREAD

**Issue by DeFilippis** [rvlenth/emmeans#140]
I keep getting the following error when trying to use pwpp:

```
devtools::install_github("rvlenth/emmeans")
contrast_means = emmeans(fit_contrast, "condition")
pwpp(contrast_means)

Error in pwpp(contrast_means) : could not find function "pwpp"
```

Running 
``??pwpp`` also yields no results.

**Comment by rvlenth** [comment]
I think you just need to attach the library before using it:

    library(“emmeans”)
    contrast_means = ...

Russ

Sent from my iPhone

On Sep 13, 2019, at 1:33 PM, Evan DeFilippis <notifications@github.com<mailto:notifications@github.com>> wrote:


I keep getting the following error when trying to use pwpp:

devtools::install_github("rvlenth/emmeans")
contrast_means = emmeans(fit_contrast, "condition")
pwpp(contrast_means)

Error in pwpp(contrast_means) : could not find function "pwpp"


Running
??pwpp also yields no results.

**Comment by rvlenth** [comment]
I have heard no response so I think this issue is resolved. Let me know if I'm wrong.
