### ISSUE TITLE
Bug in emtrends()

### ISSUE THREAD

**Issue by andreaphsz** [rvlenth/emmeans#143]
Since emmeans version 1.4.1 I get the following error:

```
library(nlme)
library(emmeans)

packageVersion("emmeans")
##> [1] ‘1.4.1’

fit <- lme(distance ~ age+Sex, data = Orthodont)

## try emtrends
emtrends(fit, "Sex", var="age")
##> Fehler in emm_basis.lme(model, attr(data, "terms"), RG@model.info$xlev,  :
##  Argument "options" fehlt (ohne Standardwert)
```

Thank you for reviewing this issue!

**Comment by rvlenth** [comment]
Thanks for reporting this. What happened is that I had implemented a provision whereby if the user supplies a `df` argument, then I wanted to bypass complicated d.f. calculations in `lme` and other objects; but I failed to complete that workaround in one call in `emtrends()`. I have fixed this and it now works:
```r
> emtrends(fit, "Sex", var = "age")
 Sex    age.trend     SE df lower.CL upper.CL
 Male        0.66 0.0713 80    0.518    0.802
 Female      0.66 0.0713 80    0.518    0.802

Degrees-of-freedom method: containment 
Confidence level used: 0.95

> emtrends(fit, "Sex", var = "age", df = 14)
 Sex    age.trend     SE df lower.CL upper.CL
 Male        0.66 0.0713 14    0.507    0.813
 Female      0.66 0.0713 14    0.507    0.813

Degrees-of-freedom method: user-specified 
Confidence level used: 0.95
```

**Comment by andreaphsz** [comment]
Thank you!

**Comment by rvlenth** [comment]
BTW, you can work around the error even without updating to the github version by adding
`options = list()` in the call. I should have thought to mention this earlier.

I'm closing as I think this is resolved.
