### ISSUE TITLE
support for html printing of xtable.emmGrid object

### ISSUE THREAD

**Issue by kirbyj** [rvlenth/emmeans#144]
The `emmeans` methods for `print.xtable`, while producing beautiful custom output, can seemingly not be output as html.

```
library(xtable)
library(emmeans)

mtcars.lm <- lm(mpg ~ disp + hp * as.factor(cyl), data = mtcars)

mtcars.emm <- emmeans(mtcars.lm, ~cyl)

> print(xtable(mtcars.emm))
% latex table generated in R 3.6.0 by xtable 1.8-4 package
% Tue Oct  8 11:17:01 2019
\begin{table}[ht]
\centering
\begin{tabular}{rrrrrr}
  \hline
cyl & emmean & SE & df & lower.CL & upper.CL \\ 
  \hline
4.0000 & 17.2261 & 2.9765 & 25 & 11.0959 & 23.3563 \\ 
  6.0000 & 17.8598 & 1.7128 & 25 & 14.3322 & 21.3874 \\ 
  8.0000 & 18.7640 & 1.6788 & 25 & 15.3064 & 22.2216 \\ 
   \hline
\multicolumn{6}{l}{{\footnotesize Confidence level used: 0.95}}\\
\end{tabular}
\end{table}
```

Very nice, however, `type="html"` appears to be ignored:

```
> print(xtable(mtcars.emm), type="html")
% latex table generated in R 3.6.0 by xtable 1.8-4 package
% Tue Oct  8 11:17:38 2019
\begin{table}[ht]
\centering
\begin{tabular}{rrrrrr}
  \hline
cyl & emmean & SE & df & lower.CL & upper.CL \\ 
  \hline
4.0000 & 17.2261 & 2.9765 & 25 & 11.0959 & 23.3563 \\ 
  6.0000 & 17.8598 & 1.7128 & 25 & 14.3322 & 21.3874 \\ 
  8.0000 & 18.7640 & 1.6788 & 25 & 15.3064 & 22.2216 \\ 
   \hline
\multicolumn{6}{l}{<font size = -1>Confidence level used: 0.95</font>}\\
\end{tabular}
\end{table}
```

Forcing using of `xtable::print.xtable` fails with

```
> xtable::print.xtable(xtable(mtcars.emm), type="html")
Error in rep(" ", nrow(x) + 2) : invalid 'times' argument
```
 
I could try to hack something together in `kable` by concatenating all the relevant `emmGrid$misc` attributes, but this seems suboptimal (given that all this work has basically been done already). 

Note that `kable(mtcars.emm)` works just fine, but without preserving any of the formatting of `print.xtable_emm`.

**Comment by rvlenth** [comment]
I'll look at this, but on the surface, I don't see how anything in the **emmeans** code forces latex formatting. The only place I see it is in the default for `type`, which you override. Are you sure this isn't a problem with the xtable package -- specifically, its `print.xtableList` function?

**Comment by rvlenth** [comment]
Here's some useful info...
```r
> library(xtable)
> example(xtableList)
... lots of results ...

> print.xtableList(xList, type = "html")
Error in print.xtableList(xList, type = "html") : 
  print.xtableList not yet implemented for this type
```
The **emmeans** methods rely on the `xtableList` object (owing to my wish to include the annotations in the results). So until that is available, there isn't much I can do. One suggestion is
to use instead `as.data.frame(mtcars.emm)`. Then you'll have available the HTML methods, I believe, because it is just a data frame.

**Comment by rvlenth** [comment]
Aha. I do see that my code fails to pass the `type` argument. I added that to the code, and now I see, with your example, an informative error message (i.e., the one I just demonstrated above) instead of the wrong result:
```r
> print(xtable(mtcars.emm), type="html")
 Error in xtable::print.xtableList(x, type = type, include.rownames = include.rownames,  : 
  print.xtableList not yet implemented for this type 
```

The correction will be in the next push; but evidently there is no hurry.

Meanwhile, my suggestion does work:

```r
> print(xtable(as.data.frame(mtcars.emm)), type="html")
<!-- html table generated in R 3.6.1 by xtable 1.8-4 package -->
<!-- Tue Oct 08 12:13:10 2019 -->
<table border=1>
<tr> <th>  </th> <th> cyl </th> <th> emmean </th> <th> SE </th> <th> df </th> <th> lower.CL </th> <th> upper.CL </th>  </tr>
  <tr> <td align="right"> 1 </td> <td align="right"> 4.00 </td> <td align="right"> 17.23 </td> <td align="right"> 2.98 </td> <td align="right"> 25.00 </td> <td align="right"> 11.10 </td> <td align="right"> 23.36 </td> </tr>
  <tr> <td align="right"> 2 </td> <td align="right"> 6.00 </td> <td align="right"> 17.86 </td> <td align="right"> 1.71 </td> <td align="right"> 25.00 </td> <td align="right"> 14.33 </td> <td align="right"> 21.39 </td> </tr>
  <tr> <td align="right"> 3 </td> <td align="right"> 8.00 </td> <td align="right"> 18.76 </td> <td align="right"> 1.68 </td> <td align="right"> 25.00 </td> <td align="right"> 15.31 </td> <td align="right"> 22.22 </td> </tr>
   </table>
```

**Comment by kirbyj** [comment]
D'oh! I did spend a lot of time trying to work out if it was an inherent `xtable` limitation, but missed the critical case. In the meantime, thanks for the workaround.
