### ISSUE TITLE
Weights in reference grid for expanded covariate

### ISSUE THREAD

**Issue by awcm0n** [rvlenth/emmeans#148]
In order to explore an interaction involving a covariate ("year"), I used the reference grid option "cov.reduce = FALSE." These are the first 10 rows of the resulting reference grid.

**year** agegroup    sex black dm0 htn0 aceiarb0risk **.wgt.**
**0**      <45   Male    no  no   no           no  **1460**
**1**      <45   Male    no  no   no           no  **1460**
**2**      <45   Male    no  no   no           no  **1460**
**3**      <45   Male    no  no   no           no  **1460**
**4**      <45   Male    no  no   no           no  **1460**
**0**    45-65   Male    no  no   no           no  **4644**
**1**    45-65   Male    no  no   no           no  **4644**
**2**    45-65   Male    no  no   no           no  **4644**
**3**    45-65   Male    no  no   no           no  **4644**
**4**    45-65   Male    no  no   no           no  **4644**
...
Surprisingly, the weights for year 0 to 4 are identical for a particular combination of the levels of the remaining factors (i.e, the pooled sample size for this combination of factor levels). I expected them to reflect the sample size for each individual year (there's sample attrition, so the weights should become progressively smaller.)
I happen to be interested in ordinary marginal means (type = "cells"), but averaging over years would  yield estimated marginal means (type = "equal"). 
What am I missing, or is this a bug?
Thanks!

**Comment by rvlenth** [comment]
Hmmmm. It may be a bug, or not. I need to ponder this. But it has to do with the fact that in determining weights, separate levels of covariates are ignored when `covnest = FALSE` (see documentation for `ref_grid`. I believe what I was thinking is that a lot of covariates have tons of unique values, so if a user specifies `cov.reduce = FALSE`, those covariate levels would show up being nested in just about everything, and that would create a real mess. (But on the other hand, in exactly that situation, you really should never, ever use `cov.reduce = FALSE`!)

At any rate, you can get the weights you want if you add `covnest = TRUE` to the `emmeans()` or `ref_grid()` arguments. This will not change anything else unless you really do have a nested structure involving `year`. 

In the meantime, I'll ponder what I'll do aboyrt this. At the very least, I should make the documentation clearer.

**Comment by rvlenth** [comment]
... and even if it does detect a nested structure, you can always add `nesting = NULL` to the call.

**Comment by rvlenth** [comment]
I looked at old versions of **emmeans** and the weighting was done the way it was in your instance -- without regard to the frequencies of separate levels of covariates. However, I now think that is not correct: if we set a covariate to several levels in the reference grid, it is conceptually just like a factor. That's certainly what you were expecting. So, I decided to change the default of `covnest` to `TRUE`.

My other option was to take that argument out completely, treating it always as `TRUE` no matter what. But I have the issue that some users may want to replicate past results, and that's why I left it in, and changed the way the documentation is written.

I'm going to close this as I have given you a way to work around the issue and fixed it for future versions. But let me know if you have further comments.

**Comment by rvlenth** [comment]
My previous fix was absolutely a bad idea! I hadn't considered what happens with covariates
truly used as concomitant variables (e.g., rainfall in an ag experiment). We definitely don't want to weight by those variables; it may even be true that the values we specify in `at` don't even occur in the data. So the default of `covnest = TRUE` is not right.

So your question led me to consider what we really want to accomplish. Generally, we want to use covariate levels for weighting *only* when (1) all the levels occur in the data; and (2) the levels we specify exhaustively cover those that occur. So, in the update I just pushed up,

  * `covnest` is gone completely
  * There is a new `cov.keep` argument, whereby we specify the covariates to be treated as factors.
That includes using them along with other factors in determining weights.
  * `cov.keep` can also include numbers. In fact the default is `cov.keep = "2"`, which means that any covariate having 2 unique values will be treated as a factor.
  * `cov.reduce = FALSE` is now made equivalent to `cov.keep = "99"`
  * Covariate levels specified via `at` do *not* contribute to weighting.

The upshot is that if you use the newest github update with your model, I suggest you specify `cov.keep = "year"` or `cov.keep = "4"` in lieu of `cov.reduce = FALSE`. However, all three will work and produce the desired weighting. I hope this helps.
