### ISSUE TITLE
Support for mgcv::gam requested

### ISSUE THREAD

**Issue by MNRK01** [rvlenth/emmeans#15]
Hi,

On line 28 of [emmeans/R/gam-support.R](https://github.com/rvlenth/emmeans/blob/master/R/gam-support.R) you open up the possibility for future support for mgcv::gam. I am wondering if you would be able to add this support?

The reason for me using the mgcv package rather than the gam package is the ability of the former to handle factor covariates in the s(...) smoother function using a keyword argument named "by=".

As an example:

```R
# load data and libraries
> library(mgcv)
Loading required package: nlme
This is mgcv 1.8-23. For overview type 'help("mgcv-package")'.

> library(emmeans)

# load mtcars
> data(mtcars)

# create a factor out of the cyl variable
> mtcars$cylfact <- factor(mtcars$cyl)

# fit a mgcv::gam model and print the summary
> mtcars.gam1 <- gam(mpg ~ 0 + cylfact + s(wt, by = cylfact), data = mtcars)
> summary(mtcars.gam1)

# attempt building an emmeans::ref_grid
> ref_grid(mtcars.gam1)
Error in emm_basis.gam_mgcv(object, trms, xlev, grid, ...) : 
  Can't handle mgcv::gam objects
```

I also run into trouble when I use gam::gam

```R
# reset R session, reload mtcars and make a factor out of the cyl variable
> library(gam)
Loading required package: splines
Loading required package: foreach
Loaded gam 1.14-4

> library(emmeans)
> data(mtcars)
> mtcars$cylfact <- factor(mtcars$cyl)

# fit a gam::gam model and print the summary
> mtcars.gam2 <- gam(mpg ~ 0 + cylfact * s(wt), data = mtcars)
> summary(mtcars.gam2)

# attempt building an emmeans::ref_grid
> ref_grid(mtcars.gam2)
Error in apply(smooth.frame[[i]], 1, paste, collapse = ":") : 
  dim(X) must have a positive length

```

Since mgcv is packaged in the R standard library, my preference is to be able to use it together with emmeans.

Thank you for considering.

**Comment by rvlenth** [comment]
I tried, but found that it is not at all straightforward to add support for `mgcv::gam` objects. To do so, it is necessary to (1) figure out how to obtain predictions with all the smoothing options; and (b) also be able to obtain standard errors of those predictions. (more precisely, variance and covariance estimates for a vector of such prediction s). With `gam::gam` objects, the structure is somewhat simpler and I was able to cobble that together.

More and more, it is becoming unrealistic for me to add support structures for other packages without help from the developers of those packages. Ideally, the **emmeans** support would be provided in those other packages, as is done by **afex** and **rsm**, for example. The developers of the packages are in the best position to understand fully how to obtain predictions and covariance matrices thereof, and to be aware of additional options for their models which necessitate providing additional **emmeans** support. I provide a vignette and other documentation that details how to do this. 

Perhaps the best approach would be to encourage the developers of **mgcv** to develop the needed **emmeans** support and incorporate it in their package. I will contact them and offer encouragement to do so; but I imagine that they would be much more convinced of the need for such support by feedback from current users than by pleas from me.

**Comment by MNRK01** [comment]
Thank you for the fast response. I will contact the developers of mgcv to see if they would be able to add support for emmeans - it makes sense since the package developers know their package the best. I was also planning to get in touch with the developers of the gam package to see if they could extend their package to include factor covariates in a manner similar to mgcv.

Thank you for developing emmeans!

**Comment by rvlenth** [comment]
I too wrote to the developer. Hoping for good results

**Comment by rvlenth** [comment]
Guess what? I think I have figured this out! See #55 (which I reopened) for a more detailed response and example.
