### ISSUE TITLE
lmerTest.limit

### ISSUE THREAD

**Issue by ntardiff** [rvlenth/emmeans#150]
I get why there is a default data limit on computing Kenward-Roger p-values due to computation time, but I'm a little unclear why the same limit is set on Satterthwaite for lmerMod objects? The current behavior is very restrictive, as even if you change the defaults or even explicitly request a df method in your function call, that is overridden and you get asymptotic p-values. It seems that at least explicitly requesting the method in your function call should override the limit?

That aside, I love this package and thank you for putting it out there!

-Nathan

**Comment by rvlenth** [comment]
Thanks for your comments, and I'm glad you like the package. 

I still think it's important to have the limits, and I think users could too easily fall into a situation with seemingly infinite computation time even when they explicitly specify the method they want. But I have tried to make it easier by adding those same parameters as optional arguments (not having to use `emm_options`):
```r
> require(lme4)
> require(emmeans)
> Oats.lmer = lmer(yield ~ Variety + factor(nitro) + (1|Block/Variety), data = nlme::Oats)
>
> emm_options(lmerTest.limit = 50)  ### Force the warning condition
> ref_grid(Oats.lmer, mode = "satterth")
Note: D.f. calculations have been disabled because the number of observations exceeds 50.
To enable adjustments, add the argument 'lmerTest.limit = 72' (or larger)
[or, globally, 'set emm_options(lmerTest.limit = 72)' or larger];
but be warned that this may result in large computation time and memory use.
'emmGrid' object with variables:
    Variety = Golden Rain, Marvellous, Victory
    nitro = 0.0, 0.2, 0.4, 0.6
> emmeans(Oats.lmer, "Variety")
 Variety     emmean  SE   df lower.CL upper.CL
 Golden Rain  104.5 7.8 8.87     86.8      122
 Marvellous   109.8 7.8 8.87     92.1      127
 Victory       97.6 7.8 8.87     79.9      115

Results are averaged over the levels of: nitro 
Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95
> # Note that it reverts to K-R if available (and its limit isn't exceeded)

> # Add the suggested argument
> emmeans(Oats.lmer, "Variety", mode = "satterth", lmerTest.limit = 72)
 Variety     emmean  SE   df lower.CL upper.CL
 Golden Rain  104.5 7.8 8.87     86.8      122
 Marvellous   109.8 7.8 8.87     92.1      127
 Victory       97.6 7.8 8.87     79.9      115

Results are averaged over the levels of: nitro 
Degrees-of-freedom method: satterthwaite 
Confidence level used: 0.95 
```
The updated version will be available the next time I push it to github. I'm closing this issue but you can still comment and it can be reopened if necessary.

**Comment by rvlenth** [comment]
Note: If you really want to never deal with this again, you can put something like this in your `.Rprofile` file:
```r
options(emmeans = list(lmerTest.limit = 10000000))
```

**Comment by ntardiff** [comment]
Thanks, that's good to know and I get the concern. I think part of my
confusion was that I've never noticed much of any computation time to speak
of for Satterthwaite on lmer objects even with over 3000 data points, but I
take it that's not true in all cases.

Thanks again,
Nathan
