### ISSUE TITLE
Question about 'contrast()' with 'pairwise' method: Why can I get the same values of "odds.ratio", "SE", "z.ratio" and "p.value" for the same contrast but different combinations of the levels of the 'by' variables?  

### ISSUE THREAD

**Issue by atrolle** [rvlenth/emmeans#151]
Hi Russell,

I'm using the latest CRAN version of `emmeans` (version 1.42).
For the same case study as in #149 , I aim at performing pairwise comparisons, with results expressed in terms of odds ratios.
So I'm using the following command:
```
summary(contrast(emm, method = "pairwise", simple = "each",
   type = "response", adjust = "tukey", combine = TRUE), frequentist = TRUE, infer = c(FALSE, TRUE))
```
With `emm` obtained as follows: 
`emm <- emmeans(grid.emm, c("Module","Wish","Gender"))`
Where `Wish` is a factor with 2 levels, `Gender` a factor with 2 levels and `Module` a factor with 8 levels; `grid.emm` is the reference grid (obtained with `ref_grid()`).

The command works fine, but there's something I don't understand in the output of the pairwise comparisons: I get the same values of "odd.ratio", "SE", "z.ratio" and "p.value" for the same contrast, here `Before` / `After` (i.e. the two levels of `Wish`), but different combinations of the levels of the `by` variables:
> 
> Wish | Gender | Module | contrast | odds.ratio | SE | df | z.ratio | p.value
> ...
>  . | Woman | P2i1 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Woman | P2i2 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Woman | P2i3 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Woman | P2i4 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Woman | P2i5 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Woman | P2i6 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Woman | P2i7 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Woman | P2i8 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Man | P2i1 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Man | P2i2 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Man | P2i3 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Man | P2i4 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Man | P2i5 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Man | P2i6 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Man | P2i7 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
>  . | Man | P2i8 | Before / After | 0.16849080 | 0.03830619 | Inf | -7.83322250 | 9.462431e-13
> ...
> 

How can such a result be possible? I miss something; I was expecting different values of "odd.ratio", "SE", "z.ratio" and "p.value".
Note that, when expressing the results of the pairwise comparisons in terms of differences of probabilities (with a "estimate" field rather than an "odds.ratio" field), this issue does not happen, i.e. the values of "estimate", "SE", "z.ratio" and "p.value" are well different, as expected.

**Comment by rvlenth** [comment]
This is a consequence of the model you specified: `yvar ~ Gender + Module + Wish`, *with no interactions*. Remember, `emmeans()` summarizes the fitted model, not the data. See the similar situation described in FAQs number 13: https://cran.r-project.org/web/packages/emmeans/vignettes/FAQs.html#additive

**Comment by atrolle** [comment]
Ok. But why, when expressing the results of the pairwise comparisons in terms of differences of probabilities (with a "estimate" field rather than an "odds.ratio" field), this issue does not happen?
Yet, the model is the same, with no interaction.

**Comment by rvlenth** [comment]
Because a ratio is not the same as a difference. For example, .05 and .025 differ by a bratio of .05/.025 = 2.0, or an additive difference of .05 - .025 = .025. Compare 0.2 and .01 in the same ways: .2/.1 = 2 (same as other example), .2 - .1 = .1 (not the same as the other example). If you do pairwise differences on the *logit* scale, those differences will be the same.
