### ISSUE TITLE
Cannot calculate degree of freedom in Windows

### ISSUE THREAD

**Issue by CharlesVero** [rvlenth/emmeans#157]
I found this issue started as early as June, 2019, and it is still a problem right now.

I first use 'lme4' package to create a model: XXX.model = lmer(RT ~ variable 1* variable 2 + (1|random factor), data = XXX.data), then I use 'emmeans' package for further comparison: XXX.emm = emmeans(XXX.model, list(pairwise ~ variable 1|variable 2)). In Windows version, the result came out very soon, but further using 'contrast()' command would observe 'infinite' in degree of freedom. In MacOS, this usually takes a while to process, and the degree of freedom would show properly.

The script and data I used for both system is exactly the same, but sadly Windows could not give degree of freedom, and thus p-values are less reliable in this case.

**Comment by CharlesVero** [comment]
I figured out myself. It seems this issue has something to do with package 'simr'. If you installed it, 'emmeans' will run properly. Once you have installed it, even though you uninstall it later, it will still work.

**Comment by rvlenth** [comment]
Sorry I didn't get to this sooner, but I'm glad you got it working. I do not have **simr** installed on my system, and I don't see how that could affect K-R (or Satterthwaite??) d.f. calculations. More likely, it seems to me, is that you restarted R after installing that package, and that reset some option such as `emm_options(disable.pbkrtest = TRUE)`. Had I responded earlier, I was going to suggest looking at those options.

**Comment by rvlenth** [comment]
Aha! I see that **simr** imports the **pbkrtest** package. I suspect you did not have that installed previously, and that's what made the difference because it would have been installed when you installed **simr**. But you should have gotten a message saying you need to install it.

**Comment by CharlesVero** [comment]
> Aha! I see that **simr** imports the **pbkrtest** package. I suspect you did not have that installed previously, and that's what made the difference because it would have been installed when you installed **simr**. But you should have gotten a message saying you need to install it.

Thank you very much! Indeed, it is the **pbkrtest** package that caused the problem. Once I uninstall it, the problem reappears. Unfortunately, I do not see any warning messages telling me that I do not have **pbkrtest** package, which is why I did not figure out the solution until recently. It would be helpful if there is a warning message that confirms the missing of **pbkrtest** package.

**Comment by rvlenth** [comment]
Oops, you are right! I tried to streamline the complicated logic surrounding `mode`, `disable.pbkrtest`, `pbkrtest.limit`, `disable.lmerTest`, and `lmerTest.limit`, and the messages kind of went by the wayside. the next push will have updates that produce message(s) [not warnings] when packages are not loaded.

```r
> library("lme4")
> Oats.lmer = lmer(yield ~ Variety + factor(nitro) + (1|Block/Variety), data = nlme::Oats)

> library("emmeans")
> ref_grid(Oats.lmer)
Cannot use mode = "kenward-roger" because *pbkrtest* package is not installed
Cannot mode = "satterthwaite" because *lmerTest* package is not installed
'emmGrid' object with variables:
    Variety = Golden Rain, Marvellous, Victory
    nitro = 0.0, 0.2, 0.4, 0.6
```

Since we also look for **lmerTest** is **pbkrtest** is not installed, apparently you don't (or didn't) have that package either. I suggest installing that as it provides the Satterthwaite method as an option (not as computationally taxing as Kenward-Roger)
