### ISSUE TITLE
emtrends piping with brms model

### ISSUE THREAD

**Issue by MikeKSU** [rvlenth/emmeans#160]
(First time posting to Github, so apologies for any etiquette violations).  I'm not sure if this is related to #158, but this is what I'm experiencing.  

I fit a model using brms that involves continuous and categorical predictors.  Piping works fine with emmeans, but throws an error with emtrends:

> bn %>%
+   emmeans(~Tx)
NOTE: Results may be misleading due to involvement in interactions
 Tx emmean lower.HPD upper.HPD
 1    27.6      23.3      31.7
 2    28.5      24.5      32.6

> bn %>%
+   emtrends(~Tx, var="c.day")
Error in as.vector(x) : object '.' not found
In addition: Warning message:
In as.vector(x) : restarting interrupted promise evaluation
Error in ref_grid(object = ., options = list(just.data = TRUE)) : 
  Perhaps a 'data' or 'params' argument is needed

Note that a direct call to emtrends works fine:

> emtrends(bn, ~Tx, var="c.day")
NOTE: Results may be misleading due to involvement in interactions
 Tx c.day.trend lower.HPD upper.HPD
 1        -5.84     -6.96     -4.70
 2        -5.39     -6.59     -4.29

**Comment by rvlenth** [comment]
This is almost certainly the same as #158. In a week or so (about Dec 1, 2019), I plan to submit an update to CRAN where there is a fix to this. However, if you can, please try installing the current github version (instructions on main page for **emmeans**), then check to see if it works right. You may need to restart R or at least completely unload **emmeans** -- `detach(package:emmeans, unload = TRUE)`. Do let me know if for some reason this doesn't work

**Comment by MikeKSU** [comment]
Russell, 
I had installed the update right after posting and it still didn't work.  However, your tip to detach the package and reload it worked!!!  I just developed an alternative (more tortured) approach without using emtrends; fortunately, the results aligned nicely with the results of the fixed emtrends piping.  

Thank you!!!

**Comment by rvlenth** [comment]
Glad it worked. I'll assume it's OK to close this issue
