### ISSUE TITLE
`mode`-argument errors in new version 1.4.3

### ISSUE THREAD

**Issue by strengejacke** [rvlenth/emmeans#161]
Here's an example that works fine with emmeans **1.4.2**:

``` r
library(emmeans)
library(AER)

data("Affairs")
m <- tobit(affairs ~ age + yearsmarried + religiousness + occupation + rating, data = Affairs)

emmeans(m, "yearsmarried")
#>  yearsmarried emmean    SE  df lower.CL upper.CL
#>          8.18  -5.99 0.719 594     -7.4    -4.58
#> 
#> Confidence level used: 0.95

emmeans(m, "yearsmarried", mode = "link")
#>  yearsmarried emmean    SE  df lower.CL upper.CL
#>          8.18  -5.99 0.719 594     -7.4    -4.58
#> 
#> Confidence level used: 0.95
```

Same example fails with emmeans **1.4.3**:

``` r
library(emmeans)
library(AER)

data("Affairs")
m <- tobit(affairs ~ age + yearsmarried + religiousness + occupation + rating, data = Affairs)

emmeans(m, "yearsmarried")
#>  yearsmarried emmean    SE  df lower.CL upper.CL
#>          8.18  -5.99 0.719 594     -7.4    -4.58
#> 
#> Confidence level used: 0.95

emmeans(m, "yearsmarried", mode = "link")
#> Error in hook(result, ...): unused argument (mode = "link")
```

This is difficult because when you use emmeans within a package (as I do), and you have a "generic" call to `emmeans()`, no matter which model class, you could use the `mode`-argument easily in previous emmeans-versions, but now you would need to check the model-type to see whether the `mode`-argument works or not.

**Comment by strengejacke** [comment]
It also seems that even for models that support the `mode`-argument, this does no longer work when `emmeans()` is called within functions, at least probably in certain contexts. See following sourcecode:

https://github.com/strengejacke/ggeffects/blob/298d6754df63c1d8b99082357727bfd9e2aa0d5d/R/emmeans_prediction_data.R#L126-L137

where `pmode` is one of the valid values for the related model.


This uses to work with emmeans **1.4.2**:

``` r
library("ggeffects")
library("betareg")

data("GasolineYield")
m1 <- betareg(yield ~ batch + temp, data = GasolineYield)
  
ggemmeans(m1, "batch")
#> 
#> # Predicted proportion of yield
#> # x = batch
#> 
#>   x predicted std.error conf.low conf.high
#>   1     0.312     0.012    0.289     0.336
#>   2     0.232     0.014    0.205     0.260
#>   3     0.280     0.015    0.251     0.309
#>   4     0.189     0.009    0.170     0.207
#>   6     0.186     0.010    0.165     0.206
#>   7     0.122     0.008    0.107     0.137
#>   8     0.117     0.008    0.101     0.133
#>  10     0.075     0.006    0.063     0.086
#> 
#> Adjusted for:
#> * temp = 332.09
```

... but no longer with emmeans **1.4.3**

``` r
library("ggeffects")
library("betareg")

data("GasolineYield")
m1 <- betareg(yield ~ batch + temp, data = GasolineYield)
  
ggemmeans(m1, "batch")
#> Can't compute marginal effects, 'emmeans::emmeans()' returned an error.
#> 
#> Reason: unused argument (mode = "response")
#> You may try 'ggpredict()' or 'ggeffect()'.
#> NULL
```

Is there anything I can do to address this issue? E.g. to avoid or replace the `mode` argument?

**Comment by rvlenth** [comment]
Thanks for your report. 

The new version includes provisions where `...` arguments are passed where previously they were not. That is the origin of this issue.  It should be easy to fix, but in the short term, your best solution is probably to revert to version 1.42. I'll keep you posted.

**Comment by strengejacke** [comment]
> but in the short term, your best solution is probably to revert to version 1.42. 

The problem is not just a personal problem, but that now my package fails for all tests on CRAN, so sooner or later I'll be contacted in order to fix the issues. I *could* deactivate those tests meanwhile, but of course, from a user perspective, those functions won't currently work for package users as well. 

I guess I'll deactivate tests when I'm contacted by CRAN and in case I get contacted by users that report issues, I'll say that the problem is known and a fix is in work... :-)

**Comment by rvlenth** [comment]
OK. It turns out that changing emmeans:::.betareg.pg fixes both of the problems you report. I'll push it to github. I can try to push CRAN to accept an emergency update...

**Comment by rvlenth** [comment]
I have submitted the update to CRAN, keeping fingers crossed

**Comment by rvlenth** [comment]
Here's a curiosity; the feedback from CRAN submit says:
```
*** Strong rev. depends ***: agriTutorial augmentedRCBD ClinReport distdichoR eda4treeR ibd jmv JWileymisc lsmeans psycho RRphylo sjstats
```
Odd that **ggeffects** isn't in there. What would it take to get it included? Like should I add it to Suggests, even though I have no examples or tests of my own that use it?

**Comment by strengejacke** [comment]
**ggeffects** suggests **emmeans**, and does not import it. The reverse dependency checks only check packages where the submitted package is imported.

I can download your latest GitHub build and run checks locally, to see if everything works at least on my PC.

**Comment by strengejacke** [comment]
> Like should I add it to Suggests, even though I have no examples or tests of my own that use it?

I think it would only work if you add it to "Suggests" _and_ add tests with ggeffects to your package - but I think such effort is not in the responsibility of package authors. Rather, CRAN could also try to check reverse-dependencies where a submitted package is listed as "Suggest", but maybe that would consume too much ressources?

**Comment by rvlenth** [comment]
Daniel,

Please do. I actually tried this by downloading my own copy from github. But I ran into situations where I don’t see how it could ever work, e.g. with ‘rq’ objects — for which no methods exist for either effects or emmeans.

Russ

Sent from my iPhone

On Nov 27, 2019, at 2:26 PM, Daniel <notifications@github.com<mailto:notifications@github.com>> wrote:


ggeffects suggests emmeans, and does not import it. The reverse dependency checks only check packages where the submitted package is imported.

I can download your latest GitHub build and run checks locally, to see if everything works at least on my PC.

**Comment by strengejacke** [comment]
Ok, local checks all pass. I also tried randomly some of the failing tests from [here](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/ggeffects-00check.html), and they work fine with your update.

So I'm optimistic that the update fixes the issues. :-)

**Comment by rvlenth** [comment]
Yay!

Sent from my iPhone

On Nov 27, 2019, at 3:07 PM, Daniel <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, local checks all pass. I also tried randomly some of the failing tests from here<https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/ggeffects-00check.html>, and they work fine with your update.

So I'm optimistic that the update fixes the issues. :-)

**Comment by rvlenth** [comment]
I see an "OK" now in the CRAN results for **ggeffects**, with r-devel-linux-x86_64-debian-gcc, dated today. So that gives me faith we have resolved this an that good check resuilts will filter through for other cases. My apologies for creating this problem and am happy that it's fixed.

**Comment by strengejacke** [comment]
Yep, everything is ok now. Remaining issues are most likely due to temporary CRAN problems. Thanks for the quick fix!
