### ISSUE TITLE
emmeans add_grouping

### ISSUE THREAD

**Issue by ImanYZ** [rvlenth/emmeans#164]
Hello Professor Lenth,

I've implemented a learning technology to reduce the gender gap(the difference between male and female student grades) in CS education. I conducted a quasi-experiment across six semesters, with ~200 students and similar numbers of males and females in each semester. The first three semesters were used as the control and we implemented the intervention in the second three semesters. To estimate the effect of the intervention on gender gap, I used the following model:

Model1 <- betareg(CourseGrade ~ Treatment * Gender)

Where each row in the dataset indicates a single student and Treatment is a dummy that indicates whether the observation was in semesters before or after the implementation of the intervention.
However, because the students and exams were different semester to semester, the gender gap is different across semesters. To control for the semester-specific effect, I implemented the following model:

Model2 <- betareg(CourseGrade ~ Semester * Gender)
Grid2 <- ref_grid( Model2 )
Treatment_Fact <- factor(c("Control", "Control", "Control", "Treated", "Treated", "Treated"), levels = c("Control", "Treated"))
Grid2 <- add_grouping(Grid2, "Condition", "Semester", Treatment_Fact)
emmeans(Grid2, revpairwise ~ Gender | Condition, type = "response")

However, it prints out:
Results are averaged over the levels of: Semester
I don't understand why! According to the documentation, the reference factor (Semester) should be nested in the grouping factor (Condition). If it correctly reports the aggregate effect, the results should not be averaged over the levels of the Semester.

Is there anything wrong with my analysis or interpretation? Is there any more reasonable way of estimating the effect size?

Thank you so much for your time in advance.

Best regards,
Iman

**Comment by rvlenth** [comment]
`Semester` remains a factor in the grid -- `Condition` is a new factor that is *added* to the grid. So when marginalizing to just `Gender` and `Condition`, we average over `Semester`, separately in each `Condition`. It may help understand this if you look at
``` 
summary(Grid2, by = "Gender")
emmeans(Grid2, ~ Condition | Gender)
```
and note that the `Condition*Gender` means are averaged over `Semester` separately within each `Condition`.

**Comment by rvlenth** [comment]
In other words, each result you see is averaged over three of the six semesters -- not all six semesters. Which three semesters are averaged over depends on `Condition`.

**Comment by ImanYZ** [comment]
This explanation is very helpful. Thank you.
I'd appreciate it if you add this explanation to the documentation to clarify it for others as well.

**Comment by rvlenth** [comment]
Note that `example(add_grouping)` is kind of a parallel example. Tthe last two results are:
```r
add_gr> emmeans(gfrg, "machine")
 machine brand    emmean    SE df lower.CL upper.CL
 A       FiberPro   40.4 0.724 11     38.8     42.0
 B       FiberPro   41.4 0.744 11     39.8     43.1
 C       Acme       38.8 0.788 11     37.1     40.5

Confidence level used: 0.95 

add_gr> emmeans(gfrg, "brand")
 brand    emmean    SE df lower.CL upper.CL
 FiberPro   40.9 0.531 11     39.7     42.1
 Acme       38.8 0.788 11     37.1     40.5

Results are averaged over the levels of: machine 
Confidence level used: 0.95 
```
and the annotation indicates that `brand` means are averaged over `machine`.

**Comment by ImanYZ** [comment]
A follow-up question:
As I explained above, I'm looking for the interaction effect of `Treatment * Gender`, but I introduced `Treatment` through add_grouping. In this case, does emmeasns disentangle the interaction effect? I'm asking because they aren't separate effects in the model. If no, what else can I do to find the interaction effect after controlling for the effect of individual semesters?
Thank you again for your help.

**Comment by rvlenth** [comment]
It doesn’t make sense for a nesting factor to interact with a factor that is nested in it.

Sent from my iPhone

On Dec 8, 2019, at 6:12 PM, Iman YeckehZaare <notifications@github.com<mailto:notifications@github.com>> wrote:


A follow-up question:
As I explained above, I'm looking for the interaction effect of Treatment * Gender, but I introduced Treatment through add_grouping. In this case, does emmeasns disentangle the interaction effect? I'm asking because they aren't separate effects in the model. If no, what else can I do to find the interaction effect after controlling for the effect of individual semesters?
Thank you again for your help.

**Comment by ImanYZ** [comment]
Sorry for my misleading question. I don't mean an interaction between a nesting factor and a factor that is nested in it. We conducted the quasi-experiment across six semesters. The first three semesters were used as the control and we implemented the intervention in the second three semesters. We need to estimate the effect of the intervention on the gender gap, i.e., `Treatment : Gender` effect on course grades. The problem is that the gender gap differs across individual semesters. My question is whether it makes sense to find `Treatment : Gender` effect through the following code:
```
Model2 <- betareg(CourseGrade ~ Semester * Gender)
Grid2 <- ref_grid( Model2 )
Treatment_Fact <- factor(c("Control", "Control", "Control", "Treated", "Treated", "Treated"), levels = c("Control", "Treated"))
Grid2 <- add_grouping(Grid2, "Condition", "Semester", Treatment_Fact)
emmeans(Grid2, revpairwise ~ Gender | Condition, type = "response")
```

**Comment by rvlenth** [comment]
This is fine. Since `Semester` interacts with `Gender` in the fitted model, a grouping variable based on `Semester` also interacts with `Gender`.

But there is also an answer to "what else can I do", though admittedly less convenient -- and that's to construct custom contrast coefficients for those comparisons of interest. Something like
```r
contrast(Grid2, list(
    diff.ctrl = c(-1,-1,-1,0,0,0,1,1,1,0,0,0)/3, 
    diff.trt  = c(0,0,0,-1,-1,-1,0,0,0,1,1,1)/3))
```

**Comment by ImanYZ** [comment]
Thank you so much for your constant support.
This is very helpful. Thank you.
