### ISSUE TITLE
Support for the WGEE

### ISSUE THREAD

**Issue by hugesingleton** [rvlenth/emmeans#165]
Dear Authors,
Is this possible, to add a support for the Weighted GEE? Currently only the GEE is supported. WGEE opens new possibilities in terms of missing data patterns. It would be extremely useful to have it! Or maybe is there any workaround code to get this already today?

**Comment by rvlenth** [comment]
I don't know exactly what package or model-fitting function you are discussing. However, if **emmeans** already supports a particular model object, it probably also supports those same objects when fitted using weights.

If that is not the case, I am trying to encourage package developers to incorporate their own **emmeans** support within their packages, as they are the ones who understand best the vagaries of their models. So it may be worthwhile to contact the developer of whatever package fits the WGEE models you mention.

It might also be possible to use the `qdrg()` function to cobble together something that works. See the documentation and example for that function.

**Comment by hugesingleton** [comment]
Thank you for your response. I mean either the https://cran.r-project.org/web/packages/wgeesel/
or https://cran.r-project.org/web/packages/gee4/index.html
This would enable the analysis with GEE, which (at some cost) relaxes certain important distributional assumptions of the GLMM, on MAR data.

**Comment by rvlenth** [comment]
It appears that `qdrg` may work. Using the *first* object `fit` from `example(wgee)`  (first example) in the package **wgeesel**:
```r
rg = qdrg(formula = fit$model, data = imps, coef = fit$beta, vcov = fit$var, df = Inf)
> rg
'emmGrid' object with variables:
    Drug = 0, 1
    Sex = 0, 1
    Time = 1.2954
> 
> emmeans(rg, ~ Drug | Sex)
Sex = 0:
 Drug emmean     SE  df asymp.LCL asymp.UCL
    0   4.77 0.1106 Inf      4.55      4.98
    1   4.21 0.0771 Inf      4.06      4.36

Sex = 1:
 Drug emmean     SE  df asymp.LCL asymp.UCL
    0   4.78 0.1171 Inf      4.55      5.01
    1   4.23 0.0750 Inf      4.08      4.37
```

**Comment by hugesingleton** [comment]
Oh, that is a great news. Could you, please, tell me, why the degrees of freedom are infinite? I saw this already with GEE. Does it mean we postulate we know the true population value of a certain parameter (wariance), even if it is estimated?

**Comment by rvlenth** [comment]
Actually, I can’t answer that. I just see that they show asymptotic tests in the model summary, so I was being consistent. This definitely makes the tests anti-conservative. But I have nearly zero expertise on these models, so it’d take somebody with more expertise to answer this.

Sent from my iPhone

On Dec 10, 2019, at 5:33 AM, hugesingleton <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh, that is a great news. Could you, please, tell me, why the degrees of freedom are infinite? I saw this already with GEE. Does it mean we postulate we know the true population value of a certain parameter (wariance), even if it is estimated?

**Comment by hugesingleton** [comment]
I found something. It's too complicated to me to understand the details, but maybe you find this useful.
https://pdfs.semanticscholar.org/de92/aba8160758f068cd33ef3a286b3e85b593e0.pdf

**Comment by rvlenth** [comment]
I think this is resolved, at least in terms of their being a workaround pending the developers providing **emmeans** support in their packages. So I am closing.
