### ISSUE TITLE
No p values in x axis when using the function pwpp

### ISSUE THREAD

**Issue by ManuelSpinola** [rvlenth/emmeans#167]
When using the function pwpp for a model with a predictor factor with 2 levels there is no p value in the x axis.

library(emmeans)
lm1 <- lm(extra ~ group, data = sleep)
lm_emm <- emmeans(lm1, "group")
pwpp(lm_emm)

**Comment by rvlenth** [comment]
Hmmm. More specifically, everything is plotted, including the one P value. But there is no scale on the horizontal axis.

**Comment by rvlenth** [comment]
Well, here's a workaround:
```r
pwpp(lm_emm) + ggplot2::geom_point(aes(x=c(.05,.10), y=c(1,1)), alpha=0)
```
![image](https://user-images.githubusercontent.com/26777519/70868501-1beedf00-1f47-11ea-9e9a-2028a0f40e38.png)

But that creates another issue of the value labels being seriously out of position.

It may become evident now that I am no **ggoplot2** wizard. I think this would happen even with several comparisons, if all the P values are nearly the same (between two tick positions). I'll tinker with it and when (if?) there's a fix, I'll refer to this issue when I commit it.

Thanks for reporting this.

**Comment by rvlenth** [comment]
OK; I verified that this can happen even with more than one P value if they are close in value; and I implemented basically the above workaround. 
```r
pwpp(lm_emm)
```
![image](https://user-images.githubusercontent.com/26777519/70869882-e6e88980-1f52-11ea-8e7f-eff933a232f1.png)

**Comment by ManuelSpinola** [comment]
Now it works thank you very much.
