### ISSUE TITLE
Possible error in Scheffe adjustment

### ISSUE THREAD

**Issue by csroka** [rvlenth/emmeans#17]
Hi,
I believe there may be an error in the way that confidence intervals are calculated using Scheffe's method of multiple comparisons. As an example, if I run the code below

```
data(fiber)
modFiber <- lm(strength ~ machine, data=fiber)
emFiber <- emmeans(modFiber, "machine")
contrast(emFiber, "pairwise", adjust="scheffe", options=list(infer=TRUE))
```
I get

```
Warning message:
In sqrt(n.contr + scheffe.adj * qf(level, n.contr + scheffe.adj,  :
  NaNs produced
```

It appears there are two issues in the calculation of the critical coefficient:

1. Parentheses are missing around `n.contr + scheffe.adj`.
2. The calculation is using the number of contrasts instead of the number of treatments. 

I have tried this on other datasets and get confidence intervals, but the numbers are incorrect. In particular, the intervals are shorter than Tukey's method for pairwise comparisons.

Thanks!
Chris

**Comment by rvlenth** [comment]
Chris,

Thanks for reporting this. On the parentheses, you are definitely tight -- good catch!

I believe, however, that having `n.contr` in there is correct. In this particular example, I trace it and at that point in the run, `n.contr = 3` and `scheffe.adj = -1`, resulting in 2 d.f.:

```
> contrast(emFiber, "pairwise", adjust="scheffe", options=list(infer=TRUE))
 contrast estimate       SE df   lower.CL  upper.CL t.ratio p.value
 A - B        -1.8 2.620433 12 -9.1046585  5.504658  -0.687  0.7934
 A - C         5.4 2.620433 12 -1.9046585 12.704658   2.061  0.1624
 B - C         7.2 2.620433 12 -0.1046585 14.504658   2.748  0.0535

Confidence level used: 0.95 
Conf-level adjustment: scheffe method with dimensionality 2 
P value adjustment: scheffe method with dimensionality 2 
```

Note that the intervals, after correction, are wider than with the Tukey method:

```
> contrast(emFiber, "pairwise", adjust="tukey", options=list(infer=TRUE))
 contrast estimate       SE df   lower.CL  upper.CL t.ratio p.value
 A - B        -1.8 2.620433 12 -8.7909567  5.190957  -0.687  0.7754
 A - C         5.4 2.620433 12 -1.5909567 12.390957   2.061  0.1402
 B - C         7.2 2.620433 12  0.2090433 14.190957   2.748  0.0434

Confidence level used: 0.95 
Conf-level adjustment: tukey method for comparing a family of 3 estimates 
P value adjustment: tukey method for comparing a family of 3 estimates 
```

On the Scheffe adjustment, I also confirm that I get the right thing when *not* contrasting the means, in which case the dimensionality is 3.

```
> summary(emFiber, adjust = "scheffe")
 machine emmean       SE df lower.CL upper.CL
 A         41.4 1.852926 12 35.40417 47.39583
 B         43.2 1.852926 12 37.20417 49.19583
 C         36.0 1.852926 12 30.00417 41.99583

Confidence level used: 0.95 
Conf-level adjustment: scheffe method with dimensionality 3
```

The correction will be made in the next push to github.

Thanks again.

**Comment by csroka** [comment]
Great, thank you for your response. This is really an excellent package. I plan to use it for the course I teach on Design of Experiments.

**Comment by rvlenth** [comment]
Design courses are its *raison d'etre*. I'm closing as I think this is now resolved.
