### ISSUE TITLE
brms emmeans

### ISSUE THREAD

**Issue by jtipples-dev** [rvlenth/emmeans#170]
Hello, Thanks for your great package. I'd be grateful for your help. ( R version 3.6.2, linux 17.04)

I am getting the following message when I try to use the latest version of emmeans (1.4.4) with any brms model

"Error in parse(text = x, keep.source = FALSE)[[1L]] :   subscript out of bounds"

Here is an example model
library(brms)
library("emmeans")
library(purrr)
 set.seed(5)
n = 10
n_condition = 5
ABC =
 tibble(
  condition = rep(c("A","B","C","D","E"), n),
response = rnorm(n * 5, c(0,1,2,1,-1), 0.5)
 )

m = brm(response ~condition+ (1|condition), data = ABC, control = list(adapt_delta = .99),
      prior = c(
           prior(normal(0, 1), class = Intercept),
           prior(student_t(3, 0, 1), class = sd),
         prior(student_t(3, 0, 1), class = sigma)
       ))
##runs fine 

emmeans(m,~condition)

Error in parse(text = x, keep.source = FALSE)[[1L]] : 
  subscript out of bounds

platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.2                         
year           2019                        
month          12                          
day            12                          
svn rev        77560                       
language       R                           
version.string R version 3.6.2 (2019-12-12)
nickname       Dark and Stormy Night

**Comment by jtipples-dev** [comment]
...the "Error in parse(text = x, keep.source = FALSE)[[1L]] :
subscript out of bounds" is specific to brms, emmeans works fine with rstanarm (on linux)

**Comment by rvlenth** [comment]
For some reason, `brms` seems to create an object that is supposed to be a formula but is in fact an empty list. I'm not sure where that comes from, but I made a simple patch to my internal `.all.vars()` function that treats anything of length 0 the same as a NULL. And now it works:
```
> emmeans(m,~condition)
 condition emmean lower.HPD upper.HPD
 A          0.138     -2.49      2.63
 B          0.985     -1.61      3.41
 C          1.841     -0.80      3.78
 D          0.988     -1.19      3.18
 E         -0.990     -3.67      1.43

Point estimate displayed: median 
HPD interval probability: 0.95 
```
I suspect this is *not* a new error with version 1.4.4. The patch will be incorporated in the next CRAN update, or you can install it now from github. Thanks for your report.

**Comment by jtipples-dev** [comment]
Thanks Russ, yes I did think it was referencing the wrong part of the model (or rather it seems brms is creating an empty list or similar). Feel free to close my first github issue
Best wishes and thanks again Jason

Jason Tipples, Senior Lecturer in Psychology
Leeds Beckett University, CL803 Calverley Building,City Campus, Leeds, LS1 3HE, UK
Tel: +44 (0)113 812 23002<tel:+44%20113%20812%2023002> | Email: W.Tipples@leedsbeckett.ac.uk<mailto:W.Tipples@leedsbeckett.ac.uk>  https://calendly.com/j-tipples/meet-dr-tipples<https://calendar.google.com/calendar/selfsched?sstoken=UU1Jdk1zazNaU19rfGRlZmF1bHR8ZmIxMjBhODc2ZGZkMmNlYWZlNjQ2YmY1OGU3ZDg3ODg>

On 30 Jan 2020, at 17:27, Russell V. Lenth <notifications@github.com> wrote:

﻿

Caution External Mail: Do not click any links or open any attachments unless you trust the sender and know that the content is safe.

For some reason, brms seems to create an object that is supposed to be a formula but is in fact an empty list. I'm not sure where that comes from, but I made a simple patch to my internal .all.vars() function that treats anything of length 0 the same as a NULL. And now it works:

> emmeans(m,~condition)
 condition emmean lower.HPD upper.HPD
 A          0.138     -2.49      2.63
 B          0.985     -1.61      3.41
 C          1.841     -0.80      3.78
 D          0.988     -1.19      3.18
 E         -0.990     -3.67      1.43

Point estimate displayed: median
HPD interval probability: 0.95


I suspect this is not a new error with version 1.4.4. The patch will be incorporated in the next CRAN update, or you can install it now from github. Thanks for your report.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frvlenth%2Femmeans%2Fissues%2F170%3Femail_source%3Dnotifications%26email_token%3DAONNCEHTQQD7H63XYDDG7U3RAMEYNA5CNFSM4KNYFZF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKL2SHA%23issuecomment-580364572&data=02%7C01%7Cw.tipples%40leedsbeckett.ac.uk%7C3c94c9a034cf4382bdd008d7a5a9b2e0%7Cd79a81124fbe417aa112cd0fb490d85c%7C0%7C1%7C637160020579976577&sdata=Sn7DPcDtbhR7MCZXuAi0Or92RK4KvuS0lkXbH%2FaIENM%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAONNCEG3UVMHZNAYP6PH4MTRAMEYNANCNFSM4KNYFZFQ&data=02%7C01%7Cw.tipples%40leedsbeckett.ac.uk%7C3c94c9a034cf4382bdd008d7a5a9b2e0%7Cd79a81124fbe417aa112cd0fb490d85c%7C0%7C1%7C637160020579986571&sdata=psNwlNNW%2F%2FgxNs9P1e9g%2Fhs5gFFMgThjrc0f5DkTvz8%3D&reserved=0>.

To view the terms under which this email is distributed, please go to:-
http://leedsbeckett.ac.uk/disclaimer/email/

**Comment by jgeller112** [comment]
I installed master from Git, but am still having issues.

**Comment by rvlenth** [comment]
Works for me:
```r
> emmeans(m,~condition)
 condition emmean lower.HPD upper.HPD
 A          0.152     -2.93      2.33
 B          0.982     -1.53      3.51
 C          1.836     -1.19      4.09
 D          0.976     -1.74      3.44
 E         -0.987     -3.95      1.53

Point estimate displayed: median 
HPD interval probability: 0.95 
```
Maybe you need to exit R and restart

**Comment by rvlenth** [comment]
PS there is kind of a CRAN mirror on git; make sure you install it from https://github.com/rvlenth/emmeans
