### ISSUE TITLE
installing packages (''lsmeans")

### ISSUE THREAD

**Issue by Van321** [rvlenth/emmeans#174]
Hi all, 
I'm trying to install package called lsmeans in Rstudio. But, it released me the warning as following:
> install.packages("lsmeans")
> Installing package into ‘C:/Users/thin4/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  dependency ‘mvtnorm’ is not available
also installing the dependencies ‘estimability’, ‘numDeriv’, ‘xtable’, ‘emmeans’
> library(lsmeans)
Error: package ‘emmeans’ required by ‘lsmeans’ could not be found
In addition: Warning message:
package ‘lsmeans’ was built under R version 3.4.4 

Any ideas to fix that problem are really appreciated!
Thank you very much!

**Comment by rvlenth** [comment]
I'm sorry you had trouble with installation. 

First, I'll mention that you do not need the **lsmeans** package at all. In fact, the `lsmeans` function itself is in the **emmeans** package. The only use for the **lsmeans** package is to provide compatibility for old code, or for saved objects that were created by the old version of **lsmeans**. 

I am not sure what went wrong. All I can suggest is trying again, naming the needed packages explicitly:
```r
install.packages(c("mvtnorm","estimability","numDeriv","xtable","plyr","emmeans"))
```
Watch the messages from this. If there are any errors, you will not be able to load the package. If all is successful, use `library("emmeans")` and it should all work.

If there are errors, it may help to quit RStudio and start again before doing this.

**Comment by rvlenth** [comment]
I have not heard from you further, so I'm assuming it has been resolved in some way. However, you may still comment even though I'm closing this issue.
