### ISSUE TITLE
[Question] How does bootstrapped Satterthwaite work?

### ISSUE THREAD

**Issue by Generalized** [rvlenth/emmeans#176]
A statistical reviewer asked me, how should he understand this term? I am requested to use either Kenward-Roger or Satterthwaite for a MMRM model for analysis repeated observations without random effects. I use nlme::gls() for that, the only R routine able to do that. Unfortunately, there is no KR for it. Satterthwaite DFs for gls() enables the R to be used whenever only SAS was required (PROC GLIMMIX - REPEATED statement with  DDFM=SATTERTHWAITE). To the point - sometimes the mode="satterthwaite" doesn't work and I have to switch to the bootstrapped version.

But not I have to explain in details what is bootstrapped? I don't need a scientific article, just the information. An effect of bootstrapping is a distribution of estimates and - usually - a confidence interval taken from it. How is this translated to the DFs?

Did you manage to validate somehow this routine (I mean both Satterthwaite and bootstrapped Satterthwaite) against any other software, like SAS? I am asking for safety and reliability of my calculations, which I wanted to use in a scientific publication.

I'd really like to avoid the df.error, as the difference between the two methods is sometimes huge and doesn't even resemble anything from SAS.

PS: did you compare the results with the lavasearch2 package? Do you use it for the calculation, or is this your own implementation?

**Comment by rvlenth** [comment]
Perhaps "bootstrap" is not the best term for what is done. It is the best thing I could think of to get the Satterthwaite d.f. To compute that, I need the variance of the variance-covariance matrix V; and in turn to get that, I need the partial derivatives of each element of V with respect to each of the covariance parameters. Ideally, one would use a numerical derivative, but that requires access to a function V(theta) that returns V as a function of the parameters. This function is doable for `gls` objects for some, but not all, weighting methods (see `emmeans:::gls_grad()`), and is not available at all for `lme` objects. 

So what I do instead is perturb the response values slightly, and see what happens to theta and V. I can use that to estimate the needed partial derivatives. This is not bootstrapping in the sense of using an empirical distribution to approximate the variance of an estimator. I already have an estimate of the variance, and I just need those partial derivatives. So I would comment that this is really a computational method more than a statistical method, and that you really *do* get the Satterthwaite d.f. in the end, approximately. Moreover, accuracy in estimating d.f. is not a big issue as long as the results are not really small. The difference between 26.2 d.f. and 26.7 d.f. is minuscule in its effect on P values and confidence intervals.

The code is found in `emmeans:::gradV.kludge()`. I had not heard of the **lavasearch2** package, but I will look at it to see if it is helpful. I have had no luck in trying to rouse interest in this from the maintainers of **nlme**.

My other comment is that a *far* more critical issue is whether the Satterthwaite d.f. is appropriate; how it is computed is only secondary. The Satterthwaite method is based on the supposition that your variance estimate is proportional to a chi-square random variable. If it is important to validate the computation of the Satterthwaite d.f., then it seems even more important to validate that chi-square assumption.

**Comment by Generalized** [comment]
Thank you so much for such detailed answer. It fully explains the topic on the level I need. I truly appreciate that!

For your convenience, please find the following information:
1. The vignette, which mentions the S. approach: https://cran.r-project.org/web/packages/lavaSearch2/vignettes/overview.pdf

2. This PDF with examples how to use it (starts on page 48): https://publicifsv.sund.ku.dk/~jufo/courses/rm2018/nlmePackage.pdf
It is confusing, as it mentions Kenward-Roger instead of the S. Oppositely to the authors in the package vignette. Maybe you will be able find the source of the discrepancy. Anyway, every source counts, as there are not many of them for the gls().

Just the last question - should I fit the gls() via ML or REML for the S. dfs?

By validation I meant correctness of the numerical method, consistency with SAS. You know, SAS stands for industry standard and statistical reviewers often want the confirmation "it works this way" (even if the OTHER way is valid too...). Whether I agree or not, I have to comply... Unfortunately, I have no access to SAS at that time. Have to download the Student version and try it out.

**Comment by rvlenth** [comment]
Thanks for your comments. I understand what you're saying about the term `"boot.satterthwaite"` and will consider -- though in my "defense" I will note that "bootstrap" borrows from a computer science term, defined (per Wikipedia) as follows: "In general, bootstrapping usually refers to a self-starting process that is supposed to proceed without external input." That said, there is probably little or no harm in my renaming it something like `"approx.satterthwaite"`.

The offerings of the **lavaSearch2** package look both promising, and not. It seems like it will not work right for objects fitted with REML, which (answering your question) I tend to prefer as the variance estimates are less biased. On the other hand, this package seems to offer a different way to adjust bias.

As I understand it (which may not be too well), the distinction between K-R and Satterthwaite is mostly in that the K-R method is based on an adjusted variance-covariance matrix; so it may well be that when you specify `adjust.Omega = TRUE`, you may be getting K-R d.f., or something akin to it.

One simple thing I can think of is to simply provide (or contribute) **emmeans** support for the various objects in the `lavasearch2` package; those come with the derivatives I need already built-in, so I can use them to get d.f. I would have to learn more before I go down that road.

**Comment by rvlenth** [comment]
PS thanks for your kind remarks about **emmeans**
