### ISSUE TITLE
adjustable pwpp aesthetics

### ISSUE THREAD

**Issue by jacobgolan** [rvlenth/emmeans#178]
Hello - this isn't quite a bug, but a request. I'll start by saying this one of the most useful and well documented packages I have come across - so thank you! It would be nice to be able to adjust the aesthetics in pwpp(); I see dot size and segment size are fixed within the function.

**Comment by rvlenth** [comment]
I am no **ggplot2** wizard, but the returned object is of class `ggplot`, and I think you may be able to add aesthetics calls that will override what is set in there. See https://github.com/rvlenth/emmeans/issues/28 for an example with `emmip()`.

Meanwhile, like most everybody else right now, I am stuck at home with not much to do, so it's possible I will educate myself some more on the finer points of **ggoplot2**. However, don't hold your breath waiting for this to happen!

**Comment by jacobgolan** [comment]
Thank you very much for referring me to #28. Thank you very much and thank
you very much for such a wonderful package - the vignettes especially have
led to many an aha moment!

**Comment by rvlenth** [comment]
Looking at old issues... is dot size still immutable, or did you find a workaround?

**Comment by jacobgolan** [comment]
Hi,
I believe it is still immutable. Overall, greater control over the ggplot
aesthetics would be very useful.
Thanks for revisiting!
Jacob Golan
ᐧ

**Comment by rvlenth** [comment]
OK, I think I have pretty fair support for that now. There's an added `aes` argument that is a list of lists. May have `point`, `segment`, and/or `label` entries and those affect the points, line segments, and value labels. Additional changes can be made by adding themes or whatever to the plot itself. Example:
```r
pigs.lm <- lm(log(conc) ~ source * factor(percent), data = pigs)
emm = emmeans(pigs.lm, ~ percent | source)

my.aes <- list(point = list(shape = "square"), 
               segment = list(linetype = "dashed", color = "red"),
               label = list(family = "serif", fontface = "italic"))
 my.pal <- c("darkgreen", "blue", "magenta", "orange")
pwpp(emm, aes = my.aes) + scale_color_manual(values = my.pal)
```
![image](https://user-images.githubusercontent.com/26777519/93284376-3553de80-f798-11ea-91fc-7c6a07cb0b13.png)

Note: The point size is 2 and the label size is 2.5, but those may be overridden in `aes`.

**Comment by jacobgolan** [comment]
Dear Prof. Lenth,
Thank you so much - the aes argument will make things pretty
straightforward.
Thanks again for a great package!
Jacob Golan
ᐧ

**Comment by rvlenth** [comment]
Closing now, as I think this is resolved. But let me know if there are other needed aesthetics that can't be changed.
