### ISSUE TITLE
gls Object doesn't work with emmeans

### ISSUE THREAD

**Issue by Fernando-Souza** [rvlenth/emmeans#181]
Hi,
I'm using emmeans with gls{nlme} model and i get the error message:

modelo1<-gls(OCIOPCT~TRATAMENTO*INTERVALO,weights=varIdent(form=~1|INTERVALO),na.action=na.omit,data=dados)

cld(emmeans(modelo1,~TRATAMENTO),Letters=letters)

"Error in ref_grid(object, ...): We are unable to reconstruct the data.
The variables needed are:
	TRATAMENTO INTERVALO
Are any of these actually constants? (specify via 'params = ')
The dataset name is:
	dados
Does the data still exist? Or you can specify a dataset via 'data = '

Traceback:

1. cld(emmeans(modelo1, ~TRATAMENTO), Letters = letters)
2. emmeans(modelo1, ~TRATAMENTO)
3. ref_grid(object, ...)
4. stop(data)
"
 can't find a solution.  
I'm using R 3.6.3 and emmeans v 1.4.5
Can you help me?

thanks

**Comment by rvlenth** [comment]
It looks like it should work. But I have struggled with how to correctly get things to work with `na.action` other than the default in `gls`. Perhaps it will work if you do something like:
```r
cc <- complete.cases(dados[, c("OCIOPCT", "TRATAMENTO", "INTERVALO")]
modelo2<-gls(OCIOPCT~TRATAMENTO*INTERVALO, weights=varIdent(form=~1|INTERVALO), 
    subset = cc, data=dados)
multcomp::cld(emmeans(modelo2, ~TRATAMENTO), Letters=letters)
```
Please let me know if that works

**Comment by Fernando-Souza** [comment]
Thanks for answer,
Your solutions worked perfectetly!
I used:
modelo1<-gls(OCIOPCT~TRATAMENTO*INTERVALO,weights=varIdent(form=~1|INTERVALO),data=dados[complete.cases(dados$OCIOPCT),])

thanks

**Comment by rvlenth** [comment]
OK -- glad it worked. So that's information, and I'll look (once again) at whether I can handle `na.action`s appropriately. Thanks for your report.

**Comment by rvlenth** [comment]
I figured out what was going wrong with this. The `weights` argument created a set of weights only for the complete cases, causing an unmatched-dimensions error when we tried to recover the data. This is fixed in the commit just made.

I'm going to close this issue, but you may still comment if anything related comes up.
