### ISSUE TITLE
Response scale

### ISSUE THREAD

**Issue by mountaingoat19** [rvlenth/emmeans#183]
Hi,

I use your package emmeans and it give me an answers on a log scale but I would like to have it on a response scale. How can I do it ?

![image](https://user-images.githubusercontent.com/62620375/78402752-2520bc00-75c9-11ea-937a-d7b921564aeb.png)

Thanks

**Comment by rvlenth** [comment]
Add   type = “response”


Sent from my iPhone

On Apr 3, 2020, at 3:36 PM, mountaingoat19 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I use your package emmeans and it give me an answers on a log scale but I would like to have it on a response scale. How can I do it ?

[image]<https://user-images.githubusercontent.com/62620375/78402752-2520bc00-75c9-11ea-937a-d7b921564aeb.png>

Thanks

**Comment by mountaingoat19** [comment]
Thank you very much
