### ISSUE TITLE
ref_grid doens't support all transform options (.cf regrid)

### ISSUE THREAD

**Issue by mattansb** [rvlenth/emmeans#188]
`ref_grid` can accept `c("none", "response", "mu", "unlink", "log")`

whereas `regrid` **also** accepts `c("logit", "probit", "cauchit", "cloglog", "log", "sqrt", "1/mu^2", "inverse")`

Should these not be the same?

**Comment by rvlenth** [comment]
To be clear, you are referring to the `transform` argument in `ref_grid()` and `regrid()`. You are correct; I added some capabilities to `regrid()` but failed to extend those to `ref_grid()`. I will fix `ref_grid()` accordingly.

In the meantime, the workaround is to do it in two steps; e.g.,
```r
bctran = make.tran("boxcox", 0.479)
ref_grid(mod, transform = bctran)    ### currently doesn't work
regrid(ref_grid(mod), transform = bctran)   ### does work
```

**Comment by rvlenth** [comment]
OK, I think I fixed this, so am closing
