### ISSUE TITLE
nnet:multinom

### ISSUE THREAD

**Issue by mcfanda** [rvlenth/emmeans#19]
Hi
while working with emmeans on a multinomial model I've noticed that you get  an error when the dependent variable has more than 3 levels and the model features a covariate (see below for reproducible code). I did a bit of exploring and found this:
There is a weird behavior in emmeans when it calls nnet multinomial functions required to compute the standard errors of the means. When the standard errors are estimated, four matrices are needed, which are in the ref_grid object called by emmeans. They are :
grid<-ref_grid(model)
grid@grid
grid@V
grid@bhat
coef(model)
when the number of categories in the dep.variable are more than 3, and there is a covariate in the model, for some reasons  the matrices are non-conformable and an error is issued. It does not happen for K=3.

Here is the code to reproduce the error 
```
K=4
gre<-rnorm(1200,0,1)
admit<-factor(rep(c(1:2),600))
rank<-factor(rep(c(1:K),1200/K))
formula <- as.formula(rank ~ admit +gre)
model <- nnet::multinom(formula)
model$call$formula <- formula
emmeans(model, formula(~ rank|admit),mode = "prob")
```

The workaround I found is to estimate the reg_grid like this:
```
grid<-ref_grid(model,cov.reduce = function(x) c(mean(x)+.1*100,mean(x)-.1*100))
````
and then it works. 
I hope this is useful
mc

**Comment by rvlenth** [comment]
Thanks for reporting this. I'm still puzzling over it and will keep you posted. The error does not occur with `mode = "latent"` so I think I know which few lines of code to narrow it down to. Of course, I could be wrong.

It also appears that I need to improve the code so the model formula is recovered correctly.

A couple of notes

  * You don't need to wrap the formula in `formula()` in the call to `emmeans` 
  * Your remedy could be simplified to `cov.reduce = function(x) mean(x) + c(10,-10)`

**Comment by rvlenth** [comment]
I had a stupid coding error where I tried to replace `bhat` in-place rather than defining a new vector of the correct length.

**Comment by jonathon-love** [comment]
hi russell,

there's a couple of us waiting on this fix, so we'd love a new CRAN release when you get around to it.

with thanks

**Comment by rvlenth** [comment]
Jonathon, I'll try to expedite this a bit. I try not to bother the CRAN people too often, plus I think it rings an alarm bell if a package is updated twice in 30 days. Last version was Feb 24. So I will still hold off a bit.

Russ

**Comment by singmann** [comment]
Hi Russ, I am sorry for coming back to this, but there still seems to be an issue with the support for `multinom` objects.

The previous bug fixed did indeed solve the initial problem:
```
library("emmeans")
K <- 4
df <- data.frame(
  gre = rnorm(1200,0,1),
  admit = factor(rep(c(1:2),600)),
  rank = factor(rep(c(1:K),1200/K))
)
model <- nnet::multinom(rank ~ admit+gre, df)

## both work
emmeans(model, "rank", by = "admit")
emmeans(model, "rank")
```

However, with some other data, it still fails for the default `mode`:

```
data("birthwt", package = "MASS")
## ?MASS::birthwt
bwt <- with(birthwt, {
  race <- factor(race, labels = c("white", "black", "other"))
  ptd <- factor(ptl > 0)
  ftv <- factor(ftv)
  levels(ftv)[-(1:2)] <- "2+"
  data.frame(low = factor(low), age, lwt, race, smoke = (smoke > 0),
             ptd, ht = (ht > 0), ui = (ui > 0), ftv)
})
bwt.mu <- nnet::multinom(low ~ race*ptd, bwt)

emmeans::emmeans(bwt.mu, "race")
# Error in linfct[rows, , drop = FALSE] %*% object@bhat : 
#   non-conformable arguments

emmeans::emmeans(bwt.mu, "race", mode = "latent")
# NOTE: Results may be misleading due to involvement in interactions
#  race   emmean    SE df lower.CL upper.CL
#  white -0.2159 0.109  6   -0.483   0.0511
#  black -0.0657 0.195  6   -0.542   0.4106
#  other -0.0199 0.121  6   -0.316   0.2765
# 
# Results are averaged over the levels of: ptd, low 
# Results are given on the log (not the response) scale. 
# Confidence level used: 0.95 
```

**Comment by rvlenth** [comment]
I have now fixed this:
```
> emmeans(bwt.mu, ~ race, mode = "prob")
NOTE: Results may be misleading due to involvement in interactions
 race  prob                     SE df lower.CL upper.CL
 white  0.5 4.9065390000000003e-18  6      0.5      0.5
 black  0.5 1.3877788000000001e-17  6      0.5      0.5
 other  0.5 0.0000000000000000e+00  6      0.5      0.5

Results are averaged over the levels of: ptd, low 
Confidence level used: 0.95 
> emmeans(bwt.mu, ~ race, mode = "latent")
NOTE: Results may be misleading due to involvement in interactions
 race  emmean SE df lower.CL upper.CL
 white      0  0  6        0        0
 black      0  0  6        0        0
 other      0  0  6        0        0

Results are averaged over the levels of: ptd, low 
Results are given on the log (not the response) scale. 
Confidence level used: 0.95 
```
Note that your example isn't interesting because the results just reflect the equal weighting. You meant:
```
> emmeans(bwt.mu, ~ low | race, mode = "prob")
race = white:
 low  prob     SE df lower.CL upper.CL
 0   0.623 0.0695  6    0.453    0.793
 1   0.377 0.0695  6    0.207    0.547

race = black:
 low  prob     SE df lower.CL upper.CL
 0   0.545 0.1355  6    0.214    0.877
 1   0.455 0.1355  6    0.123    0.786

race = other:
 low  prob     SE df lower.CL upper.CL
 0   0.512 0.0748  6    0.329    0.695
 1   0.488 0.0748  6    0.305    0.671

Results are averaged over the levels of: ptd 
Confidence level used: 0.95
```
The issue was what I've come to call "the usual": That a matrix with one row or one column automatically is changed to a vector. In this case, the multinomial outcome has two levels, and `coef(bwt.mu)` is a vector rather than a matrix. The problem is exacerbated because the code uses `t(coef(bwt))`, which is a matrix with 1 row and 6 columns, rather than a matrix with 6 rows and 1 column. So my code proceeds on the belief that there are 7 multinomial outcomes instead of just two. Simple enough fix, will be pushed to github fairly soon.

The irritating thing of course is that finding one problem leads to another, in this case a glitch in my "optimal digits" determination for displaying output; see above.

**Comment by singmann** [comment]
Thanks for the quick reply, but you seem to have not yet pushed this change to `github`. But it is actually not at all urgent. I was seeing, whether I could use a multinomial regression example for  the new `default` method for `afex_plot`. This now supports most models also supported by `emmeans`. You can [have a look at it.](http://htmlpreview.github.io/?https://github.com/singmann/afex/blob/master/doc/afex_plot_supported_models.html) I just pushed the new `afex` version to `CRAN`, so it will be some time until I need new examples.

Btw, in case you feel like supporting more new complicated models, I think [`GLMMadaptive`](https://cran.r-project.org/package=GLMMadaptive) looks really interesting and promising.

**Comment by rvlenth** [comment]
Henrik,

Right – I hadn't. But I have now. I had in my head adding some needed fixes for the model-averaging support (MuMIn::averaging objects) regarding estimability assessment – very tricky stuff. I'll look at GLMM adaptive, but lately I'm getting so many questions from various users that I'm losing control of my life!

Cheers, and hope you're thriving in your new situation.

Russ
