### ISSUE TITLE
dealing with three way interaction

### ISSUE THREAD

**Issue by goesjon** [rvlenth/emmeans#194]
Hello, 

Firstly, thank you very much for this package. 

I have a problem examining one factor in a three way interaction

``` r
df <- iris
df$factor1 <- ifelse(df$Sepal.Width > 3, "A", "B")
df$factor2 <- ifelse(df$Petal.Length > 3.5, "C", "D")
df$factor3 <- ifelse(df$Sepal.Length > 5, "E", "F")

model <- lm(Petal.Width ~ factor1 * factor2 * factor3, data=df)
emmeans::emmeans(model, "factor1")
#> NOTE: Results may be misleading due to involvement in interactions
#>  factor1 emmean    SE  df lower.CL upper.CL
#>  A       nonEst    NA  NA       NA       NA
#>  B         1.19 0.101 143    0.993     1.39
#> 
#> Results are averaged over the levels of: factor2, factor3 
#> Confidence level used: 0.95
```
There is no estimation for factor1 A? This issue also appears in my larger data sets (not reproducible). 

Thank you very much and stay healthy

**Comment by rvlenth** [comment]
This is because some combinations of facttors do not occur:
```r
> with(df, table(factor1, factor2, factor3))
, , factor3 = E

       factor2
factor1  C  D
      A 25 22
      B 69  2

, , factor3 = F

       factor2
factor1  C  D
      A  0 20
      B  1 11
```
Note there are no observations at the combination (A, C, and F), so we can't predict ther response for that combination. EMMs are equally-weighted marginal averages of those 8 cell predictions, and the ones that include that (A,C,F) combination are flagged as non-estimable.

One way to avoid such conditions is to remove some interactions from the model. But then the model may not fit the data as well.

**Comment by rvlenth** [comment]
PS -- I also definitely recommend *against* making any inference on main-effect EMMs unless the other factors do not interact with it very strongly. You should instead use one or two of the factors as `by` variables and do separate comparisons at each level of the `by` variable(s). See `vignette("interactions","emmeans")` for discussion and examples.

**Comment by goesjon** [comment]
Thank you very much for your reply. I was not aware of the fact, that, if one combination does not occur, the whole estimation fails. I will have a look at `vignette("interactions","emmeans")`, thank you for the suggestion. I close this issue.
