### ISSUE TITLE
smooth term supported in GAMs from mgcv but not brms?

### ISSUE THREAD

**Issue by DominiqueMakowski** [rvlenth/emmeans#198]
Dear @rvlenth, I'm not sure to what extent this is related to #195, but here's a discrepancy that I've noticed:

``` r
model <- mgcv::gam(Sepal.Length ~ s(Petal.Length), data=iris)
emmeans::ref_grid(model, at = list("Petal.Length"=c(2, 3, 4)))
#> 'emmGrid' object with variables:
#>     Petal.Length = 2, 3, 4

model <- brms::brm(Sepal.Length ~ s(Petal.Length), data=iris, chains=2, iter=200, refresh=0)
emmeans::ref_grid(model, at = list("Petal.Length"=c(2, 3, 4)))
#> Warning: Argument 'exact_match' is deprecated. Please use 'fixed' instead.
#> 'emmGrid' object with variables:
#>     1 = 1
```

<sup>Created on 2020-05-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

As you can see, it seems that smooth term specifications are not taken into account for brms models. Thanks a lot for your very helpful work!

**Comment by rvlenth** [comment]
Paul has merged and improved my contributed code for emmeans, so the best support is now in the **brms** package. You can install it using `remotes::install_github("paul-buerkner/brms")`. 

That said, it appears to still not support the smoothing aspect (though I at least do not get the warning message):
```r
> packageVersion("brms")
[1] ‘2.13.0’

> methods("recover_data")  # confirms it includes brmsfit method, external to emmeans
[1] recover_data.aovlist* recover_data.brmsfit* recover_data.call*   
[4] recover_data.lm*      recover_data.lme*     recover_data.merMod* 
see '?methods' for accessing help and source code

> emmeans::ref_grid(model, at = list("Petal.Length"=c(2, 3, 4)))
'emmGrid' object with variables:
    1 = 1
``` 
I'm including a reference to this issue in **brms**, https://github.com/paul-buerkner/brms/issues/418, so it'll get pinged. I'm not sure how easliy this can be resolved there, but if it's like the `gam` method, it just needs an appropriate call to a `predict` method (see `emmeans:::emm_basis.gam`)

**Comment by rvlenth** [comment]
I'm closing this, as the resolution needs to be in **brms** (perhaps a new issue there?)
