### ISSUE TITLE
Inconsistent comma in contrast output

### ISSUE THREAD

**Issue by franrodalg** [rvlenth/emmeans#199]
Hi,

When using the `contrast` method with a `by` variable, the labels on the `contrast` column are inconsistent. In the first block, the contrasted levels are separated with a comma, but not in the remaining blocks. For instance

```R
df <- iris
df$factor1 <- ifelse(df$Sepal.Width > 3, "A", "B")
df$factor2 <- ifelse(df$Petal.Length > 3.5, "C", "D")
df$factor3 <- ifelse(df$Sepal.Length > 5, "E", "F")

model <- lm(Petal.Width ~ factor1 * factor2 + factor3, data=df)
emmeans::contrast(emmeans::emmeans(model, c("factor1", "factor3"), by = c("factor2")))
```
```
factor2 = C:
 contrast   estimate     SE  df t.ratio p.value
 A,E effect   0.2542 0.0578 145  4.401  <.0001 
 B,E effect  -0.1425 0.0587 145 -2.425  0.0165 
 A,F effect   0.1425 0.0587 145  2.425  0.0165 
 B,F effect  -0.2542 0.0578 145 -4.401  <.0001 

factor2 = D:
 contrast   estimate     SE  df t.ratio p.value
 A E effect  -0.0951 0.0584 145 -1.629  0.1055 
 B E effect   0.2069 0.0796 145  2.598  0.0207 
 A F effect  -0.2069 0.0796 145 -2.598  0.0207 
 B F effect   0.0951 0.0584 145  1.629  0.1055 

P value adjustment: fdr method for 4 tests 
```

This is not an issue when checking the values from this output, but it confuses the facets when creating plots from that output:

![image](https://user-images.githubusercontent.com/7487122/82678671-e78ff500-9c41-11ea-8dd0-72d4cc8b3675.png)

Cheers,
Fran

**Comment by franrodalg** [comment]
Nevertheless, as a workaround, it is as simple as adding 
```R
facet_grid(rows=vars(factor2), labeller=label_both, scales='free_y')
```
to the plot

**Comment by rvlenth** [comment]
OK, I figured it out. This is a by-product of adding capabilities for nested designs. I had a set of all the possible levels of the combinations of the two factors -- space-separated; then a list of labels for the first by group -- comma-separated; and code that checks if the levels for subsequent by groups match the labels in the first one. They didn't, so that's why we get different ones.
```r
> contrast(emm)    # emm is the result of your emmeans() call
factor2 = C:
 contrast   estimate     SE  df t.ratio p.value
 A E effect   0.2542 0.0578 145  4.401  <.0001 
 B E effect  -0.1425 0.0587 145 -2.425  0.0165 
 A F effect   0.1425 0.0587 145  2.425  0.0165 
 B F effect  -0.2542 0.0578 145 -4.401  <.0001 

factor2 = D:
 contrast   estimate     SE  df t.ratio p.value
 A E effect  -0.0951 0.0584 145 -1.629  0.1055 
 B E effect   0.2069 0.0796 145  2.598  0.0207 
 A F effect  -0.2069 0.0796 145 -2.598  0.0207 
 B F effect   0.0951 0.0584 145  1.629  0.1055 

P value adjustment: fdr method for 4 tests 
```
I opted to go with the spaces. Somewhat simpler coding as that is the default for `paste`. But let me know if you have an opinion

**Comment by franrodalg** [comment]
Glad you managed to locate the issue so quickly!!! I'd be happy with any option you prefer :)

Thanks so much!

**Comment by rvlenth** [comment]
Gonna go ahead and close this, so my lto-do list doesn't look so daunting.

**Comment by franrodalg** [comment]
This seems to have been causing downstream issues in other packages, such as `modelbased` (see [here](https://github.com/easystats/modelbased/issues/51#issuecomment-633008902), for instance). Updating to the latest version of `emmeans` here solved the issue.
