### ISSUE TITLE
Question: How can I obtain the original levels after more than one contrast assessment?

### ISSUE THREAD

**Issue by billdenney** [rvlenth/emmeans#209]
Again, thank you for the very useful package!

In a problem that is identical to what I was asking in #62, I'm wanting to make the extraction of information from emmeans more automatic.

Specifically, in the example below, I'd like some way to see that in `comp1` the contrast that is `"End - Baseline"` is made up of the components "End" and "Baseline" to have a direct relationship back to the original data.  I realize that this would not fit well within a data.frame, so I tried to look deeper.

When looking at the `as.list(comp1)` output below, I see there is a `$levels$contrast` list element that has the difference between the two levels indicated.  What I'm asking is:  Does something exist or can something be added that will let me extract the original levels without having to try to parse the contrast levels by regexp or similar?

I also ask this because I can think of pathological (but potentially real) cases where levels may not be distinguishable by parsing.  For example, if I had a data set with levels representing people's last names and there were last names of `c("Smith", "Brown", "Smith - Brown", "Brown - Smith")` the generated contrast of `"Brown - Smith - Brown"` would not be clear between coming from `"Brown" - "Smith - Brown"` or `"Brown - Smith" - "Brown"`.  (I admit that this is contrived, but hopefully it is a reasonably motivating example.)

Assuming that it doesn't exist, an implementation option for this could be to add something like a `level_construction` list element to the `as.list()` method.  And, it could look something like: `list("End - Baseline"=list(Day=c(test="End", reference="Baseline")))`.  That would be the way to generate it for first-level comparisons (like `comp1`), and subsequent comparisons (like `comp2`) would pull from the `level_construction` element of the input emmGrid to make a nested list structure (or alternatively, it could only ever have the first level, and it would be up to the user to trace back from the current value to the original values-- more work for the user, but less work to maintain in the library).

``` r
library(lme4)
#> Loading required package: Matrix
library(emmeans)

set.seed(5)
n_subjects <- 10
placebo_effect <- 1
treatment_effect <- 2
baseline <- 0
inter_sub_sd <- 1
within_sub_sd <- 0.5

d_treatment <-
  data.frame(
    Day=rep(factor(c("Baseline", "End"), ordered=TRUE), 2),
    Treatment=rep(factor(c("Placebo", "Treated"), ordered=TRUE), each=2)
  )

d_sim_subject <-
  data.frame(
    Treatment=rep(factor(c("Placebo", "Treated"), ordered=TRUE), each=n_subjects),
    Subject=factor(seq(1, 2*n_subjects)),
    iiv=rnorm(n=2*n_subjects, mean=0, sd=inter_sub_sd)
  )

d_effect_placebo <-
  data.frame(
    Day=factor(c("Baseline", "End"), ordered=TRUE),
    E_Placebo=c(0, placebo_effect)
  )

d_effect_treatment <-
  data.frame(
    Day=rep(factor(c("Baseline", "End"), ordered=TRUE), each=2),
    Treatment=rep(factor(c("Placebo", "Treated"), ordered=TRUE), 2),
    E_Treatment=c(0, 0, 0, treatment_effect)
  )

d_sim_study <-
  Reduce(
    function(x, y) {merge(x, y, all=TRUE)},
    list(d_sim_subject, d_effect_placebo, d_effect_treatment),
    init=d_treatment
  )

d_sim_study$Residual <- rnorm(4*n_subjects, mean=0, sd=within_sub_sd)
d_sim_study$E_Total <-
  with(d_sim_study, E_Placebo + E_Treatment + iiv + Residual)

mod <- lmer(E_Total~Treatment + Day + Treatment*Day + (1|Subject),
            data=d_sim_study)
# summary(mod)

emm1 <- emmeans(mod, ~Day|Treatment)
comp1 <- pairs(emm1, reverse=TRUE)
comp2 <- pairs(comp1, reverse=TRUE, by=NULL)

as.data.frame(emm1)
#>        Day Treatment     emmean       SE       df   lower.CL  upper.CL
#> 1 Baseline   Placebo  0.2186543 0.327361 24.91914 -0.4556693 0.8929778
#> 2      End   Placebo  0.9478279 0.327361 24.91914  0.2735043 1.6221514
#> 3 Baseline   Treated -0.3635555 0.327361 24.91914 -1.0378791 0.3107680
#> 4      End   Treated  2.6104304 0.327361 24.91914  1.9361069 3.2847540
as.data.frame(comp1)
#>         contrast Treatment  estimate        SE df   t.ratio      p.value
#> 1 End - Baseline   Placebo 0.7291736 0.2672204 18  2.728734 1.378316e-02
#> 2 End - Baseline   Treated 2.9739860 0.2672204 18 11.129336 1.679916e-09
as.data.frame(comp2)
#>                                          contrast estimate        SE df
#> 1 End - Baseline,Treated - End - Baseline,Placebo 2.244812 0.3779068 18
#>    t.ratio      p.value
#> 1 5.940122 1.274328e-05

as.list(comp1)
#> $bhat
#>       (Intercept)       Treatment.L             Day.L Treatment.L:Day.L 
#>         0.8533393         0.3819765         1.3092646         1.1224062 
#> 
#> $V
#>                    (Intercept)   Treatment.L         Day.L Treatment.L:Day.L
#> (Intercept)       4.465677e-02  2.003265e-17  2.904063e-18      2.974738e-18
#> Treatment.L       2.325689e-17  8.931353e-02  3.269736e-18     -2.336641e-17
#> Day.L             2.793748e-18  2.833489e-18  1.785169e-02     -5.721145e-18
#> Treatment.L:Day.L 2.939638e-18 -2.307558e-17 -4.951419e-18      3.570338e-02
#> 
#> $levels
#> $levels$contrast
#> [1] End - Baseline
#> Levels: End - Baseline
#> 
#> $levels$Treatment
#> [1] Placebo Treated
#> Levels: Placebo Treated
#> 
#> 
#> $linfct
#>      (Intercept) Treatment.L    Day.L Treatment.L:Day.L
#> [1,]           0           0 1.414214                -1
#> [2,]           0           0 1.414214                 1
#> 
#> $dffun
#> function (k, dfargs) 
#> pbkrtest::Lb_ddf(k, dfargs$unadjV, dfargs$adjV)
#> <bytecode: 0x0000000021cb5f88>
#> <environment: 0x0000000021cb7ea8>
#> attr(,"mesg")
#> [1] "kenward-roger"
#> 
#> $dfargs
#> $dfargs$unadjV
#>                    (Intercept)   Treatment.L         Day.L Treatment.L:Day.L
#> (Intercept)       4.465677e-02  2.728526e-17  3.128974e-18      2.974738e-18
#> Treatment.L       2.728526e-17  8.931353e-02  2.974738e-18     -2.082500e-17
#> Day.L             3.128974e-18  2.974738e-18  1.785169e-02     -4.954839e-18
#> Treatment.L:Day.L 2.974738e-18 -2.082500e-17 -4.954839e-18      3.570338e-02
#> 
#> $dfargs$adjV
#> 4 x 4 Matrix of class "dgeMatrix"
#>                    (Intercept)   Treatment.L         Day.L Treatment.L:Day.L
#> (Intercept)       4.465677e-02  2.003265e-17  2.904063e-18      2.974738e-18
#> Treatment.L       2.325689e-17  8.931353e-02  3.269736e-18     -2.336641e-17
#> Day.L             2.793748e-18  2.833489e-18  1.785169e-02     -5.721145e-18
#> Treatment.L:Day.L 2.939638e-18 -2.307558e-17 -4.951419e-18      3.570338e-02
#> 
#> 
#> $post.beta
#>      [,1]
#> [1,]   NA
#> 
#> $estName
#> [1] "estimate"
#> 
#> $estType
#> [1] "pairs"
#> 
#> $infer
#> [1] FALSE  TRUE
#> 
#> $level
#> [1] 0.95
#> 
#> $adjust
#> [1] "tukey"
#> 
#> $famSize
#> [1] 2
#> 
#> $avgd.over
#> character(0)
#> 
#> $by.vars
#> [1] "Treatment"
#> 
#> $methDesc
#> [1] "pairwise differences"
#> 
#> $is.new.rg
#> [1] FALSE
#> 
#> $orig.grid
#>        Day Treatment
#> 1 Baseline   Placebo
#> 2      End   Placebo
#> 3 Baseline   Treated
#> 4      End   Treated
#> 
#> $con.coef
#>      [,1] [,2] [,3] [,4]
#> [1,]   -1    1    0    0
#> [2,]    0    0   -1    1
```

<sup>Created on 2020-06-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by billdenney** [comment]
As an update, I found a way to get the original values with relatively simple use of `strsplit()` and knowledge of what the reference values were.  I do think that a feature like this would be useful, but it is not pressing for me.

**Comment by rvlenth** [comment]
My suggestion would be -- instead of parsing -- to look at the object from which the contrasts are computed. The levels are explicitly available there.
```r
> comp1@levels
$contrast
[1] End - Baseline
Levels: End - Baseline

$Treatment
[1] Placebo Treated
Levels: Placebo Treated
```
Also, you can use the contrast function itself to discover how they will be constructed:
```r
> emmeans:::revpairwise.emmc(comp1@levels$Treatment) # or pairwise(..., reverse = TRUE)
        Treated - Placebo
Placebo                -1
Treated                 1
```
This shows that `Placebo` will be subtracted from `Treated`.

Putting the levels in `comp`@levels@contrast` with the ordering just discovered, you can anticipate that the contrasts in `comp2` will be `End - Baseline,Treated - End - Baseline,Placebo`. (The primary variables are always taken in order before the by variables.)

An example with several levels of each factor would look less trivial.

Hope this helps

**Comment by billdenney** [comment]
Aha!  `emmeans:::revpairwise.emmc()` give me just the information I was wanting.  Thanks as always for the great package and quick response.

**Comment by rvlenth** [comment]
Another thing you could consider, by the way, is the `pwpm()` function:
```r
> pwpm(comp1, by = NULL)
                       End - Baseline Placebo End - Baseline Treated
End - Baseline Placebo                [0.729]                 <.0001
End - Baseline Treated                  -2.24                [2.974]

Row and column labels: contrast:Treatment
Upper triangle: P values 
Diagonal: [Estimates] (estimate) 
Lower triangle: Comparisons (estimate)   earlier vs. later
```
The levels being compared are the row names, and you can get the estimates, differences, and P values from the matrix. If there are by variables, their levels will be the list names.
