### ISSUE TITLE
Message about "averaging over"

### ISSUE THREAD

**Issue by urskalbitzer** [rvlenth/emmeans#21]
First of all, thanks for this great package.

I am currently using a model with one numerical and two categorical variables.
Here's an example of how it might look like:

Create data frame:
``` r
y <- rnorm(n = 100, mean = -2, sd = 0.5)
x1 <- rnorm(n = 100, mean = 3, sd = 1.5)
x2 <- sample(x = c("a1", "a2", "a3"), size = 100, replace = TRUE)
x3 <- sample(x = c("b1", "b2", "b3"), size = 100, replace = TRUE)
```
Run model and show coefficients
```r
res <- lm(y ~ x1 + x2 + x3)
coef(res)
#> (Intercept)          x1        x2a2        x2a3        x3b2        x3b3 
#> -1.87891191 -0.00222856 -0.19620519 -0.16569943  0.00158045 -0.05318129
```

Then, I used emmeans to quickly calculate the predicted means and SEs for the different factor levels of x2
```r
pairs.x2 <- emmeans::emmeans(res, pairwise ~ x2)
pairs.x2$emmeans
#>  x2    emmean         SE df  lower.CL  upper.CL
#>  a1 -1.902427 0.10199471 94 -2.104940 -1.699914
#>  a2 -2.098633 0.08209662 94 -2.261637 -1.935628
#>  a3 -2.068127 0.09411921 94 -2.255003 -1.881251
#> Results are averaged over the levels of: x3 
#> Confidence level used: 0.95
```
Given the message "averaged over the levels of: x3", I thought that results were NOT averaged over the numerical variable x1

In that case, I thought that the means should be the following:
```r
# for x2 = a1
0 + coef(res)["(Intercept)"] + ((coef(res)["x3b2"] + coef(res)["x3b3"])/3)
#>   -1.896112
# For x2 = a2
coef(res)["x2a2"] + coef(res)["(Intercept)"] + ((coef(res)["x3b2"] + coef(res)["x3b3"])/3)
#> -2.092317
# For x2 = a3
coef(res)["x2a3"] + coef(res)["(Intercept)"] + ((coef(res)["x3b2"] + coef(res)["x3b3"])/3)
#> -2.061812
```
However, they are
```r
0 + coef(res)["(Intercept)"] + mean(x1) * coef(res)["x1"] + ((coef(res)["x3b2"] + coef(res)["x3b3"])/3)
#> (Intercept) 
#>   -1.902427
coef(res)["x2a2"] + coef(res)["(Intercept)"] + mean(x1) * coef(res)["x1"]  + ((coef(res)["x3b2"] + coef(res)["x3b3"])/3)
#>      x2a2 
#> -2.098633
coef(res)["x2a3"] + coef(res)["(Intercept)"] + mean(x1) * coef(res)["x1"]  + ((coef(res)["x3b2"] + coef(res)["x3b3"])/3)
#>      x2a3 
#> -2.068127
```
I was confused that the output did not indicate that results are averaged over x3 AND x1
and I was wondering if you  might want to consider including this information into the output

Thanks a lot,
Urs
```

**Comment by rvlenth** [comment]
The results shown in the output are as documented in the package. Please check out the documentation for `ref_grid()` and the basics vignette `vignette("basics")`, and note that `emmeans()` results are based on a reference grid. You can see the reference grid for your example by doing
```
ref_grid(res)
```
Note that this reference grid has only *one* value of `x1`; it is the average of the `x1` values used in the dataset. EMMs are averages of predictions on the reference grid, and only one `x1` value is involved while there are three values of `x3`; so the annotation is correct in saying that predictions are averaged over `x3`, while it would be incorrect to say that the predictions are averaged over `x1`.

If you were to do, say,
```
emmeans(res, ~ x2, at = list(x1 = c(-1,0,1))
```
then the reference grid is changed to include three values of `x1`, and the annotations would indicate that the results were averaged over both `x1` and `x3`.

**Comment by urskalbitzer** [comment]
Okay, I see what you mean. The predicted means are based on the average value of x1 but not averaged over x1.
I guess I just got confused by the output but I now understand.

**Comment by urskalbitzer** [comment]
And thanks a lot for pointing out how to use specific values of other variables to make the predictions. I was searching for that but must have overlooked it. Looks easy and intuitive.

**Comment by rvlenth** [comment]
There are a lot of details. Those vignettes are recommended... You can also see them on CRAN w/o running R. Just follow the link for the package.
