### ISSUE TITLE
rstanarm support broken for models with attached contrasts (works in older versions though)

### ISSUE THREAD

**Issue by singmann** [rvlenth/emmeans#212]
The following short code works in previous version (`1.4.6` or older), but not in the current CRAN or Github version:

```r
library("rstanarm")
library("emmeans")
m1 <- stan_glm(breaks ~ wool * tension, data = warpbreaks,
               prior = rstanarm::student_t(3, 0, 3, autoscale = FALSE), 
               contrasts = list(wool = "contr.sum", tension = "contr.sum"))
emmeans(m1, c("tension", "wool"))
```

(I think the same problems also appears when the contrast is attached directly to the factor and not passed via contrasts.)

In current devel or CRAN:
```
> emmeans(m1, c("tension", "wool"))
Error in as.matrix(object$stanfit)[, nms, drop = FALSE] : 
  subscript out of bounds
```

In `1.4.7`:
```
> emmeans(m1, c("tension", "wool"))
Error in validObject(.Object) : 
  invalid class “emmGrid” object: invalid object for slot "V" in class "emmGrid": got class "numeric", should be or extend class "matrix"
```

Works in `1.4.6` or older:
```r
> emmeans(m1, c("tension", "wool"))
 tension wool emmean lower.HPD upper.HPD
 L       A      28.2      25.0      30.9
 M       A      34.6      29.5      39.7
 H       A      27.5      22.9      32.1
 L       B      30.4      26.3      34.4
 M       B      40.1      33.1      47.3
 H       B      26.5      20.2      33.2

Point estimate displayed: median 
HPD interval probability: 0.95 
```

**Comment by rvlenth** [comment]
Thanks for the report, Henrik. 

By debugging, I can see what is happening just before that error. There is a vector `nms` of expected names, then there is the matrix with the posterior sample:
```r
Browse[2]> X = as.matrix(object$stanfit)
Browse[2]> colnames(X)
[1] "(Intercept)"    "wool1"          "tension1"       "tension2"       "wool1:tension1"
[6] "wool1:tension2" "sigma"          "mean_PPD"       "log-posterior" 
Browse[2]> nms
[1] "(Intercept)"    "woolB"          "tensionM"       "tensionH"       "woolB:tensionM"
[6] "woolB:tensionH"
```
and indeed, it is `nms` that is wrong relative to the fit.

Meanwhile, I had (in an earlier stmt) changed the code to obtain `nms` to:
```r
    pp_data = get("pp_data", envir = getNamespace("rstanarm"))
    X = pp_data(object, newdata = grid, re.form = ~0, ...)[[1]]
    nms = colnames(X)
```
That is, I am retrieving one of stanfit's internal routines and then recovering the data matrix.
And in debug mode, I see:
```r
Browse[2]> head(X)
  (Intercept) woolB tensionM tensionH woolB:tensionM woolB:tensionH
1           1     0        0        0              0              0
2           1     1        0        0              0              0
3           1     0        1        0              0              0
4           1     1        1        0              1              0
5           1     0        0        1              0              0
6           1     1        0        1              0              1
```
which is definitely using `contr.treatment`.

So it is a great mystery how it gets from the wrong contrast coding to the right coding, and how I can find that matrix. I'll let you know when/if I find something.

Russ

**Comment by rvlenth** [comment]
Here's a little gem...
```r
> new = warpbreaks[1:3,]
> debug(rstanarm:::predict.stanreg)
> predict(m1, newdata = new)
    ...
Browse[2]> n
debug: dat <- pp_data(object, newdata)
Browse[2]> n
debug: stanmat <- as.matrix.stanreg(object)
Browse[2]> n
debug: beta <- stanmat[, seq_len(ncol(dat$x))]
Browse[2]> dat
Browse[2]> dat
$x
  (Intercept) woolB tensionM tensionH woolB:tensionM woolB:tensionH
1           1     0        0        0              0              0
2           1     0        0        0              0              0
3           1     0        0        0              0              0
    ...

Browse[2]> head(stanmat)
           parameters 
iterations (Intercept)      wool1  tension1     tension2 wool1:tension1 wool1:tension2    sigma
      [1,]    29.28447  1.3622527  7.577636 -0.613489235      4.3425987      -2.514829 10.43723
      [2,]    27.65064  2.8827087  4.316248 -2.403164383      4.1367361      -5.274030 11.20949
      [3,]    25.85555  3.2250633 11.720496 -0.007404444      4.4259861      -2.203340 13.18302
    ...
```
So in **rstanarm**'s own predict method with new data, they retrieve `dat` with the wrong contrast coding...

**Comment by rvlenth** [comment]
I reported this in https://github.com/stan-dev/rstanarm/issues/444. It seems that if they fix `pp_data()`, then it'll fix this issue too.

**Comment by singmann** [comment]
Thanks for the quick response. I guess this means that the results with an earlier version of `emmeans` were actually incorrect. And it looks like it. If we use simply `lm` we get:

```r
m2 <- lm(breaks ~ wool * tension,data=warpbreaks, 
         contrasts = list(wool = "contr.sum", tension = "contr.sum"))
emmeans::emmeans(m2, c("tension", "wool"))
#  tension wool emmean   SE df lower.CL upper.CL
#  L       A      44.6 3.65 48     37.2     51.9
#  M       A      24.0 3.65 48     16.7     31.3
#  H       A      24.6 3.65 48     17.2     31.9
#  L       B      28.2 3.65 48     20.9     35.6
#  M       B      28.8 3.65 48     21.4     36.1
#  H       B      18.8 3.65 48     11.4     26.1
# 
# Confidence level used: 0.95 
```

The means differ quite dramatically form the ones given by `rstanarm` as shown below. 
This can only be avoided when changing the contrasts globally (using `emmeans` `1.4.6`):

```r
library("rstanarm")
library("emmeans")

afex::set_default_contrasts()
m1 <- stan_glm(breaks ~ wool * tension, data = warpbreaks,
               contrasts = list(wool = "contr.sum", tension = "contr.sum"))
emmeans(m1, c("tension", "wool"))
#  tension wool emmean lower.HPD upper.HPD
#  L       A      28.2      25.2      31.0
#  M       A      36.3      31.2      41.5
#  H       A      26.3      21.3      31.5
#  L       B      31.0      26.8      35.1
#  M       B      44.4      37.3      52.1
#  H       B      24.0      16.9      31.3
# 
# Point estimate displayed: median 
# HPD interval probability: 0.95 

afex::set_sum_contrasts()
m3 <- stan_glm(breaks ~ wool * tension, data = warpbreaks)
emmeans(m3, c("tension", "wool"))
#  tension wool emmean lower.HPD upper.HPD
#  L       A      44.4      36.9      51.4
#  M       A      24.0      17.2      31.7
#  H       A      24.6      17.4      32.2
#  L       B      28.3      21.0      35.4
#  M       B      28.9      21.8      36.1
#  H       B      18.7      11.7      26.3
# 
# Point estimate displayed: median 
# HPD interval probability: 0.95 
```

**Comment by rvlenth** [comment]
Hmmm, that's surprising. The code used in 1.4.6 is still in my file, commented-out:
```r
    ### if(is.null(contr <- object$contrasts))
    ###     contr = attr(model.matrix(object), "contrasts")
    ### X = model.matrix(trms, m, contrasts.arg = contr)
```
... so it should have gotten the contrasts right. I could revert to the old code, but I guess you're saying it wasn't right either, and I changed the code due to some other issues that were reported (#202 and #204). Let's see if The Stan people respond fairly quickly.

**Comment by singmann** [comment]
Sounds reasonable to me to wait for `rstanarm` people. 

I can now clarify that it works in `1.4.6` if the contrasts are directly applied to the factor, but not if passed through the `contrasts` argument. So one need to either use this or set contrasts globally.

```r
devtools::install_version("emmeans", version = "1.4.6", upgrade = "never")

library("rstanarm")
library("emmeans")

afex::set_default_contrasts()
m1 <- stan_glm(breaks ~ wool * tension, data = warpbreaks,
               contrasts = list(wool = "contr.sum", tension = "contr.sum"))
emmeans(m1, c("tension", "wool"))  # differs from lm model
#  tension wool emmean lower.HPD upper.HPD
#  L       A      28.2      25.2      31.0
#  M       A      36.3      31.2      41.5
#  H       A      26.3      21.3      31.5
#  L       B      31.0      26.8      35.1
#  M       B      44.4      37.3      52.1
#  H       B      24.0      16.9      31.3
# 
# Point estimate displayed: median 
# HPD interval probability: 0.95 

warp2 <- warpbreaks
contrasts(warp2$wool) <- "contr.sum"
contrasts(warp2$tension) <- "contr.sum"
m4 <- stan_glm(breaks ~ wool * tension, data = warp2)
emmeans(m4, c("tension", "wool"))  # same as lm
#  tension wool emmean lower.HPD upper.HPD
#  L       A      44.5      37.3      51.7
#  M       A      24.0      16.7      31.3
#  H       A      24.6      16.7      31.5
#  L       B      28.2      21.1      35.5
#  M       B      28.9      21.4      36.0
#  H       B      18.8      11.4      25.8
# 
# Point estimate displayed: median 
# HPD interval probability: 0.95 


afex::set_sum_contrasts()
m3 <- stan_glm(breaks ~ wool * tension, data = warpbreaks)
emmeans(m3, c("tension", "wool"))  # same as lm
#  tension wool emmean lower.HPD upper.HPD
#  L       A      44.4      36.9      51.4
#  M       A      24.0      17.2      31.7
#  H       A      24.6      17.4      32.2
#  L       B      28.3      21.0      35.4
#  M       B      28.9      21.8      36.1
#  H       B      18.7      11.7      26.3
# 
# Point estimate displayed: median 
# HPD interval probability: 0.95 
```

**Comment by rvlenth** [comment]
Still no response from `stan-dev/rstanarm`. The issue report there, by the way, is https://github.com/stan-dev/rstanarm/issues/445. I pinged them today, maybe that'll help

**Comment by singmann** [comment]
I am currently working on a new package, [`stanova`](https://github.com/bayesstuff/stanova) that requires some of the functionality described here. Because passing the contrast does not work at all, the currently working version attaches the contrasts directly to the factor (as shown in my response). Unfortunately, this does not work with current `emmeans`, but only `1.4.6`. 

So if there is no response from the `rstanarm` tram, I think it would be great if the `1.4.6` functionality could be restored, so there would be at least a working version.

**Comment by rvlenth** [comment]
Henrik, well that comes between a rock and a hard place. There was a part that was broken before 1.4.6 that would be broken again if I revert. So which functionality should I break?

I'll see if I can get some attention to the **rstanarm** issue.

**Comment by jgabry** [comment]
Hi @singmann and @rvlenth very sorry for the slow reply! I'm trying to catch up on your discussion now. 

> I reported this in [stan-dev/rstanarm#444](https://github.com/stan-dev/rstanarm/issues/444). It seems that if they fix `pp_data()`, then it'll fix this issue too.

Do you still think that fixing #444 will also fix this? If so we'll focus on that.

**Comment by jgabry** [comment]
Sorry again for the delay on this. I think this should be fixed by this PR : https://github.com/stan-dev/rstanarm/pull/459, which fixes both stan-dev/rstanarm#444 and stan-dev/rstanarm#445.

**Comment by rvlenth** [comment]
Henrik,

Now that I understand the fix that was needed, I added a couple of statements to my code so that it will work correctly if either:

  * Jonah's patched version of **rstanarm** is installed

or

  * the contrasts are attached to each factor, even before the patched version reaches CRAN

I will be updating again to CRAN fairly soon.

**Comment by jgabry** [comment]
Great, thanks for pointing this out to us and adding a workaround for anyone who doesn't have the patched version! Sorry again it took so long to fix this.

**Comment by singmann** [comment]
My problem is indeed completely solved with the latest fix of `rstanarm` and now everything works perfectly even with current CRAN `emmeans`. Thanks both (@jgabry @rvlenth) for your help!
