### ISSUE TITLE
[feature] Adding support for lqmm

### ISSUE THREAD

**Issue by Generalized** [rvlenth/emmeans#213]
I found this article on Cross Validated:
https://stats.stackexchange.com/questions/457464/how-to-compute-custom-contrasts-for-linear-quantile-mixed-model-from-lqmm

The "Quick and dirty reference grid" is awesome helper, which worked nicely in this case. Since quantile regression and quantile LMM are more and more often used, would you consider adding it to the list of models supported by emmeans?

Of course - it's not about EM-means, I know :) But it is a way to jointly test the main/interaction effects and selected contrasts.

I know it's only a 3-4 lines of code, absolutely not a problem to me, but people often search of ready solutions, if it comes from the author, it's more trusted. It's definitely not urgent, rather a proposal to consider, as quantile models gain popularity. And your collection of supported model would grow :)

Please treat it as a very low priority, but nice addition.

**Comment by rvlenth** [comment]
OK, I have added rudementary support. There is one optional parameter `tau` that must exactly match one of `object$tau`. The default of `"0.5"` may or may not match.
```r
> emmeans(fit_lqmm, "age")
 age emmean    SE  df lower.CL upper.CL
   8   22.0 0.530 103     20.9     23.1
  10   22.9 0.432 103     22.0     23.7
  12   24.0 0.581 103     22.8     25.2
  14   25.5 0.659 103     24.2     26.8

Confidence level used: 0.95 
> emmeans(fit_lqmm, "age", tau = "0.9")
 age emmean   SE  df lower.CL upper.CL
   8   23.6 1.11 103     21.4     25.8
  10   24.5 1.22 103     22.1     26.9
  12   26.0 1.34 103     23.4     28.7
  14   28.0 1.29 103     25.4     30.5

Confidence level used: 0.95 
```
There is support for `lqm` objects as well.
