### ISSUE TITLE
Nesting fails if contrast is specified as specs in emmeans()

### ISSUE THREAD

**Issue by banfai** [rvlenth/emmeans#214]
If there is a contrast specified in `specs` and there is `nesting` passed on in `...` (e.g. `emmeans(m, specs = pairwise ~ group | time, nesting = "group %in% time")`) then `.update.options` fails in
https://github.com/rvlenth/emmeans/blob/fecb90a9baf2602fbda0347fcd0f4f7eb6b489a8/R/contrast.R#L453

See detailed analysis below the example.

``` r
library(emmeans)

d <- data.frame(
  group = c(rep(LETTERS[1:3], each = 2),
            rep(LETTERS[1:2], each = 2)),
  time = c(rep("day1", 6),
           rep("day2", 4)),
  y = rnorm(10, 5)
)

m <- lm(y ~ group * time, data = d)

# working
emmeans(m, specs = ~ group | time, nesting = "group %in% time") 
#> time = day1:
#>  group emmean    SE df lower.CL upper.CL
#>  A       5.91 0.776  5     3.92     7.90
#>  B       4.98 0.776  5     2.99     6.97
#>  C       4.77 0.776  5     2.78     6.77
#> 
#> time = day2:
#>  group emmean    SE df lower.CL upper.CL
#>  A       4.61 0.776  5     2.62     6.61
#>  B       5.54 0.776  5     3.54     7.53
#> 
#> Confidence level used: 0.95

# error is contrast.R:453 .update.options(result, options, ...)
emmeans(m, specs = pairwise ~ group | time, nesting = "group %in% time")
#> Error in (function (object, ..., silent = FALSE) : Nonexistent variables specified in 'nesting'
```

<sup>Created on 2020-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The problem is in the following line, if the `emmGrid` object is the `result` of `contrast.emmGrid()`:
https://github.com/rvlenth/emmeans/blob/fecb90a9baf2602fbda0347fcd0f4f7eb6b489a8/R/emmGrid-methods.R#L352

```r
lst = .parse_nest(args[[nm]])$group
#> $group
#> [1] "time"
nms = union(names(lst), unlist(lst))
#> [1] "group" "time" 

names(object@grid)
#> [1] "contrast" "time"
```

The variable to contrast on (`group`) becomes `contrast` with the contrast levels, so it is missing from `object@grid`.

**Comment by banfai** [comment]
Interestingly, this is working:
```r
rfgrd <- ref_grid(m, nesting = "group %in% time")
emmeans(rfgrd, specs = pairwise ~ group | time)
```

**Comment by rvlenth** [comment]
The second comment is what I was about to say is the workaround. That works because:

  * The best time to add nesting info is when the reference grid is constructed
  * the `nesting` argument is not passed to `contrast()`, which is implicitly called when the two-sided formula is used.

The code you highlight is where the error message occurs, but it isn't where the problem is -- which is at the end of the `emmeans()` code where the just-obtained `emmGrid` object is passed to `contrast()`, along with all the `...` arguments. I have added code to screen-out many of the `...` arguments that would be unsuitable, including `nesting`.

```r
> emmeans(m, specs = list(pairwise ~ group | time), nesti = "group %in% time")

$`emmeans of group | time`
time = day1:
 group emmean    SE df lower.CL upper.CL
 A       5.80 0.945  5     3.37     8.23
 B       5.63 0.945  5     3.20     8.06
 C       4.83 0.945  5     2.40     7.26

time = day2:
 group emmean    SE df lower.CL upper.CL
 A       4.04 0.945  5     1.61     6.47
 B       5.47 0.945  5     3.04     7.90

Confidence level used: 0.95 

$`pairwise differences of group | time`
time = day1:
 contrast estimate   SE df t.ratio p.value
 A - B       0.168 1.34  5  0.126  0.9913 
 A - C       0.968 1.34  5  0.725  0.7607 
 B - C       0.800 1.34  5  0.599  0.8269 

time = day2:
 contrast estimate   SE df t.ratio p.value
 A - B      -1.425 1.34  5 -1.066  0.3351 

P value adjustment: tukey method for comparing a family of 2 estimates 
```

Thanks for the report. That was a needed correction.

**Comment by banfai** [comment]
Thanks a lot for the quick fix. I can confirm that it is working properly now.
