### ISSUE TITLE
Extreme memory requirement for largish glmer models in emmeans 1.5.0 but not prior versions

### ISSUE THREAD

**Issue by singmann** [rvlenth/emmeans#218]
Hi Russ,

I found another weird bug. On my windows machine `emmeans` 1.5.0 but not prior versions shows a very strange behaviour for `lme4::glmer` models. It suddenly requires much more RAM than before making it unusable for many somewhat larger binomial data sets.

The following is some relatively large binomial example data that shows the problem on my machine with 16GB RAM.

```r
library("lme4")
set.seed(1)
nsamp <- 1e5
df <- data.frame(
  y = rbinom(nsamp, 1, 0.5),
  x = factor(rep(letters[1:2], each = nsamp/2)),
  g = sample(LETTERS[1:50], nsamp, replace = TRUE)
)

m1 <- glmer(y ~ x + (1|g), df, family = binomial)
emmeans::emmeans(m1, "x")
```

With `emmeans` 1.4.8 and earlier versions it works without problems:

```
 x   emmean     SE  df asymp.LCL asymp.UCL
 a -0.00361 0.0124 Inf   -0.0279    0.0207
 b  0.00576 0.0124 Inf   -0.0185    0.0300

Results are given on the logit (not the response) scale. 
Confidence level used: 0.95
```

However, in `1.5.0` the memory requirement is somehow a lot higher and the same call fails with:
```
Error: cannot allocate vector of size 20.2 Gb
```

Note that this is of course only example data, but data sets of this size are not uncommon and so far never showed a problem. I also could not find anything in the NEWS that could explain this change.

Best,
Henrik

**Comment by rvlenth** [comment]
Henrik,

My apologies for this. The new `submodel` option with `update.emmGrid()` has it save some additional model-matrix information with the object. While that additional storage is not significant at all for this example, getting there definitely is, as it entails constructing the matrix `diag(sqrt(weights))` which in this case is 10000 x 10000. For now, 

  * I added a `try()` in the code to disable it if something goes wrong. 
  * I also added a provisiion for side-stepping it altogether: `emm_options(enable.submodel = FALSE)`
  * In the longer term, I can obviously do this weighting more efficiently and I'll change the code to do that.

The patched code is now committed as version 1.5.0-1.

**Comment by singmann** [comment]
Hi Russ,

Thanks for the as usual extremely fast fix. 

Also, the `submodel` option looks pretty cool. Thanks for adding it. I have already played around with it a bit. I have one comment on the documentation of it though. 

At the moment, the information about it is split across the `update.emmGrid` help page and [the vignette](https://cran.r-project.org/package=emmeans/vignettes/xplanations.html#submodels). I started by looking at the vignette which ended with the following bit: 
> Again, this will not coincide with the results of `car::Anova(..., type = 2)` except in ordinary linear fixed-effects models.

However, in the vignette `car::Anova(..., type = 2)` does not appear before the final sentence that starts with "again". I understood it after reading the help page, but not before. Maybe it would be a good idea to copy the information from the help page to the vignette so that all is at one place. Would have helped me at least.

Thanks,
Henrik

**Comment by rvlenth** [comment]
Henrik, I hear you. That "xplanations" vignette is intended to be a technical supplement. My intention had been to introduce it in a rather low-key way; but I think I may have shot myself in the foot by documenting it at all. I do need to provide one or more good examples of using the `submodel` option. One easy place would be in the "messy data" vignette with the `nutrition` example -- where that'd be an alternative approach that would make things estimable.

And now I'm thinking it's better to down-play the re-fitting aspect of it, and emphasize the idea of adding constraints to the estimates. After all, even type-2 tests in `car::Anova()` (and in SAS) are only *related* to re-fitting a smaller model; the test itself is computed using the error term from the full model. As always, I'll be interested in your comments as I revise the documentation.

**Comment by singmann** [comment]
Hi Russ,

Yes, a simple example always makes things a lot easier to understand. 

The only thing I can offer is sadly somewhat lengthy, I have just finished a new vignette on [analysing accuracy data in psychology with ANOVA and GLMMs](http://singmann.github.io/afex/doc/afex_analysing_accuracy_data.html) which at the very end also touches upon the [Type II versus Type III question](http://singmann.github.io/afex/doc/afex_analysing_accuracy_data.html#type-iii-versus-type-ii-sums-of-squares). And the final code pieces now uses the new option. I hope it does so in the correct manner.

Best,
Henrik

**Comment by rvlenth** [comment]
Interesting. I'll take a look.

Russ

**Comment by rvlenth** [comment]
Henrik, You might want to take a look at #292 - where I figured out a way to pre-average nuisance variables, thereby saving a lot of storage. This may not be pertinent to this particular issue, but it is pertinent to models with lots of predictors, which I know you deal with from time to time.
