### ISSUE TITLE
Memory problems when using emmeans::emtrends() for lme4::lmer()-model on bigger data

### ISSUE THREAD

**Issue by henningsway** [rvlenth/emmeans#219]
I'm just learning how to best use marginal effects to communicate model results.

Currently I work with a linear mixed model (fit via `lme4::lmer()`), that includes a lot of interactions of a metric covariate with multiple factor variables. To summarise the effects of these categorial covariates on the (random) slopes of the model, I am experimenting with `emmeans::emtrends()` and `modelbased::estimate_slopes()`.

The results of smaller models seem promising, but when I use a model fit on the entire dataset (100k+ rows), the creation of the reference grid seems to create memory problems: `#> Error: cannot allocate vector of size 108.2 Gb`

Would it be appropriate to compute the marginal effects on a sample of the dataset and is there a straightforward approach to implement this, that you could recommend? (I've gone through the source of `emmeans::ref_grid()`, but had no success passing a sample to the `data` argument etc)

**Comment by rvlenth** [comment]
Please note Issue #218 where this is reported. If you can install the patched version from github, it should fix this problem.My apologies for tge inconvenience.

Sent from my iPad

On Aug 24, 2020, at 8:41 AM, Henning <notifications@github.com> wrote:

﻿

I'm just learning how to best use marginal effects to communicate model results.

Currently I work with a linear mixed model (fit via lme4::lmer()), that includes a lot of interactions of a metric covariate with multiple factor variables. To summarise the effects of these categorial covariates on the (random) slopes of the model, I am experimenting with emmeans::emtrends() and modelbased::estimate_slopes().

The results of smaller models seem promising, but when I use a model fit on the entire dataset (100k+ rows), the creation of the reference grid seems to create memory problems: #> Error: cannot allocate vector of size 108.2 Gb

Would it be appropriate to compute the marginal effects on a sample of the dataset and is there a straightforward approach to implement this, that you could recommend? (I've gone through the source of emmeans::ref_grid(), but had no success passing a sample to the data argument etc)

**Comment by rvlenth** [comment]
Another alternative, of course, would be to revert to CRAN version 1.4.8.

**Comment by henningsway** [comment]
This seems to solve the problem. Thank you so much for your fast reply! :)
