### ISSUE TITLE
After updatinf to 1.5.0, vector memory exhausted (limit reached?) 

### ISSUE THREAD

**Issue by julovi** [rvlenth/emmeans#222]
Hi,

I was using emmeans 1.3.2 on a rather large dataset without problems, then I update emmeans to 1.5.0 and I get the error in the title. Am I the only one having this issue? is there anything that I should be aware in this version?

Please advise,

**Comment by rvlenth** [comment]
No, you are not alone. Please see issues #218 and #219. If you install the patched version from GItHub, it will not have this problem.

Russ

Sent from my iPad

On Sep 6, 2020, at 9:34 PM, julovi <notifications@github.com> wrote:

﻿

Hi,

I was using emmeans 1.3.2 on a rather large dataset without problems, then I update emmeans to 1.5.0 and I get the error in the title. Am I the only one having this issue? is there anything that I should be aware in this version?

Please advise,

**Comment by julovi** [comment]
Thanks Russ,
I tried this:
export R_MAX_VSIZE=32000000000
and then invoking R from the Terminal, and this also work.
I was going to report that, but you were faster. Thanks a lot!
I'll try the patched version as well.

**Comment by rvlenth** [comment]
Closing - fixed in version 1.5.1
