### ISSUE TITLE
Auto-detection of dependent-variable transforms fails when formula specified outside of model fitting call

### ISSUE THREAD

**Issue by jmb01** [rvlenth/emmeans#223]
I just ran into a minor issue that I thought I'd bring to your attention.

It seems that dependent-variable transforms are not auto-detected in some cases when the model formula is specified outside of the model-fitting call. Using as.formula() in the model-fitting call seems to correct this for some reason. 

`
# the original model (taken from the documentation)
pigs.lm1 <- lm(log(conc) ~ source + factor(percent), data = pigs)

# specify the formula outside of the call to lm()
f <- log(conc) ~ source + factor(percent)

# fit the model
pigs.lm2 <- lm(formula = f, data = pigs)

# fit the model again, this time with as.formula()
pigs.lm3 <- lm(formula = as.formula(f), data = pigs)

# try to get back-transformed emmeans
emmeans(pigs.lm1, "source", type = "response")
emmeans(pigs.lm2, "source", type = "response")
emmeans(pigs.lm3, "source", type = "response")

Apologies if this has been addressed before. 
`

**Comment by rvlenth** [comment]
Thanks. I dinked with the order of evaluation and was able to get all three to work:
```r
> ref_grid(pigs.lm1)
'emmGrid' object with variables:
    source = fish, soy, skim
    percent =  9, 12, 15, 18
Transformation: “log” 

> ref_grid(pigs.lm2)
'emmGrid' object with variables:
    source = fish, soy, skim
    percent =  9, 12, 15, 18
Transformation: “log” 

> ref_grid(pigs.lm3)
'emmGrid' object with variables:
    source = fish, soy, skim
    percent =  9, 12, 15, 18
Transformation: “log” 
```
Plus an additional test to make sure I didn't mess-up some later code:
```r
> pigs.lm4 = lm(log(conc+1) ~ source + factor(percent), data = pigs)
> ref_grid(pigs.lm4)
'emmGrid' object with variables:
    source = fish, soy, skim
    percent =  9, 12, 15, 18
Transformation: “log(mu + 1)” 
```

**Comment by jmb01** [comment]
Thanks for your prompt response @rvlenth (and of course for the fantastic package in general).
