### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by wmayner** [rvlenth/emmeans#227]
I'd like to cite this package in a research paper. Is there a preferred way to do this?

**Comment by rvlenth** [comment]
Thanks for citing my package. It seems a lot of authors don't think to do that.

In R, you can do

    citation("emmeans")

and it will display a standard way of citing it -- in APA style, more or less. This works for other R packages too!

best,

Russ

Sent from my iPad

On Sep 23, 2020, at 10:11 PM, William Mayner <notifications@github.com> wrote:

﻿

I'd like to cite this package in a research paper. Is there a preferred way to do this?

**Comment by wmayner** [comment]
> It seems a lot of authors don't think to do that. 

Indeed. I think it should be done more :)

> In R, you can do citation("emmeans") and it will display a standard way of citing it -- in APA style, more or less. This works for other R packages too!

That's great, didn't know about that—thanks!
