### ISSUE TITLE
Plotting results with missing categories in interaction with emmeans

### ISSUE THREAD

**Issue by guilhermeparreira** [rvlenth/emmeans#228]
Hi There. I posted a [question](https://stackoverflow.com/questions/64082447/plotting-results-with-missing-categories-in-interaction-with-emmeans) (which may be an issue) on `stackoverflow`, but I did not get much help. 

Could someone have a look in the question, please? If necessary, I can rewrite the question here.

**Comment by rvlenth** [comment]
Answered on SO
