### ISSUE TITLE
emmeans vs. conditional effects (brms)

### ISSUE THREAD

**Issue by nahorp** [rvlenth/emmeans#229]
Hello,

I'm trying to reconcile some results from the `emmeans` function and the [`conditional_effects` function from `brms`](https://paul-buerkner.github.io/brms/reference/conditional_effects.brmsfit.html). I just feel like I'm missing something and would appreciate some insight.

So, the model is a Gamma model with a log link function (two categorical predictors, each with 2 levels, and the maximal model being fit). Let's look at one of the predictors, age_group.

a) The below is on the link scale

<img width="372" alt="Screen Shot 2020-09-30 at 3 45 10 pm" src="https://user-images.githubusercontent.com/43395036/94647512-eed3b780-0333-11eb-9c7e-b139da3dfc46.png">

b) The below is on the response scale

<img width="364" alt="Screen Shot 2020-09-30 at 3 46 16 pm" src="https://user-images.githubusercontent.com/43395036/94647572-16c31b00-0334-11eb-8dc9-08eeabd312a5.png">

All good till now, makes sense. However, when I run the `conditional_effects` function from `brms`, I see slightly different values...

c) `conditional_effects(model_fit, method = "posterior_linpred", robust = TRUE)`

<img width="376" alt="Screen Shot 2020-09-30 at 3 49 45 pm" src="https://user-images.githubusercontent.com/43395036/94647790-92bd6300-0334-11eb-9533-ba2959bacaa9.png">

My understanding is that this should be the same as the estimates in a) but both the estimate and 95% HPD is off...

d) `conditional_effects(model_fit, method = "posterior_epred", robust = TRUE)`

<img width="336" alt="Screen Shot 2020-09-30 at 3 53 00 pm" src="https://user-images.githubusercontent.com/43395036/94648031-065f7000-0335-11eb-86fe-d3852905d3ad.png">

e) `conditional_effects(model_fit, method = "posterior_predict", robust = TRUE)`

<img width="416" alt="Screen Shot 2020-09-30 at 3 55 03 pm" src="https://user-images.githubusercontent.com/43395036/94648175-51798300-0335-11eb-83c5-dbadee8812d2.png">

And either d) or e) should be somewhat similar to b)

What conceptual link am I missing about the slight differences?

**Comment by rvlenth** [comment]
I believe the issue here is that you have two factors. With `emmeans()` with just one of those factors, you are *not* looking at conditional effects, but rather the marginal means of those, averaged over the second factor. If you look at `emmeans(model, ~ other_factor | age_group, type = "response")` you may see more clarity.

Other issues include the fact that the point estimate by default is the median; you can change it to the mean if you like -- see `? hpd.summary`. And also by default, the averaging is done on the link scale before back-transforming. You can change that via `regrid(model)`.

**Comment by nahorp** [comment]
Thanks for that @rvlenth, I realised I was slightly misinterpreting the output from `conditional_effects`. Both of them give the same estimates of centrality, however the 95% credible interval is not the same...

<img width="288" alt="Screen Shot 2020-10-07 at 3 32 30 pm" src="https://user-images.githubusercontent.com/43395036/95287710-52209500-08b2-11eb-8d09-9b84ed350bd3.png">

For `conditional_effects` it is,

<img width="379" alt="Screen Shot 2020-10-07 at 3 41 45 pm" src="https://user-images.githubusercontent.com/43395036/95288272-9d877300-08b3-11eb-8437-68a02a3cb538.png">

For convenience sake, the 95% CIs from `conditional_effects` and `emmeans` are,

-0.1156 to 0.702 vs. -0.1254 to 0.684
-0.0792 to 0.641 vs. -0.0873 to 0.630
-0.2711 to 0.579 vs. -0.2689 to 0.580
-0.0811 to 0.463 vs. -0.088 to 0.454

I understand these are relatively minimal differences but I'm curious as to why they aren't the same...

**Comment by rvlenth** [comment]
I simply don't know why this discrepancy exists. All I can think is that these effects are defined differently. Mine are based on straightforward model predictions.

By the way, perhaps it is because I am in my seventies, but the contrast is very low and I can barely read these screen shots.

**Comment by nahorp** [comment]
Oh no, it's my screenshots that are the issues - I can't find the appropriate code at the moment to do the screenshots again but I'll just write them down here. The format of them is that the mean is presented first and then the lower and then upper HPD in parantheses.

**emmeans**

a) left old: 0.306 (-0.1254 to 0.684)
b) right old: 0.287 (-0.0873 to 0.630)
c) left Young: 0.147 (-0.2689 to 0.580)
d) right Young: 0.186 (-0.088 to 0.454)

**brms**

a) left old: 0.306 (-0.1156 to 0.702)
b) right old: 0.287 (-0.0792 to 0.641)
c) left Young: 0.147 (-0.2711 to 0.579) 
d) right Young: 0.186 (-0.0811 to 0.463)

**Comment by rvlenth** [comment]
Hmmm, looking at still-open issues and wondering where we are on this. Did you find out any more about these discrepancies?

**Comment by jmgirard** [comment]
Brms usually outputs percentile intervals rather than highest probability intervals (I believe, even when robust = TRUE). Perhaps this is the difference?

**Comment by rvlenth** [comment]
@nahorp -- Could you please test out @jmgirard 's comment please?

**Comment by jmgirard** [comment]
In case it helps, the [bayestestr](https://easystats.github.io/bayestestR/index.html) package implements both: `eti()` for the percentile approach and `hdi()` for the highest density approach.

**Comment by rvlenth** [comment]
Doing some housecleaning. I think this issue is pretty much over, so am closing. It can be re-opened and/or commented on further as needed
