### ISSUE TITLE
Emmeans model = "multivariate" SE formula

### ISSUE THREAD

**Issue by jorgesinval** [rvlenth/emmeans#236]
I would like to know which is the formula being used to estimate de standard errors when I set `model = "multivariate"` within the `emmeans `function. I did not found it in the documentation.

**Comment by rvlenth** [comment]
It's not completely clear, but I guess you are referring to the multivariate option associated with `afex::aov_ez()` results. But in fact that technicality doesn't matter much, as all standard errors are computed in the same way. It is calculated from the model's regression coefficients **b**, the variance-covariance matrix **V** thereof, and the coefficients **c** that are applied to **b**. The estimate is then **c'b**, and its standard error is `sqrt(`**c'Vc**`)` (in matrix notation).

Given these objects in R:
```r
model <- aov_ez(...)
emm <- emmeans(model, ..., model = "multivariate")
```
you can find these elements as follows:
```r
b <- emm@bhat   ### or coef(model$lm)
c <- emm@linfct   ### each row is one set of coefficients
V <- emm@V   ### or vcov(model$lm)
```
Note that what `emmeans()` does is to figure out what **c** is needed for each EMM. The same is true for contrasts thereof. For example, for pairwise comparisons, use `c <- pairs(emm)@linfct` (`b` and `V` will be the same).
