### ISSUE TITLE
cld throws error when number of contrasts differ among groups

### ISSUE THREAD

**Issue by SimonShamusRiley** [rvlenth/emmeans#239]
Line 137 of cld-emm.R uses the number contrasts in the first "by group" to define expected number of contrasts for all "by groups", with the result that cld throws an error when they  are not equal equal:  

A simple example:
```{r}
library(agridat)
library(nlme)
library(emmeans)
library(multcomp)

oats = agridat::yates.oats
simple = oats$nitro < 0.6
miss = oats$gen == 'Victory' & oats$nitro == 0.4
oats = oats[simple & !miss, ]
table(oats$nitro, oats$gen)

oats$nitro = factor(oats$nitro)
oats$trt = interaction(oats$nitro, oats$gen)
oats = droplevels(oats)

fit = lme(yield ~ trt, oats, random = ~1|block/gen)
fit.rg = ref_grid(fit)
genotypes = levels(fit.rg)$trt
genotypes = sapply(genotypes, gsub, pattern = "[0-9.]", replacement = '', USE.NAMES = F)
fit.regrouped = add_grouping(fit.rg, 'gen', 'trt', newlevs = genotypes)
fit.emm = emmeans(fit.regrouped, ~ trt|gen)
fit.contr = pairs(fit.emm, adjust = 'none')
cld(fit.contr)
```

**Comment by rvlenth** [comment]
OK, I can replicate this error, but please note that `cld(fit.emm)` is what is needed to display the comparisons in `fit.contr`. `cld(fit.contr)`, if it worked, would compare the comparisons.

That said, `cld(fit.emm)` throws the same error. I'll look at it.

[Did you know that `cld()` is the bane of my existence? That of course is beside the point.]

**Comment by rvlenth** [comment]
You did indeed identify the code lines in question. I moved certian code to inside the loop and now it works correctly. The next push to GitHub will have this fixed.
```r
> emmeans:::cld.emmGrid(fit.emm, adjust = "none")

gen = GoldenRain:
 trt            emmean   SE df lower.CL upper.CL .group
 0.GoldenRain     80.0 8.63  5     57.8    102.2  1    
 0.2.GoldenRain   98.5 8.63  5     76.3    120.7   2   
 0.4.GoldenRain  114.7 8.63  5     92.5    136.9    3  

gen = Marvellous:
 trt            emmean   SE df lower.CL upper.CL .group
 0.Marvellous     86.7 8.63  5     64.5    108.9  1    
 0.2.Marvellous  108.5 8.63  5     86.3    130.7   2   
 0.4.Marvellous  117.2 8.63  5     95.0    139.4   2   

gen = Victory:
 trt            emmean   SE df lower.CL upper.CL .group
 0.Victory        71.5 8.63  5     49.3     93.7  1    
 0.2.Victory      89.7 8.63  5     67.5    111.9   2   

Degrees-of-freedom method: containment 
Confidence level used: 0.95 
significance level used: alpha = 0.05 
```

Thanks for reporting this. My (rather weak) excuse is that this code was written before I added nesting capabilities. Beforee then, the reference grid was always regular. When I added nesting capabilities, I modified `emmeans()`, `emtrends()`, and `contrast()` suitably, but somehow overlooked `cld()`.  In case you don't already know, I recommend against using `cld()` and recommend `pwpp()` or `pwpm()` instead.
```r
> pwpm(fit.emm, adjust = "none")

gen = GoldenRain
               0.GoldenRain 0.2.GoldenRain 0.4.GoldenRain
0.GoldenRain        [ 80.0]         0.0264         0.0002
0.2.GoldenRain        -18.5        [ 98.5]         0.0496
0.4.GoldenRain        -34.7          -16.2        [114.7]

gen = Marvellous
               0.Marvellous 0.2.Marvellous 0.4.Marvellous
0.Marvellous        [ 86.7]         0.0102         0.0007
0.2.Marvellous       -21.83        [108.5]         0.2779
0.4.Marvellous       -30.50          -8.67        [117.2]

gen = Victory
            0.Victory 0.2.Victory
0.Victory      [71.5]      0.0290
0.2.Victory     -18.2      [89.7]

Row and column labels: trt
Upper triangle: P values 
Diagonal: [Estimates] (emmean) 
Lower triangle: Comparisons (estimate)   earlier vs. later
```
... and *[head pounding]* `pwpp()` does not work with this example either, so no push to GitHub until I fix it too.

**Comment by rvlenth** [comment]
Have it working now
```r
pwpp(fit.emm, adjust = "none")
```
![image](https://user-images.githubusercontent.com/26777519/98306565-b4d87f80-1f89-11eb-92de-c8bf737177a4.png)

**Comment by SimonShamusRiley** [comment]
Thanks for addressing this so quickly! And yes, I am aware of the shortcomings of compact letter displays and the alternatives the package provides for (oh how I wish every other package on CRAN was documented even half as well as `emmeans`) but its what the client wants, and we all have to pick our battles. A cop out, perhaps, but there you have it.
