### ISSUE TITLE
CLD yields incoherent results

### ISSUE THREAD

**Issue by lselzer** [rvlenth/emmeans#24]
Hello, I was trying out an example for my class and found some surprising results using `cld()`

```
library(emmeans)

fert_long <- structure(list(Finca = structure(c(1L, 2L, 3L, 4L, 5L, 1L, 2L, 
                                                3L, 4L, 5L, 1L, 2L, 3L, 4L, 5L),
                                              .Label = c("1", "2", "3", "4", 
                                                         "5"), class = "factor"), 
                            Fertilizante = c("Fertilizante.1", "Fertilizante.1", 
                                             "Fertilizante.1", "Fertilizante.1", "Fertilizante.1", "Fertilizante.2", 
                                             "Fertilizante.2", "Fertilizante.2", "Fertilizante.2", "Fertilizante.2", 
                                             "Fertilizante.3", "Fertilizante.3", "Fertilizante.3", "Fertilizante.3", 
                                             "Fertilizante.3"), 
                            Produccion = c(1, 2, 7, 6, 12, 5, 8, 9, 13, 
                                           14, 8, 14, 16, 18, 17)), class = "data.frame", 
                       .Names = c("Finca", 
                                  "Fertilizante", "Produccion"), row.names = c(NA, -15L))

fert_aov <- aov(Produccion ~ Fertilizante + Finca, data = fert_long)
fert_lsm <- emmeans(fert_aov, pairwise ~ Fertilizante)
cld(fert_lsm)
```

This yields in:

```
$emmeans
 Fertilizante   emmean       SE df  lower.CL  upper.CL .group
 Fertilizante.1    5.6 0.772442  8  3.818746  7.381254  1    
 Fertilizante.2    9.8 0.772442  8  8.018746 11.581254   2   
 Fertilizante.3   14.6 0.772442  8 12.818746 16.381254    3  

Results are averaged over the levels of: Finca 
Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 3 estimates 
significance level used: alpha = 0.05 

$contrasts
 contrast                        estimate       SE df t.ratio p.value .group
 Fertilizante.1 - Fertilizante.3     -9.0 1.092398  8  -8.239  0.0001  1    
 Fertilizante.2 - Fertilizante.3     -4.8 1.092398  8  -4.394  0.0058   2   
 Fertilizante.1 - Fertilizante.2     -4.2 1.092398  8  -3.845  0.0121   2   

Results are averaged over the levels of: Finca 
P value adjustment: tukey method for comparing a family of 3 estimates 
significance level used: alpha = 0.05 
```
emmeans results is correct, but I find the constrast section kind of misleading. I think, the contrast between Fertilizante.1 - Fertilizante.2 should result in .group 3.

Is this a bug or a feature?

**Comment by rvlenth** [comment]
It's a feature, but not necessarily a well-understood one.

I'll preface my explanation by saying that my two greatest regrets in developing this package are (1) providing contrast specification in the left-hand side of the formula, and (2) including the `cld()` function. Both have been a reliable source of misunderstandings and headaches; and they are combined in this example. Both these features are quite user-convenient; however, both (especially `cld()`) provide for a kind of routinized approach to analysis (which I don't like but am unwittingly encouraging); and they create their own kinds of misunderstandings.

Here is what is happening: First, the call `emmeans(fert_aov, pairwise ~ Fertilizante)` creates an `emm_list` object, which is a *list* of two `emmGrid` objects -- even though users have a hard time distinguishing between that and just one `emmGrid` object. Second, I have designed (mis-designed?) the methods for `emm_list` to apply the `emmGrid` method to each element of the `emm_list`.

Thus, in this example, `cld()` is applied to each of the tables you see, *separately*. The `.group` column in the first table applies to comparisons among the rows of that table, as you correctly understood it. But in the second table, the `.group` column refers to comparisons of the rows of *that* table. Those comparisons (using abbreviated names) are `(F1 - F3) - (F2 - F3) = F1 - F2`, `(F1 - F3) - (F1 - F2) = F2 - F3`, and `(F2 - F3) - (F1 - F2) = 2*F2 - F1 - F3`. Note that the observed estimates of the 2nd and 3rd contrasts are -4.8 and -4.2, which are not very different and hence are in the same group, whereas the first estimate of -9.0 is markedly different from the other two.

Here are some things I could do to try to reduce confusion about this sort of thing:

1. Deprecate the `cld()` method (boy, is that tempting!)
2. Completely remove the `cld()` method for `emm_list` objects, forcing users to apply it to only one `emmGrid` object at a time
3. Have `cld` refuse to run and/or issue a warning message when the table already contains contrasts
4. Add more annotations to the output, e.g., "`Groupings shown apply to comparisons among the rows of this table`"
5. Something else I haven't considered
6. Some combination of these 

Any opinions?

**Comment by rvlenth** [comment]
Another observation: In a way, I should applaud a person who runs a call like in your example, because you are asking for groupings but also the details of testing each comparison -- whereas without the `pairwise ~` part, you just get groupings. I think that boosts the desirability of my option (3).

**Comment by rvlenth** [comment]
Second observation: This confusion can only occur when comparing 3 means. If it were 2, there'd be only one row in the second table, and if it were 4, there would be 6 rows in the second table.

**Comment by lselzer** [comment]
Thanks for your quick response!

Yes, I have run again without the `pairwise ~` and I see what `cld()` is doing.  Please, don't take it away I think it's a very useful way to see multiple comparisons. Expecially when there are a lot of levels. 

Is there a reason to run cld on all the elements of the list? Wouldn't it make more sense to just have it process the `emmeans` item of that list? I think it doesn't make much sense to group the contrasts.

**Comment by rvlenth** [comment]
An `emm_list` object can come from a variety of user actions, and it's hard to predict which elements "should" have grouping letters, other than that there is a flag stored when contrasts were computed. (Also, in some cases, people do want to do multiple comparisons of contrasts.)

Here's an idea: I could add a `cld` argument to `summary.emmGrid` so that a call like 
```
emmeans(model, pairwise ~ treatment, cld = TRUE)
```
would add groupings to the EMMs table but would revert `cld = FALSE` as the summarization option for the pairwise comparisons.

With this in place, I would phase out the `cld` method  over a year or so. Once it's gone, I'd still have the capability without having to import **multcomp**, which currently I am forced to do (to have the generic for `cld`) even though most users don't need that package at all.

**Comment by lselzer** [comment]
I don't know why someone would want to compare contrasts. I probably lack imagination to see the use of that. But I think that adding `cld `as a argument would work. The minor drawback of this option is that all the arguments of `cld()` would need to be moved to `emmeans()`

**Comment by rvlenth** [comment]
Comparing contrasts isn't all that unusual. For example, we have two factors: `treatment` (assigned to subjects randomized into groups) and `trial` (pre-test, post-test). First we obtain contrasts for `trial` (post minus pre), then we compare those differences among treatments.

I have decided to follow the maxim that "if it ain't broke, don't fix it." Really, `cld()` functions exactly as documented. I see why it can be confusing when applied to three treatments and comparisons thereof; but attempting to remedy that will just create transition woes and some other kind of confusion. So I think it will simply leave it exactly as-is, but with one very small change: a message that appears when `cld()` is called on an `emm_list`, that says that `cls()` was applied separately to each element.

**Comment by rvlenth** [comment]
BTW, in case you don't know, you can already do:
```
cld(fert_lsm, which = 1)
```
and the groupings will only be done for the first table.

**Comment by lselzer** [comment]
Thank you Russell. Yes, I think too it's best leave as it is. I wasn't aware of what `cld()` was doing. Now, it's clear.
