### ISSUE TITLE
Odd ratio for a 2-way interaction

### ISSUE THREAD

**Issue by OmidGhasemi21** [rvlenth/emmeans#241]
I am trying to follow-up one of the interactions in my GLM model. based on odd ratios, the difference between conflict and non-conflict is larger under logic instructions.

```
library (afex)
library(emmeans)

m1 <- mixed (pseudo_accuracy ~ conf*instruction* sub_type* general_ability + (conf+instruction|subj_id),
                          data2, method = "LRT",
                          control = glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 1e6)),
                          expand_re = TRUE, family=binomial(link="logit"), cl = cl)


###--- conflict x instruction----###

update(pairs(emmeans(m1, "conf", by= "instruction", type = "response")), by = NULL, adjust = "holm")

# contrast              instruction     odds.ratio   SE  df z.ratio p.value
# non_conflict / conflict Logic            10.65 2.81 Inf 8.972   <.0001 
# non_conflict / conflict Belief            6.95 1.61 Inf 8.375   <.0001 
```

However, judging based on the plots, it is obvious that the difference between the two conflict condition is larger under belief instructions.

```
plot(emmeans(m1, "conf", by= "instruction", type = "response"))
```

<img width="704" alt="Screen Shot 2020-11-06 at 10 03 57 am" src="https://user-images.githubusercontent.com/45413424/98306218-830dfa00-2017-11eb-8eec-839460f08a46.png">

I was wondering if I am interpreting odd ratios incorrectly or there is a problem in the way that I am using emmeans. Thank you.

**Comment by rvlenth** [comment]
Well, reading the values from the plot, I get about the same results:
```r
> (.99/.01) / (.90/.10)
[1] 11

> (.97/.03) / (.82/.18)
[1] 7.097561
```
You are not comparing probabilities, and odds of .99/.01 is about 3 times as big as .97/.03.
