### ISSUE TITLE
lme doesn't work with ggemmeans, but it does directly in emmeans

### ISSUE THREAD

**Issue by mamscience** [rvlenth/emmeans#242]
Hi
I've been building a linear mixed model and I want to display marginal means that can be derived. I managed to pull the data manually from emmeans but I cannot through ggemmeans. 

When I feed ggemmeans the model it throws an error instead, saying:
```
Reason: 'arg' should be one of “containment”, “satterthwaite”, “appx-satterthwaite”, “auto”, “boot-satterthwaite”
You may try 'ggpredict()' or 'ggeffect()'.
```
However, if I pass the model directly into emmeans I don't get such an error. I tried to pass the "mode" argument to fix this (at least I think this is the argument the error refers to), but it only throws more errors. 

I've attached the reprex. Please ignore the other error in throws, it's because the model is supersimplified and the data is not meaningful.

Thanks in advance!
Michel

```
library(nlme)
library(ggeffects)
reprex <- data.frame(time = c(0,1,2,3,4, 0, 1,2,3,4), group=c(1,1,1,1,1, 2,2,2,2,2), id=c(10,10,10,10,10,15,15,15,15,15), sum=c(0,5,10,15,20, 0,20,25,45,50))

reprexmodel <-  lme(log(sum+1)  ~ time * group        
                                random  = ~ 1|id,
                                correlation = corAR1(form =~  as.numeric(time)| id), 
                                data=reprex, na.action = na.exclude)

ggemmeans(reprexmodel, c("time [all]","group")) %>% plot(colors="hero")
```

**Comment by rvlenth** [comment]
Since you say this works correctly with `emmeans()`, I don't understand why this isbeing  reported as an issue for the **emmeans** package. It seems like it is an issue with the **ggeffects** package, which I do not maintain. Am I missing something?

In addition, there is an error in the model code -- should be a comma after the first line. So I'm not sure how you got this to run.

**Comment by mamscience** [comment]
You are absolutely right, I posted it to the wrong repo. Thanks for your reply!
