### ISSUE TITLE
Feature Request: Clarify what level is missing when character levels are used

### ISSUE THREAD

**Issue by billdenney** [rvlenth/emmeans#246]
I had an issue where I was trying to calculate the difference between levels, but I couldn't get the level name right.  With some sleuthing, I found that the available levels had parentheses added around them before checking for the level name.  It would help track down the issue I was having if the levels were shown.  This could be via a modification to the `.num.key()` function as follows.

With the code below, I got the error message that helped me isolate the problem:

```r
Error in .num.key(levs, ref) : 'ref' levels are out of range.
  Tried to find level, 'PART 1 DAY -1'
  Available levels are: '(PART 1 DAY -1)', '(PART 1 DAY -2)', '(PART 1 DAY -3)', '(PART 1 DAY -4)', 'PART 1 DAY 1', 'PART 1 DAY 2', 'PART 1 DAY 3', 'PART 1 DAY 4', 'PART 1 DAY 5'
```

I'm happy to make a PR for this, if it is of interest.

```r
.num.key <- function(levs, key) {
  orig.key = key
  if (is.character(key)) {
    key = match(key, levs)
    if (is.na(key)) {
      stop(
        sprintf(
          "'ref' levels are out of range.\n  Tried to find level, '%s'\n  Available levels are: %s",
          orig.key,
          paste("'", levs, "'", collapse=", ", sep="")
        )
      )
    }
  }
  key[key %in% seq_along(levs)]
}
```

**Comment by rvlenth** [comment]
There is a way to control whether things are parenthesized: the `parens` argument in `contrast()` or  `emm_options(parens = ...)`. It allows one to specify a regular expression for when levels are parenthesized. See `? contrast`.

As for the suggested change, I see the issue but I don't think that's the best way to fix it. I will look and see if somehow we can run `.num.key` *before* the parenthesization is done. Then you can use `levels()` or look at a previous summary and be able to rely on that.

**Comment by rvlenth** [comment]
I think I have this working:

```r
> emm = emmeans(warp.lm, "tension")

> levels(emm)
$tension
[1] "L" "M" "H"

> levels(emm)$tension = c("low-", "med", "hi+")

> emm
 tension emmean  SE df lower.CL upper.CL
 low-      36.4 2.8 51     30.8     42.0
 med       26.4 2.8 51     20.8     32.0
 hi+       21.7 2.8 51     16.0     27.3

Confidence level used: 0.95 

> pairs(emm)
 contrast       estimate   SE df t.ratio p.value
 (low-) - med      10.00 3.96 51 2.525   0.0385 
 (low-) - (hi+)    14.72 3.96 51 3.718   0.0014 
 med - (hi+)        4.72 3.96 51 1.192   0.4631 

P value adjustment: tukey method for comparing a family of 3 estimates 

> pairs(emm, exclude = "hi+")
 contrast     estimate   SE df t.ratio p.value
 (low-) - med       10 3.96 51 2.525   0.0147 
```
I just saved the original levels as an attribute to `levs` and then get `.num.key` to use that attribute

**Comment by billdenney** [comment]
Thanks for the quick response!

I agree that running `.num.lev()` before parenthesization is done is the best solution.  That said, I think that keeping an error message like I added would still help.

Keeping the error message would help find a typo in the code, if, for example, I typed `pairs(emm, exclude = "hi plus")` it would notify the user that "hi plus" is not a level and clarify what can be used (i.e. point the user to the solution to the problem).

**Comment by rvlenth** [comment]
I suppose, but aren't there about a zillion other cases where people get a cryptic error message if they make a typo? With this fix, it really is easy to see what the possibilities are for levels

**Comment by billdenney** [comment]
There are a zillion.  My thought was to make it a zillion minus 1.  :)

You are right, that this fix makes it much easier to resolve the issue, though.

**Comment by rvlenth** [comment]
By the way, a reminder that you can always use the numeric positions rather than their character values...
```r
> pairs(emm, exclude = 3)
 contrast     estimate   SE df t.ratio p.value
 (low-) - med       10 3.96 51 2.525   0.0147 

> contrast(emm, "trt.vs.ctrl", ref = 1)
 contrast       estimate   SE df t.ratio p.value
 med - (low-)      -10.0 3.96 51 -2.525  0.0282 
 (hi+) - (low-)    -14.7 3.96 51 -3.718  0.0010 

P value adjustment: dunnettx method for 2 tests 

> contrast(emm, "trt.vs.ctrl", ref = "low-")
 contrast       estimate   SE df t.ratio p.value
 med - (low-)      -10.0 3.96 51 -2.525  0.0282 
 (hi+) - (low-)    -14.7 3.96 51 -3.718  0.0010 

P value adjustment: dunnettx method for 2 tests 
```

**Comment by rvlenth** [comment]
I sort of, almost, addressed this, within my comfort zone; so am closing.

**Comment by billdenney** [comment]
I definitely appreciate all the work you do on `emmeans`, and thank you for the help here.  (I didn't want to push outside of your comfort zone.  Sorry if it seemed like that was my intent.)

**Comment by rvlenth** [comment]
No, I'm fine; just acknowledging I didn't address this in quite the way you had requested.
