### ISSUE TITLE
Bootstrap estimates / CIs / tests - as Bayesian?

### ISSUE THREAD

**Issue by mattansb** [rvlenth/emmeans#254]
Not so much an "issue", but I was wondering if the following makes sense:

1. Bootstrap model parameters / coefficients. 
2. Build a reference grid using `qdrg()` ***with (1) in the `post.beta` slot***.
3. Get means / contrasts / CIs

Would this method make sense? In other words, do the "Bayesian" methods apply when working not with posteriors, but with bootstrapped sampling distributions?

Thanks!

**Comment by rvlenth** [comment]
Makes sense to me. Just don't claim it's a Bayesian estimate, because there isn't necessarily a prior that could have led to those results. So call it bootstrap or simulation.

In fact, `regrid()` already implements a parametric bootstrap method -- parameterized by a multivariate normal with the estimated regression coefficients and covariance matrix as parameters. For example:
```r
example(pigs)
# ...
emm <- emmeans(pigs.lm, "source")
emms <- regrid(emm, transform = "pass", N.sim = 1000)
```
To use your own bootstrap sample instead, just do
```r
emmb <- update(emm, post.beta = my.samp)
```
where `'my.samp` is an *N* by *p* matrix of *N* bootstrap samples, each row being a bootstrap result of a vector of the *p* regression coefficients. (Note that your code is likely to product a *p* x *N* matrix because R stores matrices column-wise.) You need to make sure your bootstrap code generates the regression coefficients in the exact same order as is stored in `emm@bhat`.

**Comment by mattansb** [comment]
Great - thanks!
Looking into adding this optionality to the `parameters` package (https://github.com/easystats/parameters/pull/411).

I wonder if you would consider adding some frequentist options for such cases, such as bootstrap p-values, which would look something like this:

```r
if (side == -1) {
  k <- sum(est > null)
} else if (side == 1) {
  k <- sum(est < null)
} else {
  k <- 2 * min(sum(est > null), sum(est < null))
}

p <- (1 + k) / (1 + R)
```

Where `est` is the estimate, and `R` is the number of samples.

(Based on Hinkley (1997), Bootstrap Methods and their Application (p. 141))

**Comment by mattansb** [comment]
If we can distinguish between bootstrapped distributions and Bayesian posteriors (how?), it would also be nice to have the bootstrapped standard error.

These are just ideas (:

**Comment by rvlenth** [comment]
Interesting suggestion, and yes, it would require distinguishing between bootstrap and Bayes methods. That could be done; however, there are several other issues, such as how to deal with the `adjust` method, and whether to make incorporating bootstrap samples a global possibility. I'm not sure I want to go there.

Since your wishes have to do with incorporating new features in your package, I wonder if another option might be to override my `summary.emmGrid()` method with your own. Or more simply, by just obtaining the summary and then adding your bootstrapped P values to that summary before pushing it out to users. Would that work?

**Comment by mattansb** [comment]
That sounds like a big undertaking (I would essentially have to also update my `summary.emmGrid()` and `test()` functions anytime that you do, no?)...

I would be more than happy to help / contribute to implementing these here 😊

E.g., for `adjust` it is maybe possible to only support a Bonferroni correction? I am not aware of any other methods for adjustment that can be used for building CIs (or perhaps use the standard `p.adjust()` methods for p-values, and Bonferroni for CIs? This currently how `adjust = "fdr"` is handled).

**Comment by rvlenth** [comment]
No. It would be a bad idea to have something that depends that closely on my code. I'm thinking of something more like this within your package:
```r
do.bootstrap <- function(model, ...) {
    boot <- [... code to get bootstrap sample ...]
    emm <- update(emmeans(model, post.beta = boot)  # uses existing emmeans function
    summ <- hpd.summary(emm, point.est = mean)   # uses existing emmeans function
    bpval <- [... code to do bootstrap p values based on 'boot'  ...]
    summ$lower.HPD <- summ$upper.HPD <- NULL # (remove HPD interval, if you like)
    summ$boot.p.value <- bpval   $ add your bootstrap P values to the summary
    summ
}
```
This would return a `summary_emm` object with your bootstrap P values.

You could break this into two parts if you want to keep the `emm` results around for other purposes. But the point is you do not need to duplicate the code in **emmeans**, nor modify your code everytime I might change the `summary.emmGrid()` method.

**Comment by mattansb** [comment]
Okay I think I got it (:

``` r
library(parameters)
library(emmeans)

model <- lm(mpg ~ log(wt) + factor(cyl), data = mtcars)

b <- bootstrap_model(model, iterations = 200)
head(b)
#>   (Intercept)    log(wt) factor(cyl)6 factor(cyl)8
#> 1    36.46131 -11.560678    -2.812094    -6.490717
#> 2    35.83840 -11.659278    -2.939326    -4.954303
#> 3    33.93339  -8.265368    -4.930780    -7.465152
#> 4    35.13361 -10.936834    -2.721181    -5.489724
#> 5    37.54310 -12.949904    -2.898492    -3.961795
#> 6    38.50275 -13.195065    -3.185524    -5.644229

(em_ <- emmeans(b, consec ~ cyl))
#> $emmeans
#>  cyl emmean lower.HPD upper.HPD
#>    4   22.4      20.5      25.3
#>    6   19.3      18.4      20.0
#>    8   17.4      16.3      18.6
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95 
#> 
#> $contrasts
#>  contrast estimate lower.HPD upper.HPD
#>  6 - 4       -3.21     -6.12    -1.152
#>  8 - 6       -1.87     -3.42    -0.234
#> 
#> Point estimate displayed: median 
#> HPD interval probability: 0.95

model_parameters(em_)
#> # Estimated Marginal Means
#> 
#> Parameter | Coefficient |   SE |         95% CI |     p
#> -------------------------------------------------------
#> 4         |       22.40 | 1.27 | [20.53, 25.30] | 0.005
#> 6         |       19.27 | 0.42 | [18.40, 20.02] | 0.005
#> 8         |       17.38 | 0.59 | [16.25, 18.57] | 0.005
#> 
#> # Contrasts
#> 
#> Parameter | Coefficient |   SE |         95% CI |     p
#> -------------------------------------------------------
#> 6 - 4     |       -3.21 | 1.31 | [-6.12, -1.15] | 0.025
#> 8 - 6     |       -1.87 | 0.78 | [-3.42, -0.23] | 0.035
```

<sup>Created on 2021-02-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thanks for all your help!

**Comment by rvlenth** [comment]
Looks good, but I thought you were going to include bootstrap P values n there somewhere

Sent from my iPad

On Feb 2, 2021, at 4:40 AM, Mattan S. Ben-Shachar <notifications@github.com> wrote:

﻿

Okay I think I got it (:

library(parameters)
library(emmeans)

model <- lm(mpg ~ log(wt) + factor(cyl), data = mtcars)

b <- bootstrap_model(model, iterations = 200)
head(b)
#>   (Intercept)    log(wt) factor(cyl)6 factor(cyl)8
#> 1    36.46131 -11.560678    -2.812094    -6.490717
#> 2    35.83840 -11.659278    -2.939326    -4.954303
#> 3    33.93339  -8.265368    -4.930780    -7.465152
#> 4    35.13361 -10.936834    -2.721181    -5.489724
#> 5    37.54310 -12.949904    -2.898492    -3.961795
#> 6    38.50275 -13.195065    -3.185524    -5.644229

(em_ <- emmeans(b, consec ~ cyl))
#> $emmeans
#>  cyl emmean lower.HPD upper.HPD
#>    4   22.4      20.5      25.3
#>    6   19.3      18.4      20.0
#>    8   17.4      16.3      18.6
#>
#> Point estimate displayed: median
#> HPD interval probability: 0.95
#>
#> $contrasts
#>  contrast estimate lower.HPD upper.HPD
#>  6 - 4       -3.21     -6.12    -1.152
#>  8 - 6       -1.87     -3.42    -0.234
#>
#> Point estimate displayed: median
#> HPD interval probability: 0.95

model_parameters(em_)
#> # Estimated Marginal Means
#>
#> Parameter | Coefficient |   SE |         95% CI |     p
#> -------------------------------------------------------
#> 4         |       22.40 | 1.27 | [20.53, 25.30] | 0.005
#> 6         |       19.27 | 0.42 | [18.40, 20.02] | 0.005
#> 8         |       17.38 | 0.59 | [16.25, 18.57] | 0.005
#>
#> # Contrasts
#>
#> Parameter | Coefficient |   SE |         95% CI |     p
#> -------------------------------------------------------
#> 6 - 4     |       -3.21 | 1.31 | [-6.12, -1.15] | 0.025
#> 8 - 6     |       -1.87 | 0.78 | [-3.42, -0.23] | 0.035

Created on 2021-02-02 by the reprex package<https://reprex.tidyverse.org> (v0.3.0)

Thanks for all your help!

**Comment by mattansb** [comment]
I have - they're in the rightmost column in the `model_parameters()` output.

**Comment by rvlenth** [comment]
Aha -- my excuse is I was looking at it on a tablet, and the lines wrapped...
