### ISSUE TITLE
Interaction contrasts on the response scale?

### ISSUE THREAD

**Issue by nahorp** [rvlenth/emmeans#255]
Hello :)

The below works perfectly to get the interaction contrast on the link scale but I was wondering if there is a way to get the interaction contrasts on the _response_ scale?

`contrast(emmeans(model_fit, ~ A*B), interaction = c("pairwise", "pairwise"))`

I've tried both of the below, to no avail however...

`contrast(emmeans(model_fit, ~ A*B, type = "response"), interaction = c("pairwise", "pairwise"))` and

`contrast(emmeans(model_fit, ~ A*B), interaction = c("pairwise", "pairwise"), type = "response")`

**Comment by rvlenth** [comment]
The short answer is that contrasts, much less interaction contrasts, generally can't be back-transformed. Here's an illustration with simple made-up numbers. In this example, the link scale is the square root.
```r
> EMM
 dose treat emmean SE df asymp.LCL asymp.UCL
 L    a          7  1 NA      5.04      8.96
 H    a          5  1 NA      3.04      6.96
 L    b          4  1 NA      2.04      5.96
 H    b          3  1 NA      1.04      4.96
 L    c          2  1 NA      0.04      3.96
 H    c          2  1 NA      0.04      3.96

Results are given on the sqrt (not the response) scale. 
Confidence level used: 0.95 
```
And here are the interaction contrasts computed on the link scale:
```r
> contrast(EMM, interaction = "pairwise")
 dose_pairwise treat_pairwise estimate SE df z.ratio p.value
 L - H         a - b                 1  2 NA 0.500   0.6171 
 L - H         a - c                 2  2 NA 1.000   0.3173 
 L - H         b - c                 1  2 NA 0.500   0.6171 
```
Can you tell me what the values of these interaction contrasts should be after back-transforming? Two of these interaction contrasts are equal to 1 and the other is 2. But the question is, what scale are these on? It is not the square-root scale... how do you back-transform from the (sqrt(a1) - sqrt(a2)) - (sqrt(a3) - sqrt(a4)) scale?

Perhaps what you really want to do is to back-transform *before* computing the interaction contrasts? Then the approach is to re-compute the grid so it is on the response scale:
```r
> regrid(EMM)
 dose treat estimate SE  df asymp.LCL asymp.UCL
 L    a           49 14 NaN     21.56      76.4
 H    a           25 10 NaN      5.40      44.6
 L    b           16  8 NaN      0.32      31.7
 H    b            9  6 NaN     -2.76      20.8
 L    c            4  4 NaN     -3.84      11.8
 H    c            4  4 NaN     -3.84      11.8

Confidence level used: 0.95

> contrast(regrid(EMM), interaction = "pairwise")
 dose_pairwise treat_pairwise estimate   SE  df z.ratio p.value
 L - H         a - b                17 19.9 NaN 0.854   0.3929 
 L - H         a - c                24 18.1 NaN 1.325   0.1851 
 L - H         b - c                 7 11.5 NaN 0.609   0.5423 
```
Note that those same interaction contrasts are [17, 24, 7], compared with [1, 2, 1] from the link scale. The first and the third are not equal.

There are special cases. If the link is the log, then contrasts back-transform to ratios. Similarly, logit contrasts back-transform to odds ratios. But that's about it.

**Comment by rvlenth** [comment]
See `vignette("transformations", "emmeans") for more information.

**Comment by nahorp** [comment]
Thanks for the quick response @rvlenth, and that is a very elegant example!

Indeed, I have read the transformations vignette (very helpful!), and I am conducting my contrasts on the link scale (in line with the _model is our best guide_ and _the model is right_ adages), so want to avoid the `regrid` or `transform = "response"` function and argument. To simplify the above example to a single predictor, the below is binomial model (with a logit link) with the contrast on the link scale,

![Screen Shot 2021-02-10 at 12 03 31 pm](https://user-images.githubusercontent.com/43395036/107449761-457db780-6b98-11eb-8523-7ca26d643679.png)

On the response scale, it is below,

![Screen Shot 2021-02-10 at 12 03 38 pm](https://user-images.githubusercontent.com/43395036/107449898-81188180-6b98-11eb-8c77-603f2de9f4a3.png)

The median is just exp(0.449) but as you say the CIs aren't the same. Even for the interaction contrasts, I can do the exp(central tendency estimate) and get the central tendency estimate on the response scale (I wish to do this for ease of reading) but unsure of what the best way to report the CIs is for those interaction contrasts. Using exp() on the lower and upper HPD of the interaction contrast doesn't seem true to the data...

**Comment by rvlenth** [comment]
Use `regrid()`. It back-transforms all the posterior estimates, and that will be better than what happens with a frequentist model because it is using that actual posterior distribution instead of some approximation.

**Comment by nahorp** [comment]
Just so that I am not misperceiving, you are suggesting the use of `regrid` (or the equivalent `transform = "response"` argument) _only_ to get the CIs, correct? That is, the link scale is still the best scale on which to conduct contrasts.

**Comment by rvlenth** [comment]
No. use regrid at the beginning, then do everything else.

Sent from my iPad

On Feb 9, 2021, at 8:51 PM, Rohan Puri <notifications@github.com> wrote:

﻿

Just so that I am not misperceiving, you are suggesting the use of regrid (or the equivalent transform = "response" argument) only to get the CIs, correct? That is, the link scale is still the best scale on which to conduct contrasts.

**Comment by nahorp** [comment]
That makes _everything a lot easier_, but I'm struggling to reconcile it with statements like these from the transformations vignette, that makes sense to me...

> This choice of timing is based on the idea that the model is right. In particular, the fact that the response is transformed suggests that the transformed scale is the best scale to be working with. In addition, the model specifies that the effects of source and percent are linear on the transformed scale; inasmuch as marginal averaging to obtain EMMs is a linear operation, that averaging is best done on the transformed scale. For those two good reasons, back-transforming to the response scale is delayed until the very end by default.

**Comment by rvlenth** [comment]
That excerpt has to do with the averaging over unwanted factors to obtain marginal means. And yes, you should do that averaging, if any, on the link scale. Once you are down to the factors of interest in your interaction contrasts, `regrid` that object and go forward from there with your interaction contrasts, etc.

**Comment by nahorp** [comment]
*phew*... I've done some reading over the past few days and realised I had some gaps in my knowledge. Specifically,

1) Say for `model_fit <- y ~ A*B` with link functions that aren't log or logit (e.g., probit), you recommend using `regrid`. This would look like below I believe,

`contrast(regrid(emmeans(model_fit, ~ A)), interaction = "pairwise")`

This gives me the contrast on the response scale (with averaging done on the link scale?) but I am struggling to understand conceptually how the `regrid()` function works (even after reading the transformations vignette). Specifically, in my head, there are 2 things that can be done - averaging and back-transformation. The `type = "response"` argument does the averaging of unwanted factors on the link scale and then back-transforms to the response scale (even the contrast if the link is a log or logit) whereas the `transform = "response"` argument does the back-transformation to the response scale first and then averages over the remaining factors (giving the contrasts on the response scale always). Where does `regrid()` fit into all this?

I understand this may be more relevant for an interaction contrast but I've simplified the example to understand how `regrid` works.

2) For the log link model, as you said, the contrasts back-transform to ratios (which is exactly what I want). So, the below works perfectly.

`contrast(emmeans(model_fit, ~ A*B, type = "response"), interaction = c("pairwise","pairwise))`

I read the documentation a bit deeper and thought the below could do the same, but that doesn't seem to be the case as the interaction contrast is still on the log scale,

`contrast(emmeans(model_fit, ~ A*B), interaction = c("pairwise","pairwise"), type = "response", ratios = TRUE)`

3) Lastly, this is probably a naive theoretical question. Given that the inverse of the `probit` link function is the CDF of the standard normal distribution, do contrasts represent z scores?

**Comment by rvlenth** [comment]
I honestly can't think of any further ways to explain this. Perhaps you can find a colleague or a consultant in a nearby statistics department who can work with you and help you sort this out.

Russ

Sent from my iPad

On Feb 12, 2021, at 5:52 AM, Rohan Puri <notifications@github.com> wrote:

﻿

phew... I've done some reading over the past few days and realised I had some gaps in my knowledge. Specifically,

  1.  Say for model_fit <- y ~ A*B with link functions that aren't log or logit (e.g., probit), you recommend using regrid. This would look like below I believe,

contrast(regrid(emmeans(model_fit, ~ A)), interaction = "pairwise")

This gives me the contrast on the response scale (with averaging done on the link scale?) but I am struggling to understand conceptually how the regrid() function works (even after reading the transformations vignette). Specifically, in my head, there are 2 things that can be done - averaging and back-transformation. The type = "response" argument does the averaging of unwanted factors on the link scale and then back-transforms to the response scale (even the contrast if the link is a log or logit) whereas the transform = "response" argument does the back-transformation to the response scale first and then averages over the remaining factors (giving the contrasts on the response scale always). Where does regrid() fit into all this?

I understand this may be more relevant for an interaction contrast but I've simplified the example to understand how regrid works.

  1.  For the log link model, as you said, the contrasts back-transform to ratios (which is exactly what I want). So, the below works perfectly.

contrast(emmeans(model_fit, ~ A*B, type = "response"), interaction = c("pairwise","pairwise))

I read the documentation a bit deeper and thought the below could do the same, but that doesn't seem to be the case as the interaction contrast is still on the log scale,

contrast(emmeans(model_fit, ~ A*B), interaction = c("pairwise","pairwise"), type = "response", ratios = TRUE)

  1.  Lastly, this is probably a naive theoretical question. Given that the inverse of the probit link function is the CDF of the standard normal distribution, do contrasts represent z scores?

**Comment by nahorp** [comment]
Cheers @rvlenth 👍

**Comment by rvlenth** [comment]
If you say transform = "log" in the regrid call, it transforms to the log scale, not the response scale. Use transform = "response" there, and skip the type = "response" later, where it can have no effect as we have previously discussed.

Sent from my iPad

On Feb 22, 2021, at 7:56 PM, Rohan Puri <notifications@github.com> wrote:

﻿

Hi @rvlenth<https://github.com/rvlenth>, not sure if this is a bug or some misspecification on my end, but it has baffled me!

em <- emmeans(model, ~ A*B, dpar = "mean")
cont <- contrast(regrid(em, transform = "log"), interaction = c("pairwise", "pairwise"), type = "response")


The above does not give the back-transformed results. But, surprisingly, when I run the below, I get the back-transformed results...

summary(cont, type = "response")

Furthermore, when I replace the interaction argument with method (and drop one "pairwise"), I do get the back-transformed result for all the comparisons. I need the emmGrid class of the contrast to pass it onto another function, hence the summary command won't suffice...

**Comment by nahorp** [comment]
Sorry, I should have clarified. The link function is an identity link function so using only transform = "response" and losing the the type = "response" has no effect.

In essence, I am trying to fake a log transformation, as per the vignette [here](https://cran.r-project.org/web/packages/emmeans/vignettes/transformations.html#logs) to get ratios instead of differences. I can get the ratios for the main effect (as per below) but not for the interaction effect (as per above). Interestingly, the above code for the interaction contrast works fine when I have a log link function...

```
em <- emmeans(model_fit, ~ A, dpar = "mean")

contrast(regrid(em, transform = "log"), method = "pairwise", type = "response")
```

**Comment by rvlenth** [comment]
What is happening is in the code line: https://github.com/rvlenth/emmeans/blob/6ca8ddf4aa0333dbe9bd45c2545ae3c250de9f08/R/contrast.R#L241
For technical reasons, the `...` in the call are *not* passed in this final update to the object; hence your `type = "response"` is ignored. If still want to see ratios of [... of] ratios, you can still see those results if you summarize it separately:
```r
cont <- contrast(regrid(em, transform = "log"), interaction = c("pairwise", "pairwise"))
summary(cont, type = "response")
```

I do not intend to do any coding changes in this area. Trying to fix this slight inconvenience would create worse problems as indicated in the comments in the code. It is a rare situation that transformations will even survive an interaction contrast.

**Comment by nahorp** [comment]
Thanks for your prompt reply @rvlenth - fixing this and creating worse problems doesn't sound like the solution. I have found a workaround to do what I need to do.

Thank you for your wonderful package - writing my first manuscript based on analyses in R and `emmeans` makes everything so much easier! :)
