### ISSUE TITLE
Shifted lognormal distribution distributional parameter mean calculation

### ISSUE THREAD

**Issue by nahorp** [rvlenth/emmeans#256]
Hello,

For a shifted lognormal distribution, using the `dpar = "mean"` argument the value I get for the older group is 392. However, according to the formula of `exp(ndt) + exp(mu + ((sigma^2)/2))`, the value I should get is ~ 387. That is `exp(5.16)+exp(5.3+((0.342^2)/2))`. Similarly, the value displayed for the young group is 309, when the formula gives 302. Have I gotten the formula wrong or missing some vital step? In addition, why does the descriptor for `dpar = "mean"` say that the point estimate displayed is the median. Wouldn't the median be `exp(ndt) + exp(mu)` instead?

Thank you :)

<img width="585" alt="Screen Shot 2021-02-15 at 10 55 37 pm" src="https://user-images.githubusercontent.com/43395036/107945079-35743680-6fe3-11eb-9927-af9b4d998fb0.png">

**Comment by rvlenth** [comment]
The posterior estimates are obtained for *each iteration*, and then a summary is shown. The default point estimate is the median; see `? hpd.summary`. If you want the mean instead, use
```r
summary(emmeans(...), point.est = mean)
```
Regarding back-transformation, the posterior estimates are back-transformed for *each iteration*, and then summarized. If you back-transform the summary values, you get different results. For example, suppose it is the square:
```r
> x = 1:5

> mean(x)^2    # summarize and then square
[1] 9

> mean(x^2)    # square and then summarize
[1] 11
```
So it is not at all surprising that you found slight discrepancies - especially since you did the calculations with such limited precision.

**Comment by nahorp** [comment]
Regarding the back-transformation, that makes sense, thank you!

Regarding the "mean" and "median" argument to `summary`, I get the same values. For a lognormal distribution, I would expect the mean to be to the right of the median? Or do the same point estimates mean that my lognormal is fitted more like a symmetrical, normal, distribution? 

<img width="638" alt="Screen Shot 2021-02-16 at 5 26 26 am" src="https://user-images.githubusercontent.com/43395036/107982305-e5fc2d80-7017-11eb-8c59-caaa0ebad885.png">

**Comment by rvlenth** [comment]
Well, I guess your results are pretty symmetric, because normally, it makes a difference:
```r
set.seed(02.1521)
> pm = exp(matrix(rnorm(100), ncol = 2))
> EMM = emmobj(bhat = 1:2, levels = list(trt=c("A","B")), V = diag(2), post.beta = pm)
> summary(EMM)
 trt estimate lower.HPD upper.HPD
 A      0.964    0.0861      7.32
 B      0.702    0.1099      7.62

Point estimate displayed: median 
HPD interval probability: 0.95 

> summary(EMM, point.est = "mean")
 trt estimate lower.HPD upper.HPD
 A       1.92    0.0861      7.32
 B       1.74    0.1099      7.62

Point estimate displayed: mean 
HPD interval probability: 0.95 
```
In deed, the intervals in your example are pretty symmetric around their medians.

**Comment by nahorp** [comment]
Cheers, thank you, appreciate it :)
