### ISSUE TITLE
Regrid using an 'exp' transform argument?

### ISSUE THREAD

**Issue by nahorp** [rvlenth/emmeans#257]
Hello (again)!,

I'm wanting to regrid an emmGrid object that has mu estimates that was modelled as a natural log (not explicitly in the model call but internally as the `shifted lognormal` distribution from the `brms` package was called) with an identity link function. I am wanting these estimates on the response scale and hence want to exponentiate them but can't see a `transform = "exp"` (or thereofs) in the accepted inputs for that argument...

**Comment by rvlenth** [comment]
Looks oike a question for the brms developer. The emmeans support is in that package.

Sent from my iPad

On Feb 15, 2021, at 6:42 PM, Rohan Puri <notifications@github.com> wrote:

﻿

Hello (again)!,

I'm wanting to regrid an emmGrid object that has mu estimates that was modelled as a natural log (not explicitly in the model call but internally as the shifted lognormal distribution from the brms package was called) with an identity link function. I am wanting these estimates on the response scale and hence want to exponentiate them but can't see a type = "exp" (or thereofs) in the accepted inputs for that argument...

**Comment by nahorp** [comment]
Thanks @rvlenth, shall cross-reference this there.

**Comment by rvlenth** [comment]
Are you sure `transform = "response"` does not work?

**Comment by nahorp** [comment]
> Are you sure `transform = "response"` does not work?

Yeah, didn't seem to do anything...

![Screen Shot 2021-02-16 at 1 21 25 pm](https://user-images.githubusercontent.com/43395036/108010900-1e246000-705a-11eb-8720-c73ccc2bfa33.png)

Model information below,

![Screen Shot 2021-02-16 at 1 20 16 pm](https://user-images.githubusercontent.com/43395036/108010883-0cdb5380-705a-11eb-9d5c-03ecd9f19ffe.png)

**Comment by nahorp** [comment]
https://github.com/paul-buerkner/brms/issues/1101#event-4334740967

**Comment by rvlenth** [comment]
I'm going to go ahead and close this issue on **emmeans**. It remains an active issue #1101 for **brms**
