### ISSUE TITLE
Detect and provide informative error message (or fix) survival model with missing level

### ISSUE THREAD

**Issue by billdenney** [rvlenth/emmeans#258]
I recently fit a tobit regression via the AER package which internally uses a survival model.  The data I fit had levels assigned to a factor that were not in the current data subset.  That caused one of the estimates to be zero in the model, and therefor reference grid formation failed.

I found the error, and I fixed it in my code.  But for future users (including my future self 😄 ), it would be helpful if the `ref_grid()` automatically detected that type of issue and either built the grid excluding that level (with a warning) or gave a more informative error message to indicate to the user something like "A level is missing from the fit for covariate X".

The problem in the below is that level "C" is named for the factor, but it doesn't exist.  (I realize that a better fit would be to fix this in the survival function, but that also seems like a much bigger lift since it is part of core R.)

``` r
library(AER)
#> Loading required package: car
#> Loading required package: carData
#> Loading required package: lmtest
#> Loading required package: zoo
#> 
#> Attaching package: 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric
#> Loading required package: sandwich
#> Loading required package: survival
library(emmeans)

my_data <-
  data.frame(
    value=c(rep(0, 5), 6:10),
    treatment=factor(rep(c("A", "B"), each=5), levels=c("A", "B", "C"))
  )

model <- tobit(value~treatment, data=my_data, left=5)
emmeans(model, ~treatment)
#> Error in (function (object, at, cov.reduce = mean, cov.keep = get_emm_option("cov.keep"), : Something went wrong:
#>  Non-conformable elements in reference grid.
summary(model)
#> Error in solve.default(vcov.hyp): Lapack routine dgesv: system is exactly singular: U[2,2] = 0
```

<sup>Created on 2021-02-22 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by rvlenth** [comment]
Well, this mystifies me, because `ref_grid()` already does strip-off unused levels:
``` r
require(emmeans)
#> Loading required package: emmeans

w1.lm = lm(breaks ~ wool*tension, data = warpbreaks)
ref_grid(w1.lm)
#> 'emmGrid' object with variables:
#>     wool = A, B
#>     tension = L, M, H

w2.lm = lm(breaks ~ wool*tension, data = warpbreaks,
           subset = which(tension != "M"))
ref_grid(w2.lm)
#> 'emmGrid' object with variables:
#>     wool = A, B
#>     tension = L, H
```

<sup>Created on 2021-02-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I note that you get an error in `summary(model)` -- which has nothing to do with `emmeans()`. I think it would be tough to work around error conditions that already exist in a model object.

You can probably use `nesting` and/or `at` to work around this.

**Comment by rvlenth** [comment]
More directly to your example:
```r
> mod <- lm(value~treatment, data=my_data)
> ref_grid(mod)
'emmGrid' object with variables:
    treatment = A, B
```

**Comment by billdenney** [comment]
Sorry that the example wasn't in a standard package.  I've updated it below.  `tobit()` is a convenience function for `survreg()`, and I've converted the example to a `survreg()` example.

I agree that the underlying problem is the way that `survreg()` handles the variable keeping factors that have no data in the model.  (Which is different than the way that `lm()` does it.)  To me, the real fix would be for `survreg()` to drop the levels that do not exist.  The user-side workaround of dropping the levels is shown in the reprex below.

For some reason, the `coef()` method shows the coefficient as zero while the `print()` method shows the coefficient as `NA`.  I agree that `NA` is the correct result.

My ask here is to do detection similar to what is done in the `print()` method for values that are not fit, and exclude them from `ref_grid()` (likely with a warning).

``` r
library(survival)
library(emmeans)

my_data <-
  data.frame(
    value=c(rep(1, 5), 6:10),
    treatment=factor(rep(c("A", "B"), each=5), levels=c("A", "B", "C"))
  )
my_data$cens <- c(0, 1)[(my_data$value == 1) + 1]

model <- survreg(Surv(time=value, event=cens)~treatment, data=my_data)
#> Warning in survreg.fit(X, Y, weights, offset, init = init, controlvals =
#> control, : Ran out of iterations and did not converge
coef(model)
#> (Intercept)  treatmentB  treatmentC 
#>  0.08588218  2.40341893  0.00000000
model$coef
#> (Intercept)  treatmentB  treatmentC 
#>  0.08588218  2.40341893          NA
model$coefficients
#> (Intercept)  treatmentB  treatmentC 
#>  0.08588218  2.40341893  0.00000000
print(model)
#> Call:
#> survreg(formula = Surv(time = value, event = cens) ~ treatment, 
#>     data = my_data)
#> 
#> Coefficients: (1 not defined because of singularities)
#> (Intercept)  treatmentB  treatmentC 
#>  0.08588218  2.40341893          NA 
#> 
#> Scale= 0.09832254 
#> 
#> Loglik(model)= 4.9   Loglik(intercept only)= -15
#>  Chisq= 39.92 on 2 degrees of freedom, p= 2.15e-09 
#> n= 10
summary(model)
#> 
#> Call:
#> survreg(formula = Surv(time = value, event = cens) ~ treatment, 
#>     data = my_data)
#>               Value Std. Error     z      p
#> (Intercept)  0.0859     0.0681  1.26   0.21
#> treatmentB   2.4034     0.2198 10.93 <2e-16
#> treatmentC   0.0000     0.0000    NA     NA
#> Log(scale)  -2.3195     0.0000  -Inf <2e-16
#> 
#> Scale= 0.0983 
#> 
#> Weibull distribution
#> Loglik(model)= 4.9   Loglik(intercept only)= -15
#>  Chisq= 39.92 on 2 degrees of freedom, p= 2.1e-09 
#> Number of Newton-Raphson Iterations: 30 
#> n= 10
ref_grid(model)
#> Error in ref_grid(model): Something went wrong:
#>  Non-conformable elements in reference grid.

my_data_correct_levels <- my_data
my_data_correct_levels$treatment <- droplevels(my_data_correct_levels$treatment)

model_correct <- survreg(Surv(time=value, event=cens)~treatment, data=my_data_correct_levels)
#> Warning in survreg.fit(X, Y, weights, offset, init = init, controlvals =
#> control, : Ran out of iterations and did not converge
coef(model_correct)
#> (Intercept)  treatmentB 
#>  0.08588218  2.40341893
print(model_correct)
#> Call:
#> survreg(formula = Surv(time = value, event = cens) ~ treatment, 
#>     data = my_data_correct_levels)
#> 
#> Coefficients:
#> (Intercept)  treatmentB 
#>  0.08588218  2.40341893 
#> 
#> Scale= 0.09832254 
#> 
#> Loglik(model)= 4.9   Loglik(intercept only)= -15
#>  Chisq= 39.92 on 1 degrees of freedom, p= 2.65e-10 
#> n= 10
summary(model_correct)
#> 
#> Call:
#> survreg(formula = Surv(time = value, event = cens) ~ treatment, 
#>     data = my_data_correct_levels)
#>               Value Std. Error     z      p
#> (Intercept)  0.0859     0.0681  1.26   0.21
#> treatmentB   2.4034     0.2198 10.93 <2e-16
#> Log(scale)  -2.3195     0.0000  -Inf <2e-16
#> 
#> Scale= 0.0983 
#> 
#> Weibull distribution
#> Loglik(model)= 4.9   Loglik(intercept only)= -15
#>  Chisq= 39.92 on 1 degrees of freedom, p= 2.6e-10 
#> Number of Newton-Raphson Iterations: 30 
#> n= 10
ref_grid(model_correct)
#> 'emmGrid' object with variables:
#>     treatment = A, B
#> Transformation: "log"
```

<sup>Created on 2021-02-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by billdenney** [comment]
FYI, I also asked on R-help in case this can be fixed in base R: https://stat.ethz.ch/pipermail/r-help/2021-February/470321.html

**Comment by rvlenth** [comment]
I will look at it further. I now speculate that the problem is precisely because the `ref_grid()` *does* throw out missing levels -- i.e., the conconformity goes the opposite direction and we need to identify which coefficients to disregard. It is bizarre but also potentially useful that there are differing `coef` and `coefficients` members. This is a busy day so it may take a while for me to track all this down.

I won't be holding my breath that anything will change in base R.

**Comment by billdenney** [comment]
Thank you very much for the quick responses here, and for my immediate purposes, I'm using `droplevels()` as a workaround.  So, timing isn't critical for me.

**Comment by rvlenth** [comment]
OK, it turned out to be a simple fix. As I suspected, by the time the `emm_basis` method is called, the `ref_grid()` code has already dropped the missing levels, but the model's regression coefficients still include them. So I just subset the `bhat` slot to make them conform.

``` r
# Survival test - problem with empty levels

require(survival)
#> Loading required package: survival
require(emmeans)
#> Loading required package: emmeans
require(AER)
#> Loading required package: AER
#> Loading required package: car
#> Loading required package: carData
#> Loading required package: lmtest
#> Loading required package: zoo
#> 
#> Attaching package: 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric
#> Loading required package: sandwich


my_data <-
    data.frame(
        value=c(rep(1, 5), 6:10),
        treatment=factor(rep(c("A", "B"), each=5), levels=c("A", "B", "C"))
    )
my_data$cens <- c(0, 1)[(my_data$value == 1) + 1]

model <- survreg(Surv(time=value, event=cens)~treatment, data=my_data)
#> Warning in survreg.fit(X, Y, weights, offset, init = init, controlvals =
#> control, : Ran out of iterations and did not converge

ref_grid(model)
#> 'emmGrid' object with variables:
#>     treatment = A, B
#> Transformation: "log"

### --------------------------------------------------------------------------
tmodel <- tobit(value~treatment, data=my_data, left=5)

ref_grid(tmodel)
#> 'emmGrid' object with variables:
#>     treatment = A, B
```

<sup>Created on 2021-02-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by billdenney** [comment]
Excellent!  Thanks for the help and the great package!
