### ISSUE TITLE
Is there a `bias.adjust` option for `emmip`?

### ISSUE THREAD

**Issue by gracemhw** [rvlenth/emmeans#259]
I was running models using `glmer`. There is a `bias.adjust = TRUE` option in the `summary` function for `emmeans`. Is there an option in `emmip` to plot these bias-adjusted means?

**Comment by rvlenth** [comment]
Yes. Both `bias.adjust` and its close companion, `sigma`, are passed to `summary.emmGrid()` via the `...` argument.

Just for clarity, note that `bias.adjust` has no effect unless we are back-transforming the results; that is, there is a non-identity link or response transformation, and `type = "response"` is specified either explicitly or via that attribute of `object`
