### ISSUE TITLE
emmeans and contrast outputs after using glmer: pairwise comparisons and interpretation

### ISSUE THREAD

**Issue by jukicivan** [rvlenth/emmeans#260]
Hi Russ,

first of all, thank you for all the great work on your _emmeans_ package!

I recently used your _emmeans_ package to answer some of my research questions, but I ran into some problems regarding the interpretation of the output from the _emmeans_ function and its agreement with _ggpredict_ output from _ggeffects_ package. So, this is not really an "issue", but more of a "question". I did a lot of searching and reading on the topic, mainly on CV and SE (many of them were your posts on these platforms), but I still have some doubts regarding marginal effects, odds ratios (OR-s) and their interpretation in the context of mixed-effects logistic regression (and I'm getting time-squeezed). Briefly, in my study, I was looking at the proportion of instances (YES, NO or 1, 0) in which people managed to stay above pre-determined fatigue threshold during three different experimental conditions while performing the same task in each conditions 3 times. Importantly, all participants went through all the procedures. In that regard, I ran mixed effects logistic regression using _glmer_ from _lme4_ package.

```
 glmer(frequency ~ condition*task_number + (1 + condition |participant_ID), 
 family = binomial,
 contrasts = list(condition = "contr.sum", task_number = "contr.sum"),
 data = data, 
 control =  glmerControl(optimizer = "bobyqa"))
```

After obtaining this best model fit (which passed all the checks), I was interested in the pairwise comparisons between the conditions to determine which condition was more effective in maintaining fatigue levels above the pre-determined threshold, and for that purpose I used your _emmeans_ package. Speficially, I used _emmeans_ and _contrast_ functions.

```
a <- emmeans(model, "condition", by = "task_number",  type = "response")
contrast(a, method = "pairwise", adjust = "holm")
```

This gave me OR-s for all the comparisons between conditions by the task number (because they all performed the same task 3 times during each condition) and all the relevant statistics. However, I thought it would be useful to visualise this using _ggpredict_ from _ggeffects_ package using my own _ggplot_ code.

` b <- ggpredict(model, terms = c("condition", "task_number"))`

I'm now in doubt how to interpret all of this because I'm unsure about the conceptual differences between the _emmeans_ and _ggpredict_ outputs. I read all the vignettes of both packages related to this topic, but I still can't get it right, so I would appreciate if you could help me understand this. All I can say now is that I'm getting the same results as long as I specify the "_terms_" (i.e. _terms_ argument) in _ggeffects_, or "_by_" in _emmeans_ package.  Perhaps, I can just stick then with _emmeans_? Because of that I'm also now unsure whether it is redundant to report both comparisons (OR-s produced by _emmeans_) and predicted probabilities (produced by _ggpredict_). The way I see it now is that:

a) OR-s comparisons (from _contrast_ output) give me the information about which condition for a given task number is more effective at keeping the fatigue levels above a pre-determined threshold (e.g., during the first task, condition 1 had ~68% less chance to stay above fatigue threshold when compared to condition 2 [OR = 0.323, SE = 0.126, Z = 2.888, p =0.0055]);

b) Predicted probabilities (from _ggpredict_ output) give me the information of the overall probability for staying above the pre-determined fatigue threshold during each condition and the task number.

It seems to me that, in my case, first one is "inferential" whereas the other is more "descriptive". However, I think that the real source of confusion for me is the conceptual difference between these two things (if there is any?), and also terminology used by different people.

Finally, I thought that, while in regular logistic regression the odds ratios should be interpreted while holding all the other predictors fixed, in mixed effects logistic regression, we also have to hold the random effects fixed. This means that the odds ratio here are conditional odds ratio for both fixed effects and random effects of a given model. This is also related to predicted probabilities then too? If so, than all of this suggests to me that using both OR-s and predicted probabilities in my case should be interpreted while always considering my fixed and random effects (i.e. they are both conditioned to my fixed and random effects), while avoiding any "generalisation language" (which was not my intention at all). This means that I should make explicit statements about taking my fixed and random effects into account while _interpreting_ the results.

Thank you very much for your time,
Ivan

**Comment by rvlenth** [comment]
I have not used the **ggeffects** package and can't give advice about how to use it or how it compares with what **emmeans** does. I do know that**emmeans** provides several ways to visualize its results, such as the `plot()` method, or perhaps
```r
emmip(a, task_number ~ condition, type = "response", CIs = TRUE)
```
You could even do
```r
emmip(pairs(a), task_number ~ contrast, type = "response")
```
There is an additional consideration in that it is a mixed model: when the logit-scale results are transformed to the probability scale. The fact tyhat random effects are present biases the back-transformed estimates. See [this vignette example](https://cran.r-project.org/web/packages/emmeans/vignettes/transformations.html#cbpp) for information on how to do this. This adjustment can be made i9n the plots by adding `bias.adj = TRUE, sigma = ...` to the `emmip()` call.

My package does not support any means of holding the random effects fixed; nor have I heard of people doing this (but I lack authority to advise against it). To hold fixed effects fixed, use `by` specs, as you have done. Any factors not included among the primary or `by` variables get averaged over (on the logit scale by default), per the emphasis on estimated *marginal* means. The **effects** package (and **ggeffects** as well, possibly) may use different weights in computing such averages; the default in **emmeans** is equally weighted, but others are possible via the `weights` argument in `emmeans()`. I think it is OK to average over factors of secondary interest, as long as they don't interact with other factors, or interact only weakly.

You can also work in terms of risk ratios rather than odds ratios via
```r
aprime = regrid(a, transformation = "log")
```
The summaries of `aprime` with `type = "response"` will be the same as for `a`, but the contrasts with `type = "response"` will be ratios of probabilities rather than ratios of odds.

**Comment by jukicivan** [comment]
Thank you for your prompt response Russ, I really appreciate it.

I played around with **emmip** function from your package, and it's giving me the exact same graphs as **ggpredict** in combination with my own **ggplot** code. I wasn't aware of this function before, so thank you. 

I also played around with the calculations, and it seems that both **emmeans** and **ggpredict** are giving the same results (I tested only type = "response", so predicted probabilities). Considering that, and the fact that I used **contrast** function from your package to get pairwise comparisons (odds ratios), do you think that it is redundant to report both? I mean, is the interpretation of the odds ratios and predicted probabilities from my **original** comment above correct (i.e. "inferential" vs "descriptive")? I thought about putting OR-s in the table and visualising data using predicted probabilities (for the ease of understanding). Based on your response, it seems that there is no conceptual differences between them (just the scale, like I thought myself), so I don't understand why some people create confusion about this.

Thank you also for drawing my attention to the fact that random effect biases the back-transformed estimates (in this case, predicted probabilities). In the examples given [here](https://cran.r-project.org/web/packages/emmeans/vignettes/transformations.html#cbpp), only random **intercepts** were used, but I'm wondering should we also include random **slopes** if we have them in our model (like in my example), in the calculation of the **sigma**?

<img width="414" alt="Screen Shot 2021-03-06 at 9 19 34 am" src="https://user-images.githubusercontent.com/58959184/110169281-5b139380-7e5d-11eb-95ea-5d407060810d.png">

The reason I'm asking is because when I do: `summary(a, type = "response", bias.adj = T)` I get sigma = **1**. Clearly, it's not the same when doing manual calculation based on the screenshoot above. Can you tell me what's the issue? Also, if we need this bias adjustment due to random factors in our models, doesn't that mean that we're trying to "generalise" our results beyond our sample with it, or I'm again misunderstanding something? 

Regarding your response on holding the random effects fixed in mixed effects models, I'm under the impression that the OR-s calculated are always taking into account the influence of the random effects in the glmer model (please see the paragraph starting with "Many people prefer" [here](https://stats.idre.ucla.edu/other/mult-pkg/introduction-to-generalized-linear-mixed-models/), the "Predicted Probabilities and Graphing" section [here](https://stats.idre.ucla.edu/r/dae/mixed-effects-logistic-regression/), and top answer [here](https://stats.stackexchange.com/questions/365907/interpretation-of-fixed-effects-from-mixed-effect-logistic-regression) for more information). This is what I meant by "holding random effects fixed" when using mixed logistic regression. Therefore, I concluded that I can't "generalise" my results beyond my sample (which is completely fine for me). So, again, I'm wondering if my interpretations from the above are correct, and whether I should make explicit statements about taking random effects of my model into account while interpreting my results after using **emmeans**, **contrast** and now **emmip** functions.

**Comment by rvlenth** [comment]
If you don't specify `sigma` for `bias.adj`, it calls `sigma(model)` -- which for this class of model, always returns 1. In general. You should always use the `VarCorr()` results to obtain `sigma` when you have a mixed model. 

Having random slopes increases the complexity considerably, The right value of `sigma` will depend on the scale value(s) of the covariate(s), and right now it isn't even set up to allow different sigmas for different predictions.

I guess what you're saying is that `ggpredict` is giving you differences of probabilities. It does not seem wrong to show both odds ratios and differences of estimated probabilities, as long as they are explained correctly. You can get differences of probabilities, if you want, via `pairs(regrid(a, transform = "response"))`.

I am drawing a line at giving statistical advice versus explaining how the package works, and I don't feel comfortable commenting further on the issues relating to "holding random effects fixed," other than saying that in estimating SEs of estimates, I am using the estimated variance-covariance matrix for the fixed effects, which *includes* the variances of the random effects. That is to say, all other things being equal, if the random effects are more various, then the SEs will be larger.

**Comment by jukicivan** [comment]
Thank you for your reply.

Of course, I plan to do manual calculations anyway, so I can specify it – Thanks for clarifying that!

I see regarding _random slopes_, and I could imagine that it complicates everything further. But, would it then be correct to do `sqrt(.904521^2 + .220990^2 + .053776^2)` from the example above. Unfortunately, I specified one argument wrongly, so here is the new SS, just different numbers (question remains the same).
<img width="408" alt="Screen Shot 2021-03-07 at 8 10 59 am" src="https://user-images.githubusercontent.com/58959184/110218114-b062aa00-7f1c-11eb-8ab9-f0b073e817e1.png">

Regarding `ggpredict`, no, I just used `ggpredict` to visualise the data and now after your suggestion I used `emmip`, and I'm getting identical graphs (I mean, the same estimates). Regarding differences in probabilities, I don't see how having them and OR-s together would tell a different story – they are just on a different scale and one is a bit more intuitive or easier to comprehend. I thought about having predicted probabilities as a "descriptive" representation of my data. In my case, that would be what was the probability of staying above pre-determined threshold during each condition and the task number. I would use OR-s from `contrast` output to make inferences between conditions. This sounds reasonable to me, but I wasn't sure as I was using two different packages to get what I want. Now it's easier when I know that all functions (including `ggpredict`) are giving me the same thing, so I can just continue with `emmeans`, `contrast` and `emmip`. 

I very much appreciate your response regarding random effects, and I see that I moved away a bit from my question about the package. Well, that's great to know that SEs of the estimates **include** the variances of the random effects, which means that random effects are taken into account.

**Comment by rvlenth** [comment]
> ... would it then be correct to do sqrt(.904521^2 + .220990^2 + .053776^2) ...

No; this would be completely incorrect. These are variances of the *regression coefficients*, not of the _predictions_; in addition, there are correlations among these that were excluded. As I said, this is a complicated calculation. The needed `sigma` values will likely be different for each condition, and as I mentioned before, that possibility isn't even currently supported.

**Comment by jukicivan** [comment]
Thanks for replying Russ. 

I understand. Well I need to do some reading then on how to make this happen and perhaps ask a question on CV. If you can suggest some readings/resources that would be great. I'm going to close this as it totally moved away from my original question (and most of it was clarified). 

Thank you again for all of your responses, much appreciated.
