### ISSUE TITLE
Plotting interactions in emmeans 

### ISSUE THREAD

**Issue by Sidy2015** [rvlenth/emmeans#264]
Hello, 
I fit an aov model on my data with 3 variables:
-yield the contibuous  response variable
-Environnement= categorical with 3 categories
-Treatment= catagorical with 3 categories: ctrl, treat1,

mod=aov(yield~Environnement*Treatment, data=dat).

At first, i compute the emmeans and plot them using:
Env.mm=emmeans(mod,~treatment)
plot(Env.mm,comparisons=T)
At second, i want to plot the same emmeans for interactions but cannot do this. 
int.cont=contrast(emmeans(mod,~Environnent*Treatment), interaction=c("consec",trt.vs.ctrl"))
If i plot it, i get the plot of the contrast with the differences being compared to 0.

Is it possible to plot only the emmeans and not the contrasts. for example, for each environnement, plot only the difference "treat1 vs ctrl". 
*
I've tried the command: emmeans(mod,c("consec",trt.vs.ctrl")~Environnent*Treatment) but it was not correct. 
Thanks you in advance for your help

**Comment by rvlenth** [comment]
The `interaction` argument in `contrast()` generates *interaction* contrasts -- these are contrasts of contrasts, and I think you just want regular contrasts. To get a table of the pairwise comparisons in your first plot, you should do
```r
contrast(Env.mm, "pairwise")    # or pairs(Env.mm)
```
However, I warn you that if the interaction amounts to anything, you should NOT analyze marginal means (marginal means for Environment, as you have done, nor marginal means for Treatment). And your question implies that the interaction does amount to something.

So, if you want to bring in the levels of both factors, I suggest:
```r
Both.mm = emmeans(mod,~Environnent*Treatment)
pairs(Both.mm)
```
This generates paired comparisons of all 3 x 3 = 9 means -- a total of 36 comparisons. If you don't want to include the diagonal comparisons, do:
```r
pairs(Both.mm, by = "Environment")
pairs(Both.mm, by = "Treatment")
```
or, more simply:
```r
pairs(Both.mm, simple = "each")
```
What you tried was eqivalent to
```r
contrast(Both.mm, interaction = "pairwise")
```
and this results in 9 contrasts comprising pairwise comparisons *of* pairwise comparisons. For example, one of them is (m11 - m12) - (m21 - m22), where mij is the mean at the ith environment and jth treatment. Contrasts like that are useful if you want to see how the change in one environment compares with the change in another environment.

The `emmip()` function is a nice way of displaying interactions graphically. The `pwpp()` and `pwpm()` functions are handy for compactly displaying the results of pairwise tests, especially if you do want all 36 of those comparisons.

See `vignette("interactions", "emmeans")` for more examples.

**Comment by rvlenth** [comment]
I think this issue is resolved, so am closing it. That does not prevent you from commenting further if you see the need.
