### ISSUE TITLE
adjust="BY" throws error in contrast()

### ISSUE THREAD

**Issue by dbjanszen** [rvlenth/emmeans#267]
Although the documentation says that "BY" is a legitimate p.adjust.method, I receive the following error when I try to use it as follows: contrast(object-returned-by-emmeans, emm="eff", adjust="BY")
Error in .adj.p.value(t.ratio, result$df, adjust, fam.info, tail, corrmat, 
   Adjust method 'by' is not recognized or not valid

Is the documentation incorrect or does this need to be specified in another way?

Thanks,
Derek

**Comment by rvlenth** [comment]
Oops. You have found an embarrassing error, whereby the code converts some stuff to lower-case when it sometimes should not do that. I'll come up with a fix, then it will work as documented. Soon...

Sent from my iPhone

On Mar 31, 2021, at 7:52 PM, dbjanszen ***@***.******@***.***>> wrote:


Although the documentation says that "BY" is a legitimate p.adjust.method, I receive the following error when I try to use it as follows: contrast(object-returned-by-emmeans, emm="eff", adjust="BY")
Error in .adj.p.value(t.ratio, result$df, adjust, fam.info<http://fam.info>, tail, corrmat,
Adjust method 'by' is not recognized or not valid

Is the documentation incorrect or does this need to be specified in another way?

Thanks,
Derek

**Comment by dbjanszen** [comment]
Thanks. In researching this, I discovered on some forum that someone received the same error when they set adjust="BH", but in that case there was a fix: use "fdr" instead!

**Comment by rvlenth** [comment]
OK, I think I have it. 
``` r
library(emmeans)

warp.lm = lm(breaks ~ wool * tension, data = warpbreaks)
RG = ref_grid(warp.lm)

# test with "BY"
contrast(RG, adjust = "BY")
#>  contrast   estimate   SE df t.ratio p.value
#>  A L effect  16.4074 3.33 48  4.929  0.0002 
#>  B L effect   0.0741 3.33 48  0.022  1.0000 
#>  A M effect  -4.1481 3.33 48 -1.246  1.0000 
#>  B M effect   0.6296 3.33 48  0.189  1.0000 
#>  A H effect  -3.5926 3.33 48 -1.079  1.0000 
#>  B H effect  -9.3704 3.33 48 -2.815  0.0519 
#> 
#> P value adjustment: BY method for 6 tests

# test with wrong case
contrast(RG, adjust = "by")
#>  contrast   estimate   SE df t.ratio p.value
#>  A L effect  16.4074 3.33 48  4.929  0.0002 
#>  B L effect   0.0741 3.33 48  0.022  1.0000 
#>  A M effect  -4.1481 3.33 48 -1.246  1.0000 
#>  B M effect   0.6296 3.33 48  0.189  1.0000 
#>  A H effect  -3.5926 3.33 48 -1.079  1.0000 
#>  B H effect  -9.3704 3.33 48 -2.815  0.0519 
#> 
#> P value adjustment: BY method for 6 tests
```

<sup>Created on 2021-04-01 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


I could grouse about `p.adjust.methods` being inconsistent with case, but that doesn't do any good and would open me to inconsistencies of my own. I'll be pushing this up soon after I look at another issue. Thanks for reporting this!

**Comment by rvlenth** [comment]
I'm closing this issue. The latest CRAN version (1.6.0 or later) has this fixed.

**Comment by dbjanszen** [comment]
Thank you!
