### ISSUE TITLE
emmeans works with mblogit model objects for fixed-only models but not random effect models

### ISSUE THREAD

**Issue by vjilmari** [rvlenth/emmeans#268]
Either I am doing something wrong or there is a problem with .vcov of the random effect models ?

It would be magnificent to get emmeans support for random effect mblogit models as well (if there isn't already).

Below is an example

```r
library(mclogit)
library(emmeans)

set.seed(21385)

d<-data.frame(
  DV=as.factor(sample(c("A","B","C"),200,replace=T)),
  gender=sample(c("F","M"),200,replace=T),
  cntry=sample(letters[1:10],200,replace=T))


#fixed-only
fit.f<-mblogit(DV~gender,data=d)
summary(fit.f)

#this works well
emmeans(fit.f,specs="gender",by="DV",mode="prob")

#with random intercept
fit.r<-mblogit(DV~gender,random=~1|cntry,data=d)
summary(fit.r)

#this does not work
emmeans(fit.r,specs="gender",by="DV",mode="prob")
```

**Comment by rvlenth** [comment]
As you know, support for `mblogit` (and in this case, I guess it's mmblogit`) models is fairly new. I was able to find a more robust way to obtain the vcov matrix, and it now works for both models:

```r
> emmeans(fit.f,specs="gender", by="DV", mode="prob")
DV = A:
 gender  prob     SE  df asymp.LCL asymp.UCL
 F      0.348 0.0497 Inf     0.251     0.445
 M      0.454 0.0479 Inf     0.360     0.548

DV = B:
 gender  prob     SE  df asymp.LCL asymp.UCL
 F      0.315 0.0484 Inf     0.220     0.410
 M      0.259 0.0422 Inf     0.177     0.342

DV = C:
 gender  prob     SE  df asymp.LCL asymp.UCL
 F      0.337 0.0493 Inf     0.240     0.434
 M      0.287 0.0435 Inf     0.202     0.372

Confidence level used: 0.95 

> emmeans(fit.r, specs="gender", by="DV", mode="prob")
DV = A:
 gender  prob     SE  df asymp.LCL asymp.UCL
 F      0.344 0.0691 Inf     0.209     0.479
 M      0.465 0.0706 Inf     0.327     0.604

DV = B:
 gender  prob     SE  df asymp.LCL asymp.UCL
 F      0.337 0.0631 Inf     0.213     0.460
 M      0.263 0.0533 Inf     0.158     0.367

DV = C:
 gender  prob     SE  df asymp.LCL asymp.UCL
 F      0.319 0.0712 Inf     0.180     0.459
 M      0.272 0.0638 Inf     0.147     0.397

Confidence level used: 0.95 
```

I'm crossing my fingers and hoping this doesn't break something else. I really should listen more often to my own inner voice that says to leave this up to package developers, as they are the ones who know the internal workings of their objects. So I'm going to try to get the **mclogit** developer to incorporate this in his own package (and perhaps extend it further).

I'll push up the updated package, and you can install it from GitHub, or wait until the update reaches CRAN -- probably at least a month from now. Thanks for the report.

**Comment by rvlenth** [comment]
I am closing this issue as I think it has been addressed; and meanwhile, an emmeans interface has been added to the **mclogit** package and **emmeans** itself has been updated with its internal `mblogit` support somewhat improved.
