### ISSUE TITLE
log10 vs. log

### ISSUE THREAD

**Issue by davepum** [rvlenth/emmeans#273]
I noticed that when you do a `log10` transformation on the response, emmeans will do the back transformation automatically for the treatment means but it will not automatically back transform the pairwise comparisons to ratios of geometric means like it does if you use natural log. I didn't know whether this was intentional or not and it's not important since you can use `log`, but just curious.
```
> library(emmeans)
> pig1 = lm(log(conc)~source,data=pigs)
> (em1 = emmeans(pig1,~source,type="response"))
 source response   SE df lower.CL upper.CL
 fish       30.2 1.48 26     27.3     33.4
 soy        38.2 1.87 26     34.5     42.2
 skim       43.1 2.22 26     38.8     47.9

Confidence level used: 0.95 
Intervals are back-transformed from the log scale 
> pairs(em1)
 contrast    ratio     SE df t.ratio p.value
 fish / soy  0.791 0.0547 26 -3.390  0.0061 
 fish / skim 0.700 0.0498 26 -5.015  0.0001 
 soy / skim  0.885 0.0629 26 -1.715  0.2186 

P value adjustment: tukey method for comparing a family of 3 estimates 
Tests are performed on the log scale 

> pig2 = lm(log10(conc)~source,data=pigs)
> (em2 = emmeans(pig2,~source,type="response")) #fine
 source response   SE df lower.CL upper.CL
 fish       30.2 1.48 26     27.3     33.4
 soy        38.2 1.87 26     34.5     42.2
 skim       43.1 2.22 26     38.8     47.9

Confidence level used: 0.95 
Intervals are back-transformed from the log10 scale 
> pairs(em2) # doesn't transform back
Note: Use 'contrast(regrid(object), ...)' to obtain contrasts of back-transformed estimates
 contrast    estimate     SE df t.ratio p.value
 fish - soy   -0.1019 0.0300 26 -3.390  0.0061 
 fish - skim  -0.1548 0.0309 26 -5.015  0.0001 
 soy - skim   -0.0529 0.0309 26 -1.715  0.2186 

Note: contrasts are still on the log10 scale 
P value adjustment: tukey method for comparing a family of 3 estimates 
```

**Comment by rvlenth** [comment]
Well, this is kind of an embarrassing oversight. I'll figure out how to fix it; not quite as straightforward as it may seem, due to the way this is coded in combination with `logit`. Looks like I need to cover `log2` as well. I hope I can be forgiven for not including `logb` or `log1p` (which I actually had never noticed before).

Andperhaps I should support `log1p` in the realm of ordinary transformations (but not with contrasts).

**Comment by rvlenth** [comment]
I think this is resolved now, so am closing this issue.
