### ISSUE TITLE
emmeans on output from step function

### ISSUE THREAD

**Issue by davepum** [rvlenth/emmeans#274]
This is an odd problem that came up on a student's work. The student used the `step` function in a logistic regression but no steps lowered AIC so she ended up with the same model she started with. Applying `emmeans` to the resulting model with `type=”response”` gives the message “Unknown transformation ":": no transformation done” but it gives the right results. It just labels the estimated probabilities as "response" instead of "prob". This error doesn't occur if `step` actually makes any steps and doesn't occur with two predictor factors. I haven't explored other variations. The structure of a model from `step` has an extra component called `anova`. I don;t know if that plays a role in `emmeans`.
```
> y = c("Yes","No")
> d = data.frame(expand.grid(A=y,B=y,C=y),nYes=5:12,nNo=15:8)
> m1 = glm(cbind(nYes,nNo)~(A+B+C)^2,data=d,family=binomial)
> m2 = step(m1,scope=list(lower=m1)) # no steps are possible
Start:  AIC=41.15
cbind(nYes, nNo) ~ (A + B + C)^2

> emmeans(m1,~A+B+C,type="response")
 A   B   C    prob     SE  df asymp.LCL asymp.UCL
 Yes Yes Yes 0.251 0.0893 Inf     0.117     0.460
 No  Yes Yes 0.299 0.0951 Inf     0.149     0.509
 Yes No  Yes 0.349 0.0996 Inf     0.185     0.559
 No  No  Yes 0.401 0.1029 Inf     0.225     0.608
 Yes Yes No  0.449 0.1046 Inf     0.262     0.651
 No  Yes No  0.501 0.1052 Inf     0.306     0.696
 Yes No  No  0.551 0.1046 Inf     0.349     0.738
 No  No  No  0.599 0.1029 Inf     0.392     0.775

Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 
> emmeans(m2,~A+B+C,type="response")
 A   B   C   response     SE  df asymp.LCL asymp.UCL
 Yes Yes Yes    0.251 0.0893 Inf    0.0762     0.426
 No  Yes Yes    0.299 0.0951 Inf    0.1124     0.485
 Yes No  Yes    0.349 0.0996 Inf    0.1535     0.544
 No  No  Yes    0.401 0.1029 Inf    0.1996     0.603
 Yes Yes No     0.449 0.1046 Inf    0.2438     0.654
 No  Yes No     0.501 0.1052 Inf    0.2950     0.707
 Yes No  No     0.551 0.1046 Inf    0.3462     0.756
 No  No  No     0.599 0.1029 Inf    0.3972     0.800

Unknown transformation ":": no transformation done 
Confidence level used: 0.95 
> all.equal(m1,m2)
[1] "Length mismatch: comparison on first 30 components"
 ```

**Comment by rvlenth** [comment]
Well, this is interesting. An additional bit of info:
```r
> ref_grid(m2)
'emmGrid' object with variables:
    A = Yes, No
    B = Yes, No
    C = Yes, No
Transformation: “logit” 
Additional response transformation: “:” 
```
So the context for this is a situation similar to `glm(sqrt(y) ~ treat, family = gamma())` where we have both a response transformation and a link function. That explains why it still back-transforms to the probability scale, in spite of the message. UIt's the response transformation it wouldn't handle.

What is apparently happening is that the "formula" for `m2` is actually a `terms` object, and my code does some manipulation to isolate the l.h.s., and those manipulations don't work the same way for `terms` as for `formula`, even though `terms` inherits from `formula`. And I wind up picking up the interaction operator `:` that comes from the r.h.s. even though I thought I was looking only at the lhs. I figured out a workaround.
```r
> ref_grid(m2)
'emmGrid' object with variables:
    A = Yes, No
    B = Yes, No
    C = Yes, No
Transformation: “logit” 
```

Thanks for reporting this. It will work right in the next update. In the meantime, you can add `tran2 = NULL` to the `emmeans` (or `ref_grid`) call.
