### ISSUE TITLE
".vcov" isn't passed properly when using ref_grid() with an mcmc.list object

### ISSUE THREAD

**Issue by a-hurst** [rvlenth/emmeans#278]
I've been trying to figure out how to wrangle a raw `stanfit` object from a custom STAN model into a format I can use with `emmeans`. In the process, I think I've found a minor bug in the code:

https://github.com/rvlenth/emmeans/blob/bd29869e3afcfaa16dfc764a6406301dc862ccbe/R/MCMC-support.R#L489-L491

In the above function, the covariance matrix's argument's name is `vcov.`, but the name of the variable getting passed to `emm_basis.mcmc` is `vcov`, so if you try to pass a covariance matrix by either name it doesn't work. If I pass a single chain from the `mcmc.list` to `ref_grid` along with the `vcov.` argument, things work as intended.

**Comment by rvlenth** [comment]
Yipe -- Thanks for catching -- and reporting -- this!

I will fix this and it will be in the next update to CRAN (which should be two weeks or so). In the meantime, if you have a corrected version of `emm_basis.mcmc.list` in your workspace, it should override the internal version, so maybe that'll be a way of getting through until then. (Note it will have to call `emmeans:::emm_basis.mcmc` as that function is not exported).

In addition, if you're doing only Bayesian analysis, the `V` slot isn't even used.

**Comment by a-hurst** [comment]
No worries, glad I could help! Pretty much impossible to catch unless you were looking for it, given how the `,` makes the lack of the extra `.` hard to notice.

Also yes this is a Bayesian-only analysis, but just FYI when calling `ref_grid` on an `mcmc.list`, if I *don't* provide any vcov argument I get the following error:

```
Error in UseMethod("vcov") :
  no applicable method for 'vcov' applied to an object of class "mcmc"
```

As such, I assumed one was required. Is this another bug, or am I misunderstanding what you mean by the V slot not being used?

P.S. Thanks so much for creating and actively maintaining this package. `brms` + `emmeans` + `tidybayes` has turned Bayesian modelling in R from an absolute mess of custom code into a simple-yet-flexible workflow! I don't know what I would do without it. If only this current model were in `brms` or `rstanarm` form...

**Comment by rvlenth** [comment]
Right-o. You do get an error without this being fixed. After correction, it does work, per this really dumb test example:

```r
> library(coda)
> data(line) # an mcmc.list object with parameters alpha, beta, and sigma

> RG = ref_grid(line, formula = ~ 0 + alpha + beta + sigma, data = line[[1]], at = list(alpha=1:3))

> RG
'emmGrid' object with variables:
    alpha = 1, 2, 3
    beta = 0.78669
    sigma = 0.95442

> summary(RG)
 alpha  beta sigma prediction lower.HPD upper.HPD
     1 0.787 0.954       4.38      3.55      6.12
     2 0.787 0.954       7.41      5.83      9.96
     3 0.787 0.954      10.46      8.05     13.90

Point estimate displayed: median 
HPD interval probability: 0.95 
```

**Comment by a-hurst** [comment]
Tested the latest commit and it works now, thanks so much!
