### ISSUE TITLE
Contrast coding in data ignored when using ref_grid with an MCMC object

### ISSUE THREAD

**Issue by a-hurst** [rvlenth/emmeans#279]
Hi again,

Now that #278 is fixed I've encountered another issue with my weird use-case: essentially, when creating a `model.matrix` in `emm_basis.mcmc`, any contrast coding for factors in the data get ignored completely (see the `constrasts.arg = NULL` below):

https://github.com/rvlenth/emmeans/blob/dd1fdad3be74d5e9f3f773bea66decbd460cef67/R/MCMC-support.R#L468-L470

For brms models, any contrast schemes found in the data get extracted and used for the `model.matrix` creation:

https://github.com/rvlenth/emmeans/blob/dd1fdad3be74d5e9f3f773bea66decbd460cef67/R/brms-support.R#L17-L21

As such, using `ref_grid` with a `contr.sum` coded brms model gives different results than using `ref_grid` with that same model's internal stanfit & specifying the formula & data manually! Hacking in `emm_basis.brmsfit`'s method of contrast extraction into `emm_basis.mcmc` fixes the issue.

I'd be happy to try and provide a PR for this, but I'm not quite sure what the nicest approach would be for passing the data or contrasts to `emm_basis.mcmc` would be. Would adding a `contrasts` element to `options` work, with contrasts being extracted from the provided data if none are manually specified?

**Comment by rvlenth** [comment]
Thanks. Yes, I've been uneven in how I support contrasts. The workaround here would be, I think, setting the `contrasts` attribute in each factor the dataset itself; I believe those attributes are preserved via the `recover_data` method. But I moved `contrasts.arg` to be an argument of `emm_basis.mcmc`, so that it can be changed by the user.

**Comment by rvlenth** [comment]
I think this issue is resolved to the extent that it can be; so am closing it.
