### ISSUE TITLE
Testing if each group within a binomial GLMM differ from 0.5

### ISSUE THREAD

**Issue by mrml500** [rvlenth/emmeans#280]
Apologies if this is the wrong place to ask this, but I've struggled to find an answer elsewhere.

I have a binomial GLMM, where I have a fixed factor comprising of three groups (group1,group2,group3) and a random factor specifying ID. 

``
model <- glmer(cbind(dead/alive)~ group + (1|ID), family = binomial, data = dataset)
``

From emmeans I have the estimated probabilities for each group as well as contrasts between each group, but is there a way to test for each group separately if there is a significant difference in their response from 0.5.? 

``
emmeans(model, pairwise~group, type = "response")
``

```
$emmeans
 group     prob    SE  df asymp.LCL asymp.UCL
 group1   0.406 0.371 Inf    0.0323     0.933
 group2   0.746 0.314 Inf    0.1028     0.987
 group3   0.989 0.021 Inf    0.6586     1.000

Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 

$contrasts
 contrast                     odds.ratio     SE  df z.ratio p.value
 group1   / group2   0.23215 0.4544 Inf -0.746  0.7360 
 group1   / group3   0.00744 0.0154 Inf -2.366  0.0473 
 group2   / group3   0.03203 0.0791 Inf -1.393  0.3447 

P value adjustment: tukey method for comparing a family of 3 estimates 
Tests are performed on the log odds ratio scale 
```

Thanks,
Mike

**Comment by rvlenth** [comment]
This can be done via
```r
test(emmeans(model, ~ group, type = "response))
```
The default null hypothesis value is zero (on the *logit* scale), which corresponds to 0,.5 on the response scale, as you wish.

However, this makes me realize that I should try to do a better job of printing the null value when we are showing results on the response scale. For a parallel example...
``` r
library(emmeans)

neuralgia.glm <- glm(Pain ~ Treatment * Sex + Age, family = binomial(),
                     data = neuralgia)
EMM <- emmeans(neuralgia.glm, "Treatment", type = "response")
#> NOTE: Results may be misleading due to involvement in interactions

test(EMM)
#>  Treatment  prob     SE  df z.ratio p.value
#>  A         0.211 0.1109 Inf -1.980  0.0477 
#>  B         0.121 0.0835 Inf -2.523  0.0116 
#>  P         0.866 0.0883 Inf  2.452  0.0142 
#> 
#> Results are averaged over the levels of: Sex 
#> Tests are performed on the logit scale
```
The null of zero does not print, even though it is nonzero on the response scale. If I adjust it ever so slightly, it shows in the output:
```r
test(EMM, null = 0.0001)
#>  Treatment  prob     SE  df null z.ratio p.value
#>  A         0.211 0.1109 Inf  0.5 -1.980  0.0477 
#>  B         0.121 0.0835 Inf  0.5 -2.523  0.0116 
#>  P         0.866 0.0883 Inf  0.5  2.452  0.0142 
#> 
#> Results are averaged over the levels of: Sex 
#> Tests are performed on the logit scale
```
<sup>Created on 2021-05-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mrml500** [comment]
Brilliant - that was exactly what I was looking for!

Thanks,
Mike

**Comment by rvlenth** [comment]
It was pretty easy to fix this...
```r
> test(EMM)
 Treatment  prob     SE  df null z.ratio p.value
 A         0.211 0.1109 Inf  0.5 -1.980  0.0477 
 B         0.121 0.0835 Inf  0.5 -2.523  0.0116 
 P         0.866 0.0883 Inf  0.5  2.452  0.0142 

Results are averaged over the levels of: Sex 
Tests are performed on the logit scale 

> test(EMM, type = "link")
 Treatment emmean    SE  df z.ratio p.value
 A          -1.32 0.666 Inf -1.980  0.0477 
 B          -1.99 0.787 Inf -2.523  0.0116 
 P           1.87 0.762 Inf  2.452  0.0142 

Results are averaged over the levels of: Sex 
Results are given on the logit (not the response) scale. 
```
The updated version will be on CRAN pretty soon. I've learned that every question is an opportunity to review whether what I have is right. Thanks for bringing this to my attantion!
