### ISSUE TITLE
Error when trying to estimate simple slopes with precomputed interaction variable

### ISSUE THREAD

**Issue by mattansb** [rvlenth/emmeans#284]
For reasons, I cannot include a `hp:drat` term in my model.
That is, I have to pre-define the interaction variable.

``` r
mtcars$X <- with(mtcars, hp * drat)

m <- lm(mpg ~ hp + drat + X, data = mtcars)
```

Now I want the simple slopes of `drat` by `hp` as `hp = c(2, 10)`.

``` r
library(emmeans)

emtrends(m, ~ hp, "drat",
         at = list(hp = c(2, 10)))
#>  hp drat.trend   SE df lower.CL upper.CL
#>   2       6.07 2.88 28    0.176       12
#>  10       6.07 2.88 28    0.176       12
#> 
#> Confidence level used: 0.95
```

As expected, this didn’t work - the slope is fixed and not moderated.

Letting emmeans know that X is the interaction should solve this (I think):

``` r
emtrends(m, ~ hp, "drat",
         at = list(hp = c(2, 10)),
         cov.reduce = list(X = X ~ hp:drat))
#>  hp drat.trend   SE df lower.CL upper.CL
#>   2       6.07 2.88 28    0.176       12
#>  10       6.07 2.88 28    0.176       12
#> 
#> Confidence level used: 0.95
```

Nope. Adding X to `specs`:

``` r
emtrends(m, ~ hp + X, "drat",
         at = list(hp = c(2, 10)),
         cov.reduce = list(X = X ~ hp:drat))
#> Error in emmeans(object = new("emmGrid", model.info = list(call = lm(formula = mpg ~ : No variable named X in the reference grid
```

Weird error - X **is** in the grid:

``` r
ref_grid(m, 
         at = list(hp = c(2, 10)),
         cov.reduce = list(X = X ~ hp:drat))
#> 'emmGrid' object with variables:
#>     hp =  2, 10
#>     drat = 3.5966
#>     X = (predicted by other variables)
```

Is this a bug? Or am I doing something wrong here?

----

Should note that this produces the same error:
```R
emmeans(m, 
        ~ hp + drat + X,
        at = list(hp = c(2, 10),
                  drat = c(0, 1)),
        cov.reduce = list(X = X ~ hp:drat))
```

**Comment by rvlenth** [comment]
This is kind of out in the frontiers of what these functions are designed to do...

What is happening is pretty subtle. The grid used for computing difference quotients is computed based on the differences in `var`, but holding other variables constant. So, at one step in debug mode, we see:
```
Browse[2]> bigRG@grid
    hp     drat         X .wgt.
1    2 3.596563  7.193125     1
2   10 3.596563 35.965625     1
1.1  2 3.598733  7.193125     1
2.1 10 3.598733 35.965625     1
```
The values of `X` do not change between rows (1, 2) and rows (1.1 ,2.1), and thus the differences in `X` are not included. I may or may not be able to fix this...

**Comment by rvlenth** [comment]
Well, *maybe* I have a fix:
```r
> emtrends(m, ~ hp, "drat",
+          at = list(hp = c(2, 10)),
+          cov.reduce = X ~ hp:drat)
 hp drat.trend   SE df lower.CL upper.CL
  2       6.05 2.84 28    0.228     11.9
 10       5.96 2.70 28    0.437     11.5

Confidence level used: 0.95 
```
... this involved moving up one line of code that I had (seemingly purposefully) deferred until after the covariate formulas were applied. I wish I could remember why I deferred that one line of code. We are all good, provided that my earlier reasoning was faulty, that somehow I incorrectly thought adding increments to covariates would screw-up the covariate formulas. But I need to do some navel-gazing to try to remember what I was thinking or if I screw-up something else by moving this one line of code...

**Comment by mattansb** [comment]
Thanks Russell

> The values of X do not change between rows (1, 2) and rows (1.1 ,2.1), and thus the differences in X are not included. 

Does this also explain why `emmeans(m, ...)` gave the same error?

**Comment by rvlenth** [comment]
No, because it is not the same error. I think there are some misunderstandings here. Consider:
```r
> coef(m)
(Intercept)          hp        drat           X 
 5.54952385 -0.01340620  6.06866317 -0.01039553 

> RG1 = ref_grid(m, at = list(hp = 2:4))
> RG1
'emmGrid' object with variables:
    hp = 2, 3, 4
    drat = 3.5966
    X = 511.63

> RG2 = ref_grid(m, at = list(hp = 2:4), cov.reduce = X ~ hp:drat)
> RG2
'emmGrid' object with variables:
    hp = 2, 3, 4
    drat = 3.5966
    X = (predicted by other variables)
```
For the latter, you comment that it is weird that X is in the grid. One answer is that obviously, `X` needs to be in the grid because it is a variable in the model. However, another answer is that it is not:
```r
> RG1@levels
$hp
[1] 2 3 4
$drat
[1] 3.596563
$X
[1] 511.6338

> RG2@levels
$hp
[1] 2 3 4
$drat
[1] 3.596563
```
That is, if "X is in the grid" means that X is a *reference* level, the answer is no. That is why we see:
```r
> emmeans(RG1, ~ hp + drat + X)
 hp drat   X emmean   SE df lower.CL upper.CL
  2  3.6 512     22 10.7 28    0.145     43.9
  3  3.6 512     22 10.6 28    0.283     43.8
  4  3.6 512     22 10.5 28    0.420     43.6

Confidence level used: 0.95 

> emmeans(RG2, ~ hp + drat + X)
Error in emmeans(RG2, ~hp + drat + X) : 
  No variable named X in the reference grid
```
In this second `emmeans()` call, you're suggesting that X can be a variable that can be controlled independently of hp and drat; but it can't, because it depends on those two factors.

By the way, probably the best way to create the reference grid you want is to use a newer feature that allows for explicit calculations:
```r
> myfun = function(dat)
+             list(X = with(dat, hp*drat))
> RG3 = ref_grid(m, at = list(hp = 2:4), cov.reduce = external ~ myfun)
> RG3@grid
  hp     drat         X .wgt.
1  2 3.596563  7.193125     1
2  3 3.596563 10.789687     1
3  4 3.596563 14.386250     1
```

**Comment by rvlenth** [comment]
I think this is resolved with the update I pushed. So will close this issue. But let me know if I'm wrong.

**Comment by mattansb** [comment]
Seems to be working - thanks!
