### ISSUE TITLE
Nesting Structure was Detected in the Fitted Model 

### ISSUE THREAD

**Issue by delucalab** [rvlenth/emmeans#296]
I have data on whether individuals have lesions at various regions of the body. I am running a bayesian model of the bernoulli family and want to extract estimated marginal means taking into account the random effects and demographic covariates (sex and age) to assess contrasts between regions. I am using the following data and code:

[Example.csv](https://github.com/rvlenth/emmeans/files/7148126/Example.csv)

install.packages("brms")
library(brms)
install.packages("emmeans")
library(emmeans)

example<-read.csv("Example.csv",header=T)
as.factor(example$ID)->example$ID
as.factor(example$Sex)->example$Sex
as.factor(example$Region)->example$Region
as.factor(example$Lesion)->example$Lesion

example_model<-brm(formula=Lesion ~ Region + Sex + Age + (1 | ID), data=example, family="bernoulli",warmup=2000,iter=4000,seed=34)

example_emmeans<- emmeans(example_model, ~ Region, re_formula=NULL)

I then received the following note:

NOTE: A nesting structure was detected in the fitted model:
    ID %in% Sex

I was reading and it was suggested to add the argument nesting=NULL to get rid of that note but wanted to inquire about whether that was the right approach to answer my question of interest (ie assess differences in lesion presence between levels taking into account the covariates of age/sex and model random effects)?

As always, thank you for your help!

**Comment by rvlenth** [comment]
It is just a note, not an error nor a warning. You *do* get output, correct, if you do `summary(example_emmeans)`? I suggest you leave it alone.

**Comment by rvlenth** [comment]
PS if you really don't want to see the message, do
```r
emm_options(msg.nesting = FALSE)
```
before you run `emmeans`-related functions.

**Comment by rvlenth** [comment]
Looking at this again, I notice more clearly that `ID` is not a fixed effect in this model. So while I agree it is nested in `Sex`,  `ID` is a random factor and should not be included in the reference grid. This appears to be a bug in `brms:::recover.data.brmsfit`, because it should extract a `terms` component that includes only the fixed part of the model.

**Comment by rvlenth** [comment]
I am going to close this issue here, as I believe it needs to be resolved in **brms** and I have reported it there.
