### ISSUE TITLE
brms emmeans epred=TRUE

### ISSUE THREAD

**Issue by abadgerw** [rvlenth/emmeans#297]
When tabulating point estimates for a brms model I was using the epred=TRUE argument and was a bit confused by the output:

  Level emmean lower.HPD upper.HPD
 0       1.61     1.292      1.97
 1       1.13     0.892      1.38
 2       1.07     0.828      1.32

Point estimate displayed: median 
HPD interval probability: 0.95

The column indicates that the estimate is the mean but the comment at the bottom of the table states that it's the median. Could you clarify what is being displayed when using epred=TRUE?

In addition, I tried the same emmeans command for a bernoulli family brms model and received the following warning only when epred was set to TRUE:

Warning message:
In mean.default(y) : argument is not numeric or logical: returning NA

Any thoughts on why this occurs with a bernoulli family brms model but not a negative binomial or zero-inflated beta? 

Thanks for your help with this!

**Comment by rvlenth** [comment]
For the first question, you have a simulated posterior sample of estimated marginal means, and we compute the median of those EMMs. If you want to show a different estimate, specify it in `summary` or `hpd.summary` -- e.g., `summary(emmeans(...), point.est = mean)`. See `help("hpd.summary")`.

For the second, I think what is happening is that `epred()` doesn't produce numerical predictions. The **brms** package has its own **emmeans** support, and you may need to ask the developer of that package for details, and/or ask if the `epred` option *should* work.

**Comment by abadgerw** [comment]
Thanks! I've reached out to the brms developers to see what they think and will keep you apprised.

**Comment by rvlenth** [comment]
I will close this issue now, but feel free to comment or re-open if you think there is more I can do at this end.
