### ISSUE TITLE
Clarification on bias adjustment for log-transformed outcomes in linear regression models.

### ISSUE THREAD

**Issue by DInfanger** [rvlenth/emmeans#301]
When the outcome in a linear regression model is log-transformed, exponentiated predicted values are geometric means or the median of the corresponding log-normal distribution.

To get the unbiased arithmetic means, the required bias adjustment is `exp(x + sigma^2/2)`  where `sigma` is the estimated residual standard deviation (e.g. [Newman 1993](https://setac.onlinelibrary.wiley.com/doi/10.1002/etc.5620120618)). However, according to the [vignette](https://cran.r-project.org/web/packages/emmeans/vignettes/transformations.html), the option `bias.adj = TRUE` applies the correction `exp(x) + (1/2)*exp(x)*sigma^2` which produces different estimates.

Is my understanding correct? If yes, is it possible to apply the "correct" bias adjustment in `emmeans` or would you recommend sticking to the current implemented correction?

Here is a small `R` script to illustrate the matter:

```
library(emmeans)

set.seed(142857)
n <- 1e5
gr <- rbinom(n, 1, 0.5) # Two groups

y <- exp(0.75 + 2*gr + rnorm(n, 0, 1.2)) # Generate log-normal response

dat <- data.frame(
  y = y
  , gr = gr
  , grfac = factor(gr)
)

# Geometric means/medians of the two groups
exp(0.75)
exp(0.75 + 2)

# Arithmetic means of the two groups
exp(0.75 + 1.2^2/2)
exp(0.75 + 2 + 1.2^2/2)

# Fit the model
mod <- lm(log(y)~grfac, data = dat)

# Predicted geometric means
emmeans(mod, "grfac", type = "response")

 grfac response     SE    df lower.CL upper.CL
 0         2.12 0.0114 99998      2.1     2.14
 1        15.69 0.0839 99998     15.5    15.85

# Predictions with bias correction
emmeans(mod, "grfac", type = "response", bias.adj = TRUE)

grfac response     SE    df lower.CL upper.CL
 0         3.64 0.0196 99998     3.61     3.68
 1        26.94 0.1441 99998    26.66    27.22
```

The bias-corrected means are 3.64 and 26.94 whereas the correct arithmetic means are 4.35 and 32.14.

**Comment by rvlenth** [comment]
It is true that the correct bias adjustment is as you state. However, my code uses a Taylor-series expansion as documented, which is an approximation in the case of a log transformation. They are close to being the same correction in less extreme cases. If you had chosen larger means or smaller SDs in your simulation, it'd have come out much closer, e.g.
```r
> set.seed(142857)
> n <- 1e5
> gr <- rbinom(n, 1, 0.5) # Two groups
> y2 <- exp(0.75 + 2*gr + rnorm(n, 0, 0.12))
> mod2 <- lm(log(y2) ~ gr)

> emmeans(mod2, "gr", type = "r")
 gr response       SE    df lower.CL upper.CL
  0    2.117 0.001136 99998    2.115     2.12
  1   15.647 0.008368 99998   15.631    15.66

Confidence level used: 0.95 
Intervals are back-transformed from the log scale
 
> emmeans(mod2, "gr", type = "r", bias.adj = TRUE)
 gr response       SE    df lower.CL upper.CL
  0    2.133 0.001144 99998     2.13    2.135
  1   15.759 0.008428 99998    15.74   15.776

Confidence level used: 0.95 
Intervals are back-transformed from the log scale 
Bias adjustment applied based on sigma = 0.11979 

> exp(0.75 + 0.12^2/2)
[1] 2.132297
> exp(2 + 0.75 + 0.12^2/2)
[1] 15.75567
```
I use the same Taylor expansion for all transformations, and this one happens to be exact in the case of a square-root transformation, rather than for the log transformation.

**Comment by DInfanger** [comment]
Thank you for the clarification, that's very helpful.

**Comment by rvlenth** [comment]
I think this question is resolved, so am closing this issue.
