### ISSUE TITLE
Error: variable lengths differ

### ISSUE THREAD

**Issue by alexisdmacintyre** [rvlenth/emmeans#302]
```
finalMod <- gamlss(testVar ~ Z * scale(X1) + re(random=~1|X2), 
                   sigma.formula = ~Z * scale(X1) + re(random=~1|X2),
                   family=BCPE, data=na.omit(testTable.filtered))
emmeans(finalMod, what = c("mu"), "Z")
```
Returns:

```
Error in model.frame.default(formula, data = data, ...) : 
  variable lengths differ (found for 're(random = ~1 | X2)')
```

I have tried adding and removing NA rows, etc. I previously used `gamlss` and `emmeans` for beta regression models with success, so I wonder, is it an issue with `family=BCPE`?

**Edit:** I don't get this error when I run the exact same model, omitting my random effect term.

**Comment by rvlenth** [comment]
There is limited support for `gamlss` models. The [models vignette](https://cran.r-project.org/web/packages/emmeans/vignettes/models.html#H) mentions that  there is no support when the selected part of the model contains a smoothing method like `pb()`, and I believe that `re()` is in that category as well. This is consistent with your experience in getting it to work when the `re()` term was omitted.

Perhaps someday, broader `gamlss` support will be available. I'm sorry it doesn't work currently.

**Comment by rvlenth** [comment]
Right now, I don't see more I can do on this issue; so am closing it.
