### ISSUE TITLE
How bad is the "asymptotic" method when N is large? ("kenward-roger" are "satterthwaite" are computationally too expensive)

### ISSUE THREAD

**Issue by robertour** [rvlenth/emmeans#306]
I have been trying to calculate "kenward-roger" or "satterthwaite" but I have no idea if they will ever finished. Currently using 48GB RAM on 40CPU cluster, but it seems stalled at the moment: CPUs are not being used, and the process is not requesting more RAM. So, I don't even know if it is doing something (at least, I don't see errors).

To force this, I have increase the limit `emm_options(pbkrtest.limit = 45861)`, so it doesn't default to the asymptotic, which as far as I understand underestimates the size of the confidence interval and increase the Type I error (please point to other issues if there exists).

Considering the size of the dataframe (N=45861), and the 3 factor model (`r~a*b*c + (1|s)`), is there anyway to know if the "asymptotic" method is good enough? (p-values are generally very low)

Is there a way to approximate "kenward-roger" or "satterthwaite" methods, so the are, for example, bootstrapped? 

I have read several threads and info, but I am really not sure which are my options here, so any pointers are very welcome.

Some reads:
https://cran.r-project.org/web/packages/emmeans/vignettes/models.html#L
https://github.com/rvlenth/emmeans/issues/176
https://www.researchgate.net/publication/309725867_LmerTest_Tests_in_linear_mixed_effects_models

**Comment by rvlenth** [comment]
The low CPU is probably due to memory demands, where stuff has to be paged in and out of memory. I wouldn't hold my breath that it will ever finish. I really did try to warn people about this in the documentation and messages.

If you have reasonable numbers of subjects, you should get reasonable numbers of d.f., making the tests close to the asymptotic ones. For within-subjects effects, there isn't any concern.

**Comment by robertour** [comment]
Thanks @rvlenth . It finished after all hitting 100GB of RAM. I did not measure exactly how long did it take, a couple of hours perhaps. The results were effectively similar as you predicted, some small differences on third decimals.

I, then, run another similar test. The data here was a bit bigger (N=~55K). This one crashed **almost immediately**, I believe because of lack of memory; this was the error: "Cholmod error 'problem too large'". Just reporting here in case anybody else is struggling with this.
