### ISSUE TITLE
Contrast of interaction groups against an external baseline (general population data)

### ISSUE THREAD

**Issue by robertour** [rvlenth/emmeans#307]
## Summary

I want to compare the results of my experiment against data of the general population, considering that the general population data was not collected on my experiment (for simplicity, let's say I found it in a external source).

## Model

My `lmer` model looks like this:

`response ~ intervention*factor*month + 1|day`

The regression is currently built using only the data of my experiment, it does not include the general population data. Moreover, **the general population data has no information regarding intervention, factor, months or days**. It only shows a randomized sample of the population (the sample is big enough to be considered the population).

## Question

I found a triple interaction in the model. What I want is to use `emmeans` to compare all the interactions groups (combination of intervention-factor-month) against the data of the general population.

## Possible solutions

Here is a couple of things I have consider doing, but I am not sure what is correct:

### A) Include the general population data into the `lmer` model

In theory, this sounds like the perfect solution. In practice, I am not sure how to do this because, as I said, the general population data has no information regarding intervention, factor, months or days.

A colleague has suggest to just duplicate the general population data as many times as I needed to cover all the interactions groups, but this would cause an explosion of data. Given that I have 3 interventions, 4 factors, 4 months and months made of 100 days, I would have to impute the general population data (N=200) 4800 times, i.e. 960000 imputed rows which is much bigger than my experimental dataset: ~50000. 

Before doing that, I would like to know if this imputation is a valid approach, and if it could have an effect on the regression. Perhaps there is a way to tell lmer to use some external data as baseline.

### B) Post t-test with Bonferroni correction

A quick way around is to just obtain the means and standard deviations of all the interactions groups through `emmeans` in the current `lmer` model, and use t-tests to compare them against the mean and standard deviations generated from the population data. Then, use Bonferroni to adjust the p-values.

A problem here is the specification of N for the interaction groups, because, in practice, the number of observations varies for each of the days. Here are some options:
 1. Use the the theoretical maximum observations which is 50, but that rarely happens as the observation might fail producing a missing. I also have 4 subjects (removed from the `lmer` model because they didn't add any explanatory power), so I perhaps I should use 200 instead as I believe that the N in the t-test will add to the power (the idea of including 4 subjects in the first place)
 2. Use the average/median of observations actually collected per interaction group
 3. Use the average/median of observations actually collected per interaction group per subject

Any guidance would be very much appreciated.

**Comment by rvlenth** [comment]
If I understand it, your goal is to compare the mean at each combination of intervention, factor, and month with the mean of the general population. It is not clear to me why such a comparison is motivated by noticing a 3-way interaction, but that is another matter.

In (A), you seem to suggest that you need another general-population group for each factor combination. Why is that? It is certainly permissible to compare the same one mean with each of the others. That's what's done, for example, with Dunnett-style comparisons.

My suggestion is to append the general population data to your dataset. Give the level `GP`, say, as the levels of intervention, factor, month, and day. (If `day` is numeric, maybe you need to give it a value of 99999 or something instead.) Then create a new variable from the combinations of the fixed factors. Then just do Dunnett comparisons:
```
all.dat <- transform(dat, trt = interaction(intervention, factor, month))
newmod <- lmer(y ~ trt + (1|day), data = all.dat)
EMM <- emmeans(newmod, "trt")
contrast(EMM, "trt.vs.ctrl", ref = "GP.GP.GP")
```

**Comment by robertour** [comment]
> You seem to suggest that you need another general-population group for each factor combination. Why is that?

Only because of lack of knowledge on how to properly feed it to the model and emmeans. I just though of a hack-ish way that could also explain what I was trying to do. I had special concerns regarding the day (numerical), and I did not expect the `99999` value solution, I would have gone for `-1` but I guess it doesn't really matter because, at the end, I just want to tell the model to fit the data "within the day"?

So, I think I am clear with this part. Thanks again!!

(For other readers, please do not attempt (A). I tried it, and it completely inflates Type I error when I compare the results to what @rvlenth suggested)

----

I am now wondering on the consequences of changing the model to test the contrasts. I originally had `lmer(y ~ intervention*factor*month + (1|day), data = all.dat)`, but what you suggest `lmer(y ~ trt + (1|day), data = all.dat)` is very different. It ignores the main effects, and double interactions which, I know, mean little for the interpretation of results but it just "feels" wrong to simply throw them away. 

Would that affect the results?

If so, would it be possible to customize the contrasts without changing the model? Something like this:

```
oldmod <- lmer(y ~ intervention*factor*month + (1|day), data = all.dat)
EMM <- emmeans(oldmod,   ~ intervention|(factor:month) )
contrast(EMM, interaction = c("intervention", "factor","month"), ref=c("GP", "GP", "GP"))
```

**Comment by rvlenth** [comment]
The model `y  ~ trt + (1|day)` has exactly the same fitted values as `y ~ intervention*factor*month + (1|day)`. Those are just different parameterizations of the same model. The interaction contrast you suggest would not work, but if it did, it would be contrasts *of* contrasts *of* contrasts -- not at all what we need.

I wonder if you have a clear idea of your research goals in conducting this experiment, and I suggest that you find a statistical consultant who can talk that over with you and make sure that the tests you are doing answer those goals. Most university statistics departments offer some way of connecting you with someone who could help.

**Comment by rvlenth** [comment]
Closing this issue, as I think it's resolved.
