### ISSUE TITLE
Support for gnls objects

### ISSUE THREAD

**Issue by femiguez** [rvlenth/emmeans#313]
Thank you for the excellent package which has been extremely useful over the years. I'm trying to add support for objects of class 'gnls'. I'm running into some issues that might be easier for you to address. I would be happy to test it if we find something that works. This is what I have at the moment:

```
### For gnls objects: More code might be required to extract parameter
### list and names
### Additional REQUIRED argument is 'param' - parameter name to explore
recover_data.gnls = function(object, param, ...) {
    if(missing(param))
        return("'param' argument is required for gnls objects")
    fcall = object$call
    if (!is.null(fcall$weights))
        fcall$weights = nlme::varWeights(object$modelStruct)
    ## The 'fixed' part in a gnls object is not as simple as in an nlme object
    plist <- object$plist
    pnames <- names(plist)
    if(is.null(params <- eval(object$call$params))){
        params <- list(formula(paste0(paste(pnames, collapse = "+"), "~ 1")))
    }else{ 
        if (!is.list(params)) params <- list(params)
    }
    params <- unlist(lapply(params, function(pp){
        if(is.name(pp[[2]])){
            list(pp)
        }else{
            ## multiple parameters on left hand side
            eval(parse(text = paste("list(",
                                    paste(paste(all.vars(pp[[2]]), deparse(pp[[3]]), sep = "~"),
                                          collapse = ","),
                                    ")")))
        }
    }), recursive=FALSE)
    
    names(params) <- pnames
    fixed = params
    if (is.call(fixed))
        fixed = eval(fixed, envir = parent.frame())
    if(!is.list(fixed))
        fixed = as.list(fixed)
    form = NULL
    for (x in fixed)
        if (param %in% all.names(x)) form = x   
    if (is.null(form))
        return(paste("Can't find '", param, "' among the parameters", sep = ""))
    fcall$weights = NULL
    ## trms = delete.response(terms(update(terms(object), form)))
    trms <- nlme::asOneFormula(formula(object), fcall$params,
                               omit = c(names(object$plist), "pi",
                                        deparse(nlme::getResponseFormula(object)[[2]])))
    if (length(.all.vars(trms)) == 0)
        return(paste("No predictors for '", param, "' in fixed model", sep = ""))
    recover_data(fcall, trms, object$na.action, ...)
}

emm_basis.gnls = function(object, trms, xlev, grid, param, ...) {
    idx = object$pmap[[param]]
    V = object$varBeta[idx, idx, drop = FALSE]
    bhat = object$coefficients[idx]
    contr = attr(object$plist[[param]], "contrasts")
    m = model.frame(trms, grid, na.action = na.pass, xlev = xlev)
    X = model.matrix(trms, m, contrasts.arg = contr)
    dfx = rep(object$dims$N, ncol(object$plist[[param]])) - rep(1, ncol(object$plist[[param]]))
    names(dfx) <- colnames(object$plist[[param]])
    ## dfx[1] = min(dfx) # I'm assuming 1st one is intercept
    ## There is no intercept in nonlinear models. I'm confused about this
    dffun = function(k, dfargs) { # containment df
        idx = which(abs(k) > 1e-6)
        ifelse(length(idx) > 0, min(dfargs$dfx[idx]), NA)
    }
    list(X = X, bhat = bhat, nbasis = estimability::all.estble, 
         V = V, dffun = dffun, dfargs = list(dfx = dfx), 
         misc = list(estName = param))
}
```

I feel like I'm close. When I test it however, it does not work.

```
require(nlme)
require(nlraa)
fmg <- gnls(weight ~ SSbgf(Time, w.max, t.e, t.m), data = Soybean,
             param = w.max + t.e + t.m ~ Variety,
            start = c(18, 0, 78, 0, 60, 0))
 
 emmeans(fmg, ~ Variety, param = "w.max")
# Error in (function (object, at, cov.reduce = mean, cov.keep = get_emm_option("cov.keep"),  : 
#  Something went wrong:
# Non-conformable elements in reference grid.
```
Any ideas?

**Comment by femiguez** [comment]
Update: It looks like I need to remove the covariate from the trms object

**Comment by femiguez** [comment]
This seems to be working:

```
### For gnls objects: More code might be required to extract parameter
### list and names
### Additional REQUIRED argument is 'param' - parameter name to explore
recover_data.gnls = function(object, param, ...) {
    if(missing(param))
        return("'param' argument is required for gnls objects")
    fcall = object$call
    if (!is.null(fcall$weights))
        fcall$weights = nlme::varWeights(object$modelStruct)
    ## The 'fixed' part in a gnls object is not as simple as in an nlme object
    plist <- object$plist
    pnames <- names(plist)
    if(is.null(params <- eval(object$call$params))){
        params <- list(formula(paste0(paste(pnames, collapse = "+"), "~ 1")))
    }else{ 
        if (!is.list(params)) params <- list(params)
    }
    params <- unlist(lapply(params, function(pp){
        if(is.name(pp[[2]])){
            list(pp)
        }else{
            ## multiple parameters on left hand side
            eval(parse(text = paste("list(",
                                    paste(paste(all.vars(pp[[2]]), deparse(pp[[3]]), sep = "~"),
                                          collapse = ","),
                                    ")")))
        }
    }), recursive=FALSE)
    
    names(params) <- pnames
    fixed = params
    if (is.call(fixed))
        fixed = eval(fixed, envir = parent.frame())
    if(!is.list(fixed))
        fixed = as.list(fixed)
    form = NULL
    for (x in fixed)
        if (param %in% all.names(x)) form = x   
    if (is.null(form))
        return(paste("Can't find '", param, "' among the parameters", sep = ""))
    fcall$weights = NULL
    ## trms = delete.response(terms(update(terms(object), form)))
    vars.wo.parms <- setdiff(all.vars(formula(object)), pnames)
    trms <- nlme::asOneFormula(formula(object), fcall$params,
                               omit = c(names(object$plist), "pi", vars.wo.parms))
    if (length(.all.vars(trms)) == 0)
        return(paste("No predictors for '", param, "' in fixed model", sep = ""))
    recover_data(fcall, trms, object$na.action, ...)
}

emm_basis.gnls = function(object, trms, xlev, grid, param, ...) {
    idx = object$pmap[[param]]
    V = object$varBeta[idx, idx, drop = FALSE]
    bhat = object$coefficients[idx]
    contr = attr(object$plist[[param]], "contrasts")
    m = model.frame(trms, grid, na.action = na.pass, xlev = xlev)
    X = model.matrix(trms, m, contrasts.arg = contr)
    dfx = rep(object$dims$N, ncol(object$plist[[param]])) - rep(1, ncol(object$plist[[param]]))
    names(dfx) <- colnames(object$plist[[param]])
    ## dfx[1] = min(dfx) # I'm assuming 1st one is intercept
    ## There is no intercept in nonlinear models. I'm confused about this
    dffun = function(k, dfargs) { # containment df
        idx = which(abs(k) > 1e-6)
        ifelse(length(idx) > 0, min(dfargs$dfx[idx]), NA)
    }
    list(X = X, bhat = bhat, nbasis = estimability::all.estble, 
         V = V, dffun = dffun, dfargs = list(dfx = dfx), 
         misc = list(estName = param))
}
```

**Comment by femiguez** [comment]
This seems to be working. Do you want me to submit a PR?

**Comment by rvlenth** [comment]
I'm not sure what you're trying to do with dffun and dfargs. Seems to me we don't have random effects or a group structure here, so we don't need containment d.f. like we used in `lme`.  Your code seems to just create a constant vector in `dfargs`, then return the minimum of it via `dffun`; but that will always be the same value since all the elements of `dfx` are equal. So why not
```
dfx = object$dims$N - object$dims$p
dffun = function(k, dfargs) dfargs$dfx
```
Note I subtract the number of parameters from `dims$N`; this seems consistent with what I see at the end of `summary(fmg)`.

Also, I wonder if you need to work that hard to recover the data. It looks like `formula(object)` is (almost) completely irrelevant because what we need is the `params` part. As I understand it, every `param` has the same right-hand-side - is that correct? And we need only the right-hand side for `recover_data`.  Thinking along those lines, I was able to get this to work (at least with your example) with a very much simpler `recover_data` method:
```
recover_data.gnls = function(object, param, data, ...) {
    fcall = object$call$params
    if (is.null(fcall))
        return("Models fitted without a 'params' specification are not supported.")
    if(missing(param))
        return("'param' argument is required for gnls objects")
    trms = delete.response(terms(eval(fcall, envir = environment(formula(object)))))
    if(is.null(data))
        data = eval(object$call$data, envir = environment(formula(object)))
    recover_data(fcall, trms, object$na.action, data = data, ...)
}
```
Note that we need to wrap a couple of things we extracted from the call in `eval()`, and what we *do* need from the formula is the environment. We probably should also do something in case there is a `subset` argument in the call.

**Comment by femiguez** [comment]
This is very useful! Part of the reason for the extra work is that it is possible to fit models such as this one

```
fm2 <- gnls(weight ~ SSbgf(Time, w.max, t.e, t.m), data = Soybean,
            param = list(w.max ~ Variety, t.e + t.m ~ 1),
            start = c(18, 0, 78, 60))
```

In this case, the simpler version of recover_data.gnls returns

```
> emmeans(fm2, ~ Variety, param = "w.max")
Error in terms.default(eval(fcall, envir = environment(formula(object)))) : 
  no terms component nor attribute
Error in (function (object, at, cov.reduce = mean, cov.keep = get_emm_option("cov.keep"),  : 
  Perhaps a 'data' or 'params' argument is needed
```

So I'm proposing this slightly improved version of recover_data.gnls

```
# experimental support for gnls
recover_data.gnls = function(object, param, data, ...) {
    fcall = object$call$params
    if (is.null(fcall))
        return("Models fitted without a 'params' specification are not supported.")
    if(missing(param))
        return("'param' argument is required for gnls objects")

    plist = object$plist
    pnames = names(plist)
    params = eval(object$call$params)
    if (!is.list(params)) params = list(params)
    
    params = unlist(lapply(params, function(pp){
        if(is.name(pp[[2]])){
            list(pp)
        }else{
            ## multiple parameters on left hand side
            eval(parse(text = paste("list(",
                                    paste(paste(all.vars(pp[[2]]), deparse(pp[[3]]), sep = "~"),
                                          collapse = ","),
                                    ")")))
        }
    }), recursive=FALSE)

    names(params) = pnames
    form = params[[param]]
    
    trms = delete.response(terms(eval(form, envir = environment(formula(object)))))
    if(is.null(data))
        data = eval(object$call$data, envir = environment(formula(object)))
    recover_data(fcall, trms, object$na.action, data = data, ...)
}
```

Which does handle the case above. I'll admit that I'm a bit surprised that the current code does handle a model such as this one:

```
fm3 <- nlme(weight ~ SSbgf(Time, w.max, t.e, t.m), data = Soybean,
            fixed = list(w.max ~ Variety, t.e + t.m ~ 1),
            random = w.max ~ 1,
            start = c(18, 0, 78, 60))

emmeans(fm3, ~ Variety, param = "w.max")
```
But maybe that is because of how `eval` handles objects of class nlme vs. gnls.

I tried the subset argument and I do not find any problems. For example, this seems to work,

```
fm2s <- gnls(weight ~ SSbgf(Time, w.max, t.e, t.m), data = Soybean,
            param = list(w.max ~ Variety, t.e + t.m ~ 1),
            subset = Year == 1988,
            start = c(18, 0, 78, 60))           

emmeans(fm2s, ~ Variety, param = "w.max")
```

I really did not understand the degrees of freedom part. I was imitating the nlme version of the code. For example, the line `dfx[1] = min(dfx)` states that it is assumed that the first one is the intercept. But why take the minimum? Is this to contemplate unbalanced designs or missing data? And why modify only the first element of that vector?

I agree that for gnls. Your solution seems to work well.

**Comment by rvlenth** [comment]
OK, thanks. If you want to make a PR, I'll merge it. I may tweak it a bit to suit my coding style.

**Comment by femiguez** [comment]
Great! I'll keep testing and see if I encounter any other issues.

**Comment by femiguez** [comment]
I had one more thought and would like your opinion. In a model such as this one

```
fit5 <- gnls(weight ~ SSlogis(Time, Asym, xmid, scal), data = ChickWeight, 
             weights = varPower(),
             correlation = corCAR1(form = ~ Time | Chick))
```
There are 3 parameters for the nonlinear model. So `fit5$dims$p` is 3, but the total number of parameters for the model also include the coefficient for the variance structure, the correlation parameter and the residual variance. So, the logLik `logLik(fit5)` returns 6 degrees of freedom. So, should we replace ` dfx = object$dims$N - object$dims$p` with ` dfx = object$dims$N - attr(logLik(object), "df")`?

**Comment by rvlenth** [comment]
Good question. I'm thinking so. Should I make that change in the code?

BTW, this particular example won't work with `emmeans`, because there is no `params` component:
```
> ref_grid(fit5)
Error in ref_grid(fit5) : 
  Models fitted without a 'params' specification are not supported.
```
We can make the parameters depend on Diet, though:
```
> fit6 <- gnls(weight ~ SSlogis(Time, Asym, xmid, scal), data = ChickWeight, 
+              weights = varPower(), params = Asym+xmid+scal ~ Diet,
+              correlation = corCAR1(form = ~ Time | Chick),
+              start = rep(c(341,17,8.5), each = 4))

> emmeans(fit5, "Diet", param = "Asym")
 Diet emmean   SE  df lower.CL upper.CL
 1       295 44.7 577      208      383
 2       336 51.0 577      236      436
 3       500 96.5 577      311      690
 4       296 33.1 577      231      361

Confidence level used: 0.95 
> emmeans(fit5, "Diet", param = "xmid")
 Diet emmean   SE  df lower.CL upper.CL
 1      18.4 2.75 577    13.05     23.8
 2      16.3 2.18 577    12.00     20.6
 3      19.6 2.53 577    14.67     24.6
 4      12.3 1.31 577     9.78     14.9

Confidence level used: 0.95 
> emmeans(fit5, "Diet", param = "scal")
 Diet emmean    SE  df lower.CL upper.CL
 1     10.16 0.611 577     8.96    11.37
 2      8.21 0.495 577     7.24     9.18
 3      8.11 0.442 577     7.24     8.98
 4      6.75 0.352 577     6.06     7.44

Confidence level used: 0.95 
```
This is interesting, but I also see that the df are shown as 577, which is N - 1, not even N - p. So I'm wondering what's going on here... I'll see what I can discover.

**Comment by femiguez** [comment]
Yes, I forgot to add the effect of Diet. However, I get a different answer

```
fit6 <- gnls(weight ~ SSlogis(Time, Asym, xmid, scal), data = ChickWeight, 
                             weights = varPower(), params = Asym+xmid+scal ~ Diet,
                             correlation = corCAR1(form = ~ Time | Chick),
                             start = rep(c(341,17,8.5), each = 4))

anova(fit6)
Denom. DF: 566 
                 numDF   F-value p-value
Asym.(Intercept)     1 2821.0901  <.0001
Asym.Diet            3   41.8569  <.0001
xmid.(Intercept)     1 1004.0656  <.0001
xmid.Diet            3   54.9994  <.0001
scal.(Intercept)     1 1257.1235  <.0001
scal.Diet            3    8.4769  <.0001

emmeans(fit6, ~ Diet, param = "Asym")
 Diet emmean   SE  df lower.CL upper.CL
 1       295 44.7 563      208      383
 2       336 51.0 563      236      436
 3       500 96.5 563      311      690
 4       296 33.1 563      231      361

Confidence level used: 0.95 
```

With the version of the code that uses `dfx = object$dims$N - attr(logLik(object), "df")`. I do notice that the df in `anova` are different from `emmeans` when we use this method, but I tend to think that the method `dfx = object$dims$N - attr(logLik(object), "df")` is better since it includes all the parameters in the model.

**Comment by rvlenth** [comment]
Duh! I realized what was going on this morning while in the shower, of all places. I still had your original code in my workspace and it overrode the revised package code.
```
> rm(recover_data.gnls, emm_basis.gnls)

> emmeans(fit5, trt.vs.ctrl1 ~ Diet, param = "Asym", adjust = "none")
$emmeans
 Diet emmean   SE  df lower.CL upper.CL
 1       295 44.7 563      208      383
 2       336 51.0 563      236      436
 3       500 96.5 563      311      690
 4       296 33.1 563      231      361

Confidence level used: 0.95 

$contrasts
 contrast estimate    SE  df t.ratio p.value
 2 - 1      40.866  67.8 563   0.603  0.5470
 3 - 1     204.744 106.3 563   1.926  0.0547
 4 - 1       0.633  55.6 563   0.011  0.9909
```
I did opt for what seems like more elegant code:
```
    dfx = with(attributes(logLik(object)), nobs - df)
```
But here's something *very* different from your `anova` result:
```
> joint_tests(fit6, param = "Asym")
 model term df1 df2 F.ratio p.value
 Diet         3 563   1.459  0.2249
```
Compare this F = 1.46 with F = 41.86 from the anova. However, the `joint_tests()` result seems consistent with the comparisons with the first level we see above, which in turn agree with the model summary:
```
> summary(fit6)
    ...
Coefficients:
                     Value Std.Error   t-value p-value
Asym.(Intercept) 295.39692  44.65060  6.615744  0.0000
Asym.Diet2        40.86576  67.80628  0.602684  0.5470
Asym.Diet3       204.74374 106.33068  1.925538  0.0547
Asym.Diet4         0.63330  55.56160  0.011398  0.9909
   ...
```
However, here are the other two:
```
> joint_tests(fit6, param = "xmid")
 model term df1 df2 F.ratio p.value
 Diet         3 563   3.127  0.0254

> joint_tests(fit6, param = "scal")
 model term df1 df2 F.ratio p.value
 Diet         3 563   8.301  <.0001
```
which is fairly close to the anova ... and now I'm realizing that `anova()` by default yields *sequential* tests. But I sure don't understand what it means to enter the diets sequentially in this nonlinear model.. The "marginal" results make a lot more sense and align pretty closely with `joint_tests()`:
```
> anova(fit6, type = "marginal")
Denom. DF: 566 
                 numDF   F-value p-value
Asym.(Intercept)     1  44.69601  <.0001
Asym.Diet            3   1.48953  0.2163
xmid.(Intercept)     1  45.96158  <.0001
xmid.Diet            3   3.19292  0.0233
scal.(Intercept)     1 282.22856  <.0001
scal.Diet            3   8.47695  <.0001
```

**Comment by rvlenth** [comment]
I never answered your d.f. question fully. The context is "containment" and it has to do with which random effects play a role in the uncertainty of an estimate. 

Take the classical split-plot experiment in `nlme::Oats`, for example. We have 6 blocks; each block is divided into 3 whole plots in separate randomization, and those plots are assigned to `Variety` such that all 3 varieties appear in each block. So at this point we have 18 plots, 6 of each variety, in a complete-block design. Note that these plots are the experimental units (EUs) to which the levels of `Variety` are assigned, and there are 6 of them for each level. The d.f. for this part of the experiment are 1 for the grand mean, 3-1=2 for `Variety`, 6-1=5 for `Block`, and 2x5=10 for `Block:Variety` which is the error term for this block design. These d.f. add to 18, the number of whole plots.

Now for the spl;it-plot part of the design. We divide each of the whole plots into 4 split plots in 18 separate randomizations; and assign the four `nitro` levels to the 4 split plots in each plot. Thus, we have a total of 72 split plots, which are the EUs for `nitro`, 18 split plots for each level. Counting d.f., we have 4-1=3 for `nitro` and 72-3-18=51 for error (the 18 we subtracted are from the whole-plot part above). But that 51 d.f. for error only applies to `nitro` comparisons because we've already explained what happens with `Variety`.

The containment method has to do with only going as far down in the grouping as is justified based on which random effects are involved. To illustrate, let's fit a model:
```
> Oats.lme = lme(yield ~ Variety + factor(nitro), random = ~1|Block/Variety, data = Oats)
```
(and note that `Block/Variety` identifies the 18 whole plots). The d.f. information in terms of how the fixed effects relate to the random effects is here:
```
> Oats.lme$fixDF$X
      (Intercept) VarietyMarvellous    VarietyVictory  factor(nitro)0.2  factor(nitro)0.4 
               51                10                10                51                51 
 factor(nitro)0.6 
               51
```
We see that the d.f. for the `Variety` effects is 10, and for `nitro` effects, 51 as explained above. However, what is not visible here is the 5 d.f. for `Block`; and I claim that the d.f. for `(Intercept)` should be 6-1=5, the d.f. for the coarsest level of grouping. I have a posting about this in [CrossValidated](https://stats.stackexchange.com/questions/140156/degrees-of-freedom-using-containment-method) where I maintain that not just `lme`, but SAS, have this wrong. So I change the d.f. for `(Intercept)` to 5.

Now, containment d.f. says that when we want the d.f. for a linear function c0 + c1*b1 + c2*b2 + ... + ck*bk,  look at the nonzero cj and the corresponding d.f. -- and pick the *smallest* d.f. involved. So for this model, this is what we get:
```
> emmeans(Oats.lme, trt.vs.ctrl ~ Variety)
$emmeans
 Variety     emmean  SE df lower.CL upper.CL
 Golden Rain  104.5 7.8  5     84.5      125
 Marvellous   109.8 7.8  5     89.7      130
 Victory       97.6 7.8  5     77.6      118

Results are averaged over the levels of: nitro 
Degrees-of-freedom method: containment 
Confidence level used: 0.95 

$contrasts
 contrast                 estimate   SE df t.ratio p.value
 Marvellous - Golden Rain     5.29 7.08 10   0.748  0.6833
 Victory - Golden Rain       -6.88 7.08 10  -0.971  0.5476

Results are averaged over the levels of: nitro 
Degrees-of-freedom method: containment 
P value adjustment: dunnettx method for 2 tests 

> emmeans(Oats.lme, trt.vs.ctrl ~ nitro)
$emmeans
 nitro emmean   SE df lower.CL upper.CL
   0.0   79.4 7.13  5     61.1     97.7
   0.2   98.9 7.13  5     80.6    117.2
   0.4  114.2 7.13  5     95.9    132.6
   0.6  123.4 7.13  5    105.1    141.7

Results are averaged over the levels of: Variety 
Degrees-of-freedom method: containment 
Confidence level used: 0.95 

$contrasts
 contrast estimate   SE df t.ratio p.value
 0.2 - 0      19.5 4.25 51   4.588  0.0001
 0.4 - 0      34.8 4.25 51   8.196  <.0001
 0.6 - 0      44.0 4.25 51  10.353  <.0001

Results are averaged over the levels of: Variety 
Degrees-of-freedom method: containment 
P value adjustment: dunnettx method for 3 tests 
```
For the EMMs them selves, they all involve the intercept plus some other stuff so they get the minimum, 5 d.f. (which is what I changed the intercept to). For the `Variety` comparisons, we get 10 d.f. because the intercept effects cancel out but we still have `Variety` effects. And for `nitro`, the intercept and both the `Variety` effects are zeroed-out and we get 51 d.f. 

This is a nice balanced experiment, and if we use the Satterthwaite method we still get the same d.f. -- another justification for my changing the intercept d.f. for containment.

I hope that clarifies things

**Comment by rvlenth** [comment]
Closing this for now, as I think all is at a good stopping point. In the future, I might want to consider making `params` optional; and if not specified, it incorporates all the parameters, kike we do for a multivariate response. Doing so would facilitate, for example, doing multivariate contrasts via `mvcontrast()`.

**Comment by femiguez** [comment]
Thank you so much for the detailed response! I read your CrossValidated post and that led me down the rabbit hole. The main thing that was confusing was the line of code `dfx[1] = min(dfx)`. Thank you again for your detailed answer.
