### ISSUE TITLE
lm and aov model do not always produce identical emmeans

### ISSUE THREAD

**Issue by singmann** [rvlenth/emmeans#32]
Hi Russ,

I noticed some surprising behavior when comparing the marginal means between two equivalent models estimated with both `lm` and `aov`. When the models include all interactions, the emmeans are equal. However, when only including a main effect between two of the variables, the emmeans are not any more identical. The following example code shows it:

```
df_wide <- structure(list(id = structure(1:16, .Label = c("1", "2", "3", 
"4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", 
"16"), class = "factor"), treatment = structure(c(1L, 1L, 1L, 
1L, 1L, 2L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 3L, 3L), .Label = c("control", 
"A", "B"), class = "factor", contrasts = "contr.sum"), gender = structure(c(2L, 
2L, 2L, 1L, 1L, 2L, 2L, 1L, 1L, 2L, 2L, 2L, 1L, 1L, 1L, 1L), .Label = c("F", 
"M"), class = "factor", contrasts = "contr.sum"), fup = c(3, 
4, 7, 4, 4, 9, 9, 6, 5, 8, 6, 8, 8, 6, 7, 8), post = c(3, 3, 
5, 3, 6, 9, 8, 5, 4, 7, 5, 9, 6, 5, 7, 7), pre = c(2, 4, 6, 5, 
4, 8, 5, 3, 4, 4, 3, 6, 6, 2, 3, 5)), .Names = c("id", "treatment", 
"gender", "fup", "post", "pre"), row.names = c(NA, -16L), class = "data.frame")

library(emmeans)
options(contrasts=c('contr.sum', 'contr.poly'))

lm_main <- lm(cbind(fup, post, pre) ~ treatment + gender, df_wide)
lm_inter <- lm(cbind(fup, post, pre) ~ treatment * gender, df_wide)

df_long <- reshape2::melt(df_wide, id.vars = c("id", "treatment", "gender"))
aov_main <- aov(value ~ (gender + treatment)*variable + Error(id/variable), df_long)
aov_inter <- aov(value ~ (gender * treatment)*variable + Error(id/variable), df_long)

emm_lm_inter <- emmeans(lm_inter, "treatment")
emm_aov_inter <- emmeans(aov_inter, "treatment")
summary(emm_lm_inter)$emmean 
# [1] 4.222222 6.250000 6.027778
summary(emm_aov_inter)$emmean
# [1] 4.222222 6.250000 6.027778

emm_lm_main <- emmeans(lm_main, "treatment")
emm_aov_main <- emmeans(aov_main, "treatment")
summary(emm_lm_main)$emmean 
# [1] 4.100365 6.250000 6.071168
summary(emm_aov_main)$emmean
# [1] 4.126521 6.276156 6.097324
```

As you can see, the example requires both independent sample factors (between which the critical distinction between an interaction or main effect is included) and the repeated-measures factors.

Interestingly, if you remove one of the independent samples factors, the emmeans also differ:

```
lm2 <- lm(cbind(fup, post, pre) ~ treatment, df_wide)
aov2 <- aov(value ~ treatment*variable + Error(id/variable), df_long)
summary(emmeans(lm2, "treatment"))$emmean
# [1] 4.20 6.25 6.00
summary(emmeans(aov2, "treatment"))$emmean
# [1] 4.216667 6.266667 6.016667
```

It would be great to know if this is indeed some sort of bug or just a consequence of the different models. The fact that for the full models with the interaction are in fact identical, somehow suggests there might be some problem here.

Cheers,
Henrik

**Comment by rvlenth** [comment]
I don't think the models are equivalent. I agree that the fixed-effects parts are the same, but the `lm` models specify an unstructured covariance among the repeated measures, while the `aov` models assume more structure in the variance-covariance matrix. For instance, the `aov` model assumes that the variance of the prediction at a given `treatment*gender` combination are the same for each repeated measure, while the multivariate model does not. This can be seen by comparing the variance estimates:
```
> diag(vcov(emmeans(aov_main, ~ treatment*gender*variable)))
 [1] 0.7123341 0.7015494 0.5350339 0.5946250 0.7112358 0.6357169
 [7] 0.7123341 0.7015494 0.5350339 0.5946250 0.7112358 0.6357169
[13] 0.7123341 0.7015494 0.5350339 0.5946250 0.7112358 0.6357169

> diag(vcov(emmeans(lm_main, ~ treatment*gender*rep.meas)))
 [1] 0.5434493 0.5842080 0.3532420 0.4483457 0.5842080 0.4211732
 [7] 0.7791216 0.8375557 0.5064290 0.6427753 0.8375557 0.6038192
[13] 0.8613494 0.9259506 0.5598771 0.7106132 0.9259506 0.6675458
```
It is not surprising that *some* EMMs are the same for *some* models, because the fixed-effects structures are the same and the designs are balanced. With the interaction model, the predictions are all just the cell means:
```
> predict(emmeans(aov_inter, ~ treatment*gender*variable))
 [1] 4.000000 5.500000 7.250000 4.666667 9.000000 7.333333
 [7] 4.500000 4.500000 6.250000 3.666667 8.500000 7.000000
[13] 4.500000 3.500000 4.000000 4.000000 6.500000 4.333333

> predict(emmeans(lm_inter, ~ treatment*gender*rep.meas))
 [1] 4.000000 5.500000 7.250000 4.666667 9.000000 7.333333
 [7] 4.500000 4.500000 6.250000 3.666667 8.500000 7.000000
[13] 4.500000 3.500000 4.000000 4.000000 6.500000 4.333333
```
But with the main-effects models, the `lm` method produces the same predictions as would separate regressions on the three independent variables, while the `aov` model borrows covariance information across repeated measures:
```
> predict(emmeans(aov_main, ~ treatment*gender*variable))
 [1] 3.745134 6.708637 6.825426 4.880170 7.843674 7.960462
 [7] 3.369221 5.978710 6.128345 4.464112 7.073601 7.223236
[13] 3.770681 4.646594 3.843674 4.529805 5.405718 4.602798
> predict(emmeans(lm_main, ~ treatment*gender*rep.meas))
 [1] 3.718978 6.682482 6.799270 4.854015 7.817518 7.934307
 [7] 3.343066 5.952555 6.102190 4.437956 7.047445 7.197080
[13] 3.744526 4.620438 3.817518 4.503650 5.379562 4.576642
## compare 1st row with:
> lmm1 = lm(fup ~ treatment + gender, data = df_wide)
> predict(emmeans(lmm1, ~ treatment+gender))
[1] 3.718978 6.682482 6.799270 4.854015 7.817518 7.934307
```

Anyway, the bottom line is that I do not think this is a bug; it is a consequence of the different models, which really are different, not equivalent.

**Comment by singmann** [comment]
Thanks for the clarification. I suspected something along those lines, but could not come up with the explanation myself. I will close this issue, because your response solves it for me.
