### ISSUE TITLE
Best way to limit max memory allocated by emmeans

### ISSUE THREAD

**Issue by borjaevo** [rvlenth/emmeans#320]
I have some problem with emmeans function taking too much memory. Sometimes it could eat 10G or more.  
I have to increase lmerTest limit and pbkrTest limit to get it to work with the data a i need so maybe is too much data for emmeans to process. 
What i would like to know is if there is a limit i can set to one emmeans process only taking (for example) 6G. I understand setting this limit should make the process slower, or maybe its impossible so all data has to be in RAM.
 I read about new rg limit, but im worried it could impact the result?
Thanks

**Comment by borjaevo** [comment]
Im not sure about what implications could have the mode change to asymptotic in the results fidelity and precision. I'm comparing results now. But about computation.... we are talking differences about 1.1% in computing time and about 25% in memory consumption in the tests i made so its a veeeeery big difference. 

Thanks!

**Comment by rvlenth** [comment]
I think this is resolved, so am closing this issue
