### ISSUE TITLE
Is it possible to get emmeans for all posterior draws from a brmsfit object?

### ISSUE THREAD

**Issue by qdread** [rvlenth/emmeans#322]
Apologies if this is covered in the documentation but I cannot find it. Currently when you call `emmeans()` on a `brmsfit` object you get a point estimate and limits of a HPD interval. Is it possible to use `emmeans()` on a `brmsfit` object and get the raw emmean values for each posterior draw so that I can do things like plot distributions and things like that? Thanks again for the great package.

**Comment by rvlenth** [comment]
There is actually quite a bit of documentation on this, including a [vignette section on MCMC models](https://cran.r-project.org/web/packages/emmeans/vignettes/sophisticated.html#mcmc). The `as.mcmc()` method is what you need.

The [vignette index](https://cran.r-project.org/web/packages/emmeans/vignettes/vignette-topics.html) provides a lot of links that I had hoped would be helpful.

**Comment by qdread** [comment]
Excellent thanks, sorry for missing your helpful documentation!!!
