### ISSUE TITLE
Issue with odds ratio printing with pair function

### ISSUE THREAD

**Issue by Eun-San-Kim** [rvlenth/emmeans#325]
Hello, thank for your dedication to programming.

Recently, I found some error with `pair` and `summary` function in `emmeans` package.

The problem is as follows.

When calculation odds ratio, the lower confidence interval should be more than 0.

However, when the odds ratio is less than 1, I found that some results print out lower confidence interval less than 0.

This is example, using `pigs` data. I found this data in your vignettes.
(https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html)

First, I made dummy variable. This is because I want to make the results brief.

`pigs$fish_yn <- factor(I(pigs$source %in% c("fish")))`

Then, I ran logistic regression with response variable as categorical variable.

`pigs.glm <- glm(I(conc < 30) ~ fish_yn, data = pigs, family = "binomial")`

Then, I put this model into `emmeans`, `pairs` and `summary` function

`com_mod1 <- emmeans(pigs.glm, ~fish_yn, type = "response")`
`com_mod2 <- pairs(com_mod1)`
`summary(com_mod2, infer=TRUE)`

The result is as follows.

 `contrast     odds.ratio    SE  df asymp.LCL asymp.UCL z.ratio p.value`
` FALSE / TRUE     0.0833 0.101 Inf    -0.115     0.282   0.824  0.4098`

As you can see, the lower confidence interval (`asymp.LCL`) is less than 0 (-0.115).

I would really appreciate if you give me your opinion.

Thanks.

**Comment by Eun-San-Kim** [comment]
To notice, the odds ratio in `summary(pigs.glm)' is less than 1. However, I inverse the odds ratio on purpose. The significance of results is same.

**Comment by rvlenth** [comment]
It's important to read the annotations in the output:
```
> summary(com_mod2, infer=TRUE)
 contrast     odds.ratio    SE  df asymp.LCL asymp.UCL z.ratio p.value
 FALSE / TRUE     0.0833 0.101 Inf    -0.115     0.282   0.824  0.4098

Confidence level used: 0.95 
Intervals are back-transformed from the identity scale 
Tests are performed on the identity scale 
```
The fact that it says "identity scale" indicates that something is awry. The way your model is coded, `I(conc < 30)` is interpreted as a response transformation. So what `emmeans()` sees is
```
> ref_grid(pigs.glm)
'emmGrid' object with variables:
    fish_yn = FALSE, TRUE
Transformation: “logit” 
Additional response transformation: “identity” 
```
Your output has *both* transformations reversed, and the most recent one with the identity caused it to use an ordinary symmetric CI: 
```
> 0.0833 + c(-1,1) * 1.96 * 0.101
[1] -0.11466  0.28126
```
If you use "unlink" instead of "response", we don't do that second step with the identity transformation and you get the right thing:
```
> summary(com_mod2, type = "unlink", infer = TRUE)
 contrast     odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio p.value
 FALSE / TRUE     0.0833 0.101 Inf   0.00773     0.899    1  -2.048  0.0406

Confidence level used: 0.95 
Intervals are back-transformed from the log odds ratio scale 
Tests are performed on the log odds ratio scale
```
See the help page for `summary.emmGrid`

**Comment by rvlenth** [comment]
Thinking about this, though, it does seem like it'd be better when there is both a link function and a response transformation for both back-transformation steps to be included in CIs and tests. Doing so is harder to program, but I will see if I can do it.

**Comment by Eun-San-Kim** [comment]
Thanks for your kind reply. I appreciate it.

**Comment by rvlenth** [comment]
I think I have this worked out. First, for a general model with two transformations:
```
> mod = glm(log(conc) ~ source, family = Gamma, data = pigs)
> EMM = emmeans(mod, "source")

> summary(EMM, null = c(.290, .280, .270), infer = c(TRUE, TRUE), type = "link", adjust = "sid")
 source emmean      SE df lower.CL upper.CL null t.ratio p.value
 fish    0.293 0.00391 26    0.283    0.303 0.29   0.886  0.7661
 soy     0.275 0.00366 26    0.265    0.284 0.28  -1.486  0.3843
 skim    0.266 0.00373 26    0.256    0.275 0.27  -1.160  0.5889

Results are given on the inverse (not the response) scale. 
Confidence level used: 0.95 
Conf-level adjustment: sidak method for 3 estimates 
P value adjustment: sidak method for 3 tests 

> orig.lcl = .Last.value$lower.CL     # saved for later
> summary(EMM, null = c(.290, .280, .270), infer = c(TRUE, TRUE), type = "unlink", adjust = "sid")
 source response     SE df lower.CL upper.CL null t.ratio p.value
 fish       3.41 0.0454 26     3.30     3.53 3.45   0.886  0.7661
 soy        3.64 0.0485 26     3.52     3.77 3.57  -1.486  0.3843
 skim       3.76 0.0529 26     3.63     3.90 3.70  -1.160  0.5889

Confidence level used: 0.95 
Conf-level adjustment: sidak method for 3 estimates 
Intervals are back-transformed from the inverse scale 
P value adjustment: sidak method for 3 tests 
Tests are performed on the inverse scale 

> summary(EMM, null = c(.290, .280, .270), infer = c(TRUE, TRUE), type = "resp", adjust = "sid")
 source response   SE df lower.CL upper.CL null t.ratio p.value
 fish       30.2 1.37 26     27.0     34.0 31.4   0.886  0.7661
 soy        38.2 1.85 26     33.9     43.4 31.4  -1.486  0.3843
 skim       43.1 2.28 26     37.9     49.6 31.4  -1.160  0.5889

Confidence level used: 0.95 
Conf-level adjustment: sidak method for 3 estimates 
Intervals are back-transformed from the log[inverse] scale 
P value adjustment: sidak method for 3 tests 
Tests are performed on the log[inverse] scale 
```
Note that the t tests and p values stay the same regardless of which type, but the estimates, SEs, confidence limits, and null values go with the transformation stages. However, the conf limits are all computed based n the original confidence limits on the link scale:
```
> orig.lcl
[1] 0.2834882 0.2652327 0.2561535
> 1/orig.lcl
[1] 3.527484 3.770274 3.903910
> exp(1/orig.lcl)
[1] 34.03822 43.39195 49.59598
```

And for your model:
```
> summary(com_mod2, infer=TRUE)
 contrast     odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio p.value
 FALSE / TRUE     0.0833 0.101 Inf   0.00773     0.899    1  -2.048  0.0406

Confidence level used: 0.95 
Intervals are back-transformed from the identity[log odds ratio] scale 
Tests are performed on the identity[log odds ratio] scale 

> summary(com_mod2, infer=TRUE, type = "unlink")
 contrast     odds.ratio    SE  df asymp.LCL asymp.UCL null z.ratio p.value
 FALSE / TRUE     0.0833 0.101 Inf   0.00773     0.899    1  -2.048  0.0406

Confidence level used: 0.95 
Intervals are back-transformed from the log odds ratio scale 
Tests are performed on the log odds ratio scale 
```
These two latter results differ only in the annotation messages
