### ISSUE TITLE
`emtrends()` fails with ordinal models

### ISSUE THREAD

**Issue by rvlenth** [rvlenth/emmeans#327]
This issue is based on one that came up in https://github.com/vincentarelbundock/marginaleffects/issues/173. When we fit an ordinal model with `mode = "prob"`, we get a message about an irregular reference grid. After tracing, we find out that that happens because of an incorrect indexing calculation. For most models with multivariate response(s), the multivariate factors come last in the sort order, but this is not true when the RG was created from an ordinal model. A brute-force method fixed this problem, but created other issues, e.g. in cases with `cov.reduce = <some formula>`. So somehow we are going to have to find a workaround.

**Comment by rvlenth** [comment]
OK, I think I finally got this figured out. Using example in linked issue, we now get
```
> emtrends(mod, ~Sat, var = "Freq", mode = "prob")

Re-fitting to get Hessian

 Sat    Freq.trend      SE  df asymp.LCL asymp.UCL
 Low     -2.90e-03 0.00309 Inf -0.008946   0.00315
 Medium  -3.18e-05 0.00043 Inf -0.000874   0.00081
 High     2.93e-03 0.00316 Inf -0.003259   0.00911

Results are averaged over the levels of: Infl 
Confidence level used: 0.95 
```
It turns out this corrects another issue in `emtrends()`, in that recent versions returned zero trend estimates when there was a computed covariate. This was due to my moving a line of code in `ref_grid()` upward. But there was a good reason for it to be where it was, after covariate formulas were resolved.

**Comment by rvlenth** [comment]
@mattansb I think I fixed the issue in `emtrends()`

**Comment by mattansb** [comment]
Fantastic! Thanks!

CC @vincentarelbundock

**Comment by rvlenth** [comment]
Fixed, so closing
