### ISSUE TITLE
Error when hurdle model Conditional has at least one factor variable not present in Zero-Truncated 

### ISSUE THREAD

**Issue by marosteg** [rvlenth/emmeans#328]
I ran into an error using **emmeans** on a glmmTMB hurdle model in which the conditional portion of the model does not have a factor variable present in the zero-truncated (zi) portion. However, the reverse situation works. In this case, I am trying to extract EMMs for the 'zi' portion. A working example with available data is provided:

```
library(glmmTMB)
library(emmeans)
data(Salamanders)

# Conditional has same factor variables as Zero-Truncated ("mined" in both)
test1 <- glmmTMB(count ~ spp + mined,
                 zi=~spp + mined,
                 family=truncated_nbinom2, data=Salamanders)

emmeans(test1,c("spp","mined"),component="zi",type="response") # WORKS


# Conditional has one more factor variable than Zero-Truncated ("mined" only in the conditional)
test2 <- glmmTMB(count ~ spp + mined,
              zi=~spp,
              family=truncated_nbinom2, data=Salamanders)

emmeans(test2,c("spp","mined"),component="zi",type="response") # WORKS


# Conditional has one less factor variable than Zero-Truncated ("mined" only in the zi)
test3 <- glmmTMB(count ~ spp,
                 zi=~spp + mined,
                 family=truncated_nbinom2, data=Salamanders)

emmeans(test3,c("spp","mined"),component="zi",type="response") # ERROR
```
The resulting error:
```
Error in (function (object, at, cov.reduce = mean, cov.keep = get_emm_option("cov.keep"),  : 
  Something went wrong:
 Non-conformable elements in reference grid.
```
...suggests that the internal call to ref_grid() is only accessing the grid for the conditional portion even though I am specifically requesting the zi portion. This is confirmed with looking at the results of ref_grid() for the three tests, which all show the ref_grid for the conditional portion:
```
ref_grid(test1)
ref_grid(test2)
ref_grid(test3)
```
Thus, if the ref_grid result is identical for both model portions OR the conditional ref_grid is inclusive of the zi ref_grid, there are no errors generated, but if the zi portion contains a factor not present in the conditional portion the error is generated.

**Comment by rvlenth** [comment]
I think this will be a temporary fix: Copy the following function into your workspace:
```
recover_data.glmmTMB <- function (object, component = "cond", ...) 
{
    fcall <- getCall(object)
    if (!requireNamespace("emmeans")) 
        stop("please install (if necessary) and load the emmeans package")
    emmeans::recover_data(fcall, delete.response(terms(object, component = component)), 
        attr(model.frame(object), "na.action"), ...)
}
```
This overrides the `recover_data` method in the **glmmTMV** namespace. The only difference is it includes the `component` argument, and it uses the corresponding `terms` from the model. Now we have:
```r
> emmeans(test3,c("spp","mined"),component="zi",type="response")
 spp   mined response     SE  df lower.CL upper.CL
 GP    yes      0.853 0.0356 628    0.768    0.910
 PR    yes      0.969 0.0108 628    0.939    0.984
 DM    yes      0.791 0.0452 628    0.688    0.866
 EC-A  yes      0.946 0.0165 628    0.903    0.970
 EC-L  yes      0.791 0.0452 628    0.688    0.866
 DES-L yes      0.747 0.0506 628    0.636    0.833
 DF    yes      0.791 0.0452 628    0.688    0.866
 GP    no       0.343 0.0580 628    0.240    0.464
 PR    no       0.737 0.0597 628    0.605    0.837
 DM    no       0.254 0.0501 628    0.169    0.364
 EC-A  no       0.612 0.0648 628    0.480    0.730
 EC-L  no       0.254 0.0501 628    0.169    0.364
 DES-L no       0.211 0.0449 628    0.136    0.312
 DF    no       0.254 0.0501 628    0.169    0.364

Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 
```
I'll alert Ben that this change is needed.

**Comment by marosteg** [comment]
I just tried this out and it works perfectly. Thanks for the quick response and fix! Much appreciated.

**Comment by bbolker** [comment]
I think this can be closed because a `glmmTMB` fix is in progress: https://github.com/glmmTMB/glmmTMB/pull/781

**Comment by rvlenth** [comment]
OK. BTW, I am noticing that the `if (!requireNamespace("emmeans")) ...` part, while harmless, isn't really necessary because this method will always be called *from* the **emmeans** package.

Going ahead and closing...
