### ISSUE TITLE
Bayesian enhancements desired

### ISSUE THREAD

**Issue by rvlenth** [rvlenth/emmeans#33]
Note to self on future enhancement of Bayesian support:

1. Consider not requiring the `bhat` and `V` slots when there is a nontrivial `post.beta`. we no longer 
    need these when doing a summary. However, we need to work around having these absent in methods
    like `regrid()`. Could be a tough row to hoe.
**Skip this -- (See add'l comment below)**
2. Best posterior point estimate: currently the median. But this does create confusion in calling these estimates `emmean`, though. Re-label to `med.emmean`? Change the default to the mean?
3. Consider adding `type` argument to `as,mcmc`, so that `as.mcmc(emm, type = "response")` would 
    return the EMM sample already back-transformed.

**Comment by rvlenth** [comment]
4. Consider limiting the precision by which point estimates and HPD intervals are displayed (per comment on Stan forum -- http://discourse.mc-stan.org/t/standard-operating-procedures-for-anova/3964/19)

**Comment by rvlenth** [comment]
Re (1): The recent addition of code for non-estimability checking requires the `bhat` slot to contain `NA` values in the right places. That seems like a good approach, so I think we probably won't mess with this goal going forward.

**Comment by benwhalley** [comment]
Just to weigh-in on the point estimate issue noted above... it's definitely confusing to have median as the default, and to call it means. I just spent 10 minutes and ended up checking the source in trying to reconcile differences between summarising tidybayes::add_fitted_draws, vs using emmeans with an rstanarm fit.

Quoting Ben Goodrich  (https://stats.stackexchange.com/questions/298650/mean-median-or-mode-of-skewed-posterior) 
> The posterior distribution is special in the sense that the posterior mean minimizes expected loss when the loss function is squared error and the posterior median minimizes expected absolute error. The posterior mode is most analogous to a MLE but I don't consider that a virtue. 

Given the history of emmeans inheriting from LSMeans it probabaly needs quite a bit of signposting if you are going to return the median by default.

On a separate point: When predicting from binomial models, is it ever useful to not write `type="response"`? Perhaps that would also be a good default?

**Comment by rvlenth** [comment]
Would have been easier to read the help file than looking at the source...
```
? hpd.summary

hpd.summary(object, prob, by, type, point.est = median,
  bias.adjust = get_emm_option("back.bias.adj"), sigma, ...)
```
I will consider this anew.

On the separate point: yes, it can be useful. However, if you do not agree, you can always do
```r
emm_options(summary = list(type = "response"))
```
and henceforth, any summary will be on the response scale unless you specify otherwise.

**Comment by benwhalley** [comment]
Ah - thanks. Both very helpful. 

I wasn't aware of the hpd.summary until I saw the code though... the output of contrast contains the median and HPDI without needing to refer to it explicitly. I think more dififcult discoverability is sometimes the downside of being able to overload functions like this in R.

**Comment by rvlenth** [comment]
I have not changed the default, but I did add an annotation:
```r
> example(as.mcmc.emmGrid)
> ### (output omitted, but creates a reference grid 'cbpp.rg')

> emmeans(cbpp.rg, "period", type = "response")
 period   prob lower.HPD upper.HPD
 1      0.1930    0.1214     0.288
 2      0.0836    0.0398     0.137
 3      0.0748    0.0369     0.129
 4      0.0489    0.0138     0.101

Point estimate displayed: median 
Results are back-transformed from the logit scale 
HPD interval probability: 0.95 

> summary(emmeans(cbpp.rg, "period", type = "response"), point.est = mean)
 period   prob lower.HPD upper.HPD
 1      0.1960    0.1214     0.288
 2      0.0873    0.0398     0.137
 3      0.0782    0.0369     0.129
 4      0.0528    0.0138     0.101

Point estimate displayed: mean 
Results are back-transformed from the logit scale 
HPD interval probability: 0.95

> summary(cbpp.rg, point.est = function(x) mean(range(x)))
 size period prediction lower.HPD upper.HPD
   15 1           -1.44     -1.96    -0.894
   15 2           -2.43     -3.13    -1.823
   15 3           -2.61     -3.19    -1.862
   15 4           -3.21     -3.88    -1.998

Point estimate displayed: user-supplied function 
Results are given on the logit (not the response) scale. 
HPD interval probability: 0.95
```
and also another link on the help page:
```r
? summary.emmGrid
```
![image](https://user-images.githubusercontent.com/26777519/63181961-f7294000-c016-11e9-923a-5126bff8326e.png)

**Comment by benwhalley** [comment]
Sorry to hijack this thread, but I had one more related thought: Is it possible to extract the posterior samples from an emmeans or contrast result? 

This would be helpful in enabling users to plot or provide other summaries. For example,  `brms::hypothesis` accepts a dataframe so emmeans would be a quick way of extracting predictions for cells in design to then get an evidence ratio for directed hypotheses.

**Comment by rvlenth** [comment]
`as.mcmc(cbpp.rg)`

**Comment by rvlenth** [comment]
It's been three weeks plus, and I finally pushed the updated code to github (and forgot to reference this issue). The annotation that shows the point estimate is now there.
