### ISSUE TITLE
summary() on the output from emmeans() is stuck

### ISSUE THREAD

**Issue by gtbil** [rvlenth/emmeans#338]
Hi, I recently switched from lsmeans to emmeans and cannot figure out how to extract the least-squares means from the output of emmeans. It appears that `summary` is stuck running. I wait for >20 min and I get no output; just the flashing symbol in the console after I submit the summary command. A couple of times I've tried and R eventually crashes. I want to extract the estimates for the fixed effects corresponding to the `name` variable. My dataset has 2,687 observations.

```r
this.mod <- lmer(val ~ name + env + name:env + (1|rep:env) + (1|iblock:rep:env),
       data = this.dat)
> fixed-effect model matrix is rank deficient so dropping 14 columns / coefficients
this.lsm <- emmeans(this.mod, specs = "name",
                      pbkrtest.limit = 5000)
> NOTE: Results may be misleading due to involvement in interactions
this.lsm.df <- summary(this.lsm)
# cursor flashes like it is running but nothing happens
```

Trying to print `this.lsm` also just hangs.
```r
this.lsm
# cursor flashes like it is running but nothing happens
```
Thanks in advance, Grant

**Comment by gtbil** [comment]
I waited 90 minutes and it did eventually finish, FYI.

**Comment by rvlenth** [comment]
There really isn't any difference between `lsmeans` and `emmeans` - it's just how the results are labeled.

An `lmer` model can take a lot of computing time, especially with the default Kenward-Roger d.f. method is used. I see that you added the `pbkrtest.limit` option, so presumably you saw a warning message or read documentation that large datasets with a lot of random effects can slow things down.

What I wonder is how long it took it to generate `this.lsm` before you summarized it. I always thought that the bulk of the computation time was in setting up the adjusted covariance matrix, which is done in that step; and that summarizing `this.lsm` would not take so long, relative to how long it takes to create `this.lsm`. But your question suggests that isn't the case. How many levels does `name` have?

In any case, the problem you describe probably stems from excessive memory usage where things get paged in and out. In R, everything is kept in memory, so it might help if you don't have a lot of other stuff in your R global workspace, or any unneeded other packages loaded, when you do these computations.

**Comment by gtbil** [comment]
`name` has 263 levels, `this.lsm` took around a minute to create. Fitting the model in `lmer` took around 20 seconds. Looking at my task manager it looks like my memory utilization is low, around 30% of 48GB of RAM (including chrome and other programs I have open).

I did try using sattertheaite instead and saw a small improvement in run time for `summary` but it was still in the tens of minutes range.

I'll try running the same commands with only lmer and emmeans loaded, along with my data, and see if I get any improvement in run time. 

It seems like something is getting hung up when converting the output from `emmeans` into a data frame and/or a viewable form. `view(this.lsm)` was also an extremely slow operation - I gave up on waiting for that.

**Comment by rvlenth** [comment]
Well, in summarizing, it does do some significant computation, not just converting to a data frame. That is when the estimates and their d.f. are actually computed, so you have 263 calls to `pbkrtest::Lb_ddf()`. I surmise that that's where the snag lies. Keep in mind that the vcov and adjusted vcov matrices are each at least 264 x 264 and probably bigger, so that's 1.2MB or more of storage right there.

**Comment by rvlenth** [comment]
You can get an idea of what you're up against by looking at the code for `pbkrtest::Lb_ddf`. The arguments for your case can be found in `this.lsm@dfargs`. In particular, let `adjV <- this.lsm@dfargs$adjV)` and `P <- attr(adjV, "P")`. Let `k = nrow(P[[1]])` and `n = length(P)`. 

From the code, notice that to compute `Theta`, you need to compute a quadratic form that involves inverting a k x k matrix, and go through a loop with n iterations where some other quadratic forms of the same dimension are calculated (but with no matrix inversion), then some other calculations that look more modest. Anyway, if k (dimension of the fixed parameters) is large, that gets you into a lot of computation, and if n is large, that adds additional significant work.

**Comment by rvlenth** [comment]
Actually, it's simpler to get `k = length(this.lsm@bhat)`, and I think `n` is the number of parameters you see in `VarCorr(this.mod)`

**Comment by gtbil** [comment]
Hi, thanks for following up on this. I think the issue can be closed for now.

**Comment by rvlenth** [comment]
I'm closing this as I think it is resolved.
