### ISSUE TITLE
Discrepancy between joint_tests and geeasy::drop1

### ISSUE THREAD

**Issue by hugesingleton** [rvlenth/emmeans#343]
I checked the joint_tests against drop1 from [geeasy ](https://cran.r-project.org/web/packages/geeasy/index.html) and it agrees only partially. I decided to report it anyway. I don't say the joint_tests has any problem, reporting the discrepancy just in case, for "cross-verification".

The data:

```
d <- structure(list(ID = c(1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 
4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 
9, 9, 10, 10, 10, 10), TimeOrd = structure(c(1L, 2L, 3L, 4L, 
1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 
1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 
1L, 2L, 3L, 4L), .Label = c("M0", "M1", "M2", "M3"), class = c("ordered", 
"factor")), Result = c(1, 1.1, 1.5, 2, 1.1, 1.1, 1.4, 3, 1.1, 
1.2, 1.7, 5, 1.5, 3, 4.6, 6, 2.3, 4.4, 5.5, 8, 2, 2.2, 2.3, 7, 
4.5, 1, 3, 7, 3.3, 4.4, 5.5, 5, 3, 4, 5, 8, 1.1, 2.2, 3.3, 5), 
    SucN = c(0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 
    0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 
    1, 1, 1, 1, 0), Time = structure(c(1L, 2L, 3L, 4L, 1L, 2L, 
    3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 
    2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 1L, 2L, 3L, 4L, 
    1L, 2L, 3L, 4L), .Label = c("M0", "M1", "M2", "M3"), class = "factor")), row.names = c(NA, 
40L), class = "data.frame")
```

And the rest:
```
> m_geepack <- geeglm(SucN ~ Time * Result, family=binomial(link = "logit"), data=d, id=ID, corstr = "exchangeable", std.err="san.se")

> drop1(m_geepack,scope = SucN~Time*Result)
Single term deletions

Model:
SucN ~ Time * Result
            DF Wald Pr(>Chi)  
Time         3 6.49    0.090 .
Result       1 0.28    0.595  
Time:Result  3 7.22    0.065 .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

> joint_tests(m_geepack)
 model term  df1 df2 F.ratio p.value
 Time          3 Inf   3.123  0.0250
 Result        1 Inf   0.282  0.5950
 Time:Result   3 Inf   2.406  0.0650
```
It agrees for Result and Time:Result, but not for Time.

**Comment by hugesingleton** [comment]
As taking any answer from the maintainers takes time and it's not guaranteed to get any (yeah, we both know how it looks like...) - in the meantime, do you think this may be a bug in drop1? I will try to investigate the code of drop1 and join_tests, to see where the approach diverges (since the results agree in part and disagree in part), but maybe you have some idea where should I start?

This kind of analysis, allowing one to assess the main and interaction effects (either by comparing models via residual variance like ANOVA or deviance via LRT-sequence, or by jointly testing coefficients with Wald) is a fundamental feature for all regression models with more than 1 effect... If this fails, the entire analysis becomes useless. And for GEE your package is the only (except this drop1 function), which provides type-3 comparisons out of the box :)

**Comment by rvlenth** [comment]
Technically, type-3 tests are tests of certain functions of regression coefficients, and they are tricky when trying to do them via model comparisons. See the documentation for `car::Anova` and notice the cautionary notes. 

If you try a different parameterization, e.g.,
```r
options(contrasts = c("contr.sum", "contr.poly"))
```
and re-fit the model, I would not be a bit surprised if you get different results from `drop1` (but the same results from `joint_tests`).

**Comment by hugesingleton** [comment]
I obtained the above results with this parametrisation. I was surprised, that the 2 last elements are the same, only the first differs and I'm wondering why.

For the treatment contrast, the difference indeed exists (except the interaction - which is expected to be the same), and agreed with the sequential testing done via anova()

```
> options(contrasts = c("contr.treatment", "contr.poly"))
> m_geepack <- geeglm(SucN ~ Time * Result, family=binomial(link = "logit"), data=d, id=ID, corstr = "exchangeable", std.err="san.se")
> 
> drop1(m_geepack,scope = SucN~Time*Result)
Single term deletions

Model:
SucN ~ Time * Result
            DF Wald Pr(>Chi)  
Time         3 6.49    0.090 .
Result       1 3.20    0.074 .
Time:Result  3 7.22    0.065 .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> emmeans::joint_tests(m_geepack)
 model term  df1 df2 F.ratio p.value
 Time          3 Inf   3.123  0.0250
 Result        1 Inf   0.282  0.5950
 Time:Result   3 Inf   2.406  0.0650
```

So now they differ, but it agrees with the classic sequential test:

```
 anova(m_geepack)
Analysis of 'Wald statistic' Table
Model: binomial, link: logit
Response: SucN
Terms added sequentially (first to last)

            Df   X2 P(>|Chi|)   
Time         3 6.53    0.0886 . 
Result       1 7.24    0.0071 **
Time:Result  3 7.22    0.0653 . 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

Since GEE doesn't support LRT (non-likelihood), I thought the drop1 does the same that emmeans::joint_tests. I mean - test the coefficients jointly via Wald's approach, so I expected agreement between the methods.

**Comment by rvlenth** [comment]
The results of `joint_test())` are indeed tests of the regression coefficients, but for the main effects in a two-factor model with interaction, it isn't totally straightforward as you can't just give zero weight to the interaction coefficients. The following shows how it works with a fake data set having the same structure as your example. The model is fitted using `contr.treatment` contrasts.
```r
> fake = expand.grid(A = factor(1:4), B = factor(1:2), rep = 1:2)
> set.seed(123)
> fake$y = (1:16)^2 + rep(c(7,5), each = 8) + rnorm(16)
> fake.lm = lm(y ~ A*B, data = fake)

> joint_tests(fake.lm)
 model term df1 df2 F.ratio p.value
 A            3   8   0.203  0.8912
 B            1   8   1.923  0.2029
 A:B          3   8   0.010  0.9986
```
Now I'll dissect each of the main-effect terms. First for `A`, I'll construct and test the contrast for comparing consecutive levels. 
```r
> RG = ref_grid(fake.lm)
> 
> CONA = contrast(emmeans(RG, "A"), "consec")
NOTE: Results may be misleading due to involvement in interactions
> test(CONA, joint = TRUE)
 df1 df2 F.ratio p.value
   3   8   0.203  0.8912
```
Note that this is the same as the result from `joint_tests`. Here are the linear functions being tested:
```r
> CONA@linfct
     (Intercept) A2 A3 A4 B2 A2:B2 A3:B2 A4:B2
[1,]           0  1  0  0  0   0.5   0.0   0.0
[2,]           0 -1  1  0  0  -0.5   0.5   0.0
[3,]           0  0 -1  1  0   0.0  -0.5   0.5
```
Note that some of the interaction coefficients get weights of -0.5 or +0,5 in correspondence with the main-effect coefficients getting weights of -1 or +1.

On to `B`:
```r
> CONB = contrast(emmeans(RG, "B"), "consec")
NOTE: Results may be misleading due to involvement in interactions
> test(CONB, joint = TRUE)
 df1 df2 F.ratio p.value
   1   8   1.923  0.2029

> CONB@linfct
     (Intercept) A2 A3 A4 B2 A2:B2 A3:B2 A4:B2
[1,]           0  0  0  0  1  0.25  0.25  0.25
```
Again, the `test` result corresponds to `joint_tests`. The interaction terms each receive a weight of 0.25.

You get very similar results from **SAS** if you specify the `/ nE3` option to see the estimable functions; only their parameterization uses the last level as the reference level. These results are not surprising if you consider that marginal means are equally-weighted averages of predictions over the reference grid.

But it is not at all surprising to me that `drop1` would yield different tests, especially because the reduced models would not assign the same weights in the GLM computations as would be present in the full model.

**Comment by hugesingleton** [comment]
@rvlenth Thank you very much for all the clarification.

So, just the last question - does it mean, that for type 3 the R car::Anova(, type=3) is wrong in general, because **it assigns wrong weights in the analysed contrasts**? 

Well, either must be wrong, there cannot be, at the same time, two valid different ways of doing the same, and giving very different results. Sure, some discrepancies is expected to happen, but still it's rather consistent (even if we use different statistic F, Chi2 or Z or a bit different degrees of freedom).

In your opinion, should this be reported to the authors?

In the last 20 years, I believe, tens of thousands of researchers based their research/papers on the results of car::Anova or drop1, and sometimes the differences are really big (not something like 0.033 - 0.04, but rather 0.001, 0.3). If there is something, that can be improved, it definitely should be.

Or let me ask a different way. Do you, as the author of joint_tests, use car::Anova or drop1 for type 2 or 3 in your work, or do you find them (I mean the implementation) unreliable and stick only to joint_tests?

You mentioned, that the results agree with those in SAS. Does it mean, that the Anova or anova() or drop1 disagrees with SAS in basic (just lm) type-3 analyses, when you compare them? I ask, because I have no access to SAS, but I didn't notice much alerts in the internet in the past. I do understand, that different methods provide different results, but here we say about something very basic, and you claimed it's the way SAS does.

Please, don't get me wrong. As a researcher, I'm very afraid of using methods, that may put me in troubles in future. Whatever it is - base R or any external package.

OK, let's look at the simple lm(), to not be distracted by complicated extensions.

For all below examples the contrasts were set to sum.
```
> options("contrasts")
$contrasts
[1] "contr.sum"  "contr.poly"
```

**For Type 2 - indeed, no issue,** whatever approach I use:

```
> car::Anova(lm(mtcars$mpg ~ wt + disp, data=mtcars), type=2, test="F")
Anova Table (Type II tests)

Response: mtcars$mpg
          Sum Sq Df F value Pr(>F)   
wt          70.5  1    8.29 0.0074 **
disp        31.6  1    3.72 0.0636 . 
Residuals  246.7 29                  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

> joint_tests(lm(mtcars$mpg ~ wt + disp, data=mtcars))
 model term df1 df2 F.ratio p.value
 wt           1  29   8.290  0.0074
 disp         1  29   3.720  0.0636

> drop1(lm(mtcars$mpg ~ wt + disp, data=mtcars), test="F")
Single term deletions

Model:
mtcars$mpg ~ wt + disp
       Df Sum of Sq RSS  AIC F value Pr(>F)   
<none>              247 71.4                  
wt      1      70.5 317 77.4    8.29 0.0074 **
disp    1      31.6 278 73.2    3.72 0.0636 . 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

 
> anova(lm(mtcars$mpg ~ wt + disp, data=mtcars))
Analysis of Variance Table

Response: mtcars$mpg
          Df Sum Sq Mean Sq F value  Pr(>F)    
wt         1    848     848   99.66 6.9e-11 ***
disp       1     32      32    3.72   0.064 .    <---------- OK
Residuals 29    247       9                    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> anova(lm(mtcars$mpg ~ disp + wt, data=mtcars))
Analysis of Variance Table

Response: mtcars$mpg
          Df Sum Sq Mean Sq F value  Pr(>F)    
disp       1    809     809   95.09 1.2e-10 ***
wt         1     70      70    8.29  0.0074 **      <---------- OK
Residuals 29    247       9                    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

Now, the type 3 with interaction. Again the same approach (with respective changes)

```
> car::Anova(lm(mpg ~ wt * disp, data=mtcars), type=3)
Anova Table (Type III tests)

Response: mpg
            Sum Sq Df F value  Pr(>F)    
(Intercept)   1201  1   199.2 3.0e-14 ***
wt             147  1    24.5 3.2e-05 ***
disp           109  1    18.1 0.00021 ***
wt:disp         78  1    12.9 0.00123 ** 
Residuals      169 28                    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

> drop1(lm(mpg ~ wt * disp, data=mtcars), test="F", scope = ~wt * disp)
Single term deletions

Model:
mpg ~ wt * disp
        Df Sum of Sq RSS  AIC F value  Pr(>F)    
<none>               169 61.2                    
wt       1     147.4 316 79.3    24.5 3.2e-05 ***
disp     1     109.2 278 75.2    18.1 0.00021 ***
wt:disp  1      77.9 247 71.4    12.9 0.00123 ** 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

# Now - one by one
> anova(lm(mpg ~ wt * disp, data=mtcars), lm(mpg ~ wt + wt:disp, data=mtcars))
Analysis of Variance Table

Model 1: mpg ~ wt * disp
Model 2: mpg ~ wt + wt:disp
  Res.Df RSS Df Sum of Sq    F  Pr(>F)    
1     28 169                              
2     29 278 -1      -109 18.1 0.00021 ***    <----- OK
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

> anova(lm(mpg ~ wt * disp, data=mtcars), lm(mpg ~ disp + wt:disp, data=mtcars))
Analysis of Variance Table

Model 1: mpg ~ wt * disp
Model 2: mpg ~ disp + wt:disp
  Res.Df RSS Df Sum of Sq    F  Pr(>F)    
1     28 169                              
2     29 316 -1      -147 24.5 3.2e-05 ***     <----- OK
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

> anova(lm(mpg ~ wt * disp, data=mtcars), lm(mpg ~ disp + wt, data=mtcars))
Analysis of Variance Table

Model 1: mpg ~ wt * disp
Model 2: mpg ~ disp + wt
  Res.Df RSS Df Sum of Sq    F Pr(>F)   
1     28 169                            
2     29 247 -1     -77.9 12.9 0.0012 **     <----- OK
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

> joint_tests(lm(mpg ~ wt * disp, data=mtcars))
 model term df1 df2 F.ratio p.value
 wt           1  28  11.460  0.0021
 disp         1  28   4.130  0.0517    <----- Well, this difference is rather big
 wt:disp      1  28  12.930  0.0012
```

https://stats.oarc.ucla.edu/other/mult-pkg/faq/general/faqhow-are-the-likelihood-ratio-wald-and-lagrange-multiplier-score-tests-different-andor-similar/

**Comment by rvlenth** [comment]
Please look at the documentation for `joint_tests`. In part it says:

> In models with only factors, no covariates, we believe these tests correspond to “type III” tests a la SAS, as long as equal-weighted averaging is used and there are no estimability issues. When covariates are present and interact with factors, the results depend on how the covariate is handled in constructing the reference grid. See the example at the end of this documentation. 

The `lm` example you present has *no* factors in the model, just two numerical covariates. The tests for covariates depend pretty closely on what values you use in testing them. For example, given `LM` is your model with interaction,
```r
> emmeans::joint_tests(LM, at = list(wt = c(-1,1), disp = c(-1,1)))
 model term df1 df2 F.ratio p.value
 wt           1  28  24.461  <.0001
 disp         1  28  18.123  0.0002
 wt:disp      1  28  12.931  0.0012
```
These are *exactly the same* as the `car::Anova` results. So if you think it is reasonable to consider `wt` and `disp` values in intervals symmetric about zero, then you are welcome to those `Anova` results. The default (as documented) in `joint_tests` is to use the range of the covariate values. Another reasonable choice (maybe better) is to use their mean +/- their SD.

More broadly, what I would say is with `joint_tests`, you can find out what it is you are testing:
```r
> COND = contrast(emmeans(LM, "disp", cov.reduce = range), "consec")
NOTE: Results may be misleading due to involvement in interactions

> test(COND, joint = TRUE)
 df1 df2 F.ratio p.value
   1  28   4.129  0.0517

> COND@linfct
     (Intercept) wt  disp  wt:disp
[1,]           0  0 400.9 1390.522
```
The test you get from `Anova` gives weight 0 to the interaction term:
```r
> COND0 = COND
> COND0@linfct[1,4] = 0
> test(COND0, joint = TRUE)
 df1 df2 F.ratio p.value
   1  28  18.123  0.0002
```
But I claim that this doesn't make sense to set the coefficient for `wt:disp` to 0 in the context of a reasonable reference grid, none of which are anywhere near zero"
```r
> RG@linfct
  (Intercept)    wt  disp   wt:disp
1           1 1.513  71.1  107.5743
2           1 5.424  71.1  385.6464
3           1 1.513 472.0  714.1360
4           1 5.424 472.0 2560.1280

> emmeans(RG, "disp")@linfct
NOTE: Results may be misleading due to involvement in interactions
     (Intercept)     wt  disp   wt:disp
[1,]           1 3.4685  71.1  246.6103
[2,]           1 3.4685 472.0 1637.1320
```
The `linfct` for the `disp` means above are those for the two means being compared.

BTW, John Fox's notes in his documentation for `Anova` are completely consistent with what I am saying.

> In a model that contains factors, numeric covariates, and interactions, main-effect tests for factors will be for differences over the origin. In contrast (pun intended), type-II tests are invariant with respect to (full-rank) contrast coding. If you don't understand this issue, then you probably shouldn't use Anova for type-III tests.

Personally, I don't think type III tests make any sense at all in the context of model selection. Where they may make sense is in doing joint tests of estimable functions of the regression coefficients, in cases where you *know what is being estimated.*

**Comment by hugesingleton** [comment]
Ah! I felt it must be about the grid, but I missed the "at" option to construct the appropriate ranges in joint_tests! 

![obraz](https://user-images.githubusercontent.com/47183766/162551284-cb9653d6-fbf3-4ea9-9b3d-36bc3798188c.png)

Now it's all consistent. **Thank very much you for your patience and all explanations**! Sometimes, when I read the manuals, the words of explanation don't "resonate" in my mind and I am unable to understand the core, until someone goes through examples. Let me close this topic now. I think it may serve for reference, in future, for those, who are lost a bit with all those possibilities in R.

PS: no, I don't use this for model selection. It's just the assessment of the main and interaction effects over the underlying model. I have a simple rule: if the interactions are significant, not only statistically, but also visibly (because sometimes the test lacks of power, while it's clear the interaction occurs), I don't interpret the main effects - OK, maybe at the first glance - and instantly go to the analysis of the simple and marginal effects. When the interaction doesn't seem to occur, I use the type-2, as it's term order independent. Actually, I could leave only with type-1 anova(): it tests the most-nested interaction, then it can be used also to test the type-2 as well. Honestly, type-3 is not my "holly grail", I was only afraid about the numerical consistency - regardless of whether it's sensible or not.

I needed a few days to think about, supported by your technical explanations. I wish you were my teacher in the past. Thank you again.

**Comment by Generalized** [comment]
Dear @rvlenth ,
I'm making a comment here as I don't know how to message you in other way.
Since you refer to SAS in the documentation, you certainly know the internals of SAS perfectly.
But maybe you will find interesting the following links? I just found them and thought I could share them with you.
I am sorry, if you already know them or find it not interesting.
1) https://documentation.sas.com/doc/en/vdmmlcdc/8.1/casstat/viyastat_genselect_details49.htm
2) https://support.sas.com/documentation/onlinedoc/stat/131/introglmest.pdf
3) https://support.sas.com/documentation/onlinedoc/v82/techreport_r101.pdf

**Comment by rvlenth** [comment]
Thanks. I am quite familiar especially with (2), and use it for reference on how covariates are handled, for example; and also helpful for the `submodel` option. I had not seen (1) before. Report (3) has kind of a sentimental value. I think I actually used it in teaching not long after it came out. When I started my academic job at Iowa in 1975, we still had the original 1972 version of SAS, when they had `PROC REGR`, the predecessor of `PROC GLM`, and all the documentation had that kind of teletype look to it.

By the way, you can find out how to contact me directly by going to the [CRAN page for **emmeans**](https://cran.r-project.org/web/packages/emmeans/index.html) under "Maintainer".
