### ISSUE TITLE
[Question] One level vs. all other levels

### ISSUE THREAD

**Issue by jgaf151** [rvlenth/emmeans#346]
Hello,

I was wondering if there was a way of comparing one level of a categorical variable to all other levels, given the observed N of each group. This applies to variables with more than two levels. I have tried using "del.eff" but it does not produce the same output as if I create dummy variables for each level. What I gathered from "del.eff" is that it sums up the estimates and then produces an average, but this process does not consider each level's size (i.e., N).

I am trying to avoid creating dummy variables since I am running a huge for loop with many variables and subsets. So adding extra variables would be inefficient at this point. 

Here is a toy example:

```
currcrss <- "Dept" #Dept variable has 5 levels (i.e., "A", "B", "C", "D", "E")

svy <- svydesign(strata = ~STRAT, fpc = ~FPC, data = DAT, weights = ~WGT, ids=~1)

glm <- svyglm((SAT == "Very satisfied") ~  Dept)), design = svy, family = quasibinomial()) 

emeans <- summary(emmeans::emmeans(glm, specs = as.formula(paste0("del.eff~ ", currcrss)), 
                                               regrid="response", adjust = "none"))
```

This produces the following output (only showing the estimate column):
```
$emmeans  
--  --
Dept | prob
A | 0.1094
B | 0.0991
C | 0.0921
D | 0.0942
E | 0.048
   
$contrasts  
contrast | estimate
A effect | 0.02601
B effect | 0.0132
C effect | 0.00439
D effect | 0.00707
E effect | -0.05067
```

The way emmeans is grouping 1-level vs all others is taking the "probs" from $emmeans,  calculating an average and then comparing to X level. For example, for the A effect: 

`0.1094 - (0.0991 +  0.0921 + 0.094 + 0.048)/4; in other words A - (B + C + D + E)/4`

Now, if I create a dummy variable for "Dept" (i.e., where all As = 1, and all others = 0) and run the same process I get the comparison result I am interested in, but obviously for one single 1 vs. all comparison.

```
$emmeans  
--  --
Dept_A | prob
0 | 0.0935
1 | 0.1094
   
$contrasts  
contrast | estimate
0 effect | -0.0159
1 effect | 0.0159
```

I am trying to achieve this result for all potential groupings without having to create dummy variables and running five different models. Is this possible? Are there any parameters I can use within emmeans or within the glm() call to achieve this? I have been trying to find a solution by looking through vignettes and examples, but my coding skills are limited. I know there is a way to code custom contrast families for emmeans, but I would not know where to start. Any help and/or guidance will be deeply appreciated. 

Thank you!

**Comment by rvlenth** [comment]
I can't reproduce this toy example because I don't have a dataset named `DAT` (I also needed to figure out that you had loaded `library(survey)`). 

Perhaps we also need `STRAT`, `WGT`, and `FPC`??

**Comment by rvlenth** [comment]
Are you sure it isn't `"eff"` contrasts you want, rather than `"del.eff"`? Those are the contrasts you'd get from the dummy variables. The two differ only by a proportionality constant.

**Comment by rvlenth** [comment]
This may serve your needs:
```r
weff.emmc = function(levs, wts = rep(1, length(levs)), ...) {
    M = data.frame(row.names = levs)
    wts = wts / sum(wts)
    for (i in seq_along(levs)) {
        con = -wts
        con[i] = 1 + con[i]
        nm = paste(levs[i], "effect")
        M[[nm]] = con
    }
    attr(M, "desc") = "weighted differences from grand mean"
    attr(M, "adjust") = "fdr"
    M
}

wdel.eff.emmc = function(levs, wts = rep(1, length(levs)), ...) {
    M = weff.emmc(levs, wts, ...)
    for(i in seq_along(M))
        M[[i]] = M[[i]] / M[[i]][i]
    attr(M, "desc") = "weighted differences from mean of others"
    M
}
```
To use these, you probably want to specify weights other than the equal weights used by default.

Illustrations
```r
> weff.emmc(1:4) # default - same as emmeans:::eff.emmc(1:4)
  1 effect 2 effect 3 effect 4 effect
1     0.75    -0.25    -0.25    -0.25
2    -0.25     0.75    -0.25    -0.25
3    -0.25    -0.25     0.75    -0.25
4    -0.25    -0.25    -0.25     0.75

> weff.emmc(1:4, wt = 4:1)
  1 effect 2 effect 3 effect 4 effect
1      0.6     -0.4     -0.4     -0.4
2     -0.3      0.7     -0.3     -0.3
3     -0.2     -0.2      0.8     -0.2
4     -0.1     -0.1     -0.1      0.9

> wdel.eff.emmc(1:4) # default - same as emmeans:::del.eff.emmc(1:4)
    1 effect   2 effect   3 effect   4 effect
1  1.0000000 -0.3333333 -0.3333333 -0.3333333
2 -0.3333333  1.0000000 -0.3333333 -0.3333333
3 -0.3333333 -0.3333333  1.0000000 -0.3333333
4 -0.3333333 -0.3333333 -0.3333333  1.0000000

> wdel.eff.emmc(1:4, wt = 4:1)
    1 effect   2 effect 3 effect   4 effect
1  1.0000000 -0.5714286   -0.500 -0.4444444
2 -0.5000000  1.0000000   -0.375 -0.3333333
3 -0.3333333 -0.2857143    1.000 -0.2222222
4 -0.1666667 -0.1428571   -0.125  1.0000000

> ### data example ###
> with(mtcars, table(cyl))
cyl
 4  6  8 
11  7 14 

> foo = lm(mpg ~ factor(cyl), mtcars)
> EMM = emmeans(foo, "cyl")

> contrast(EMM, "eff")
 contrast    estimate    SE df t.ratio p.value
 cyl4 effect    6.161 0.817 29   7.544  <.0001
 cyl6 effect   -0.759 0.920 29  -0.825  0.4161
 cyl8 effect   -5.402 0.774 29  -6.976  <.0001

P value adjustment: fdr method for 3 tests 
> contrast(EMM, "weff", wt = c(11, 7, 14))
 contrast    estimate    SE df t.ratio p.value
 cyl4 effect    6.573 0.787 29   8.349  <.0001
 cyl6 effect   -0.348 1.077 29  -0.323  0.7490
 cyl8 effect   -4.991 0.646 29  -7.725  <.0001

P value adjustment: fdr method for 3 tests 
```

**Comment by jgaf151** [comment]
Thank you for the quick response, and sorry I didn't provide a reproducible example. I cannot share the data, but I managed to produce an example using a data set that comes with survey.

```
library(emmeans)
library(survey)
library(fastDummies)

data(hospital)

hospital$oblevel <- as.factor(hospital$oblevel)

hospital <- fastDummies::dummy_cols(hospital, select_columns = "oblevel", remove_selected_columns = F)

svy <- svydesign(data = hospital, weights = ~weightats, ids=~1)


glm <- svyglm(births ~ oblevel, svy)

emeans <- summary(emmeans::emmeans(glm, del.eff ~ oblevel, regrid="response", adjust = "none"))
emeans  
```          

```
$emmeans
 oblevel emmean    SE df lower.CL upper.CL
 1          356  59.9 12      225      486
 2         1183 317.4 12      492     1874
 3         3055 518.8 12     1925     4185

Confidence level used: 0.95 

$contrasts
 contrast estimate  SE df t.ratio p.value
 1 effect    -1764 310 12  -5.690  0.0001
 2 effect     -522 411 12  -1.271  0.2279
 3 effect     2286 543 12   4.207  0.0012   
```   
356 - (1183 + 3055)/2 # Averaged estimates - Level 1 vs 2 and 3 combined.

Note that this produces the contrast estimate by adding together estimates from the other groups (i.e., levels 2 and 3) from the emeans$emmeans section. But does not consider the size of these groups to calculate. 

```
# Using dummy variable to estimate level 1 vs all other.
glm2 <- svyglm(births ~ oblevel_1, svy)
emeans <- summary(emmeans::emmeans(glm2, del.eff ~ oblevel_1, regrid="response", adjust = "none"))
# In this example I could use "pairwise" instead of "del.eff" to get the same result 
# since the variable was collapsed(2-level)
emeans
```

```
$emmeans
 oblevel_1 emmean    SE df lower.CL upper.CL
         0   1457 317.3 13      772     2143
         1    356  59.9 13      226      485

Confidence level used: 0.95 

$contrasts
 contrast estimate  SE df t.ratio p.value
 0 effect     1102 323 13   3.412  0.0046
 1 effect    -1102 323 13  -3.412  0.0046

```

The absolute difference in means between level 1 and all others is 1,102. Given that oblevel_1 is about 26.6% of all cases, and the rest combined are 73.4%. 

```
svytotal(~oblevel, svy)
         total      SE
oblevel1    42 18.6145
oblevel2    99 37.4185
oblevel3    17  5.5646

svymean(~oblevel, svy)
            mean     SE
oblevel1 0.26582 0.1276
oblevel2 0.62658 0.1413
oblevel3 0.10759 0.0533
```

**Comment by rvlenth** [comment]
We commented at the same time. See if my suggestion works

**Comment by rvlenth** [comment]
This is what I get.
```r
> EMM = emmeans(glm, "oblevel")

> contrast(EMM, "del.eff")
 contrast        estimate  SE df t.ratio p.value
 oblevel1 effect    -1764 310 12  -5.690  0.0003
 oblevel2 effect     -522 411 12  -1.271  0.2279
 oblevel3 effect     2286 543 12   4.207  0.0018

P value adjustment: fdr method for 3 tests 

> ### Using the contrast function earlier...
> contrast(EMM, "wdel.eff", wt = c(42, 99, 17))
 contrast        estimate  SE df t.ratio p.value
 oblevel1 effect  -1101.8 288 12  -3.831  0.0042
 oblevel2 effect     49.7 353 12   0.141  0.8905
 oblevel3 effect   2118.5 565 12   3.750  0.0042

P value adjustment: fdr method for 3 tests 
```
How's that?

**Comment by jgaf151** [comment]
Yes, that looks about right! I haven't had a chance to test. But the results do track with the dummy variable models. Thank you so much!

**Comment by rvlenth** [comment]
I'm thinking of adding these functions to be standardly available. Need to decide how to handle `exclude` options...

Russ

**Comment by jgaf151** [comment]
Just tested on one of the subsets I am running and it worked. Had to change the adjust parameter to "none" for my use case. Thank you!

**Comment by rvlenth** [comment]
Just s note that in the update to the package on GitHub, I just made the wts argument an option in eff.emmc and del.eff.emmc, rather than adding the two new functions.

Sent from my iPhone

On Apr 15, 2022, at 1:02 PM, jgaf151 ***@***.******@***.***>> wrote:


Just tested on one of the subsets I am running and it worked. Had to change the adjust parameter to "none" for my use case. Thank you!

**Comment by dan11mcguire** [comment]
Hi @rvlenth , 

Is it possible to specify weights in a 'del.eff' type contrast in a model with interaction?

```
m <- lm(mpg ~ factor(cyl) + factor(gear) + factor(cyl):factor(gear),data=mtcars)
em <- emmeans::emmeans(m, "cyl", by = "gear")
deleff_contrast <- emmeans::contrast(em, "del.eff")

```
![image](https://user-images.githubusercontent.com/49620432/218593859-57effb2a-a4d6-4518-acf4-0558e1961c78.png)

also, what is the best way to ensure the proper ordering of weights?

**Comment by rvlenth** [comment]
The issue here is that you have a `by` variable in force:
```
> em
gear = 3:
 cyl emmean    SE df lower.CL upper.CL
   4   21.5 3.349 24     14.6     28.4
   6   19.8 2.368 24     14.9     24.6
   8   15.1 0.967 24     13.1     17.0

gear = 4:
 cyl emmean    SE df lower.CL upper.CL
   4   26.9 1.184 24     24.5     29.4
   6   19.8 1.674 24     16.3     23.2
   8 nonEst    NA NA       NA       NA

gear = 5:
 cyl emmean    SE df lower.CL upper.CL
   4   28.2 2.368 24     23.3     33.1
   6   19.7 3.349 24     12.8     26.6
   8   15.4 2.368 24     10.5     20.3

Confidence level used: 0.95 
```
Therefore, when you call `contrast`, it is expecting to contrast sets of 3 means. So a set of 3 `wts` works fine:
```
> contrast(em, "del.eff", wts = c(3,2,1))
gear = 3:
 contrast    estimate   SE df t.ratio p.value
 cyl4 effect    3.317 3.72 24   0.893  0.5715
 cyl6 effect   -0.138 3.46 24  -0.040  0.9686
 cyl8 effect   -5.750 2.42 24  -2.374  0.0779

gear = 4:
 contrast    estimate   SE df t.ratio p.value
 cyl4 effect   nonEst   NA NA      NA      NA
 cyl6 effect   nonEst   NA NA      NA      NA
 cyl8 effect   nonEst   NA NA      NA      NA

gear = 5:
 contrast    estimate   SE df t.ratio p.value
 cyl4 effect    9.933 3.35 24   2.966  0.0101
 cyl6 effect   -5.300 3.84 24  -1.382  0.1798
 cyl8 effect   -9.400 3.07 24  -3.063  0.0101

P value adjustment: fdr method for 3 tests 
```
Or if you don't want the `by` variable...
```
> contrast(em, "del.eff", wts = em@grid$.wgt., by = NULL)
 contrast          estimate   SE df t.ratio p.value
 cyl4 gear3 effect    1.455 3.40 24   0.428  1.0000
 cyl6 gear3 effect   -0.363 2.45 24  -0.149  1.0000
 cyl8 gear3 effect   -8.065 1.22 24  -6.596  <.0001
 cyl4 gear4 effect    9.113 1.37 24   6.666  <.0001
 cyl6 gear4 effect   -0.389 1.79 24  -0.217  1.0000
 cyl8 gear4 effect   nonEst   NA NA      NA      NA
 cyl4 gear5 effect    8.650 2.45 24   3.537  0.0050
 cyl6 gear5 effect   -0.403 3.40 24  -0.119  1.0000
 cyl8 gear5 effect   -5.003 2.45 24  -2.046  0.1167

P value adjustment: fdr method for 9 tests 
```
And of course, you could work with a subset:
```
> contrast(em[1:3], "del.eff", wts = em@grid$.wgt.[1:3], by = NULL)
 contrast          estimate   SE df t.ratio p.value
 cyl4 gear3 effect     5.78 3.47 24   1.667  0.1114
 cyl6 gear3 effect     4.20 2.54 24   1.653  0.1114
 cyl8 gear3 effect    -5.28 2.16 24  -2.444  0.0667

P value adjustment: fdr method for 3 tests 
```
The order of weights is always the order of the grid.

**Comment by dan11mcguire** [comment]
Thanks so much! The last version, subsetting em[1:3], I think is exactly what I want to accomplish.  For example, using the gear=3 specific weights, to compare 

cyl4 vs. avg other | gear=3
cyl6 vs. avg other | gear=3
cyl8 vs. avg other | gear=3
