### ISSUE TITLE
[Question] Emmeans throws error on mixed brms model

### ISSUE THREAD

**Issue by LucaLeisten** [rvlenth/emmeans#348]
Hi all,

I am running a mixed brms model with a three level factor. My model looks like this:

model_relationship_brms <- brm(relationship ~ poly(s_age,3) * scale + (1|class/ID) + (0+poly(s_age,3)|class), data = df_long, family=skew_normal("identity"), chains = 4, cores = 4, iter = 4000, warmup = 2000, control=list(adapt_delta=0.99))

Relationship is a skewed continuous variable, age is a standardised continuous variable of which I include the linear, quadratic and cubic term, and scale is a factor with three levels.

I am using sum-to-zero coding, scale3 is thus omitted. Now I am interested in the main effect of scale 3, the interaction of scale3 with age and the differences between scale3 and the other scales. 

When running emmeans (or emtrends) with the following code:

model_means <- emmeans(model_relationship_brms, specs = pairwise ~"scale", point.est = mean, level = .95)

I get this error:

Error in (function (..., degree = 1, coefs = NULL, raw = FALSE) : wrong number of columns in new data: c(-1.67233114181055, -0.660674031332563)

Can anyone help me figure out if this is my mistake or if it is simply impossible to get the mean comparisons for my model?

Thanks a lot for the help!

**Comment by LucaLeisten** [comment]
Edit: I've re-ran the model without the poly effect of age and don't get the error anymore, so apparently it has to do with the poly term.

**Comment by rvlenth** [comment]
I'm not sure, but I think this model involves calls to `scale()`, and my experience has been that `poly()` and `scale()` do not mix -- the meta information in `poly()` gets lost. Also, it is unnecessary to scale because `poly()` also scales and centers the variable(s). I think if you re-fit using `poly(age, 3)` instead of `poly(s_age, 3)` you will have better luck.
