### ISSUE TITLE
conway maxwell poisson regression objects

### ISSUE THREAD

**Issue by jbogomolovas2** [rvlenth/emmeans#349]
Hi!

I am just wondering are you planning to expand emmeans for cmp class of objects, aka make it work for CMP regression.
Or maybe you have dirty script to calculate post-hocs such models?

**Comment by rvlenth** [comment]
This is not a method I have ever used, and had not even heard of until now. And I do not know what R package can be used to fit these models.

I try to encourage package developers to create their own emmeans-support functions; so you may want to contact the package developer and point them to the [vignette on how to add such support](https://cran.r-project.org/web/packages/emmeans/vignettes/xtending.html).

In the meantime, perhaps the `qdrg()` function will work. See `? qdrg` with **emmeans** loaded. Please note that you usually need to supply at least `formula`, `data`, `coef`, and `vcov`, and make sure that all those are conformable.

**Comment by jbogomolovas2** [comment]
Thank you for great suggestions and link on how to connect emmeans and new regression models. Will give it a try.
I am using mpcmp to do COM-Poisson regression.
