### ISSUE TITLE
emmeans for gamm4

### ISSUE THREAD

**Issue by DominiqueMakowski** [rvlenth/emmeans#35]
Do you plan on adding support for gamm4 objects? 

Thanks a lot for your awesome package!

**Comment by rvlenth** [comment]
Not currently. There are so many packages, and more and more I need to suggest that people try to encourage package developers to add support for emmeans. There is documentation and a vignette on how to do it.

Russ

Sent from my iPhone

On May 11, 2018, at 2:43 PM, Dominique Makowski <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you plan on adding support for gamm4 objects?

Thanks a lot for your awesome package!

**Comment by DominiqueMakowski** [comment]
Okay, thanks!
