### ISSUE TITLE
Support for svyolr?

### ISSUE THREAD

**Issue by healthy-psycho** [rvlenth/emmeans#350]
Would it be possible to add support for the svyolr (survey ordinal logistic regression) model from the survey package? Does this require any heavy lifting computation wise, or does the data just need to be extracted and passed to the existing ordinal model infrastructure?

**Comment by rvlenth** [comment]
I had lost sight of this, but I have added this support to the package now.
```
> data(api)
> dclus1<-svydesign(id=~dnum, weights=~pw, data=apiclus1, fpc=~fpc)
> dclus1<-update(dclus1, mealcat=cut(meals,c(0,25,50,75,100)))
> m<-svyolr(mealcat~avg.ed+mobility+stype, design=dclus1)

> ref_grid(m)
'emmGrid' object with variables:
    avg.ed = 2.6215
    mobility = 17.72
    stype = E, H, M
```
I think I can close this issue now, but feel free to comment if anything comes up
