### ISSUE TITLE
set mode = "satterthwaite", but result was based on df.error? Object was gls.

### ISSUE THREAD

**Issue by tlin-corrona** [rvlenth/emmeans#353]
Hello,

My analysis was comparing the difference in outcome y between the control and treatment groups across 300+ time points using generalized least squared (gls). After obtaining the gls results, I used **emmeans()** to calculate the contrasts (control minus treatment) at each time point and the standard errors as well, adjusted for multiple comparison later on. 

I set **mode = "satterthwaite"** in **emmeans()**. However, when checking the emmean results (using **str(emmeans_result)** for example), it shows that  the degree-of-freedom method is df.error. I repeated the analysis, but with **mode = "df.error"**; the result was identical to that generated previously (i.e., based on **mode = "satterthwaite"**).

1. Could anyone shed some light on why this happened, i.e., getting the results based on **mode = "df.error"** although I set **mode = "satterthwaite"**? Is it because there is some internal check in the source code, determining which method to use? I went through part of the [source codes](https://github.com/rvlenth/emmeans/blob/master/R/helpers.R) but still did not have a clue.

2. If automatically switching from satterthwaite to df.error is not an error, then I am tempted to set **mode = "df.error"**, because there are multiple data sets and I'd like to ensure that each data is analyzed using the same methods to estimate degree of freedom, which would be **mode = "df.error"**. However,  the [vignettes](https://cran.r-project.org/web/packages/emmeans/vignettes/models.html) says **mode = "df.error"** would typically over-estimate degree of freedom; is there a way to roughly know how much **mode = "df.error"** would overestimate?  

The analysis was performed using R 3.6.1 on Linux Centos 6.8; the emmeans version was 1.7.2.Thanks so much.

**Comment by rvlenth** [comment]
I can't really answer this question without knowing more about your model. That said, the model-specific code for `gls` models can be found in `emmeans:::emm_basis.gls`. The pertinent line of code is likely to be this one:
```r
    if (!is.matrix(object$apVar))
        mode = "df.error"
```
-- which, in practical terms, says that if there are no variance estimates in place besides the residual error, we just use the residual error and its degrees of freedom. The Satterthwaite method is applicable only to models with a heterogeneous error structure, such as one fitted with a `weights = varIdent(...)` argument.

You can easily verify if I am right, simply by doing `<my.model>$apVar` where `<my.model>` is the name of your fitted model object. If you get `NULL`, that would set the mode to `df.error`, as it should.

**Comment by tlin-corrona** [comment]
Thanks so much for your prompt response, and the gls model (**my_gls**) has a heterogenous error structure using weights =varIdent(...). **my_gls$apVar** is not null, but the variance-covariance matrix is non-positive definite, which I think is the reason why **emmeans** switched to **mode = "df.error"** as described in the code you posted above. Thanks again.

**Comment by rvlenth** [comment]
Perhaps a simpler `varIdent` model would do the trick then. It is tempting to fit fancy models since it is so easy, but there is a price to pay for that, especially with small-to-medium data sets.

**Comment by rvlenth** [comment]
I think this issue is resolved, or at least explained, so am closing it
