### ISSUE TITLE
Issue with emmeans when lme() argument 'weights' is passed as a variable.

### ISSUE THREAD

**Issue by marcschwartz** [rvlenth/emmeans#356]
Hi,

I have spent a number of hours today trying to track down what appears to be an error with emmeans() when passing an lme() based model, where the 'weights' argument is passed as a variable, even when that variable is the default NULL value.

I Googled, used rseek.org and checked the Issues here, but am not seeing anything obvious that is helpful in providing a resolution.

I have managed to track down, at least at a higher level, that the issue is somewhere in ref_grid(), when:
```
do.call(ref_grid, args)
```
is called in emmeans(), but going down the rabbit hole in the code, cannot seem to isolate the problem, or where the difference is in the model object itself, that is causing the issue.

I am attaching a sample dataset and will define the model here that I am using, as an example.

[DF.MOD.csv](https://github.com/rvlenth/emmeans/files/8971168/DF.MOD.csv)

What I am trying to ultimately do is to create a wrapper function for both lme() and emmeans() that allows me to pass options for the model random effects formula, the correlation argument, and the weights argument, to deal with various issues, depending upon the data. Then pass the relevant arguments as variables as apropos, rather than coding separate models for each possible combination.

In this case, the essential model is:

```
library(nlme)
library(emmeans)
```

```
  MOD <- lme(Response ~ Group + Time + Group:Time + T1 + Group:T1,
             random = RandEff,
             data = DF.MOD, na.action = na.omit,
             correlation = Correlation,
             weights = Weights)
```

where the RandEff value, in this case, is: 
```
RandEff <- as.formula("~1 | ID")
```
Correlation is:
```
Correlation <- corAR1(form = ~as.numeric(Time) | ID)
```
and Weights is:
```
Weights <- NULL
```

I can replicate this issue outside of the function, in a new R session, with the sample data, the model as above, and get the error:

```
> emmeans(MOD, ~ Group + Time, adjust = "mvt")
Error in rep(1, attr(object, "conLin")$dims$N) : invalid 'times' argument
Error in (function (object, at, cov.reduce = mean, cov.keep = get_emm_option("cov.keep"),  : 
  Perhaps a 'data' or 'params' argument is needed
```

I have tried to specify the data argument but get the following shorter error:
```
> emmeans(MOD, ~ Group + Time, adjust = "mvt", data = DF.MOD)
Error in rep(1, attr(object, "conLin")$dims$N) : invalid 'times' argument
```

The curious thing, is that if I specify the 'weights' argument explicitly as a NULL:

```
  MOD <- lme(Response ~ Group + Time + Group:Time + T1 + Group:T1,
             random = RandEff,
             data = DF.MOD, na.action = na.omit,
             correlation = Correlation,
             weights = NULL)
```

emmeans() works:

```
> emmeans(MOD, ~ Group + Time, adjust = "mvt")
 Group   Time   emmean    SE df lower.CL upper.CL
 Group 1 Time 2   27.8 0.601 21     26.2     29.4
 Group 2 Time 2   27.1 0.578 21     25.5     28.6
 Group 1 Time 3   28.0 0.620 21     26.3     29.7
 Group 2 Time 3   26.3 0.594 21     24.7     27.8

Degrees-of-freedom method: containment 
Confidence level used: 0.95 
Conf-level adjustment: mvt method for 4 estimates 
```

So, there seems to be an issue when the 'weights' argument is passed as a variable, rather than explicitly.

Any guidance here would be appreciated, including that my eyes have glazed over and I am missing something simple.

If you need more information, let me know.

Thanks!

**Comment by rvlenth** [comment]
Well, I am not sure. The problem occurs in the function `recover_data.lme` which begins like this:
```
recover_data.lme = function(object, data, ...) {
    fcall = object$call
    if (!is.null(fcall$weights)) { ...
       ...
```
In your first model, `fcall$weights` comes out as a name, `Weights`, so it is deemed non-NULL and that leads to problems later. When you fit the other model and specify `weights = NULL`, it works out correctly.

So this is indeed a bug. I replaced `fcall$weights` with `eval(fcall$weights)` and now it runs. I just yesterday sent in an update, so it'll be awhile before this gets to CRAN. It will be in the next GitHub push though, which will be sooner.

Thanks for reporting this.

**Comment by marcschwartz** [comment]
Hi Russel,

Thanks for the resolution. I have installed the updated code from here using devtools and the fix does seem to work now.

Thanks again!

**Comment by marcschwartz** [comment]
Hi Russel,

Well, my perception of a fix was short lived.

Apparently, eval(), as you have it now implemented, works when the 'Weights' variable is in the global environment, but not when this process is contained within a function. So there is presumably an environment conflict.

If I take my example as above, and encapsulate it in a function:

```
DF.MOD <- read.csv("DF.MOD.csv", stringsAsFactors = TRUE)

library(nlme)
library(emmeans)

MyFun <- function() {

  RandEff <- as.formula("~1 | ID")
  Correlation <- corAR1(form = ~as.numeric(Time) | ID)
  Weights <- NULL

  MOD <- lme(Response ~ Group + Time + Group:Time + T1 + Group:T1,
               random = RandEff,
               data = DF.MOD, na.action = na.omit,
               correlation = Correlation,
               weights = Weights)

  print(MOD$call$weights)
  print(eval(MOD$call$weights))
	     
  emmeans(MOD, ~ Group + Time, adjust = "mvt")
}
```

we get the following output:

```
> MyFun()
Weights
NULL
Error in eval(fcall$weights) : object 'Weights' not found
Error in (function (object, at, cov.reduce = mean, cov.keep = get_emm_option("cov.keep"),  : 
  Perhaps a 'data' or 'params' argument is needed
```

In my real function, I have arguments that would be passed for the data frame, random effects, correlation and weights , but this is to keep it simple and still exhibit the behavior.

Another value for 'Weights', just to give you another example for possible testing, is: 
```
Weights <- varIdent(form = ~1 | Time)
```

and that also works with emmeans(), when in the global environment.

So the output of the eval(MOD$call$weights) is ok when this is done within the function body itself, but when the code in emmeans() is called, the 'Weights' object is not found in the parent.frame() environment, which is the default for eval().

It is not clear to me if there is a generic fix for this, relative to finding the relevant variable in an enclosing environment, that would not result in problems in other use cases for you.

One option that I came across might be the use of ?get0 (that is a zero), which has an 'inherits = TRUE' default, to search enclosing frames of the environment for the named object, but again, not sure if that is a generic enough fix, or might cause problems in some use cases. 

The basic use of get0() might be along the lines of:

```
fcall = object$call
if (!is.null(get0(fcall$weights))) { ...
       ...
...
```

instead of using eval() given the environment limitations, or a combination of the two, one being the primary and the other being a fallback if the first results in an error.

In the case where 'Weights' is NULL, I get:

```
Browse[2]> get0(MOD$call$weights)
NULL
```

and where it is varIdent(form = ~1 | Time), I get:

```
Browse[2]> get0(fcall$weights)
Variance function structure of class varIdent with no parameters, or uninitialized
```

I was thinking about another alternative short term approach, which might be to use substitute() or a similar approach, to replace the weights component in the MOD$call object, so that the variable name 'Weights' is replaced with the actual value, before I call emmeans(). 

Let me know your thoughts here.

Thanks!

**Comment by rvlenth** [comment]
Leaving on a vacation early tomorrow. It'll be awhile before I can look at this - sorry.

Sent from my iPad

On Jun 24, 2022, at 7:31 PM, Marc Schwartz ***@***.***> wrote:

﻿

Hi Russel,

Well, my perception of a fix was short lived.

Apparently, eval(), as you have it now implemented, works when the 'Weights' variable is in the global environment, but not when this process is contained within a function. So there is presumably an environment conflict.

If I take my example as above, and encapsulate it in a function:

DF.MOD <- read.csv("DF.MOD.csv", stringsAsFactors = TRUE)

library(nlme)
library(emmeans)

MyFun <- function() {

  RandEff <- as.formula("~1 | ID")
  Correlation <- corAR1(form = ~as.numeric(Time) | ID)
  Weights <- NULL

  MOD <- lme(Response ~ Group + Time + Group:Time + T1 + Group:T1,
               random = RandEff,
               data = DF.MOD, na.action = na.omit,
               correlation = Correlation,
               weights = Weights)

  print(MOD$call$weights)
  print(eval(MOD$call$weights))

  emmeans(MOD, ~ Group + Time, adjust = "mvt")
}


we get the following output:

> MyFun()
Weights
NULL
Error in eval(fcall$weights) : object 'Weights' not found
Error in (function (object, at, cov.reduce = mean, cov.keep = get_emm_option("cov.keep"),  :
  Perhaps a 'data' or 'params' argument is needed


In my real function, I have arguments that would be passed for the data frame, random effects, correlation and weights , but this is to keep it simple and still exhibit the behavior.

Another value for 'Weights', just to give you another example for possible testing, is:

Weights <- varIdent(form = ~1 | Time)


and that also works with emmeans(), when in the global environment.

So the output of the eval(MOD$call$weights) is ok when this is done within the function body itself, but when the code in emmeans() is called, the 'Weights' object is not found in the parent.frame() environment, which is the default for eval().

It is not clear to me if there is a generic fix for this, relative to finding the relevant variable in an enclosing environment, that would not result in problems in other use cases for you.

One option that I came across might be the use of ?get0 (that is a zero), which has an 'inherits = TRUE' default, to search enclosing frames of the environment for the named object, but again, not sure if that is a generic enough fix, or might cause problems in some use cases.

The basic use of get0() might be along the lines of:

fcall = object$call
if (!is.null(get0(fcall$weights))) { ...
       ...
...


instead of using eval() given the environment limitations, or a combination of the two, one being the primary and the other being a fallback if the first results in an error.

In the case where 'Weights' is NULL, I get:

Browse[2]> get0(MOD$call$weights)
NULL


and where it is varIdent(form = ~1 | Time), I get:

Browse[2]> get0(fcall$weights)
Variance function structure of class varIdent with no parameters, or uninitialized


I was thinking about another alternative short term approach, which might be to use substitute() or a similar approach, to replace the weights component in the MOD$call object, so that the variable name 'Weights' is replaced with the actual value, before I call emmeans().

Let me know your thoughts here.

Thanks!

**Comment by marcschwartz** [comment]
Hi Russel,

Have a great vacation.

Some additional comments here for your consideration when you get back:

I tried various combinations of using get0(), also wrapping the eval() code in try(), to see if I could come up with a conditional approach if the variable is not found. For example, initially using exists() as a high level check for the existence of object$call$weights.

There were some nuances here depending upon whether or not the value of 'weights' in the model object was explicitly a scalar value, such as NULL, or if it is an expression/language object, such as 'varIdent(form = ~1 | Time)', or if it is the name of a variable that holds a scalar or an expression/language object.

I was not completely successful in doing that, and it may be do to the rabbit hole of R environments.

As a result, at least as a near term solution, I modified my actual wrapper function, so that it explicitly deals with the two most common scenarios that I am likely to use, which is an AR(1) correlation, where:

```
lme(...,
    correlation = corAR1(form = ~as.numeric(Time) | ID),
    weights = NULL,
    ...)
```

and an unstructured correlation, where:

```
lme(...,
    correlation = corSymm(form = ~as.numeric(Time) | ID),
    weights = varIdent(form = ~1 | Time),
    ...)
```

In other words, rather than passing weights as a variable in the lme() call, I set up two lme() calls, one for each scenario and am passing the two different sets of correlation and weights arguments explicitly.

So, at this point, I have it working in some 'real-world' tests with actual project datasets.

If you might be concerned that there would be use cases where the change that you made as above might cause problems, feel free to revert that change as apropos.

I am not clear on whether there may be a generic approach here, when emmeans is used within a function body, as I am doing here, where it does not otherwise cause issues in other use cases. Clearly, it all works fine when emmeans() is used in the global environment. 

I know that emmeans() already has a 'weights' argument for other reasons, and perhaps there is some logic to be able to pass another argument, for example, mod.weights or similar, where one can explicitly pass the weights used in the model object in the setting where emmeans() is used within a function. The model weights argument, at least in this narrow case, seems to be the primary culprit, albeit perhaps others have differing experiences that are relevant here.

Thanks for your consideration.

**Comment by rvlenth** [comment]
Back from vacation. This does not look easy to fix, but at least it's back on my radar screen.

**Comment by wdkrnls** [comment]
I ran into this issue with nlme::nlme as well. On my end the solution was to refit the model with a `do.call(nlme, list(...))` expression where ... included all the arguments I needed to fit the model. Being an ordinary list, these arguments became ordinary values. That enabled my nlme analysis to work for me. Maybe something to that effect could be added to the documentation as a "fix"?

**Comment by rvlenth** [comment]
Thanks @wdkrnls -- this is a great idea, because it's an easy way to force everything to be evaluated in the right environment. R's scoping is one of its best features over the old S and S-Plus architectures -- but also a source of the toughest challenges, at least for me.

**Comment by marcschwartz** [comment]
Thanks @wdkrnls for the idea and to Russell for the follow up.

Adding an example of this use to the help file and/or perhaps a relevant FAQ is a really good idea.

As noted previously, I had implemented a workaround for the issue and that has been working well to date. I will take a look at the list based approach as well, which may help to simplify the code where this is an issue.

Thanks again!

**Comment by rvlenth** [comment]
Well, maybe I have it working!
```
> MyFun()
Weights
NULL
 Group   Time   emmean    SE df lower.CL upper.CL
 Group 1 Time 2   27.8 0.601 21     26.2     29.4
 Group 2 Time 2   27.1 0.578 21     25.5     28.6
 Group 1 Time 3   28.0 0.620 21     26.3     29.7
 Group 2 Time 3   26.3 0.594 21     24.7     27.8

Degrees-of-freedom method: containment 
Confidence level used: 0.95 
Conf-level adjustment: mvt method for 4 estimates 
```
I also tested this with a different version of `MyFun()` where the `weights` argument is omitted. (I don't want to break something that already works...)

This was accomplished by evaluating the `weights` argument in `environment(terms(object)`. I think this will succeed as long as the model (including its formula) is defined within the body of the function. If you pass the formula as an argument to the function, you may still have problems.

Dare I close this as completed, at last? Let's first see if you can still break it, after I push this up and let you install it from GitHub...

**Comment by marcschwartz** [comment]
Hi Russell,

I can confirm that the update appears to resolve this issue with some testing. I have not done an extensive set of tests, but at least staying with the basic approach of being able to pass the additional arguments within the body of a wrapper function seems to work now.

I appreciate your efforts in resolving this problem! Thank you!

**Comment by rvlenth** [comment]
I'm going to go ahead and close this issue. Feels so good to not have it hanging over me anymore!
