### ISSUE TITLE
new brms import adds many dependencies

### ISSUE THREAD

**Issue by jonathon-love** [rvlenth/emmeans#36]
hi russell,

i notice the most recent `emmeans` adds an import to `brms`. this adds *a lot* of additional dependencies. `emmeans` went from having 34 dependencies, to having 87!

is it possible for `brms` to be changed to a `suggests`?

i'm happy to explore this option if you like.

with thanks

jonathon

**Comment by rvlenth** [comment]
Ouch!

I was careless in doing that, and sorry for those implications. I think I can navigate what’s needed to change it to suggests. I’m less sure if CRAN will embrace an early update submission to fix it. Do you think this is an issue of sufficient urgency to warrant that, versus awaiting a month?

Russ

Sent from my iPhone

On May 12, 2018, at 1:36 AM, Jonathon Love <notifications@github.com<mailto:notifications@github.com>> wrote:


hi russell,

i notice the most recent emmeans adds an import to brms. this adds a lot of additional dependencies. emmeans went from having 34 dependencies, to having 87!

is it possible for brms to be changed to a suggests?

i'm happy to explore this option if you like.

with thanks

jonathon

**Comment by rvlenth** [comment]
Using `tools::package_dependencies("emmeans", recursive = TRUE)`, I got 104, so I guess it is growing by leaps and bounds.  And the same for `"brms"` yields 96, so clearly that's a big factor.

I'm traveling, so it will be kind of awkward to fix this -- but if necessary, possible, I think, with my cheapo laptop).

**Comment by jonathon-love** [comment]
thanks russell (this is definitely the best response i've gotten so far, when pointing out dependency creep :)

maybe you could leave it two weeks, rather than a month?

i think (and i'm not completely sure about this) the CRAN update process is completely automated these days, provided your package doesn't throw any errors or warnings. however, a warning which *will* get thrown, is if you resubmit within a week (i think, or maybe it's 10 days, not sure).

with thanks

**Comment by rvlenth** [comment]
Hooray -- **emmeans** 1.2.1 is now on CRAN.
```
> tools::package_dependencies("emmeans", recursive = TRUE)
$`emmeans`
 [1] "estimability" "ggplot2"      "graphics"     "methods"      "stats"       
 [6] "utils"        "nlme"         "coda"         "multcomp"     "plyr"        
[11] "mvtnorm"      "xtable"       "lattice"      "digest"       "grid"        
[16] "gtable"       "MASS"         "reshape2"     "scales"       "tibble"      
[21] "lazyeval"     "survival"     "TH.data"      "sandwich"     "codetools"   
[26] "Rcpp"         "grDevices"    "stringr"      "zoo"          "RColorBrewer"
[31] "dichromat"    "munsell"      "labeling"     "R6"           "viridisLite" 
[36] "Matrix"       "splines"      "cli"          "crayon"       "pillar"      
[41] "rlang"        "assertthat"   "colorspace"   "utf8"         "glue"        
[46] "magrittr"     "stringi"      "tools" 
```
We're down to 48 dependencies, anyway.

**Comment by jonathon-love** [comment]
great! thanks russell!

thanks for being so responsive on this.

with thanks

**Comment by rvlenth** [comment]
I think the latest commit has it down to 9 dependencies, if I count right:
```
> imp = c("estimability", "graphics", "methods", "stats", "utils",
+         "plyr", "mvtnorm", "xtable")
> dep = unlist(tools::package_dependencies(imp, recursive = TRUE))
> sort(unique(c(imp, dep)))
[1] "estimability" "graphics"     "methods"      "mvtnorm"      "plyr"         "Rcpp"        
[7] "stats"        "utils"        "xtable"
```

**Comment by jonathon-love** [comment]
hahaha! you're out of control!

**Comment by jonathon-love** [comment]
maybe we should sponsor you to clean up a few more packages out there :)
