### ISSUE TITLE
do.call(rbind, ListOfemmGridObjects) does not work with glmer() poisson model, when 'at' is used with different values

### ISSUE THREAD

**Issue by marcschwartz** [rvlenth/emmeans#360]
Hi Russell,

I have created a second wrapper function, in parallel to the first that I posted on recently, the difference being that the initial function was using lme() with a continuous response, and I am now using glmer() with a count response, so a poisson family. The essential model incantation is the same:
```
  MOD <- glmer(Response ~ Group + Time + Group:Time + T1 + Group:T1 + (1 | ID),
               data = DF.MOD, na.action = na.omit,
               family = poisson)
```
The underlying essential commonality is to be able to create both within and between group contrasts, where the within group contrasts include a comparison to the baseline value, which appears as a covariate in the model, and not as a response. That is, if there are 3 timepoints, T1, T2 and T3, only T2 and T3 appear as records in the model dataset, and T1 is a covariate.

To accomplish the within group comparisons to baseline, I use the general approach of:
```
contrast(EMM, "identity", offset = -BaselineMean, ...)
```
where EMM is the result of using emmeans() on the model object and I am subtracting the baseline mean as an offset.
```
   EMM <- emmeans(MOD, ~ Group + Time, adjust = "mvt",
                   regrid = "response", bias.adj = TRUE, sigma = SIGMA)
```
and where:
```
SIGMA <- as.data.frame(VarCorr(MOD))$sdcor
```
Note that I am using regrid = "response" here to get back to the response scale for subsequent operations, since I want to be able to perform contrasts on the counts and not on the rates.

I had created options to use either an overall baseline mean value (as above) to generate the various contrasts, or to use group specific means via the 'at' argument, the latter in the setting where using a hypothesis based upon a common mean does not make contextual sense. In that case, I loop over a data.frame that is the result of using:
```
DF.Mean.Groups.T1 <- aggregate(Response ~ Group, data = DF.T1, mean)
```
where DF.T1 contains just the T1 group and measurement values.

The loop is as follows:
```
    EMM.List <- lapply(seq(nrow(DF.Mean.Groups.T1)),
                       function(i) emmeans(MOD, ~ Group + Time,
                                           regrid = "response", bias.adj = TRUE, sigma = SIGMA,
                                           at = list(T1 = DF.Mean.Groups.T1$Response[i],
                                                     Group = DF.Mean.Groups.T1$Group[i])))
```
In the simple case, DF.Mean.Groups.T1 has two rows, one each for the two different group levels, each with its own baseline mean. So, EMM.List will have two elements. 

I then use:
```
EMM <- update(do.call(rbind, EMM.List), adjust = "mvt")
```
to combine the two sets of estimates into a single object, so that I can then use 'mvt' for holistic adjustments.

In the case of the lme() models, this all works just fine.

However, in the case of the glmer() poisson model, I get the following error isolated from the rbind() operation:
```
Browse[2]> do.call(rbind, EMM.List)
Error in rbind(deparse.level, ...) : 
  All objects must have the same fixed effects
```
I searched online and found an older report here with the same error message, however, the implication there was that different underlying models were being used, whereas I am using the same model.

In the course of trying to debug this a bit, if the two elements in EMM.List were derived using the same baseline values, for both group and T1, the rbind() operation worked just fine. 

So, there seems to be something different about the glmer() poisson model, as compared to the lme() model, when using the sub-group specific baseline means in the loop as above, and then trying to combine the results via rbind() for common adjustments.

It is not clear to me if this is a bug of sorts, or I am doing something that was not intended. I would appreciate any guidance, including whether there is intended to be a simper way of doing what I am attempting to do here, relative to being able to specify group specific means for the contrasts in a more unified approach.

Thanks!

**Comment by rvlenth** [comment]
It's not a bug; it is a limitation. There's only so much we can do. Here's a small example to illustrate
```
> library(emmeans)
> fiber.lm <- lm(strength ~ diameter + machine, data=fiber)
> 
> em1 = emmeans(fiber.lm, "machine")
> em2 = emmeans(fiber.lm, "machine", at = list(diameter = c(3,5), machine = c("A", "C")))
> em1 + em2
 machine emmean    SE df lower.CL upper.CL
 A         40.4 0.724 11     38.1     42.6
 B         41.4 0.744 11     39.1     43.7
 C         38.8 0.788 11     36.4     41.2
 A         21.2 2.521 11     13.3     29.0
 C         19.6 2.087 11     13.1     26.1

Results are averaged over some or all of the levels of: diameter 
Confidence level used: 0.95 
Conf-level adjustment: bonferroni method for 5 estimates 

> regrid(em1) + regrid(em2)
 Error in rbind(deparse.level, ...) : 
All objects must have the same fixed effects
```
So we can `cbind` the original objects, but not their regridded versions. Why? Because they are structured differently:
```
> em1@bhat
[1] 17.3595092  0.9539877  1.0368098 -1.5840491
> em2@bhat
[1] 17.3595092  0.9539877  1.0368098 -1.5840491
> em1@linfct
     (Intercept) diameter machineB machineC
[1,]           1 24.13333        0        0
[2,]           1 24.13333        1        0
[3,]           1 24.13333        0        1
> em2@linfct
     (Intercept) diameter machineB machineC
[1,]           1        4        0        0
[2,]           1        4        0        1
```
These have the *same* regression coefficients and different `linfct` slots. However,
```
> regrid(em1)@bhat
[1] 40.38241 41.41922 38.79836
> regrid(em2)@bhat
[1] 21.17546 19.59141
```
The "coefficients" are just the predicted values, and so of different lengths; and the `linfct`s are identity matrices (3x3 and 2x2 resp.). But even if they were the same length, we couldn't `cbind` them because they'd have different `bhat`s.

What you can do instead is include all the `at` values in one call, then subset the results using `[]`.

**Comment by marcschwartz** [comment]
Hi Russell,

Thanks for expediently replying on a Friday evening.

Ok, that all makes sense and I will work on that over the weekend and figure out a generic subsetting approach, since I cannot know a priori how many groups, or for that matter, how many time points >= 3, there may be.

I have one additional and related question.

In the course of Googling for possible solutions this evening since posting here, I came across an older post on SO:

https://stackoverflow.com/questions/54590281/marginal-means-and-confidence-levels-per-group-with-emmeans-and-geepack-in-r

The key is that in one of your replies, you recommended using a formula for the 'cov.reduce' argument, which I had not considered.  

Would that approach work here to do what I want, if I were to use something along the lines of:
```
EMM <- emmeans(MOD, ~ Group + Time, 
               **cov.reduce = T1 ~ Group,**
               adjust = "mvt",
               regrid = "response", bias.adj = TRUE, sigma = SIGMA)
```
Would that generate the contrasts using the group specific means as I would like, or am I missing something there? 

Thanks!

**Comment by rvlenth** [comment]
Yes, that is correct. An equivalent way to do this is to adjust the covariate before fitting the model:
```r
DF.MOD$adj.T1 <- resid(lm(T1 ~ Group, data = DF.MOD)
adjMOD <- glmer(Response ~ Group + Time + Group:Time + adj.T1 + Group:adj.T1 + (1 | ID),
               data = DF.MOD, na.action = na.omit,
               family = poisson)
```
Then *don't* use the `cov.reduce` spec.

This is probably preferable because subsequent steps don't require remembering to do the `cov.adjust`. This is also a fairly well-known method for dealing with mediating covariates.

**Comment by marcschwartz** [comment]
Hi Russell,

Thanks for your reply above.

I have this all working now, without the need for subsetting, which greatly simplifies the handling of the results.

However, there is one issue still pending.

When I want to get the change from T1 for each of the groups at T2 and T3, in the default incantation with a common T1 mean, I use the general approach of subtracting the T1 mean as the offset that I had in my initial post above, and that works fine.

However, in this case where I am using group specific T1 means, and where I now want to use those as group specific offsets, I use:
```
    EMM.C <- contrast(EMM,
                      by = "Group", 
                      method = "identity", offset = -DF.Mean.Groups.T1$Response)
```
which, given the documentation for contrast(), suggests that the vector of values in DF.Mean.Groups.T1$Response would be separately used in each "by" group. So, if there are two groups, as in the simple example, DF.Mean.Groups.T1$Response would be a vector of length 2, and each value would be used per by group for the contrasts.

However, that does not appear to be occurring as I might have anticipated. If there are two groups and two time points, only the first time point for the first group and the second time point for the second group, seem to yield the correct estimates:
```
rbind(EMM.C)
 Group     contrast    estimate    SE  df z.ratio p.value
 1         T2            -11.86 0.599 Inf -19.801  <.0001
 1         T3            -22.04 0.465 Inf -47.420  <.0001
 2         T2             -4.86 2.082 Inf  -2.335  0.0782
 2         T3            -19.17 1.053 Inf -18.217  <.0001
```
On the other hand, if I pass each group's value separately, first with DF.Mean.Groups.T1$Response[1]:
```
rbind(EMM.C)
 Group     contrast    estimate    SE  df z.ratio p.value
 1         T2            -11.86 0.599 Inf -19.801  <.0001
 1         T3            -12.45 0.465 Inf -26.782  <.0001
 2         T2             -4.86 2.082 Inf  -2.335  0.0782
 2         T3             -9.58 1.053 Inf  -9.103  <.0001
```
and then with DF.Mean.Groups.T1$Response[2]:
```
rbind(EMM.C)
 Group     contrast    estimate    SE  df z.ratio p.value
 1         T2             -21.5 0.599 Inf -35.811  <.0001
 1         T3             -22.0 0.465 Inf -47.420  <.0001
 2         T2             -14.5 2.082 Inf  -6.942  <.0001
 2         T3             -19.2 1.053 Inf -18.217  <.0001
```
I seem to get the correct estimates for each group separately. 

Am I missing something in how the offset values are recycled for each by group?

Thanks!

**Comment by marcschwartz** [comment]
Hi Russell,

I think that I may have answered my own question on this last issue.

the EMM object is created using:
```
    EMM <- emmeans(MOD, ~ Group + Time, adjust = "mvt",
                   regrid = "response",
                   bias.adj = TRUE, sigma = SIGMA)
```
If I generate the contrasts using:
```
    EMM.C <- contrast(EMM,
                      method = "identity", offset = -DF.Mean.Groups.T1$Response,
                      adjust = "mvt")
```
that is, using the vector of T1 means, and without the 'by = "Group"' argument, the vector of offset values appears to be correctly recycled, and the resulting estimates appear to be correct:
```
EMM.C
 contrast              estimate    SE  df z.ratio p.value
 Group 1 T2               -11.9 0.599 Inf -19.801  <.0001
 Group 2 T2               -14.5 2.082 Inf  -6.942  <.0001
 Group 1 T3               -12.5 0.465 Inf -26.782  <.0001
 Group 2 T3               -19.2 1.053 Inf -18.217  <.0001
```

Now that I read the Note in ?contrast, I believe that this is what is referred to when the formula is used in creating the EMM object initially. That is, even though a 'by' argument was not specified in the emmeans() call, the formula in essence, becomes the inferred 'by' values, in this case, Groups as the top level, and Time as the second level, or 4 (2x2) combinations in this case.

From the Note:

"When object has a nesting structure (this can be seen via str(object)), then any grouping factors involved are forced into service as by variables, and the contrasts are thus computed separately in each nest. This in turn may lead to an irregular grid in the returned emmGrid object, which may not be valid for subsequent emmeans calls."

This seems to be reinforced if I call contrast() using:
```
    EMM.C <- contrast(EMM,
                      method = "identity", offset = -rep(DF.Mean.Groups.T1$Response, 2),
                      adjust = "mvt",
                      parens = FALSE, enhance.levels = FALSE)
```
where the vector of T1 means is now of length 4, rather than 2, such that they are sequenced to match the output structure of EMM.C.

I missed the Note entry in my prior read of the help file and took the notion of 'by' groupings explicitly in terms of how emmeans() was called. 

I might suggest that text be added to the definition of the 'by' argument in ?contrast and point the reader to the Note explicitly, which may be helpful in avoiding the confusion that I experienced on this.

Thanks Russell! I appreciate all of your help on this!

**Comment by rvlenth** [comment]
The *same offsets* are used in each `by` group -- just as the same contrasts are used. That is, I view the offset as an additive constant term for the linear functions being estimated. So if you want different constants for each group, definitely do *not* use group as a `by` variable.

**Comment by marcschwartz** [comment]
Hi Russell,

Yah, the key point that I missed is that the RHS of the formula in emmeans() essentially becomes the possibly nested "by" values, and that by using "by" in contrasts, I was apparently creating an interaction between emmeans() and contrast(), which, in hindsight, compromised the subsequent sequencing of the offsets that I passed to contrast().

Having read the Note in ?contrast, the proverbial light bulb went on... :-) 

Again, thanks for all of your help with this. I will close this issue as resolved.

Thanks!
