### ISSUE TITLE
Is it possible the estimates are not back transforming correctly?

### ISSUE THREAD

**Issue by marireeves** [rvlenth/emmeans#371]
Hi There - I also thank you for writing this package. 

I'm trying to re-run code I wrote about a year ago, to reproduce some figures for a paper, but I am getting totally different estimates. I'm wondering whether it's not back transforming the estimates correctly from the log scale? The code and data are [here](https://github.com/marireeves/RatTrapPaper). 

I ran linear models (glms) on log transformed data, as in:

glm_logdeadthingsptn_season<-glm(log(deadthingsptn+0.00001)~season, data = randomtrain)

and the estimates I am now getting out of emmeans are several orders of magnitude lower than those I was getting before...to me, it looks like they are not back transforming correctly, though I haven't checked the math. It could be an error in  my code, but it was running before and giving me much higher estimates, which are more in line with the raw data. 

Anyway, thoughts are appreciated.

In the meantime, is it possible to download the previous version of this package, just so I can get the figures to the publisher?

**Comment by marireeves** [comment]
Great, I did wrap it in a data.frame argument. Can you get to the code in that github link I sent?
https://github.com/marireeves/RatTrapPaper

**Comment by marireeves** [comment]
Thanks for the speedy reply

**Comment by rvlenth** [comment]
No, I don't see code, only data. And it'd also help to see the old results you were expecting. Finally, try taking out the as.data.frame and read what it says below the results. It should say something like"estimates are back-transformed from the log scale" or "estimates are "on" the log scale - that is, you can actually read it and tell what was done and what wasn't done.

Sent from my iPad

On Aug 16, 2022, at 8:14 PM, Mari K Reeves ***@***.***> wrote:

﻿

Great, I did wrap it in a data.frame argument. Can you get to the code in that github link I sent?
https://github.com/marireeves/RatTrapPaper

**Comment by marireeves** [comment]
ok, let me look at that. There may be an error in my code there because it is working as expected on a different code for the same project. Strange. I will look for those annotations

**Comment by marireeves** [comment]
if you want to look, the rmd is here

https://github.com/marireeves/RatTrapPaper/blob/main/22_08_16_HPK_FinalFigures.Rmd

**Comment by rvlenth** [comment]
Glancing through, I see several instances of emmip(), but none with the additional argument type = "response" that would instruct it to back-transform.

Sent from my iPad

On Aug 16, 2022, at 8:31 PM, Mari K Reeves ***@***.***> wrote:

﻿

if you want to look, the rmd is here

https://github.com/marireeves/RatTrapPaper/blob/main/22_08_16_HPK_FinalFigures.Rmd

**Comment by marireeves** [comment]
I see it in both, but I added a smaller number to the first code, but not the second, and the output says zero, is it possible it's a rounding error?

> library(emmeans)
> heightmeans<-emmeans(glm_logdeadthingsptn, "height", type = "response")
> summary(heightmeans, infer = TRUE)
 height response       SE  df lower.CL upper.CL null t.ratio p.value
 High   0.000399 8.92e-05 463 0.000256 0.000618    1 -35.771  <.0001
 Low    0.000692 1.56e-04 463 0.000444 0.001077    1 -32.655  <.0001

Results are averaged over the levels of: habitat, season 
Confidence level used: 0.95 
Intervals are back-transformed from the log(mu + 0) scale 
Tests are performed on the log(mu + 0) scale 
> pairs(heightmeans)
 contrast   ratio    SE  df null t.ratio p.value
 High / Low 0.582 0.175 463    1  -1.801  0.0724

Results are averaged over the levels of: habitat, season 
Tests are performed on the log scale

And I am seeing it in the code that is? Weird. 

> baitagemeansnoout<-emmeans(logdeadthingsptnfull,  "bait.age" , type = "response")
> summary(baitagemeansnoout, infer = TRUE)
 bait.age response       SE  df lower.CL upper.CL  null t.ratio p.value
 new       0.00174 0.000272 327  0.00126  0.00234 0.999 -59.508  <.0001
 old       0.00229 0.000477 327  0.00147  0.00337 0.999 -39.434  <.0001

Results are averaged over the levels of: landscape, blocker, lure, month 
Confidence level used: 0.95 
Intervals are back-transformed from the log(mu + 0.001) scale 
Tests are performed on the log(mu + 0.001) scale 
> pairs(baitagemeansnoout)

**Comment by marireeves** [comment]
the code that is not working added a smaller number to the raw data prior to log transform. 

glm_logdeadthingsptn_habitat<-glm(log(deadthingsptn+0.00001)~habitat , data = randomtrain)

**Comment by rvlenth** [comment]
It’s rounding, but it’s not an error. If we specify type = “response”, it correctly back-transforms:

```
> w1.lm = glm(log(breaks+.00001) ~ wool*tension, data = warpbreaks)
> emmeans(w1.lm, "wool", type = "response")
NOTE: Results may be misleading due to involvement in interactions
wool response   SE df lower.CL upper.CL
A        27.6 1.99 48     23.9     31.9
B        23.7 1.71 48     20.5     27.4

Results are averaged over the levels of: tension 
Confidence level used: 0.95 
Intervals are back-transformed from the log(mu + 0) scale 
```

```
> emmeans(w1.lm, "wool", type = "link")
NOTE: Results may be misleading due to involvement in interactions
wool emmean    SE df lower.CL upper.CL
A      3.32 0.072 48     3.17     3.46
B      3.17 0.072 48     3.02     3.31

Results are averaged over the levels of: tension 
Results are given on the log(mu + 0) (not the response) scale. 
Confidence level used: 0.95
```

Meanwhile, your .Rmd file has several instances of things like
```
    emmip(w1.lm, wool ~ tension)
```
when it should be
```
    emmip(w1.lm, wool ~ tension, type = "response")
```

**Comment by marireeves** [comment]
I'll try that change. thanks!

**Comment by marireeves** [comment]
It worked. thanks

**Comment by rvlenth** [comment]
I think this issue is resolved, so am closing it.
