### ISSUE TITLE
Marginal Means with Nested Structure

### ISSUE THREAD

**Issue by davidreilly007** [rvlenth/emmeans#372]
When estimating marginal means for fixed factors, the design is treated as if it was balanced, but in the case of nested fixed, averaging is performed separately for each nested group.  Why not keep it consistent and treat the nested terms as if they were balanced?

**Comment by rvlenth** [comment]
I think I am being consistent. If you have group 1 with 2 treatments and group 2 with 5 treatments, that's 5 treatments total and I give them equal weight by default.

If in addition, you have a factor "dose" that appears with all 5 treatments, and we want the EMMs for dose, you have two choices
```
EMM1 <- emmeans(model, "dose")   # gives equal weight to the 5 treatments

GRPEMM <- emmeans(model, ~ group * dose)   # averages each nest, so nesting structure is gone
EMM2 <- emmeans(GRPEMM, "dose")   # gives equal weight to the  2 groups
```

**Comment by davidreilly007** [comment]
Ok that makes sense. Thank you very much.
