### ISSUE TITLE
Change default for `point.est` in `hpd.summary()`?

### ISSUE THREAD

**Issue by rvlenth** [rvlenth/emmeans#375]
In **emmeans**, when we have a Bayesian model, it is summarized using `hpd.summary()`. That function has a `point.est` argument that has defaulted to `median` in version 1.8.0 and earlier. 

But my sense is that most users would really prefer that the default be `mean`. Plus it can be confusing having a column labeled `emmean` which displays the median of the posterior means.

So I am reaching out to users I know of who may have an opinion. (Plus others who happen to see this.) How disruptive would it be if I change the default point estimate to the mean? Note: this could also affect plots produced by `emmip()` and `plot.emmGrid()`. 

Thanks in advance.

Addressees:
@qdread @dallak @bpleahy @OmidGhasemi21 @singmann @mattansb @abadgerw @nahorp @DominiqueMakowski @lucasdeschamps @LucaLeisten @meflynn @a-hurst @jmgirard @StaffanBetner @paul-buerkner @dshelldhillon @nlpaces

**Comment by lucasdeschamps** [comment]
Hi!

Personnaly, I tend to use the median of the posterior distribution when I work with the bayesian approach.

However, the mean seems to be the default in `brms`. (Has it always been the case?).

Would you plan to add a similar "robust = T or F" argument?

Thank you for asking!

Have a good day!

**Comment by qdread** [comment]
Yes, I agree with Lucas that I tend to use the median. But it does make sense for consistency with `brms` to have the defaults be the same. Would it be possible to provide a warning or message text, at least in the next few versions, to the effect that the point estimate is now mean by default and can be changed by using the `point.est` argument?

**Comment by rvlenth** [comment]
@lucasdeschamps Thanks! Can you tell me more specifically what would be different in the summary with `robust = TRUE` versus `robust = FALSE`? It seems to me that much of what is regarded as robustness considerations go into the choice of model, and specific aspects of that model; but if we have an *existing* model and we want *post hoc* results from it, what options in that follow-up analysis would be more robust than others?

**Comment by mattansb** [comment]
In [`{bayestestR}` we default to the median](https://easystats.github.io/bayestestR/reference/describe_posterior.html), as does `{rstanarm}`, which I feel is more common. (However `{posterior}` defaults to the mean.)

If you switch to using the mean, this would potentially cause some unit tests in `bayestestR` to fail (where we compare our outputs to yours), but we can fix that in time if needed.

I think what @qdread and @lucasdeschamps mean by "robust" is a robust point estimate of the posterior, as the median is more statistically robust (more stable) than the mean.

**Comment by qdread** [comment]
Yes the `robust` argument is in the `summary` method for a `brmsfit` object. See documentation: https://rdrr.io/cran/brms/man/summary.brmsfit.html

I agree with Russ that the argument name `robust` is a little confusing. As Russ said, robustness depends on a lot of other things besides whether median or mean is chosen as measure of central tendency. So I think `point.est = "median"` is preferable.

**Comment by mattansb** [comment]
The labelling of the column seems like a minor issue to me - the label in emmGrid objects indicates what we are estimating, not how we are estimating. 

But even that might be an issue, such as in the following examples:

```R

mod <- brms::brm(
  bf(mpg ~ hp,
     sigma ~ factor(cyl)),
  data = mtcars,
  backend = "cmdstanr",
  cores = 4
)

emmeans::emmeans(mod, ~ cyl, dpar = "sigma")
#>  cyl emmean lower.HPD upper.HPD
#>    4  1.858      1.38      2.42
#>    6  0.596      0.01      1.27
#>    8  1.140      0.76      1.60
#> 
#> Point estimate displayed: median 
#> Results are given on the log (not the response) scale. 
#> HPD interval probability: 0.95
```

The estimate is not a marginal _mean_, it is a marginal... standard deviation... on the log scale (?).

Perhaps a compromise would be to have that label be `"estimate"` for Bayesian models?

**Comment by rvlenth** [comment]
Just to clarify a couple of things on labeling.

First, having the possibility of modeling some parameter other than the mean is definitely *not* unique to Bayesian models. There are plenty of frequentist scenarios for this as well. So whether or not it is a Bayesian model would not be a reasonable criterion for deciding how estimates are labeled.

Second, it may not be well-known, but there is a simple way to modify the column heading. With @mattansb 's latest example:
```r
> emmeans::emmeans(mod, ~ cyl, dpar = "sigma", estName = "emsigma")
 cyl emsigma lower.HPD upper.HPD
   4   1.859    1.3761      2.43
   6   0.607    0.0369      1.29
   8   1.147    0.7326      1.60

Point estimate displayed: median 
Results are given on the log (not the response) scale. 
HPD interval probability: 0.95 
```

Third, in a sense, there is already a warning (or at least an indication) that the median is being used, in that there is an annotation to that effect (see the preceding output). Perhaps it could be expanded a bit, e.g. `Point estimate displayed: median of the posterior sample of estimates` -- would that help, or just be awkward?

On the second point, it *would* be possible to allow the *model-specific* supporting code to pass an `estName`; so in Mattan's example, `emm_basis.brmsfit` could so something like set `misc@parName <- dpar` or some such. Currently that would not work, but I could make it work. That'd probably be a good thing to allow for if the coding doesn't get too dicey. (The complication is we need to carry that beyond `ref_grid` and into `emmeans()` and perhaps beyond, but remember to "forget" it when we don contrasts and trends.) I'll think about it.

**Comment by nahorp** [comment]
Personally, I prefer the `median` over the `mean` too but can appreciate the argument to keep it consistent with `brms`. A warning text for a few versions would be good and I like the `point.est` argument to the function.

**Comment by rvlenth** [comment]
I have received comments from several people.

It appears that I was wrong in sensing people wanted the mean by default. That, or the the ones who do have not weighed-in. 
So, lacking the firestorm of support I was expecting for changing the default, I will leave the default at the median.

I think I've allowed time for comment on this, so will close the issue. Thanks to everyone who weighed-in.
