### ISSUE TITLE
emtrends for individual subjects

### ISSUE THREAD

**Issue by toouggy** [rvlenth/emmeans#39]
Hi,

I have been using emtrends to estimate slopes in a mixed effects model and it works nicely to get the trend for the different groupings.  Is there a way to use emtrends to get not the group trend, but the individual subject trends?

Thank you.

Paco

**Comment by rvlenth** [comment]
Generally, no. `emtrends` (and `emmeans`) work only with the fixed-effects part of a model. 

You could fit a model with subjects as a fixed factor and use `emtrends` with that model to explore, and perhaps graph, the subjects' trends, and that could in some ways supplement the main analysis of the model with subjects as a random factor.

**Comment by toouggy** [comment]
Thank you for the quick response.  Is there a way to get the estimated trends for individual subjects from the model itself?

**Comment by rvlenth** [comment]
I thought I already answered that -- no, unless perhaps some other package does it. But not in **emmeans**

**Comment by rvlenth** [comment]
Closing this as I believe it is now inactive.
