### ISSUE TITLE
Incorrect citation in basics vignette

### ISSUE THREAD

**Issue by dipetkov** [rvlenth/emmeans#391]
The basic emmeans vignette, [Basics of estimated marginal means](https://cran.r-project.org/web/packages/emmeans/vignettes/basics.html), cites the American Statistical Association (ASA) statement about p-values. It mis-spells the name of the first author as "Wasserman RL". It's "Wasserstein RL".
https://doi.org/10.1080/00031305.2016.1154108

**Comment by rvlenth** [comment]
How embarrassing! I actually cite two articles by this author, and got them both wrong. I have corrected this in my source files, and the corrections will be in the next update. Thank you for bringing this long-standing error to my attention.

I'll go ahead and close this issue, but that does not prevent further comment.
