### ISSUE TITLE
`emtrends` for `rma` and `rma.mv` objects (`metafor`)

### ISSUE THREAD

**Issue by zacrobinson5** [rvlenth/emmeans#396]
Similar to a previously posted issue about `emmeans` - would it be possible to have `emtrends` work for `rma` and `rma.mv` objects from the `metafor` package?

Sincerely appreciated!

**Comment by rvlenth** [comment]
My suggestion is to use `qdrg()` as described in #269, but specify two different values for the covariate for which you want the trend. Something like
```
mx <- mean(data$x)
rg <- qdrg(..., at = list(x = mx + c(-.5, .5)))
emt <- update(contrast(rg, "consec", simple = "x"), by = NULL)
confint(emt)
```
Now, `trnd` will comprise differences with `x` spaced one unit apart -- i.e., slopes or trends for `x`. You can do `emmeans(emt, ...)` to average those down further as needed.

**Comment by rvlenth** [comment]
I think this is resolved, so am closing. But you can still comment if this didn't answer something.
