### ISSUE TITLE
using cld with a list of emmGrids created with pairwise

### ISSUE THREAD

**Issue by SalvatoreMangiafico** [rvlenth/emmeans#4]
I don't know if this is intentional or not, but a student was totally stumped by this, so I'll pass it on.

The first _cld_ works.  The second does not.  The object created with _pairwise_ is _mmGrid_, not _emmGrid_.

_
warp.lm <- lm(breaks ~ wool * tension, data = warpbreaks)

warp.emmGrid <- emmeans(warp.lm, ~ tension | wool)
cld(warp.emmGrid)

warp2.emmGrid <- emmeans(warp.lm, pairwise ~ tension | wool)
cld(warp2.emmGrid)
_

**Comment by rvlenth** [comment]
I’ll look at this to see if there’s a bug, but warp2 should NOT be an emmGrid in any case. It should be a list of emmGrids — I.e., an emmList. This is the way it has always worked (in lsmeans, it was lsmList).

I understand it’s confusing. It’s why I occasionally regret allowing the lhs to be used to specify contrasts. But you have to realize that when you do this, you are always asking for more than one thing, so you can never treat the result as if it is one thing. But if I were to follow my inclinations and remove the lhs capability, I think I’d hear unending complaints.

Russ

Sent from my iPhone

On Nov 18, 2017, at 12:11 PM, SalvatoreMangiafico <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't know if this is intentional or not, but a student was totally stumped by this, so I'll pass it on.

The first cld works. The second does not. The object created with pairwise is mmGrid, not emmGrid.

_
warp.lm <- lm(breaks ~ wool * tension, data = warpbreaks)

warp.emmGrid <- emmeans(warp.lm, ~ tension | wool)
cld(warp.emmGrid)

warp2.emmGrid <- emmeans(warp.lm, pairwise ~ tension | wool)
cld(warp2.emmGrid)
_

**Comment by rvlenth** [comment]
Here is what I get:
```
> warp.lm <- lm(breaks ~ wool * tension, data = warpbreaks)
> warp2.emmGrid <- emmeans(warp.lm, pairwise ~ tension | wool)
> class(warp2.emmGrid)
[1] "emm_list" "list"    

> cld(warp2.emmGrid[[1]])
wool = A:
 tension   emmean       SE df lower.CL upper.CL .group
 M       24.00000 3.646761 48 16.66769 31.33231  1    
 H       24.55556 3.646761 48 17.22325 31.88786  1    
 L       44.55556 3.646761 48 37.22325 51.88786   2   

wool = B:
 tension   emmean       SE df lower.CL upper.CL .group
 H       18.77778 3.646761 48 11.44547 26.11008  1    
 L       28.22222 3.646761 48 20.88992 35.55453  1    
 M       28.77778 3.646761 48 21.44547 36.11008  1    

Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 3 estimates 
significance level used: alpha = 0.05 
```

**Comment by SalvatoreMangiafico** [comment]
Okay.  That all makes sense. Thanks.

The context in which this came up was that the student was following an example using _lsmeans_.  So in the following, both _cld_ calls work and give the same results, despite the fact that warp4.emmGrid is a list of 2 mmGrids. 

library(lsmeans)

warp3.emmGrid <- lsmeans(warp.lm, ~ tension + wool)
lsmeans::cld(warp3.emmGrid)

warp4.emmGrid <- lsmeans(warp.lm, pairwise ~ tension + wool)
lsmeans::cld(warp4.emmGrid)

**Comment by rvlenth** [comment]
I think I remember dropping a couple of lsmList methods that had ‘which’ arguments, thinking it’d cause confusion if it guesses wrong on which member the user really wants. I’ll consider returning a message that tells the user to try again by calling the method on the desired element.

Russ

Sent from my iPhone

On Nov 18, 2017, at 6:02 PM, SalvatoreMangiafico <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay. That all makes sense. Thanks.

The context in which this came up was that the student was following an example using lsmeans. So in the following, both cld calls work and give the same results, despite the fact that warp4.emmGrid is a list of 2 mmGrids.

library(lsmeans)

warp3.emmGrid <- lsmeans(warp.lm, ~ tension + wool)
lsmeans::cld(warp3.emmGrid)

warp4.emmGrid <- lsmeans(warp.lm, pairwise ~ tension + wool)
lsmeans::cld(warp4.emmGrid)

**Comment by SalvatoreMangiafico** [comment]
Sounds good.  Thank you.  I've been revising materials from using _lsmeans_ to using _emmeans_.  So far, it's been easy enough.  I think this was the only difference I found between the two so far.  While I have your attention, I will bring up another issue in separate thread.

~ Sal

**Comment by rvlenth** [comment]
OK; I finally got around to checking this. And in fact, what I did in many of the `emm_list` methods, was to implement a `which` argument that defaults to `seq_along(object)`. In other words, the default is to apply the method to every single member of the `emm_list`. But I made an error in exporting `cld.emm_list()`. After fixing that errror, this is what I get:
```
> cld(warp2.emmGrid)
$emmeans
wool = A:
 tension   emmean       SE df lower.CL upper.CL .group
 M       24.00000 3.646761 48 16.66769 31.33231  1    
 H       24.55556 3.646761 48 17.22325 31.88786  1    
 L       44.55556 3.646761 48 37.22325 51.88786   2   

wool = B:
 tension   emmean       SE df lower.CL upper.CL .group
 H       18.77778 3.646761 48 11.44547 26.11008  1    
 L       28.22222 3.646761 48 20.88992 35.55453  1    
 M       28.77778 3.646761 48 21.44547 36.11008  1    

Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 3 estimates 
significance level used: alpha = 0.05 

$contrasts
wool = A:
 contrast   estimate       SE df t.ratio p.value .group
 M - H    -0.5555556 5.157299 48  -0.108  0.9936  1    
 L - H    20.0000000 5.157299 48   3.878  0.0009   2   
 L - M    20.5555556 5.157299 48   3.986  0.0007  12   

wool = B:
 contrast   estimate       SE df t.ratio p.value .group
 L - M    -0.5555556 5.157299 48  -0.108  0.9936  1    
 L - H     9.4444444 5.157299 48   1.831  0.1704  1    
 M - H    10.0000000 5.157299 48   1.939  0.1389  1    

P value adjustment: tukey method for comparing a family of 3 estimates 
significance level used: alpha = 0.05 
```
I'm not sure that's the right default, but at least the needed table is included along with a pretty weird one.

**Comment by SalvatoreMangiafico** [comment]
That makes sense.  

For routine use, I will recommend students and readers keep the _pairwise_, but be explicit in which item in the _emm.Grid_ list is passed to _cld_.  This way, both the EM means and contrasts are included in the output, and then only the one cld table is included.  I think this is probably what most users would be looking for in most cases.

```
> warp.lm <- lm(breaks ~ wool * tension, data = warpbreaks)
> warp5.emmGrid <- emmeans(warp.lm, pairwise ~ tension)
> warp5.emmGrid

$emmeans
 tension   emmean      SE df lower.CL upper.CL
 L       36.38889 2.57865 48 31.20417 41.57361
 M       26.38889 2.57865 48 21.20417 31.57361
 H       21.66667 2.57865 48 16.48194 26.85139

Results are averaged over the levels of: wool 
Confidence level used: 0.95 

$contrasts
 contrast  estimate       SE df t.ratio p.value
 L - M    10.000000 3.646761 48   2.742  0.0229
 L - H    14.722222 3.646761 48   4.037  0.0006
 M - H     4.722222 3.646761 48   1.295  0.4049

Results are averaged over the levels of: wool 
P value adjustment: tukey method for comparing a family of 3 estimates

> cld(warp5.emmGrid$emmeans)
    
      ### or cld(warp5.emmGrid[[1]])

 tension   emmean      SE df lower.CL upper.CL .group
 H       21.66667 2.57865 48 16.48194 26.85139  1    
 M       26.38889 2.57865 48 21.20417 31.57361  1    
 L       36.38889 2.57865 48 31.20417 41.57361   2   

Results are averaged over the levels of: wool 
Confidence level used: 0.95 
P value adjustment: tukey method for comparing a family of 3 estimates 
significance level used: alpha = 0.05 
```

**Comment by rvlenth** [comment]
Right. But another suggestion (which I’d recommend more) is to do everything incrementally:

   warp6.emm = emmeans(warp.lm, ~ tension | wool)

then

    pairs(warp6.emm)

and/or

    cld(warp6.emm)

as desired.

Russ

**Comment by SalvatoreMangiafico** [comment]
Thanks.  I do like that better.

~ Sal

**Comment by rvlenth** [comment]
Late comment. In reviewing another question on `cld`, I remember that there is a `details` argumenty. So in the preceding example, you could do:

```
cld(warp6.emm, details = TRUE)
```
and it will show *both* the groupings and the results of `pairs(warp6.emm)`
