### ISSUE TITLE
pwpp and "within-subject confidence intervals"

### ISSUE THREAD

**Issue by dhalpern** [rvlenth/emmeans#419]
There is a small literature, mostly among methodologists in cognitive psychology on how to visualize "within-subject comparisons" with roughly appropriate error bars, starting with [Loftus & Masson (1994)](https://link.springer.com/article/10.3758/BF03210951). Despite very little contribution from statisticians, these methods and [subsequent](https://www.tqmp.org/RegularArticles/vol04-2/p061/p061.pdf) [ones](https://www.tqmp.org/RegularArticles/vol04-2/p061/p061.pdf) are now fairly widely adopted in cognitive psychology and neuroscience -- according to google scholar, the original has been cited almost 3000 times and the other two nearly 2000. I only recently discovered the comparison arrows plot in emmeans and this seems to me like to be a highly related, although far more general, idea than has been written about in the cognitive psychology literature. In particular, the concerns pointed out in the "xplanations" vignette are similar to the pitfalls pointed out by [Franz & Loftus (2012)](https://link.springer.com/article/10.3758/s13423-012-0230-1). 

If I'm right about the connection, I wonder if it would be helpful for those from a similar background to mine (cognitive psychology) to make this connection explicit in the vignette? It would perhaps make the use-case a bit clearer to a field that really desires this kind of thing, and also remind people of the potential issues with using this method.

**Comment by rvlenth** [comment]
I think there is a lot of literature in various disciplines about making comparisons when there are multiple sources of variation. But I agree the 2012 reference does emphasize doing it graphically, so I added a reference to it in the vignette. 

Thanks for the suggestion. I am closing this issue as I think it is resolved.
