### ISSUE TITLE
stanreg error

### ISSUE THREAD

**Issue by DominiqueMakowski** [rvlenth/emmeans#42]
Here's the continuation of your mail with the error in the `psycho` package.

It is rather strange: 

For example, this chunk of code appear as broken if emmeans is not loaded (library(emmeans))

```r
fit <- rstanarm::stan_glm(Sepal.Width ~ Sepal.Length * Species, data=iris)

formula <- "Sepal.Length * Species"
formula <- as.formula(paste0("~", formula))
means_posterior <- fit %>%
    emmeans::emmeans(formula) %>%
    coda::as.mcmc() %>%
    as.matrix() %>%
    coda::as.mcmc() %>%
    as.data.frame()
```

``` 
Error in y[, var.cols] <- x : 
  number of items to replace is not a multiple of replacement length
```

It works if I load the package beforehand. In the same way, the error in the test-get_contrasts of the `psycho` package also works after explicitly loading emmeans... 

Is there an internal outside scope call that is made?

**Comment by DominiqueMakowski** [comment]
@rvlenth It works smoothly after replacing all the cdoa::as.mcmc by emmeans::as.mcmc.emmGrid(). Thanks :)

**Comment by rvlenth** [comment]
OK -- makes sens. But now I think you need to make sure to specify a version dependency `emmeans (>= 1.2.2)` in `DESCRIPTION`. 

Sorry for all this hassle!

**Comment by DominiqueMakowski** [comment]
Changed :) Thanks for letting me now and for your work.
