### ISSUE TITLE
Using survreg model with a strata() term gives the error "Non-conformable elements in reference grid."

### ISSUE THREAD

**Issue by Chris-Angell** [rvlenth/emmeans#429]
## Describe the bug
Trying to extract emmeans from a survreg model with with a strata() term fails, and gives the error "Non-conformable elements in reference grid."

## To reproduce
```
library(survival)
model1 <- survreg(Surv(futime, fustat) ~ age + strata(rx), dist= "weibull", data=ovarian)
emmeans(model1, specs = "age")
```

A similar model with "rx" as a regular factor works fine with emmeans:
```
model2 <- survreg(Surv(futime, fustat) ~ age + rx, dist= "weibull", data=ovarian)
emmeans(model2, specs = "age")
```

## Expected behavior
I expected emmeans() to produce an output for the emmean of age for model1 as it does for model2.

## Additional context
I tried to find a workaround by manually asking ref_grid() to look at just the non-strata terms in the model. I tried `ref_grid(model1, terms = drop.terms(terms(model1),3))` and got the same "Non-conformable elements" error.

I tried asking emmeans() and ref_grid() to ignore the strata values with `params = ` but the syntax for knots from the examples in the vignette and online is not the same as for strata() and I couldn't get it to work.

Thanks for your help in advance!

**Comment by rvlenth** [comment]
Here's a question for you... What does it mean if I *interact* one of thse `strata()` or `cluster()` or `frailty()`) terms with other predictors? For example,
```
> model2 = survreg(formula = Surv(futime, fustat) ~ age * strata(rx), data = ovarian, 
+                  dist = "weibull")
> coef(model2)
       (Intercept)                age age:strata(rx)rx=2 
      11.512555818       -0.086210384        0.007642672 
```
This model does *not* play well with `emmeans`. Is this model sensible in practice? And if so, why do we have a fixed effect for `age:strata(rx)` but not a main effect for `strata(rx)`?

**Comment by rvlenth** [comment]
Well, `strata()` is just a function, and I think `survreg()` just uses the code in **stats**. Those two models generate pretty similar model matrices...
```
> library(survival)

> head(model.matrix(~ age * strata(rx), data = ovarian))
  (Intercept)     age strata(rx)rx=2 age:strata(rx)rx=2
1           1 72.3315              0             0.0000
2           1 74.4932              0             0.0000
3           1 66.4658              0             0.0000
4           1 53.3644              1            53.3644
5           1 50.3397              0             0.0000
6           1 56.4301              0             0.0000

> head(model.matrix(~ ~ age:as.factor(rx) + strata(rx), data = ovarian))
  (Intercept) strata(rx)rx=2 age:as.factor(rx)1 age:as.factor(rx)2
1           1              0            72.3315             0.0000
2           1              0            74.4932             0.0000
3           1              0            66.4658             0.0000
4           1              1             0.0000            53.3644
5           1              0            50.3397             0.0000
6           1              0            56.4301             0.0000
```
And the documentation for `strata()` says it's basically the same as `interaction()` which is pretty trivial with just one factor:
```
> with(ovarian, strata(rx))
 [1] rx=1 rx=1 rx=1 rx=2 rx=1 rx=1 rx=2 rx=2 rx=1 rx=2 rx=1 rx=2 rx=2 rx=2 rx=1 rx=1 rx=1 rx=1 rx=2
[20] rx=2 rx=2 rx=1 rx=1 rx=2 rx=2 rx=2
Levels: rx=1 rx=2
```
So maybe `survreg()` just takes what you give it and splits off the `strata()` part. And just doesn't anticipate that the user would specify a nonsense model where `strata()` interacts with something.

Anyway, I'm not too worried that a user will specify a model like mine, so will just let it slide.

**Comment by rvlenth** [comment]
I changed it again... Please see comment in #473
