### ISSUE TITLE
Add Pull Request Template

### ISSUE THREAD

**Issue by SaarthakMaini** [rvlenth/emmeans#433]
Pull request templates allow your organizations to have a default text when you create a pull request on GitHub.

**Comment by rvlenth** [comment]
I don't really see the necessity of having a template for pull requests. I think people who would want to create a pull request for my package already have quite a bit of experience with GitHub, and a pull request is already reproducible by nature. I think those people would already know what they are doing, and a template could just make it more awkward. So thanks, but I think I'll decline at this time.
