### ISSUE TITLE
Update of the list of supported models (mmrm)

### ISSUE THREAD

**Issue by Generalized** [rvlenth/emmeans#437]
emmeans supports the mmrm package just perfectly. I think it's really worth adding it to the list of supported models. Lots of clinical biostatisticians will be very happy while browsing the list! The MMRM (via GLS and GEE) is a daily workhorse in the clinical trials industry.

Everything works well: EM-means, their contrasts (and trends), (type-3) joint testing, analysis of slopes, mvt adjustment...

What makes it double awesome is that emmeans supports MMRM on MICE-imputed datasets (which allows the analyst to perform complex sensitivity analyses against the MNAR pattern).

https://cran.r-project.org/web/packages/emmeans/vignettes/models.html
https://cran.r-project.org/web/packages/mmrm/vignettes/introduction.html

**Comment by rvlenth** [comment]
Thanks for letting me know. I added `mmrm` to the list of supported models, and it will show up in the next update.

**Comment by rvlenth** [comment]
BTW, I am liking the **mmrm** package. I have a standard repeated-measures example I used to use in teaching (getting to be long ago...), where an AR(1) correlation structure fits much better than an uncorrelated one. This package makes it doable in one call with no muss or fuss.

The one addition I would wish for is a covariance structure option for uncorrelated errors, just so we can compare with other models.

**Comment by Generalized** [comment]
Yes, the "independence" structure would be indeed worth adding! I will issue a ticket on their GitHub :)
In the meantime, the good-old nlme::gls() remains, but - I absolutely agree - beginners may find the specification of correlation and weights a bit complicated. Why using N tools and align their outputs if we can use just single with a common interface!

PS: thank you for documenting the mmrm!
