### ISSUE TITLE
qdrg with MICE (as.mira) - is there any way to marry them?

### ISSUE THREAD

**Issue by Generalized** [rvlenth/emmeans#446]
I need to run ordinal logistic regression for repeated observations via GEE.
I can use either ordLORgee from the multgee package or repolr from the repolr package.
Unfortunately, neither supports emmeans. They can be integrated with emmeans via qdrg, though. This works very well.

Now, I have multiply imputed dataset. I know that emmeans works with via as.mira() - I use it with mmrm and gee - but this seems to work with models that emmeans can recognize.

But how to deal with qdrg this way? I'm afraid it's impossible, because how to pass all those coefficients and variances?

For example (from another question):
```
list_ords <- lapply(imp_data_long, 
                       function(data)
                         ordLORgee(formula = ODIPain ~ Visit_nOrd * Arm + Age_centered + Age_centered : Visit_nOrd,
                                             data = data, id = PatientId, repeated = as.numeric(Visit_nOrd), LORstr = "RC"))
```
but what to do with qdrg?
```
qdrg(formula = ODIPain ~ Visit_nOrd * Arm + Age_centered + Age_centered : Visit_nOrd,....?
```

I thought, that maybe I should create qdrg in each iterated analysis:
```

ord_gee_imp <- lapply(imp_data_long, 
                       function(ddd) {
                         fitmod <- ordLORgee(formula = ODIPain ~ Visit_nOrd * Arm + Age_centered + Age_centered : Visit_nOrd,
                                             data = ddd, id = PatientId, repeated = as.numeric(Visit_nOrd), LORstr = "uniform")

                          lord_grid <- qdrg(formula = ODIPain ~ Visit_nOrd * Arm + Age_centered + Age_centered : Visit_nOrd,
                                             data=ddd, 
                                             coef = fitmod$coefficients, 
                                             vcov = fitmod$robust.variance, 
                                             df = Inf, 
                                             ordinal.dim =length(levels(data$ODIPain)), 
                                             link = fitmod$link)
                          })
```

and somehow pass it to emmeans, but it also doesn't work:

```
> emmeans(as.mira(ord_gee_imp), specs = ~Arm * Visit_nOrd)
Error in UseMethod("recover_data") : 
  no applicable method for 'recover_data' applied to an object of class "emmGrid"
Error in (function (object, at, cov.reduce = mean, cov.keep = get_emm_option("cov.keep"),  : 
  Perhaps a 'data' or 'params' argument is needed
```

I desperately try to complete the analysis... I'm about to write the components necessary to implement the emmeans through the vignette, but I thought there is some workaround that can save me this time?

**Comment by Generalized** [comment]
OK, I think I found a quick-and-(very)dirty workaround.

I looked at the source in this file: https://github.com/rvlenth/emmeans/blob/3957a59d33d35963afebacdb7856ce84ee5be71c/R/multiple-models.R#L139

namely to this function:
```{r}
emm_basis.mira = function(object, trms, xlev, grid, ...) {
    # In case our method did a "pass it on" with the data, we need to add that attribute
    data = list(...)$misc$data
    if(!is.null(data))
        object$analyses = lapply(object$analyses, function(a) {attr(a, "data") = data; a})
    bas = emm_basis(object$analyses[[1]], trms, xlev, grid, ...)
    k = length(object$analyses)
    # we just average the V and bhat elements...
    V = 1/k * bas$V
    allb = cbind(bas$bhat, matrix(0, nrow = length(bas$bhat), ncol = k - 1))
    for (i in 1 + seq_len(k - 1)) {
        basi = emm_basis(object$analyses[[i]], trms, xlev, grid, ...)
        V = V + 1/k * basi$V
        allb[, i] = basi$bhat
    }
    bas$bhat = apply(allb, 1, mean)  # averaged coef
    notna = which(!is.na(bas$bhat))
    bas$V = V + (k + 1)/k * cov(t(allb[notna, , drop = FALSE]))   # pooled via Rubin's rules
    bas
}
```
This creates the emm.basis, which is kinda "input" for the emmeans. It prepares the necessary components, like pooled coefficients and (co)variances, passed later to emmeans.

And that's exactly what I need to pass to qdrg: coefficients, var_cov and df.

So I took your code and plugged in my as.mira(list_of_models).

```{r}
ord_gee_imp <- lapply(imp_data_long, 
                       function(ddd) {
                         fitmod <- ordLORgee(formula = ODIPain ~ Visit_nOrd * Arm + Age_centered + Age_centered : Visit_nOrd,
                                             data = ddd, id = PatientId, repeated = as.numeric(Visit_nOrd), LORstr = "uniform")
                          })

ord_gee_imp_mira <- as.mira(ord_gee_imp)

  k = length(ord_gee_imp_mira$analyses)
  # we just average the V and bhat elements...
  V = 1/k * ord_gee_imp_mira$analyses[[1]]$robust.variance
  allb = cbind(ord_gee_imp_mira$analyses[[1]]$coefficients, matrix(0, nrow = length(ord_gee_imp_mira$analyses[[1]]$coefficients), ncol = k - 1))
  for (i in 1 + seq_len(k - 1)) {
    V = V + 1/k * ord_gee_imp_mira$analyses[[i]]$robust.variance
    allb[, i] = ord_gee_imp_mira$analyses[[i]]$coefficients
  }
  pooled_coefs = apply(allb, 1, mean)  # averaged coef
  notna = which(!is.na(pooled_coefs))
  pooled_VC = V + (k + 1)/k * cov(t(allb[notna, , drop = FALSE]))   # pooled via Rubin's rules

  ord_gee_imp_grid <- qdrg(formula = ODIPain ~ Visit_nOrd * Arm + Age_centered + Age_centered : Visit_nOrd,
                    data=imp_data_long[[1]], # fake data in any case 
                    coef = pooled_coefs, 
                    vcov = pooled_VC, 
                    df = Inf, 
                    ordinal.dim =length(unique(imp_data_long[[1]]$ODIPain)), 
                    link = fitmod$link)
  
(ord_gee_imp_em <- emmeans(ord_gee_imp_grid, specs = ~Arm * Visit_nOrd , data=data))

update(contrast(ord_gee_imp_grid,
                list("Month 6  : SoC vs. HD" = c(-1, 1, 0, 0, 0, 0),
                     "Month 12 : SoC vs. HD" = c( 0, 0,-1, 1, 0, 0),
                     "Month 20 : SoC vs. HD" = c( 0, 0, 0, 0,-1, 1))),
       adjust="none", level = 0.95, infer = c(TRUE, TRUE))
```

So now I have a universal way of dealing with unknown models in the framework of multiple imputation. At least as long, as all necessary components will be provided...

**Comment by rvlenth** [comment]
Thanks. I don't want to export that function as it has such a narrow purpose. However, I am providing a link to this issue in Section I of the `models` vignette, so that people with this situation can find it.

**Comment by adrianolszewski** [comment]
Thank you!

Would you consider adding a binary option: "pool = FALSE" (by default) to qdrg to pool estimates and covariances? They are provided by the user anyway, as well as the degrees of freedom and other parameters (as well as the number of levels in case of ordinal regression).

This would reduce the need for external functions, ensure consistency and make qdrg() similarly universal to emmeans() in terms of working with MIRA objects. The note in the documentation would say, then, that it's up to the user to extract the coefficients and covariances from the MIRA object (storing the list of analyses) and pass them to qdrg().

It could show 2 examples:
for an ordinary list of analyses - like in my case:
```{r}
lapply(list_of_analyses_on_the_imputed_data, function(analysis) analysis$name_of_coefficients)
lapply(list_of_analyses_on_the_imputed_data, function(analysis) analysis$name_of_var_cov_matrix)
```

or, if one is using MIRA object, they replace the list_of_analyses_on_the_imputed_data with `object$analyses` and that's all.

The number of entries could be retrieved either from the list itself `length(list_of_analyses_on_the_imputed_data)` or `length(object$analyses)`.

The only question is which data to use with all "types" of variables that you use for constructing the model matrix (so their types of columns must agree).

So it could look like (this example could be added to the qdrg() vignette:
```{r}
 qdrg(formula = ODIPain ~ Visit_nOrd * Arm + Age_centered + Age_centered : Visit_nOrd,
data=imp_data_long[[1]], # fake data in any case 
coef = lapply(MIRA_object$analyses, function(analysis) analysis$coefficients),
vcov = lapply(MIRA_object$analyses, function(analysis) analysis$robust.variance)
df = Inf, 
ordinal.dim = 6, 
link = "Cumulative logit"),
pool = TRUE)  # <----- This one is new.
```

This would reduce the amount of necessary code and the risk of making an error. Moreover, it would use THE code for pooling that you originally wrote, so no need to have this code repeated twice in emmeans() and locally.

**Comment by rvlenth** [comment]
`qdrg()` is designed as something for pretty general use, I think an option like that is too specific to a very narrow class of models, so I'm not interested in adding that option at this time. And it *would* require essentially repeating the same code, because it can't just call `emm_basis.mira` without some fancy workarounds.

By the way, `link = "Cumulative logit"` is not supported. You should specify `link = "logit"`.

**Comment by Generalized** [comment]
Thank you. Yes, you are right. Anyway, it's great the qdrg() facilitates "bridging" emmeans to models in so many situations. It was a great idea to make it.
