### ISSUE TITLE
Partial argument patch of `just` to `justify`

### ISSUE THREAD

**Issue by pawelru** [rvlenth/emmeans#463]
This occurred when calling `print()` on `"emmGrid"` class of object but the root cause is there:
https://github.com/rvlenth/emmeans/blob/b04aa6e936e0496448727c1d193824bbeb4ae667/R/summary.R#L1318

I assume reprex is not needed here.

**Comment by rvlenth** [comment]
... and if you think this did cause an error, then yes, a reprex is required.

**Comment by pawelru** [comment]
The longer story is that I am testing my code against some potential errors due to partial argument match:

```
list(
  warnPartialMatchDollar = TRUE,
  warnPartialMatchArgs = TRUE,
  warnPartialMatchAttr = TRUE,
  warn = 2
)
```

This however tests the whole stack of calls (i.e. not only my code but also packages that I depend on - both directly and indirectly). I am aware that this is rather an unusual setup but it's done on purpose. Now I am sharing my discoveries with respective pkg authors.
