### ISSUE TITLE
Emmeans package fails to load

### ISSUE THREAD

**Issue by munizdiezclara** [rvlenth/emmeans#468]
When trying to load emmeans with
`library(emmeans)`
the following bug report appears:
Error: package or namespace load failed for ‘emmeans’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘estimability’

Emmeans has been installed in RStudio via CRAN, RStudio version is 2023.12.1 and R version is 4.2.3. 

I would like to know how to fix this.

**Comment by rvlenth** [comment]
This is an issue with your system, not with the **emmeans** package.  The package requires the additional package **estimability** to be installed on your system, and it is apparently not. To remedy, run the following code from the R console:
```
install.packages("estimability")
```
Then after this is complete, you should be able to successfully load **emmeans**.

**Comment by munizdiezclara** [comment]
I am very sorry I did not realize. Thank you very much for explaining it.

**Comment by rvlenth** [comment]
Closing this issue as it is resolved
