### ISSUE TITLE
standardization of slopes

### ISSUE THREAD

**Issue by samyogita-hardikar** [rvlenth/emmeans#476]
I recently reported emtrends slopes in a paper, and was asked to provide standardized estimates. 
If I want to be quick, does it make sense to standardize them in the same way I would an "estimate" from linear model output? 
standardized slope = unstandardized slope * stdev(predictor) / stdev(outcome)? 
Thank you in advance!

**Comment by rvlenth** [comment]
That seems like one possibility. Another is that a slope cand be regarded as an "effect", in which case maybe they want an effect size, which you could get from the `eff_size()` function, standardizing just by the response SD.. Maybe it's best to ask them to clarify; or give your answer and say it's not completely clear that is what was requested.

**Comment by samyogita-hardikar** [comment]
Makes sense. Thank you!

**Comment by samyogita-hardikar** [comment]
Makes sense. Thank you!
