### ISSUE TITLE
Statistical test used to calculate p-values for Poisson regression

### ISSUE THREAD

**Issue by gevro** [rvlenth/emmeans#483]
Hi,
I wanted to clarify - what is the correct terminology to describe the statistical test that calculates a p-value for a specific predictor variable in a Poisson regression.

i.e. emmeans(~glm(formula = ...), family=poisson) %>% pairs -> produces p-values. What is the statistical test used to calculate these?

Thanks

**Comment by rvlenth** [comment]
I don't know how to answer this. People in different fields call it different things. For GLMs you typically obtain a z ratio of the observed difference divided by its asymptotic standard error. It is used to test a null hypothesis that the true difference of means is zero versus a two-sided alternative. And by default with comparisons, a Tukey adjustment is applied to the P values, which are thus right-tail areas of the Studentized Range distribution.

If you need more clarification , I suggest posting a question on [CrossValidated](https://stats.stackexchange.com/)

**Comment by gevro** [comment]
Thank you!

**Comment by gevro** [comment]
Ok I posted it on CrossValidated, because I also wanted to confirm the default for 'pairs' is a two-sided test.

**Comment by rvlenth** [comment]
The documentation for `summary.emmGrid` has a lot of details, including that.

**Comment by gevro** [comment]
Thanks, but I don't see a default value for 'side' mentioned in that documentation, I just read through it. Maybe I'm missing it somewhere?
