### ISSUE TITLE
Plot trends of emtrends

### ISSUE THREAD

**Issue by jpospina88** [rvlenth/emmeans#49]
Hello,

I mainly use your functions of emmeans and emtrends to get summary statistics from my models. Your package is awesome!

I've been able to retrieve the means and standard errors of emmeans and plot them in bar graphs. Now, I am working with data where one of my predictors is a factor and the other is numeric. So I would be plotting trends.

Is there a similar way to plot trends with the emmGrid object that I get from emtrends?

Thanks!

**Comment by rvlenth** [comment]
I'm not sure what you're asking. You can visualize the fitted lines themselves using `emmip`, e.g.,
```
fiber.lm <- lm(strength ~ diameter*machine, data=fiber)
emmip(fiber.lm, machine ~ diameter, cov.reduce = range)
```
where `cov.reduce = range` is added so we compute predictions at both the minimum and maximum of the covariate.

To graph the values of the estimated slopes and SEs, the `emtrends()` function returns exactly the same kind of object as `emmeans()`, so you can plot those results using the same methods you used to produce your bar graphs for EMMs.

**Comment by rvlenth** [comment]
Not sure where this stands. I'm closing this issue, but re-open it if it hasn't been addressed to your satisfaction.
