### ISSUE TITLE
list of p-value adjustments not included in documentation for summary.emmGrid

### ISSUE THREAD

**Issue by SalvatoreMangiafico** [rvlenth/emmeans#5]
_?lsmeans::summary_ provides an explicit list and discussion of p-value adjustment methods in the Details section.

?summary.emmGrid suggests in the Arguments section that a similar discussion p-value adjustment methods would be included in the Details section, but that discussion is not included there.

**Comment by rvlenth** [comment]
Yikes! Thanks for pointing this out. There is some other material that should have been included as well (e.g., estimability) that I have added back in. The next push will have that stuff restored.

**Comment by SalvatoreMangiafico** [comment]
Great.  Thank you.
