### ISSUE TITLE
some recover_data() methods are not yet exported

### ISSUE THREAD

**Issue by singmann** [rvlenth/emmeans#50]
Hi Russ,

I am working on extending my new [`afex_plot()`](https://cran.rstudio.com/web/packages/afex/vignettes/afex_plot_introduction.html) function with a `default` method. In this method I rely on `emmeans::recover_data()` to obtain the raw data used for fitting the model. This works in many cases, but not in all. For example:

```
require("ordinal")
wine.clm <- clm(rating ~ temp + contact, scale = ~ judge,
                data = wine, link = "probit")
emmeans::recover_data(wine.clm, list(pairwise ~ temp, pairwise ~ contact))
# Error in UseMethod("recover_data") : 
#   no applicable method for 'recover_data' applied to an object of class "clm"
```

However
```
emmeans:::recover_data.clm(wine.clm)
#    temp contact judge
# 1  cold      no     1
# 2  cold      no     1
# 3  cold     yes     1
# 4  cold     yes     1
# [...]
```

It would be great if you could export all `recover_data` methods so they could be used in other packages, such as `afex`. If it helps, I could submit a pull request.

Thanks,
Henrik

**Comment by singmann** [comment]
Same holds for example for `polr`:

```
mod.wvs <- MASS::polr(poverty ~ gender + religion + degree + country*poly(age,3),
                    data=carData::WVS)
emmeans::recover_data(mod.wvs)       # fails
emmeans:::recover_data.polr(mod.wvs) # works
```

**Comment by rvlenth** [comment]
For the sake of keeping things "lean and mean," I like the idea of keeping exports at a minimum; and there are probably 20 or 30 `recover_data` methods in the package -- I didn't actually count them. On the other hand, it does seem that these `recover_data` methods could be useful to other package developers, even though that is far from the central purpose of **emmeans**.

But here's an idea: I export a hidden `.recover_data()` function that just calls `recover_data()` internally, thereby providing access to all available methods:

```
> wd = emmeans::.recover_data(wine.clm)
> head(wd)
  temp contact judge
1 cold      no     1
2 cold      no     1
3 cold     yes     1
4 cold     yes     1
5 warm      no     1
6 warm      no     1
```

That can join the other functions I export as a courtesy, like `.std.link.labels()`. Would that suit your purposes? I have in fact already added this new function and will push to github soon.

Footnote: Here is what is exported now:
```
> methods(recover_data)
[1] recover_data.aovlist* recover_data.call*    recover_data.lm*      recover_data.lme*    
[5] recover_data.merMod* 
```
I think I should continue to export at least the `call` and `lm` methods, but if `.recover_data()` is available, it may make sense to not export the others, if you are inclined to make minor changes in  your support code for your objects. What do you think?

**Comment by singmann** [comment]
Adding the new function `.recover_data` does work for my use case and it is not really a problem to change my code, but I cannot really see, why you think that it this solution is necessary. 

In general, I very much see the value of keeping a package "lean and mean" (that is also why the latest version of `afex` does not `Depend` on `emmeans` any more), but I am not sure that applies here. At least I cannot see what kind of ballast this ads to `emmeans`, it also does not seem to produce clutter anywhere or make things slower. Furthermore, you do not need to document the methods and do not need to maintain the methods above what you do now.

I think the main benefit of exporting the methods explicitly is that it makes it easier for users or programmers to see for which objects methods exist, without looking it up in the documentation. In my eyes, this increase in usability trumps a perceived increase in package size.

In any case, it is your package and I can work equally well with either solution.

PS: My goal is to provide full `emmeans` support for my new [`afex_plot`](https://singmann.github.io/afex_plot_introduction.html) which then could also solve the problem in #28.

**Comment by rvlenth** [comment]
Henrik,

Well, I understand what you are saying. However, at this time my decision is to leave what I export in place (so you need not alter your existing code), and will provide `.recover_data()` and `.emm_basis()`. 

Exporting all those additional methods does add a lot of stuff to the S3 method registry, which theoretically reduces performance somewhat (though admittedly that is a very minor effect, and perhaps no performance issue at all relative to looking them up in **emmeans**'s namespace, as is done with my dot functions). Nonetheless, there is also the work of adding a few dozen `@export` tags to my code -- which impacts what I do with my time. Only a very small number of users and developers would ever want to use those methods directly.

afex_plot looks potentially useful. I'll take a look at it and will try to remember to refer users to it when they run up against limitations in `emmip()` and such.

**Comment by rvlenth** [comment]
PS - Are you now settled-in in Merry Old England? Hope you are finding it a really rewarding situation.

**Comment by singmann** [comment]
Ahh yes, the developer time. This is of course a factor one also has to consider. 

Let me know when you submit the new version of `emmeans` with the `.` functions to `CRAN` so I can prepare my next submission. However, this is not urgent at all as my new job in the UK starts next Monday and I will immediately start with teaching there. I guess this will prevent me from working extensively on my packages for the next two months. I am looking forward to it. 

I will close this issue for now. The `.` variants solve the problem.
