### ISSUE TITLE
Unexpected result when using emmeans on coxph object

### ISSUE THREAD

**Issue by lang-benjamin** [rvlenth/emmeans#505]
Running `emmeans` on a `coxph` fit seems to produce results on the risk scale, even though the output says they're not. Consider for example:
``` r
library(survival)
library(emmeans)
#> Welcome to emmeans.
#> Caution: You lose important information if you filter this package's results.
#> See '? untidy'

lung2 <- na.omit(lung)
lung2$sex <- as.factor(lung2$sex)
fit <- coxph(Surv(time, status) ~ age + sex, lung2)
emmeans(fit, specs = "sex")
#>  sex emmean    SE  df asymp.LCL asymp.UCL
#>  1     1.09 0.678 Inf    -0.242      2.42
#>  2     0.64 0.724 Inf    -0.780      2.06
#> 
#> Results are given on the log (not the response) scale. 
#> Confidence level used: 0.95
```

<sup>Created on 2024-08-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I would have expected the results being (different due to adjustment for `age` but) similar to
``` r
library(survival)
lung2 <- na.omit(lung)
lung2$sex <- as.factor(lung2$sex)
fit <- coxph(Surv(time, status) ~ age + sex, lung2)
aggregate(predict(fit, type = "lp") ~ sex, data = lung2, FUN = mean)
#>   sex predict(fit, type = "lp")
#> 1   1                 0.0157548
#> 2   2                -0.4720460
```

<sup>Created on 2024-08-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

In fact, the results are very similar to `aggregate(predict(fit, type = "risk") ~ sex, data = lung2, FUN = mean)`, suggesting that `emmeans` results are already on the risk scale.
Also, it seems that `emmeans(fit, specs = "sex", type = "response")` is not sensible because this in turn calculates `exp()` of results that are already on the risk scale. For completeness, see this reproducible example:
``` r
library(survival)
library(emmeans)
#> Welcome to emmeans.
#> Caution: You lose important information if you filter this package's results.
#> See '? untidy'
lung2 <- na.omit(lung)
lung2$sex <- as.factor(lung2$sex)
fit <- coxph(Surv(time, status) ~ age + sex, lung2)
aggregate(predict(fit, type = "risk") ~ sex, data = lung2, FUN = mean)
#>   sex predict(fit, type = "risk")
#> 1   1                   1.0281650
#> 2   2                   0.6316325
emmeans(fit, specs = "sex", type = "response")
#>  sex response   SE  df asymp.LCL asymp.UCL
#>  1       2.97 2.01 Inf     0.785     11.20
#>  2       1.90 1.37 Inf     0.459      7.85
#> 
#> Confidence level used: 0.95 
#> Intervals are back-transformed from the log scale

sessionInfo()
#> R version 4.2.2 (2022-10-31 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19045)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
#> [3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
#> [5] LC_TIME=German_Germany.utf8    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] emmeans_1.10.3 survival_3.4-0
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_4.2.2     R.methodsS3_1.8.2  R.utils_2.12.3     tools_4.2.2       
#>  [5] digest_0.6.34      evaluate_0.23      lifecycle_1.0.4    R.cache_0.16.0    
#>  [9] lattice_0.20-45    rlang_1.1.2        reprex_2.1.0       Matrix_1.6-5      
#> [13] cli_3.6.2          rstudioapi_0.15.0  yaml_2.3.8         mvtnorm_1.2-4     
#> [17] xfun_0.42          fastmap_1.1.1      withr_3.0.0        styler_1.10.2     
#> [21] knitr_1.45         fs_1.6.3           vctrs_0.6.5        grid_4.2.2        
#> [25] glue_1.7.0         rmarkdown_2.26     multcomp_1.4-25    TH.data_1.1-2     
#> [29] purrr_1.0.2        magrittr_2.0.3     codetools_0.2-18   htmltools_0.5.7   
#> [33] splines_4.2.2      MASS_7.3-58.1      xtable_1.8-4       sandwich_3.1-0    
#> [37] estimability_1.4.1 zoo_1.8-12         R.oo_1.26.0
```

<sup>Created on 2024-08-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by rvlenth** [comment]
Well, the estimates come straight from the linear predictor:
```
> coef(fit)
       age       sex2 
 0.0173728 -0.4466906 

> RG = ref_grid(fit)   # reference grid for this model
> RG@bhat            # coefs - match coef(fit)
       age       sex2 
 0.0173728 -0.4466906 

> RG@linfct    # linear functions
       age sex2
1 62.56886    0
2 62.56886    1

> RG@linfct %*% RG@bhat
       [,1]
1 1.0869965
2 0.6403058

> head(model.matrix(fit), 3)   # sanity check on RG@linfct
  age sex2
2  68    0
4  57    0
6  74    0
```
So everything looks to be in line. BTW, the predictions from `RG` are the same as those from `emmeans()`, as no factors are averaged over.

On the other hand, I do see:
```
> predict(fit, newdata = RG@grid, type = "lp")
         1          2 
 0.0000000 -0.4466906 
```
So what the heck do we mean by "linear predictor" if it isn't `X %*% beta`? Maybe this is a clue:
```
> predict(fit, newdata = RG@grid, type = "terms")
  age        sex
1   0  0.0000000
2   0 -0.4466906
attr(,"constant")
[1] 1.086996
```
This is close to what you say you expected. The help page for `predict.coxph` talks about centering around a reference value. Evidently in this case, that reference value is the `"constant"` attribute, which happens to be equal to `emmeans`'s prediction for `sex2 = 1`. Wherever that came from, I am not comfortable with `emmeans` returning a hard zero.

I do not work with these models, and I just don't know. But the emmeans code for `coxph` models has been around for a decade, and I do not recall anyone questioning the values returned. Also, if I were to change this, it would affect existing users who are accustomed to the way it works, and I can't take that lightly.

In any case, this does not have to do with exponentiating the estimates. I will consult with some colleagues who work with these kinds of models and see what they advise.

**Comment by rvlenth** [comment]
A couple more notes here.

 1. What `emmeans()` and `ref_grid()` do is analogous to running `predict.coxph(..., type = "lp", reference = "zero")` 
 2. The centering that `predict.coxph()` does involves adjusting the *covariate*. In **emmeans**, the user has complete control over covariate settings through the `at` argument. So we can reproduce the `predict()` results above by setting `age` equal to zero, which is its adjusted value at the mean `age`:
```
 ref_grid(fit, at = list(age = 0))   |> summary()
 age sex prediction    SE  df
   0 1        0.000 0.000 Inf
   0 2       -0.447 0.198 Inf

Results are given on the log (not the response) scale. 
```

 3. While I get the point that estimates are relative to the data and that centering them around the mean or the strata helps with numerical stability, I'm still reluctant to change what it does. It seems weird to me that when given `newdata`, `predict.coxph()` actually *changes* the new data that it was given. It seems like a "truth in advertising" problem to me. I can't think of other model classes in R where that is done.

**Comment by rvlenth** [comment]
FWIW, I added this to the "models" vignette, section G:

> For `coxph` objects, the estimates we obtain are comparable to running 
`predict.coxph()` with `reference = "zero"`; that is, no covariate centering is done.
The user may use `at` to specify adjusted covariate values. For example, the 
default reference grid sets each covariate to its mean, so estimates comparable
to `predict.coxph(..., reference = "sample")` would be obtained by specifying
`at = list(x = 0)`.

**Comment by lang-benjamin** [comment]
Thanks for your response. I can follow your argumentation and understand the underlying behaviour now (I also just started to work with these kind of models). I think the added information in the vignette is a good source that can be consulted.

**Comment by rvlenth** [comment]
OK, am glad it is resolved to your satisfaction. One of the challenges of maintaining a package that supports so many models is constantly being out of my depth.
