### ISSUE TITLE
Proposal to inform about the opt.digits option very early.

### ISSUE THREAD

**Issue by adrianolszewski** [rvlenth/emmeans#511]
Dear Professor @rvlenth,

I just caught myself at forgetting about the `emm_options(opt.digits = TRUE)` option...
(Just a toy example):
```
d <- read.table(header=TRUE, stringsAsFactors=TRUE, text="
Classroom  Gender    Height
 A          Male    151
 A          Male    150
 A          Male    152
 A          Male    149
 A          Female  155
 A          Female  156
 A          Female  157
 A          Female  158
 B          Male    151
 B          Male    150
 B          Female  155
 B          Female  156
 B          Female  157
 B          Female  158
 B          Female  156
 B          Female  157
")

> tapply(d$Height, d$Classroom, mean)
    A     B 
153.5 155.0 

> emmeans(lm(Height ~ Classroom, data = d), ~ Classroom)
 Classroom emmean   SE df lower.CL upper.CL
 A            154 1.13 14      151      156            # a little in panic...
 B            155 1.13 14      153      157

Confidence level used: 0.95 

# What's inside?
> as.data.frame(emmeans(lm(Height ~ Classroom, data = d), ~ Classroom))
 Classroom emmean       SE df lower.CL upper.CL
 A          153.5 1.125992 14  151.085  155.915                 # ahhh, OK, it's all fine!
 B          155.0 1.125992 14  152.585  157.415

Confidence level used: 0.95 

> emm_options(opt.digits = FALSE)                       # I should be more vigilant!

> emmeans(lm(Height ~ Classroom, data = d), ~ Classroom)
 Classroom emmean       SE df lower.CL upper.CL
 A          153.5 1.125992 14  151.085  155.915
 B          155.0 1.125992 14  152.585  157.415

Confidence level used: 0.95 
```

I know that the [vignette](https://cran.r-project.org/web/packages/emmeans/vignettes/utilities.html) says it clearly in section **Optimal digits to display**, but still it's easy to forget...

I do not justify myself for being clumsy here, there are many details when doing statistics one needs to remember about.
But I think it would be practical and beneficial, not only for beginners, to add such information in two more places:

1. when the emmeans is loaded. Actually, you start with a very important message here:

> Welcome to emmeans.
> Caution: You lose important information if you filter this package's results.
> See '? untidy'

so, I think it is a perfect place to inform also about the precision of displayed numbers,

2. and also here, on GitHub:
![obraz](https://github.com/user-attachments/assets/67d37e3f-c4fa-4615-bd5c-14a00bc6922c)

What is your opinion on this little reminder?

**Comment by rvlenth** [comment]
I suggest that you try to not panic when you see estimates rounded to 3 digits (typically), as really in most cases more digits than that are expressing your results to greatly exaggerated precision. In your example, the estimates are rounded to the nearest integer, and that is not incorrect because 153.5 does round to 154. Also, the CI for the first mean is (151, 156), which is wide enough that the distinction between 154 and 153.5 is not that important. Plus note that the midpoint of the CI is 153.5.

Anyway, I don't think the optimal-digits output causes enough confusion to warrant a startup message.

**Comment by adrianolszewski** [comment]
Thank you for the response!

Yes, I understand the reasons behind having the optimal-digits output (kind of which is present also in the Tidyverse, namely in "tibbles"). But the issue is it can be a source of unnecessary negative feedback from statistical reviewers, who often ask me or my colleagues for at least one decimal digit in such case, even if rounding as above is just fine. Of course, we can still access the exact values, so it won't affect any additional calculations. But  since I just caught myself on forgetting it, I thought it would be really helpful to add at least a little additional reminder...

Not even for me - I will keep this in mind (and I totally do not panic, I am totally not a "fan" of making up false precision), but for new users of emmeans, less advanced researchers, like those who I sometimes support in their medical research.

I am going to close this topic, but also let me, please, kindly ask you for considering adding at least a little warning "earlier" than in the vignette. Maybe, for example, in the main GitHub page, next to the "Tidiness can be dangerous" section? 
Some people may never reach this vignette (yes, that's their problem to not read full documentation, but still...). 

With Kind Regards!

**Comment by rvlenth** [comment]
OK, as suggested, I am adding this section to the README file:

> ## Rounding
> For its summary output, **emmeans** uses an optimal-digits algorithm that rounds results to about the number of digits that are useful, relative to estimates' confidence limits. This avoids cluttering the output, but it is unlike other results, which are typically less round. If this is annoying to you, there is an option (`opt.digits = FALSE`) that disables the optimal-digits routine.

I also added a section to the `FAQs` vignette.
