### ISSUE TITLE
emtrends estimates differ from model output when polynomial is added

### ISSUE THREAD

**Issue by dmfoster06** [rvlenth/emmeans#512]
First, thank you for fielding questions about emmeans. I've been down a rabbit hole for days trying to find an answer to my question with documentation, but I've not been successful. I'm hoping you can provide some insight if nothing more than spotting a gap in my knowledge about the package. 

## Problem Context
I'm building a mixed effects logistic regression model for a work project. The first model I tested (aka Model 1) was a random intercepts model with my outcome ('satisfied' with values 0,1) predicted by an interaction between a within-person continuous IV ('year' with values 1,2,3) and a between-person factor IV ('business_unit' with 6 levels, BU1 is baseline). See the model code below. For confidentiality purposes, variable names and R output will be modified, but the information is substantively the same as my original work. 

``` r
Model.1 <- glmer(satisfied~ year * business_unit + (1 | ID), family = binomial(), data = df, control = glmerControl(optimizer = "bobyqa"))
```

The fixed effect estimate for year in the model output summary is -0.13 (p < .05). When I run the model through emtrends to see the year trend by business unit, the year trend, standard error, z statistic, and p-value for BU1 is identical to the fixed effect for year in the model output, which is what I expected. See emtrends code below. 

``` r
m.lst <- emtrends(Model.1, "business_unit", var = "year")
m.summary <- summary(m.lst, infer = c(TRUE))
m.summary
```

The second model I tested (Model 2) was the same as Model 1, but I included a quadratic year term. 

``` r
Model.2 <- glmer(satisfied~ poly(year,2) * business_unit + (1 | ID), family = binomial(), data = df, control = glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000)))
```

The linear and quadratic fixed effect estimates for year were -8.3 and -8.4, respectively. I again wanted to see the year trend by business unit, but for both the linear and quadratic trends. I ran the emtrends code below. 

``` r
m.lst <- emtrends(Model.2, "business_unit", var = "year", max.degree=2)
m.summary <- summary(m.lst, infer = c(TRUE))
m.summary
```

This time, the linear and quadratic year trends for BU1 were -0.15 and -0.20, respectively. I'm not getting any additional notes i nthe m.summary output other than "Confidence level used: 0.95". These trend results (including their standard errors, z statistics, and p-values) were very different from the fixed effect estimates in the model summary. 

## The Question/ Problem
Is emtrends doing a different calculation than what is being done to produce the model output when polynomials are involved? If so, how can I get the emtrends results to match the model output for BU1?

Thank you!

**Comment by rvlenth** [comment]
The `poly()` function uses an orthogonal basis for polynomials, thus making the linear and quadratic effects independent (and also scaled differently). But `emtrends()` does not do that; it just estimates the raw linear and quadratic trends. So yes, it is doing a different calculation.

If you fit a different quadratic model using `poly(year, 2, raw = TRUE)`, you should get comparable results from `emtrends()`.

**Comment by dmfoster06** [comment]
Thank you for your quick response. When I fit a modified model (Model 3) using the code below, the raw linear and quadratic fixed effects for the year predictor are now .70 and -.20, respectively. 

``` r
Model.3 <- glmer(satisfied~ poly(year,2,raw=TRUE) * business_unit + (1 | ID), family = binomial(), data = df, control = glmerControl(optimizer="bobyqa", optCtrl = list(maxfun = 100000)))
```

I then pass Model.3 through emtrends: 

``` r
m.lst <- emtrends(Model.3, "business_unit", var = "year", max.degree=2)
m.summary <- summary(m.lst, infer = c(TRUE))
m.summary
```

The raw quadratic estimate from Model 3 (-.20) is now comparable to the quadratic year trend for BU1 produced by emtrends. However, the raw linear estimate from Model 3 (.70) is still quite different from the linear year trend for BU1 produced by emtrends (-.15). 

I don't know what emtrends is calculating for the linear year trend if it's not the raw or orthogonal linear estimate. Any idea what might be causing this discrepancy?

**Comment by rvlenth** [comment]
Here is a parallel example with one of **emmeans**'s data sets.
```
> mod = lm(conc ~ source * poly(percent, 2, raw = TRUE), data = pigs)
> emtrends(mod, "source", "percent", max.degree = 2, infer = c(TRUE, TRUE))
degree = linear:
 source percent.trend    SE df lower.CL upper.CL t.ratio p.value
 fish          0.8006 0.494 20   -0.231    1.832   1.619  0.1211
 soy           0.7972 0.479 20   -0.201    1.796   1.665  0.1114
 skim          2.6269 0.498 20    1.587    3.666   5.271  <.0001

degree = quadratic:
 source percent.trend    SE df lower.CL upper.CL t.ratio p.value
 fish         -0.1177 0.159 20   -0.449    0.214  -0.741  0.4675
 soy          -0.0609 0.172 20   -0.420    0.298  -0.354  0.7270
 skim          0.0230 0.175 20   -0.343    0.389   0.131  0.8970

Confidence level used: 0.95 
> summary(mod)$coef
                                            Estimate Std. Error     t value  Pr(>|t|)
(Intercept)                               1.04800000 28.8608298  0.03631219 0.9713934
sourcesoy                                17.59745455 40.2072752  0.43766842 0.6663167
sourceskim                               14.32747170 40.7364237  0.35171157 0.7287331
poly(percent, 2, raw = TRUE)1             3.84355556  4.3876950  0.87598514 0.3914380
poly(percent, 2, raw = TRUE)2            -0.11770370  0.1589091 -0.74069851 0.4674840
sourcesoy:poly(percent, 2, raw = TRUE)1  -1.47082828  6.2699950 -0.23458205 0.8169180
sourceskim:poly(percent, 2, raw = TRUE)1 -1.81106080  6.3497119 -0.28521937 0.7784088
sourcesoy:poly(percent, 2, raw = TRUE)2   0.05676094  0.2342505  0.24230871 0.8110084
sourceskim:poly(percent, 2, raw = TRUE)2  0.14069462  0.2366244  0.59459058 0.5587844
```
We do indeed see a difference between the linear treands for `source = soy`. However, we are dealing with curved trends, and so the linear component depends on where you are estimating it. For example with an upward-curving parabola, its left end is rapidly decreasing, its middle is flat, and its right end is rapidly increasing. If we do these estimates **at the origin**, then they agree with the coefficients:
```
> emtrends(mod, "source", "percent", max.degree = 2, infer = c(TRUE, TRUE), at = list(percent = 0))
degree = linear:
 source percent.trend    SE df lower.CL upper.CL t.ratio p.value
 fish          3.8446 4.389 20   -5.311   13.000   0.876  0.3915
 soy           2.3733 4.480 20   -6.973   11.719   0.530  0.6022
 skim          2.0323 4.591 20   -7.545   11.610   0.443  0.6628

degree = quadratic:
 source percent.trend    SE df lower.CL upper.CL t.ratio p.value
 fish         -0.1177 0.159 20   -0.449    0.214  -0.741  0.4675
 soy          -0.0609 0.172 20   -0.420    0.298  -0.354  0.7270
 skim          0.0230 0.175 20   -0.343    0.389   0.131  0.8970

Confidence level used: 0.95 
```

**Comment by dmfoster06** [comment]
The addition of the at option at the origin solved my issue. Thank you very much for your help!
