### ISSUE TITLE
Confidence interval on response for a zero-inflated Poisson glmmTMB

### ISSUE THREAD

**Issue by qdread** [rvlenth/emmeans#516]
Hi Russ, I apologize if this is a glmmTMB question and if so I can take this issue there. And as usual thanks for all your work on emmeans.

I see that emmeans for a zero-inflated Poisson model fit with glmmTMB now supports specifying `component = 'response'` to estimate the mean response: conditional mean * (1 - zi). My problem is that in certain circumstances I get a negative value for the confidence interval lower bound of this estimate. I am curious why this is happening, as my understanding is that conditional mean is back-transformed from the log scale and zi is back-transformed from the logit scale, so their product should always be >0. Do you have any insight as to why this is?

Here is an example with a subset of my data, that I think does not display any "pathological" behavior. It has a reasonably low proportion of zeros and the nonzero values are reasonably close to Poisson distributed. The emmeans for `component = 'cond'` and `component = 'zi'` are sensible and indicate the appropriate back transformations. But the confidence limit lower bounds for `component = 'response'` are negative. 

```
library(emmeans)
library(glmmTMB)

exampledata <- structure(list(study = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                  1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                  1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                                  2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
                                                  3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
                                                  3L), levels = c("1", "2", "3"), class = "factor"), 
                              genotype = structure(c(1L, 
                                                     1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L, 
                                                     3L, 1L, 1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L, 
                                                     2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L, 3L, 1L, 
                                                     1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L, 
                                                     3L, 1L, 1L, 2L, 2L, 3L, 3L), levels = c("a", "b", "c"), class = "factor"), 
                              eggs = c(100, 40, 22, 60, 0, 14, 1, 3, 13, 6, 8, 1, 0, 0, 
                                       6, 4, 0, 6, 10, 2, 0, 6, 7, 0, 2, 0, 21, 56, 0, 12, 2, 0, 
                                       34, 1, 2, 0, 1, 1, 59, 0, 11, 0, 4, 31, 17, 1, 0, 9, 3, 7, 
                                       1, 13, 0, 20, 101, 55, 0, 2, 65, 56, 1, 8, 16, 21, 8, 24, 
                                       25, 11, 24, 12, 6, 40)), row.names = c(NA, -72L), class = "data.frame")

examplefit <- glmmTMB(eggs ~ genotype + (genotype || study),
                      ziformula = ~ genotype + (genotype || study),
                      family = poisson(link = 'log'),
                      data = exampledata)

emmeans(examplefit, ~ genotype, component = 'cond', type = 'response')
emmeans(examplefit, ~ genotype, component = 'zi', type = 'response')
emmeans(examplefit, ~ genotype, component = 'response')
```

**Comment by rvlenth** [comment]
There are TWO components that are separately back-transformed, and the SE of the result is obtained via the delta method. So the CI is just based on the estimate plus or minus a multiple of the SE.

When CIs are obtained by back-transforming other CIs, that is noted in the annotations below the output.

On Oct 24, 2024, at 2:33 AM, Quentin Read ***@***.***> wrote:

﻿

Hi Russ, I apologize if this is a glmmTMB question and if so I can take this issue there. And as usual thanks for all your work on emmeans.

I see that emmeans for a zero-inflated Poisson model fit with glmmTMB now supports specifying component = 'response' to estimate the mean response: conditional mean * (1 - zi). My problem is that in certain circumstances I get a negative value for the confidence interval lower bound of this estimate. I am curious why this is happening, as my understanding is that conditional mean is back-transformed from the log scale and zi is back-transformed from the logit scale, so their product should always be >0. Do you have any insight as to why this is?

Here is an example with a subset of my data, that I think does not display any "pathological" behavior. It has a reasonably low proportion of zeros and the nonzero values are reasonably close to Poisson distributed. The emmeans for component = 'cond' and component = 'zi' are sensible and indicate the appropriate back transformations. But the confidence limit lower bounds for component = 'response' are negative.

library(emmeans)
library(glmmTMB)

exampledata <- structure(list(study = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L,
                                                  1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,
                                                  1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L,
                                                  2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 3L, 3L,
                                                  3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L,
                                                  3L), levels = c("1", "2", "3"), class = "factor"),
                              genotype = structure(c(1L,
                                                     1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L,
                                                     3L, 1L, 1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L,
                                                     2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L, 3L, 1L,
                                                     1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L, 3L, 1L, 1L, 2L, 2L, 3L,
                                                     3L, 1L, 1L, 2L, 2L, 3L, 3L), levels = c("a", "b", "c"), class = "factor"),
                              eggs = c(100, 40, 22, 60, 0, 14, 1, 3, 13, 6, 8, 1, 0, 0,
                                       6, 4, 0, 6, 10, 2, 0, 6, 7, 0, 2, 0, 21, 56, 0, 12, 2, 0,
                                       34, 1, 2, 0, 1, 1, 59, 0, 11, 0, 4, 31, 17, 1, 0, 9, 3, 7,
                                       1, 13, 0, 20, 101, 55, 0, 2, 65, 56, 1, 8, 16, 21, 8, 24,
                                       25, 11, 24, 12, 6, 40)), row.names = c(NA, -72L), class = "data.frame")

examplefit <- glmmTMB(eggs ~ genotype + (genotype || study),
                      ziformula = ~ genotype + (genotype || study),
                      family = poisson(link = 'log'),
                      data = exampledata)

emmeans(examplefit, ~ genotype, component = 'cond', type = 'response')
emmeans(examplefit, ~ genotype, component = 'zi', type = 'response')
emmeans(examplefit, ~ genotype, component = 'response')

**Comment by qdread** [comment]
Thank you Russ. Do you have any other recommendations other than the delta method for finding a defensible 95% CI of the means, that has better properties? Otherwise I will just switch to Bayesian estimation, but I am trying to avoid that because I am doing this for a client who is not familiar with Bayes.

**Comment by rvlenth** [comment]
No suggestions, sorry.

On Oct 24, 2024, at 8:33 AM, Quentin Read ***@***.***> wrote:

﻿

Thank you Russ. Do you have any other recommendations other than the delta method for finding a defensible 95% CI of the means, that has better properties? Otherwise I will just switch to Bayesian estimation, but I am trying to avoid that because I am doing this for a client who is not familiar with Bayes.

**Comment by qdread** [comment]
No need to apologize, thanks for the insight about the delta method!
