### ISSUE TITLE
t tests become z tests on shinyapps.io

### ISSUE THREAD

**Issue by AnovaF** [rvlenth/emmeans#53]
Dear prof.Lenth,

When I run the following Shiny app on my Windows computer it uses t-test in the emmeans paired comparisons. The calculated P-values are in agreement with the results from the Mixed Model with Paired comparison in SAS/JMP Pro 13 EN.
However when I publish this Shiny app on shinyapps.io the paired comparisons use the z-test. See https://gmwebapplications.shinyapps.io/InvestigatePvalue/
Would it be possible to use the t-test on the shinyapps.io ?
Thanks for your attention, Gerben

`# Investigate difference in calculated P-values between Windows and shinyapps.io

suppressWarnings(suppressMessages(library(shiny)))
suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(lme4)))
suppressWarnings(suppressMessages(library(emmeans)))

ui <- fluidPage(
  
  tags$hr(),
  
  sidebarLayout(
    
    sidebarPanel(),
    
    mainPanel(
      verbatimTextOutput("lme4Results"),
      tags$hr(),
      verbatimTextOutput("emmeansResults")
    )
  )
)

server <- function(input, output) {

  ## Build dataset -----------------------------------------------------------
  
  FI <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,1,0,0,0,0,0,0,1,2,0,0,0,0,-1,0,1,3,2,-1,-2,1,1,0,0,1,0,0,-1,3,1,0,0,0,0,1,1,0,1)
  Assessor <- c("am","am","an","an","ca","ca","ch","ch","gr","gr","kl","kl","na","na","ro","ro","sa","sa","st","st","am","am","an","an","ca","ca","ch","ch","gr","gr","kl","kl","na","na","ro","ro","sa","sa","st","st","am","am","an","an","ca","ca","ch","ch","gr","gr","kl","kl","na","na","ro","ro","sa","sa","st","st")
  Product <- rep(c("1=Ref","2=Alt","3=Alt2"), each = 20)
  dt <- tibble(Product,Assessor,FI)
  
  # Calculations ------------------------------------------------------------
  
  # Mixed model with Product and Assessor -----------------------------------
  MixedModel <- 
    lmer(FI ~ Product + (1| Assessor) + (1| Product:Assessor), data = dt)
  output$lme4Results <- renderPrint(summary(MixedModel))
  # Paired comparison with Dunnett correction using emmeans
  MixedModel.emm <- emmeans(MixedModel,"Product")
  ConfIntTbl <- as.data.frame(MixedModel.emm)
  MixedModel.emm.Dunnett <- contrast(MixedModel.emm, "trt.vs.ctrl", ref = 1)
  output$emmeansResults <- renderPrint(summary(MixedModel.emm.Dunnett))
  }

shinyApp(ui, server)
`
Result in Windows:

`contrast       estimate        SE df t.ratio p.value
 2=Alt - 1=Ref       0.6 0.3333333 18     1.8  0.1594
 3=Alt2 - 1=Ref      0.3 0.3333333 18     0.9  0.5807

P value adjustment: dunnettx method for 2 tests `

Result in shinyapps.io:

`contrast       estimate        SE  df z.ratio p.value
 2=Alt - 1=Ref       0.6 0.3333333 Inf     1.8  0.1318
 3=Alt2 - 1=Ref      0.3 0.3333333 Inf     0.9  0.5683

P value adjustment: dunnettx method for 2 tests `

**Comment by rvlenth** [comment]
I suspect this happens because the **pbkrtest** package is not installed on the `shinyapps.io system`. If you can get them to install it, then `emmeans()` will make use of it. 

An alternative is to do `emm_options(lmer.df = "satterth")` after the package is loaded; then the Satterthwaite method is used for d.f. -- provided that **lmerTest** is installed on that system.

See `vignette("models")`, section L, for more details.

**Comment by AnovaF** [comment]
Thanks very much for your answer. This solves the problem. 
The problem is solved by adding
**library(pbkrtest )** 
to the list of library's at the start of my program. Then the result on shinyapp.io becomes equal to the windows results, see
https://gmwebapplications.shinyapps.io/InvestigatePvalue/
