### ISSUE TITLE
plot.emmGrid

### ISSUE THREAD

**Issue by nlpaces** [rvlenth/emmeans#58]
I have a stan_lm model.

I created a ref_grid:

> str(StandardizedOME.stan_lm.1.emmGrid)
'emmGrid' object with variables:
    c.Age = -0.015501
    c.AnesthesiaDuration = 1.1255
    AnesthesiaTechniqueBlock = No, Yes
    AnesthesiaTechniqueGeneral = Yes, No
    AnesthesiaTechniqueNeuraxial = No, Yes
    o.ASAClass = 1, 2, 3, 4
    EmergencyStatusYN = No, Yes
    Race = White, Unknown, AsiaPac, Multi, Black, HispW, AmerInd, MidEast, HispB
    Sex = Male, Female
    REMI = No, Yes
    NonOpioidAnalgesicsCount = 1.2984
    o.AIM1Year = 2012, 2013, 2014, 2015, 2016
    CPTBucket = Chest, Other, Abdomen, Extremity, UroGyn, HeadNeck, Spine, XRay
    MPOGInstitutionID = 9360, 9355, 9326, 9334, 9356, 9330, 9340, 9354, 9357, 9331
Transformation: “log” 

Next I created a emmeans object.

> str(Race.emmGrid)
'emmGrid' object with variables:
    Race = White, Unknown, AsiaPac, Multi, Black, HispW, AmerInd, MidEast, HispB
Transformation: “log” 

Next I created a summary_emmeans object.

> str(Race.summary_emmeans)
Classes ‘summary_emm’ and 'data.frame':	9 obs. of  4 variables:
 $ Race     : Factor w/ 9 levels "White","Unknown",..: 1 2 3 4 5 6 7 8 9
 $ response : num  422 425 456 445 398 ...
 $ lower.HPD: num  420 422 452 436 395 ...
 $ upper.HPD: num  424 427 460 455 401 ...
 - attr(*, "estName")= chr "emmean"
 - attr(*, "clNames")= chr  "lower.HPD" "upper.HPD"
 - attr(*, "pri.vars")= chr "Race"
 - attr(*, "mesg")= chr  "Results are back-transformed from the log scale" "HPD interval probability: 0.95"

I get an error message when plotting.

plot(Race.summary_emmeans)
Error in FUN(X[[i]], ...) : object 'the.emmean' not found

I get the same error message when plotting the emmgrid object.

plot(Race.emmGrid, intervals = T, type = 'response')
Error in FUN(X[[i]], ...) : object 'the.emmean' not found

I don't know what to do.

Nathan

**Comment by nlpaces** [comment]
Thanks for the quick reply.

For the moment I’ll use frequentist methods for plot.

I have noticed something else.

Summary(grid mcmc object, level = 0.9) does not change the HPD. It is always reported 0.95.

Expected result?

Nathan

**Comment by nlpaces** [comment]
I just discovered hpd.summary.

Delete my last question.

Nathan

**Comment by rvlenth** [comment]
You also noted by e-mail that `summary(..., level = ...)` creates 95% HPD intervals regardless of `level`. I consider this a bug as well, because `summary()` should invoke `hpd.summary()` consistently.

I fixed two errors:

  1. An error in `hpd.summary()` whereby an attribute is incorrectly set when there is a back 
      transformation. This is what caused the error in `plot(..., type = "response")` 
  2. An omission in `summary()`. When there is a Bayesian reference grid and `frequentist` is `FALSE`,
    it now passes the value of `level` as the `prob` argument in `hpd.summary()`.

**Comment by rvlenth** [comment]
Test code:

```
example(hpd.summary)
## ... output suppressed ...
emm = emmeans(cbpp.rg, "period")

summary(emm, level = .90)
# period    emmean lower.HPD  upper.HPD
# 1      -1.430451 -1.857119 -0.9530337
# 2      -2.394991 -2.896885 -1.8428527
# 3      -2.515846 -3.012423 -1.9085993
# 4      -2.967635 -3.828616 -2.2711029
#
# Results are given on the logit (not the response) scale. 
# HPD interval probability: 0.9 

summary(emm, level = .90, type = "response")
# period       prob  lower.HPD upper.HPD
# 1      0.19302852 0.12319583 0.2647904
# 2      0.08355542 0.05177301 0.1359956
# 3      0.07475475 0.03845347 0.1171591
# 4      0.04890967 0.01623193 0.0847095
#
# Results are back-transformed from the logit scale 
# HPD interval probability: 0.9 

plot(emm, level = .90, type = "response")
# (Does not throw an error)
```

**Comment by nlpaces** [comment]
Thanks for attending to these matters.

I am running my analyses on a server (Windows 2016 Server).

I use RStudio Version 1.1.453.

I run R 3.5.1.

I do not have system privileges.

Packages I install must be in a custom directory:

‘C:/Users/leonpace/Documents/R_libs’

I am unable to install the patched version.

I first attempted to install Rtools as recommended:
Warning in install.packages :
  package ‘Rtools’ is not available (for R version 3.5.1)

I attempted to install the patch:

devtools::install_github("rvlenth/emmeans", dependencies = TRUE,
+                          build_vignettes = TRUE)
Error in loadNamespace(name) : there is no package called ‘devtools’

I then successfully installed devtools and dependencies.

I attempted to install the patch again:

> devtools::install_github("rvlenth/emmeans", dependencies = TRUE,
+                          build_vignettes = TRUE)
Downloading GitHub repo rvlenth/emmeans@master
Installing 17 packages: biglm, car, carData, lpSolve, maptools, MatrixModels, mediation, openxlsx, ordinal, pbkrtest, quantreg, rio, rsm, sp, SparseM, ucminf, zip
Installing packages into ‘C:/Users/leonpace/Documents/R_libs’
(as ‘lib’ is unspecified)
Error: (converted from warning) unable to access index for repository http://glmmadmb.r-forge.r-project.org/repos/bin/windows/contrib/3.5:
  cannot open URL 'http://glmmadmb.r-forge.r-project.org/repos/bin/windows/contrib/3.5/PACKAGES'
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

I can’t debug this problem.

Nathan

**Comment by nlpaces** [comment]
Thanks for attending to these matters.

I am running my analyses on a server (Windows 2016 Server).

I use RStudio Version 1.1.453.

I run R 3.5.1.

I do not have system privileges.

Packages I install must be in a custom directory:

‘C:/Users/leonpace/Documents/R_libs’

I am unable to install the patched version.

I first attempted to install Rtools as recommended:
Warning in install.packages :
  package ‘Rtools’ is not available (for R version 3.5.1)

I attempted to install the patch:

devtools::install_github("rvlenth/emmeans", dependencies = TRUE,
+                          build_vignettes = TRUE)
Error in loadNamespace(name) : there is no package called ‘devtools’

I then successfully installed devtools and dependencies.

I attempted to install the patch again:

> devtools::install_github("rvlenth/emmeans", dependencies = TRUE,
+                          build_vignettes = TRUE)
Downloading GitHub repo rvlenth/emmeans@master
Installing 17 packages: biglm, car, carData, lpSolve, maptools, MatrixModels, mediation, openxlsx, ordinal, pbkrtest, quantreg, rio, rsm, sp, SparseM, ucminf, zip
Installing packages into ‘C:/Users/leonpace/Documents/R_libs’
(as ‘lib’ is unspecified)
Error: (converted from warning) unable to access index for repository http://glmmadmb.r-forge.r-project.org/repos/bin/windows/contrib/3.5:
  cannot open URL 'http://glmmadmb.r-forge.r-project.org/repos/bin/windows/contrib/3.5/PACKAGES'
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

I can’t debug this problem.

Nathan

**Comment by rvlenth** [comment]
Please send an e-mail directly to my regular e-mail address -- russell-lenth AT uiowa.edu -- and I will send you a pre-built version that you can just install. via the tools menu.

**Comment by rvlenth** [comment]
I think this is now resolved, so am closing.

**Comment by nlpaces** [comment]
Thanks for the rapid response to the problem I posted.

I am using the next version of emmeans that you updated on CRAN.

On CrossValidated there are some to and fro statements about emmeans.

One poster appears to liken it to TYPE III means in an unfavorable fashion.

I have read the paper by Searle.

Can you suggest others?

Nathan

**Comment by nlpaces** [comment]
Yes, those threads are referenced.

I appreciate reading your comments.

I am doing a Bayesian linear model (stan_lm) with no interactions.

So even the joint_tests function should not be relevant.



Nathan

**Comment by rvlenth** [comment]
Right; the `joint_tests()` function has no relevance *per se* with a Bayesian model. But I want to make sure you understand that using Bayesian models does not exempt you from some related concerns:

  1. It is still a "type III"-style inference to obtain marginal posterior EMMs for main effects if they are involved in interactions in the underlying model.
  2. If an interaction is *needed* but absent in the model, that is a mistake whether it is a Bayesian model or not.

**Comment by nlpaces** [comment]
Thanks for these pointers.

My model has no interactions. Perhaps it should, but I don’t have sufficient CPU or RAM to attempt it.

My model is run in stan_lm using a R2 prior to provide some mild regularization:

stan_lm
family:       gaussian [identity]
formula:      log(StandardizedOME) ~ Age + AnesthesiaDuration + AnesthesiaTechniqueBlock +
      AnesthesiaTechniqueGeneral + AnesthesiaTechniqueNeuraxial +
      o.ASAClass + EmergencyStatusYN + t.Race + Sex + REMI + o.NonOpioidAnalgesicsCount +
      o.AIM1Year + CPTBucket + MPOGInstitutionID
observations: 1104358
predictors:   37

There are two covariates and 12 factor predictors.

This is messy, unbalanced observational data.

stan_lm runs relatively quickly and the model object is 1 Gb.

I create the ref_grid object using the at argument to set four points for each covariate ( 4 by 4 grid).

It takes 5+ hours to create the ref_grid object; the ref_grid object is 10.4 Gb.

I am hoping to get more resources on the stats server.

I have a question about explaining an EMM.

In a vignette: “Estimated marginal means (EMMs) are defined as equally weighted means of these predictions at specified margins…”

Is it correct to state: “EMMs predict the means at factor levels and covariate points as if the data was balanced across factors and covariates.”

Is this the distinction that Searle makes in the 1980 article in defining equations 2.2 (PMM) and 2.3 (expectation of the observed row mean)?

Nathan

**Comment by rvlenth** [comment]
On your question, I think you have it about  right.

You might try some frequentist models (perhaps on random subsets of the data) as a device for deciding which terms you may need and which interactions should be added. With N that large, virtually anything is “significant” so use plots and subject-matter knowledge to decide whether observed effects are important.

Russ

Sent from my iPhone

On Jan 4, 2019, at 12:43 AM, nlpaces <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for these pointers.

My model has no interactions. Perhaps it should, but I don’t have sufficient CPU or RAM to attempt it.

My model is run in stan_lm using a R2 prior to provide some mild regularization:

stan_lm
family: gaussian [identity]
formula: log(StandardizedOME) ~ Age + AnesthesiaDuration + AnesthesiaTechniqueBlock +
AnesthesiaTechniqueGeneral + AnesthesiaTechniqueNeuraxial +
o.ASAClass + EmergencyStatusYN + t.Race + Sex + REMI + o.NonOpioidAnalgesicsCount +
o.AIM1Year + CPTBucket + MPOGInstitutionID
observations: 1104358
predictors: 37

There are two covariates and 12 factor predictors.

This is messy, unbalanced observational data.

stan_lm runs relatively quickly and the model object is 1 Gb.

I create the ref_grid object using the at argument to set four points for each covariate ( 4 by 4 grid).

It takes 5+ hours to create the ref_grid object; the ref_grid object is 10.4 Gb.

I am hoping to get more resources on the stats server.

I have a question about explaining an EMM.

In a vignette: “Estimated marginal means (EMMs) are defined as equally weighted means of these predictions at specified margins…”

Is it correct to state: “EMMs predict the means at factor levels and covariate points as if the data was balanced across factors and covariates.”

Is this the distinction that Searle makes in the 1980 article in defining equations 2.2 (PMM) and 2.3 (expectation of the observed row mean)?

Nathan
