### ISSUE TITLE
mult.levs= factors not passed to ref_grid() output

### ISSUE THREAD

**Issue by TDJorgensen** [rvlenth/emmeans#59]
Hello,

This is related to issue [#6](https://github.com/rvlenth/emmeans/issues/6), but the error does not occur until you try to extract EM means because the `mult.levs=` factors do not appear in the `ref_grid()` output.  Adapted from the `?ref_grid` help page:
```
MOats.lm <- lm(yield ~ 1, data = MOats)
foo <- ref_grid(MOats.lm, mult.levs = list(T=LETTERS[1:2], U=letters[1:2]))
as.data.frame(foo) # no columns for T or U
emmeans(foo, specs =~T*U) # error
```
Thanks for a great package. It very much simplifies teaching.
Terrence

**Comment by rvlenth** [comment]
Terrence,

Thanks for the report. I'd swear I checked this fairly recently and it worked. But in fact with version 1.3.0, `example(ref_grid)`, the last call does not generate levels for the multivariate response either.  What's even worse, `example(ref_grid)` errors out in my current development version. Very mysterious -- I will look into it.

Russ

**Comment by rvlenth** [comment]
For reason, some brackets got into the code somewhere along the line whereby `mult.levs` was completely ignored. It's fixed in latest commit, along with the other error I mentioned.
```
> MOats.lm1 <- lm(yield ~ 1, data = MOats)
> ref_grid(MOats.lm1, mult.levs = list(T=LETTERS[1:2], U=letters[1:2]))
'emmGrid' object with variables:
    1 = 1
    T = multivariate response levels: A, B
    U = multivariate response levels: a, b
```

**Comment by TDJorgensen** [comment]
> the last call does not generate levels for the multivariate response either

Oh yeah, I thought it was strange that the levels did not show up in the `print` method, but at least the variable was in the grid so that `emmeans(..., specs = ~ rep.meas)` would work.

Thanks for the quick fix, it works!
