### ISSUE TITLE
CLD support for brms

### ISSUE THREAD

**Issue by liamkendall** [rvlenth/emmeans#60]
Hi there,

I was wondering if you would be possible for emmeans to provide support of `CLD` to `brmsfit` objects i.e. different letters due to non-overlapping HPDs of a given alpha?

 At present, I get the following error when I attempt to use `CLD`:

`em_1=emmeans(m1, ~ A | B, transform ="response",
                    level = .95, type = "response")

`cld(em_1)`
`Error in if (k2 == 0) { : missing value where TRUE/FALSE needed`

Any help would be much appreciated

**Comment by rvlenth** [comment]
To tell the truth, I never bothered to do this because I didn't think Bayesians would ever want this type of analysis. I will consider (but not promise) adding some sort of support,

You can trick `CLD` into working by removing the posterior sample, thus making it appear to be a frequentist object. Here's an example:
```
> library(emmeans)
> example(hpd.summary)
# ... (some output not shown) ...
> emm = emmeans(cbpp.rg, "period")
> CLD(emm)
Error in if (k2 == 0) { : missing value where TRUE/FALSE needed
```
... which is the error you saw. Now make a copy and remove the posterior sample:
```
> emmf = emm
> emmf@post.beta = matrix(NA)
> CLD(emmf)
 period    emmean        SE df asymp.LCL asymp.UCL .group
 4      -2.985176 0.4633889 NA -3.893402 -2.076951  1    
 3      -2.514019 0.3408710 NA -3.182114 -1.845924  1    
 2      -2.405356 0.3373780 NA -3.066605 -1.744108  1    
 1      -1.450956 0.2825317 NA -2.004708 -0.897204   2   
```
Results are given on the logit (not the response) scale. 
Confidence level used: 0.95 
Results are given on the log odds ratio (not the response) scale. 
P value adjustment: tukey method for comparing a family of 4 estimates 
significance level used: alpha = 0.05
```
This does not use HPD intervals, however; it uses a frequentist analysis; see `?summary.emmGrid` and the `frequentist` option.

**Comment by rvlenth** [comment]
Ah -- My workaround was more elaborate than needed. Just do:
```
> CLD(emm, freq = TRUE)
 period    emmean        SE df asymp.LCL asymp.UCL .group
 4      -2.985176 0.4633889 NA -3.893402 -2.076951  1    
 3      -2.514019 0.3408710 NA -3.182114 -1.845924  1    
 2      -2.405356 0.3373780 NA -3.066605 -1.744108  1    
 1      -1.450956 0.2825317 NA -2.004708 -0.897204   2   
```
as the `frequentist` argument is passed to `summary()`

**Comment by rvlenth** [comment]
I decided to support `CLD` for Bayesian models. However, I still maintain that CLD groupings is a frequentist concept; moreover, trying to use HPD tails for differences creates a whole new set of issues, such as what to do about options such as multiplicity adjustments. For those reasons, I believe it suffices to base the CLD display on the frequentist summary of the object and tests of its pairwise differences. A message is issued that says so.

From my perspective, the best justification for making this change is that it avoids an unhelpful error message.

If I hear from more users who are comfortable with displaying groupings based on Bayesian inferences, I will reconsider what to do, and also am open to advice on what approach[es] are acceptable from a Bayesian point of view. 

Thanks, Liam, for raising this issue. I will close it for now but it can always be reopened.
