### ISSUE TITLE
Error in temporary data.frame

### ISSUE THREAD

**Issue by wep69** [rvlenth/emmeans#69]
Dear maintainers of emmeans,

With the emmeans 1.30, or less, the following script run without problem: 

dados<-data.frame(
  Ciclo = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
            2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
            2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
            2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
            2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
            2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
            2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
            2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2),
  Periodo = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
              1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
              1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
              2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
              2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
              3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
              3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1,
              1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
              1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
              1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
              2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
              2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3,
              3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
              3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3),
  Bloco = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
            2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
            2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
            3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
            2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4,
            4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
            2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
            4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
            3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4),
  Trat = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9,
           10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4,
           5, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
           1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7,
           8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 2, 3,
           4, 5, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
           11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4, 5, 6,
           7, 8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1,
           2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9,
           10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4,
           5, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
           1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7,
           8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 2, 3,
           4, 5, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
           11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11),
  N = c(90, 90, 210, 210, 150, 15, 285, 90, 210, 15, 0, 90, 90, 210,
        210, 150, 15, 285, 90, 210, 15, 0, 90, 90, 210, 210,
        150, 15, 285, 90, 210, 15, 0, 90, 90, 210, 210, 150, 15,
        285, 90, 210, 15, 0, 90, 90, 210, 210, 150, 15, 285, 90,
        210, 15, 0, 90, 90, 210, 210, 150, 15, 285, 90, 210, 15, 0,
        90, 90, 210, 210, 150, 15, 285, 90, 210, 15, 0, 90, 90,
        210, 210, 150, 15, 285, 90, 210, 15, 0, 90, 90, 210, 210,
        150, 15, 285, 90, 210, 15, 0, 90, 90, 210, 210, 150, 15,
        285, 90, 210, 15, 0, 90, 90, 210, 210, 150, 15, 285, 90,
        210, 15, 0, 90, 90, 210, 210, 150, 15, 285, 90, 210, 15,
        0, 90, 90, 210, 210, 150, 15, 285, 90, 210, 15, 0, 90,
        90, 210, 210, 150, 15, 285, 90, 210, 15, 0, 90, 90, 210,
        210, 150, 15, 285, 90, 210, 15, 0, 90, 90, 210, 210, 150,
        15, 285, 90, 210, 15, 0, 90, 90, 210, 210, 150, 15, 285,
        90, 210, 15, 0, 90, 90, 210, 210, 150, 15, 285, 90, 210,
        15, 0, 90, 90, 210, 210, 150, 15, 285, 90, 210, 15, 0,
        90, 90, 210, 210, 150, 15, 285, 90, 210, 15, 0, 90, 90,
        210, 210, 150, 15, 285, 90, 210, 15, 0, 90, 90, 210, 210,
        150, 15, 285, 90, 210, 15, 0, 90, 90, 210, 210, 150, 15,
        285, 90, 210, 15, 0, 90, 90, 210, 210, 150, 15, 285, 90,
        210, 15, 0),
  K = c(144, 336, 144, 336, 240, 144, 336, 24, 456, 24, 0, 144, 336,
        144, 336, 240, 144, 336, 24, 456, 24, 0, 144, 336, 144,
        336, 240, 144, 336, 24, 456, 24, 0, 144, 336, 144, 336,
        240, 144, 336, 24, 456, 24, 0, 144, 336, 144, 336, 240,
        144, 336, 24, 456, 24, 0, 144, 336, 144, 336, 240, 144,
        336, 24, 456, 24, 0, 144, 336, 144, 336, 240, 144, 336, 24,
        456, 24, 0, 144, 336, 144, 336, 240, 144, 336, 24, 456,
        24, 0, 144, 336, 144, 336, 240, 144, 336, 24, 456, 24, 0,
        144, 336, 144, 336, 240, 144, 336, 24, 456, 24, 0, 144,
        336, 144, 336, 240, 144, 336, 24, 456, 24, 0, 144, 336,
        144, 336, 240, 144, 336, 24, 456, 24, 0, 144, 336, 144,
        336, 240, 144, 336, 24, 456, 24, 0, 144, 336, 144, 336,
        240, 144, 336, 24, 456, 24, 0, 144, 336, 144, 336, 240, 144,
        336, 24, 456, 24, 0, 144, 336, 144, 336, 240, 144, 336,
        24, 456, 24, 0, 144, 336, 144, 336, 240, 144, 336, 24,
        456, 24, 0, 144, 336, 144, 336, 240, 144, 336, 24, 456, 24,
        0, 144, 336, 144, 336, 240, 144, 336, 24, 456, 24, 0,
        144, 336, 144, 336, 240, 144, 336, 24, 456, 24, 0, 144,
        336, 144, 336, 240, 144, 336, 24, 456, 24, 0, 144, 336, 144,
        336, 240, 144, 336, 24, 456, 24, 0, 144, 336, 144, 336,
        240, 144, 336, 24, 456, 24, 0, 144, 336, 144, 336, 240,
        144, 336, 24, 456, 24, 0),
  TCAAP = c(1.7, 1.7, 1.64, 2.13, 1.7, 1.7, 1.21, 1.29, 1.83, 0.87, 1.42,
            2.2, 1.27, 1.65, 2.05, 2, 1.2, 1.35, 1.58, 2.03, 1.34,
            1.03, 1.22, 1.55, 1.18, 1.57, 1.17, 1.53, 1.07, 1.79,
            1.36, 1.43, 0.91, 1.21, 1.05, 0.95, 1.71, 2.01, 1.47, 1.28,
            2.05, 2.2, 0.97, 1.12, 1.47, 1.62, 1.67, 1.53, 1.51,
            1.48, 1.37, 1.56, 1.64, 1.15, 1.4, 1.69, 2.07, 1.64, 1.83,
            1.82, 1.59, 1.65, 1.68, 1.57, 1.77, 1.18, 1.57, 1.61, 1.6,
            1.66, 1.68, 1.74, 1.66, 1.59, 1.26, 1.63, 1.03, 1.73,
            1.74, 1.6, 1.71, 1.72, 1.59, 1.64, 1.68, 1.78, 1.16, 1.21,
            0.89, 1.07, 1.03, 1.05, 0.92, 1.07, 1.12, 1.17, 1.13,
            0.92, 1.07, 1.39, 1.05, 1.1, 1.15, 0.74, 1.95, 1.22, 1.17,
            1.04, 0.96, 1.11, 1.7, 0.73, 1.2, 1.1, 1.07, 1.12, 1.22,
            1.23, 1.65, 1.01, 1.03, 1.14, 1.02, 1.09, 0.89, 1.05, 0.93,
            1.09, 0.91, 1.26, 0.87, 1.07, 1.27, 1.42, 1.19, 1.45,
            1.45, 1.24, 1.25, 1.37, 1.17, 1.56, 1.36, 1.32, 1.6, 1.45,
            1.54, 1.4, 2.39, 1.32, 1.34, 1.27, 1.3, 1.31, 1.11, 1.35,
            0.85, 1.48, 1.32, 1.08, 1.5, 1.25, 1.35, 1.46, 1.25,
            1.17, 1.18, 1.65, 1.3, 1.22, 1.61, 1.15, 1.34, 1.19, 1.27,
            1.3, 1.3, 1.53, 1.2, 0.85, 1.35, 1.2, 1.52, 1.02, 1.27,
            0.51, 1.18, 1.56, 1.52, 1.42, 1.67, 1.52, 1.2, 1.44, 1.45,
            1.49, 1.16, 1.08, 1.48, 1.76, 2.3, 1.41, 1.54, 1.44,
            1.42, 1.33, 1.22, 1.3, 0.95, 1.54, 1.41, 0.8, 1.76, 1.63,
            1.46, 1.61, 1.24, 1.59, 0.92, 1.07, 0.82, 1.06, 1.09, 2.01,
            0.75, 0.85, 1.06, 0.71, 2.58, 0.58, 0.62, 0.88, 1.01,
            1.03, 1.06, 1.06, 1.23, 1.23, 1.11, 0.5, 0.8, 0.87, 1.2,
            0.94, 1.13, 1.31, 0.88, 1.23, 1.38, 1.11, 1.84, 0.61, 0.69,
            0.92, 1.17, 0.71, 1.03, 1.1, 0.62, 1.5, 0.94, 1.62, 0.7,
            0.72),
  TCADPS = c(0.14, 0.14, 0.13, 0.16, 0.13, 0.12, 0.1, 0.11, 0.16, 0.08,
             0.11, 0.16, 0.12, 0.12, 0.14, 0.15, 0.07, 0.11, 0.12,
             0.15, 0.11, 0.08, 0.1, 0.12, 0.09, 0.12, 0.1, 0.12, 0.08,
             0.14, 0.12, 0.11, 0.08, 0.09, 0.09, 0.07, 0.13, 0.14,
             0.12, 0.12, 0.16, 0.17, 0.08, 0.09, 0.1, 0.1, 0.11, 0.09,
             0.11, 0.09, 0.11, 0.12, 0.1, 0.1, 0.1, 0.08, 0.12, 0.13,
             0.13, 0.11, 0.1, 0.11, 0.11, 0.11, 0.09, 0.09, 0.11, 0.1,
             0.12, 0.11, 0.13, 0.11, 0.12, 0.09, 0.12, 0.11, 0.09,
             0.13, 0.11, 0.13, 0.11, 0.11, 0.11, 0.1, 0.07, 0.11, 0.1,
             0.09, 0.04, 0.05, 0.03, 0.05, 0.02, 0.08, 0.05, 0.03, 0.08,
             0.05, 0.02, 0.07, 0.04, 0.01, 0.05, 0.03, 0.07, 0.05,
             0.05, 0.02, 0.05, 0.05, 0.04, 0.06, 0.03, 0.06, 0.05, 0.02,
             0.04, 0.05, 0.02, 0.04, 0.05, 0.03, 0.04, 0.04, 0.06,
             0.03, 0.02, 0.05, 0.07, 0.04, 0.04, 0.04, 0.119, 0.121,
             0.125, 0.115, 0.152, 0.095, 0.124, 0.112, 0.127, 0.137,
             0.133, 0.154, 0.134, 0.123, 0.135, 0.121, 0.193, 0.133, 0.099,
             0.13, 0.115, 0.125, 0.127, 0.115, 0.121, 0.155, 0.123,
             0.115, 0.124, 0.115, 0.111, 0.128, 0.15, 0.137, 0.113,
             0.125, 0.117, 0.135, 0.219, 0.11, 0.131, 0.13, 0.12, 0.136,
             0.086, 0.125, 0.022, 0.106, 0.063, 0.115, 0.076, 0.097,
             0.084, 0.057, 0.096, 0.08, 0.116, 0.094, 0.11, 0.088,
             0.079, 0.062, 0.061, 0.081, 0.065, 0.072, 0.104, 0.157,
             0.102, 0.093, 0.094, 0.102, 0.127, 0.095, 0.089, 0.107, 0.045,
             0.091, 0.117, 0.08, 0.129, 0.123, 0.122, 0.081, 0.076,
             0.112, 0.084, 0.071, 0.013, 0.016, 0.039, 0, 0.006, 0.011,
             0.033, 0.001, 0.053, 0.008, 0.015, 0.011, 0.03, 0.004,
             0.01, 0.025, 0.036, 0.023, 0.025, 0.011, 0, 0.017, 0,
             0.007, 0.024, 0.009, 0.019, 0.015, 0.009, 0.013, 0.069, 0,
             0.016, 0.007, 0, 0, 0.001, 0.002, 0.015, 0, 0.007, 0,
             0.032, 0.0161),
  TCRAP = c(0.0107, 0.0115, 0.0117, 0.0127, 0.011, 0.0108, 0.0089, 0.0107,
            0.0115, 0.0085, 0.0103, 0.0121, 0.0111, 0.0114, 0.0138,
            0.0113, 0.0089, 0.0116, 0.0119, 0.0116, 0.0095, 0.0078,
            0.0095, 0.0087, 0.0091, 0.0118, 0.0101, 0.0105, 0.0123,
            0.0115, 0.0106, 0.0122, 0.007, 0.0098, 0.0085, 0.0079,
            0.0096, 0.0107, 0.0082, 0.0099, 0.0112, 0.0115, 0.0061,
            0.0084, 0.0058, 0.0063, 0.0065, 0.0054, 0.0059, 0.0058,
            0.0062, 0.0068, 0.0062, 0.006, 0.006, 0.0058, 0.0085, 0.0064,
            0.0064, 0.0065, 0.0071, 0.007, 0.0066, 0.0057, 0.0074,
            0.0058, 0.0069, 0.0065, 0.0071, 0.0067, 0.0075, 0.007,
            0.0076, 0.0061, 0.0056, 0.0068, 0.0053, 0.0075, 0.008,
            0.0077, 0.0066, 0.0061, 0.0066, 0.0071, 0.006, 0.0061, 0.0058,
            0.0057, 0.003, 0.0035, 0.0034, 0.0033, 0.003, 0.0035,
            0.004, 0.0039, 0.0037, 0.0035, 0.0036, 0.0044, 0.0034,
            0.0036, 0.0035, 0.0023, 0.0063, 0.0041, 0.0038, 0.0035,
            0.0032, 0.004, 0.0057, 0.0025, 0.0041, 0.0036, 0.0037, 0.0037,
            0.0043, 0.004, 0.0059, 0.0034, 0.0038, 0.0038, 0.0036,
            0.0039, 0.0029, 0.0033, 0.0031, 0.0039, 0.003, 0.0043,
            0.0033, 0.0038, 0.0041, 0.0049, 0.0037, 0.0043, 0.0047,
            0.004, 0.0048, 0.0047, 0.0033, 0.0058, 0.0057, 0.0038, 0.0057,
            0.005, 0.0051, 0.0049, 0.0104, 0.0043, 0.0045, 0.0038,
            0.0041, 0.0049, 0.0038, 0.0062, 0.0037, 0.0052, 0.0051,
            0.0034, 0.0051, 0.0038, 0.0046, 0.0051, 0.0057, 0.0042,
            0.0043, 0.0059, 0.0046, 0.0037, 0.0062, 0.0039, 0.0041,
            0.0034, 0.0063, 0.005, 0.0033, 0.004, 0.003, 0.002, 0.0034,
            0.0031, 0.0043, 0.0028, 0.0029, 0.0015, 0.0037, 0.0035,
            0.004, 0.0037, 0.0041, 0.004, 0.0033, 0.0036, 0.0038,
            0.0036, 0.0029, 0.0031, 0.004, 0.0055, 0.007, 0.0037, 0.0044,
            0.0036, 0.0037, 0.0032, 0.0032, 0.0035, 0.0033, 0.0042,
            0.004, 0.0023, 0.0046, 0.0039, 0.0041, 0.0042, 0.003,
            0.0036, 0.0033, 0.0034, 0.0018, 0.0022, 0.0024, 0.0043,
            0.0016, 0.0018, 0.0025, 0.0017, 0.0051, 0.0015, 0.0015,
            0.0017, 0.0021, 0.0023, 0.0022, 0.0022, 0.0027, 0.0027, 0.0023,
            0.0011, 0.0018, 0.002, 0.0027, 0.0022, 0.0025, 0.0029,
            0.002, 0.0026, 0.003, 0.0023, 0.0041, 0.0014, 0.002,
            0.0021, 0.0026, 0.0018, 0.0022, 0.0022, 0.0014, 0.0033, 0.002,
            0.0031, 0.0021, 0.0018),
  TCRDPS = c(0.0123, 0.0134, 0.0122, 0.0121, 0.0116, 0.011, 0.0084, 0.0102,
             0.012, 0.0088, 0.0101, 0.0142, 0.0129, 0.0114, 0.0132,
             0.0114, 0.0084, 0.0117, 0.0091, 0.0114, 0.0102, 0.0087,
             0.0096, 0.01, 0.0093, 0.0107, 0.011, 0.0111, 0.0089,
             0.0133, 0.0121, 0.0119, 0.0082, 0.0069, 0.0096, 0.0086, 0.012,
             0.0118, 0.0099, 0.0123, 0.0148, 0.0114, 0.0074, 0.009,
             0.0054, 0.005, 0.0055, 0.0044, 0.0056, 0.005, 0.0064,
             0.0065, 0.0047, 0.0064, 0.006, 0.004, 0.0063, 0.0067, 0.0064,
             0.0057, 0.0069, 0.0064, 0.0062, 0.0054, 0.0055, 0.0056,
             0.0063, 0.0055, 0.007, 0.0059, 0.0071, 0.0062, 0.0074,
             0.0046, 0.0063, 0.006, 0.0056, 0.008, 0.0068, 0.0082,
             0.0058, 0.0056, 0.0062, 0.0055, 0.0036, 0.0051, 0.0063,
             0.0057, 0.0017, 0.0021, 0.0015, 0.0022, 8e-04, 0.0037, 0.0024,
             0.0013, 0.0036, 0.0024, 0.0012, 0.0032, 0.002, 5e-04,
             0.0021, 0.0014, 0.0036, 0.0025, 0.0024, 0.0065, 0.0026,
             0.0028, 0.002, 0.0028, 0.0015, 0.0026, 0.0026, 8e-04, 0.0018,
             0.0025, 0.0011, 0.0021, 0.0023, 0.0014, 0.0022, 0.0019,
             0.0026, 0.0013, 9e-04, 0.0024, 0.0035, 0.0019, 0.0021,
             0.0021, 0.0055, 0.0052, 0.0049, 0.0042, 0.0061, 0.0042,
             0.0059, 0.0049, 0.0044, 0.0063, 0.007, 0.0053, 0.006,
             0.0054, 0.0051, 0.0056, 0.0101, 0.005, 0.004, 0.0048, 0.0045,
             0.0056, 0.0058, 0.0069, 0.0062, 0.0066, 0.0064, 0.0046,
             0.0057, 0.0047, 0.005, 0.0058, 0.0079, 0.0058, 0.0052,
             0.0061, 0.0054, 0.005, 0.015, 0.0046, 0.0049, 0.0047, 0.0078,
             0.007, 0.0035, 0.0047, 9e-04, 0.0036, 0.0023, 0.0047,
             0.0032, 0.0037, 0.0028, 0.0024, 0.0042, 0.0026, 0.0045,
             0.0036, 0.0038, 0.0036, 0.0032, 0.0023, 0.0027, 0.0029,
             0.0026, 0.0029, 0.0041, 0.0072, 0.0044, 0.0034, 0.0042,
             0.0037, 0.0049, 0.0035, 0.0036, 0.0043, 0.002, 0.0034, 0.0046,
             0.0034, 0.0051, 0.0041, 0.0051, 0.0032, 0.0028, 0.0036,
             0.0043, 0.0031, 5e-04, 5e-04, 0.0014, 0, 2e-04, 4e-04,
             0.0012, 0, 0.0015, 3e-04, 6e-04, 3e-04, 0.001, 1e-04,
             3e-04, 9e-04, 0.0013, 7e-04, 9e-04, 4e-04, 0, 6e-04, 0, 3e-04,
             9e-04, 3e-04, 7e-04, 5e-04, 3e-04, 4e-04, 0.0025, 0,
             6e-04, 3e-04, 0, 0, 0, 1e-04, 5e-04, 0, 2e-04, 0, 0.0014,
             6e-04)
)
library(tidyverse)
colunas<-c(1,2,3,4,5,6)
dados<-dados %>% mutate_at(., colunas, factor)

col2<-c(7:10)

dados<-dados %>% mutate_at(., col2, function(x) x*1000)

todos<-gather(dados,key=Ys, value=Valores, -Ciclo:-K, -Nq, -Kq)

contrasts(todos$Ciclo) <- contr.sum(2) 
contrasts(todos$Periodo) <- contr.sum(3) 
contrasts(todos$Trat) <- contr.sum(11) 

modelos<-todos %>% split(.$Ys) %>% 
  map(~(aov(Valores~Trat*Ciclo*Periodo+Error(Bloco/Trat/Ciclo), data=.)))

library(emmeans)

cld.lista = function(object, ..., which = seq_along(object)) {
  lapply(object[which], CLD, ...)
}

medias<-function(x){
  medias<-emmeans(x, list(~Ciclo, ~Periodo, ~Ciclo|Periodo, ~Periodo|Ciclo, ~Ciclo|Trat, ~Periodo|Trat, ~Ciclo|Periodo|Trat, ~Periodo|Ciclo|Trat))
  cld.lista(medias, adjust="tukey", Letters=letters, reversed=T)
}

map(modelos, medias)

********************************
With emmeans 1.30, or less  - OK

$TCRAP$`emmeans of Ciclo | Trat`
Trat = 1:
 Ciclo   emmean        SE    df lower.CL upper.CL .group
 1     7.083333 0.2666351 52.91 6.469628 7.697038  a    
 2     3.266667 0.2666351 52.91 2.652962 3.880372   b   

Trat = 2:
 Ciclo   emmean        SE    df lower.CL upper.CL .group
 1     6.841667 0.2666351 52.91 6.227962 7.455372  a    
 2     3.975000 0.2666351 52.91 3.361295 4.588705   b   

Trat = 3:
 Ciclo   emmean        SE    df lower.CL upper.CL .group
 1     6.900000 0.2666351 52.91 6.286295 7.513705  a    
 2     3.608333 0.2666351 52.91 2.994628 4.222038   b   

And so on....

BUT, with emmeans 1.31 - Error:

----------------------------------
 Error in terms.formula(formula, "Error", data = data) : 
  object '.' not found 

-------------------------------------

Apparently, it is related to  the fact that lm or any similar commands, as glm,  is depending on temporary  data (data=.).  Please, could you give any suggestion to overcome this problem.

Thanks in advance.

Walter Pereira

**Comment by wep69** [comment]
The correct it is:

modelos<-todos %>% split(.$Ys) %>% 
  map(~(aov(Valores~Trat*Ciclo*Periodo+Error(Bloco/Trat/Ciclo), data=.)))

**Comment by wep69** [comment]
[Script-OK.txt](https://github.com/rvlenth/emmeans/files/2710943/Script-OK.txt)

**Comment by rvlenth** [comment]
I believe I have been able to reproduce the particular model you illustrate:
```
> options(contrasts = c("contr.sum", "contr.poly"))
> mod <- aov(TCRAP~Trat*Ciclo*Periodo+Error(Bloco/Trat/Ciclo), data=dados)

> emmeans(mod, ~ Ciclo | Trat)
NOTE: Results may be misleading due to involvement in interactions
Trat = 1:
 Ciclo emmean    SE   df lower.CL upper.CL
 1       7.08 0.267 52.9     6.55     7.62
 2       3.27 0.267 52.9     2.73     3.80

Trat = 2:
 Ciclo emmean    SE   df lower.CL upper.CL
 1       6.84 0.267 52.9     6.31     7.38
 2       3.98 0.267 52.9     3.44     4.51

Trat = 3:
 Ciclo emmean    SE   df lower.CL upper.CL
 1       6.90 0.267 52.9     6.37     7.43
 2       3.61 0.267 52.9     3.07     4.14

Trat = 4:
 Ciclo emmean    SE   df lower.CL upper.CL
 1       7.19 0.267 52.9     6.66     7.73
 2       3.77 0.267 52.9     3.23     4.30

Trat = 5:
 Ciclo emmean    SE   df lower.CL upper.CL
 1       6.78 0.267 52.9     6.25     7.32
 2       3.51 0.267 52.9     2.97     4.04

Trat = 6:
 Ciclo emmean    SE   df lower.CL upper.CL
 1       6.79 0.267 52.9     6.26     7.33
 2       3.88 0.267 52.9     3.35     4.42

Trat = 7:
 Ciclo emmean    SE   df lower.CL upper.CL
 1       7.24 0.267 52.9     6.71     7.78
 2       3.78 0.267 52.9     3.25     4.32

Trat = 8:
 Ciclo emmean    SE   df lower.CL upper.CL
 1       7.12 0.267 52.9     6.59     7.66
 2       3.18 0.267 52.9     2.65     3.72

Trat = 9:
 Ciclo emmean    SE   df lower.CL upper.CL
 1       7.18 0.267 52.9     6.65     7.72
 2       3.48 0.267 52.9     2.95     4.02

Trat = 10:
 Ciclo emmean    SE   df lower.CL upper.CL
 1       6.31 0.267 52.9     5.77     6.84
 2       3.27 0.267 52.9     2.74     3.81

Trat = 11:
 Ciclo emmean    SE   df lower.CL upper.CL
 1       5.96 0.267 52.9     5.42     6.49
 2       3.51 0.267 52.9     2.97     4.04

Results are averaged over the levels of: Periodo 
Confidence level used: 0.95
```
So I think that `emmeans()` is now functioning correctly with this model.

If the problem is in not finding the data, note that `emmeans()` does support an optional `data` argument; with all your tidyverse code, you may need `map2()` or some such to pass the data as well as other parameters.

**Comment by wep69** [comment]
Thank you for your quick answer. My purpose it is to model many dependents variables simultaneously, that it was Ok until 1.30.
I tried with data option and map2, with the same error.Attached the todos dataframe and the corresponding script.
Thank you.
Walter Pereira

 
 
 
Your scrip[t fails for me well before any calls to emmeans():
> todos<-gather(dados,key=Ys, value=Valores, -Ciclo:-K, -Nq, -Kq)
Error in is_character(x) : object 'Nq' not found

At any rate, I suspect the error you are experiencing is related to #66, which has been fixed in the current version on this github site.

This is an extremely elaborate example, I would appreciate a smaller one that reproduces the same error. If nothing else, give me the final dados and todos datasets and skip all the code to create them.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
   


library(rio)
todos<-import("todos.xlsx")

todos$Ciclo<-as.factor(todos$Ciclo)
todos$Periodo<-as.factor(todos$Periodo)
todos$Trat<-as.factor(todos$Trat)
contrasts(todos$Ciclo) <- contr.sum(2) 
contrasts(todos$Periodo) <- contr.sum(3) 
contrasts(todos$Trat) <- contr.sum(11) 

library(tidyverse)

modelos<-todos %>% split(.$Ys) %>% 
  map(~(aov(Valores~Trat*Ciclo*Periodo+Error(Bloco/Trat/Ciclo), data=.)))

library(emmeans)

cld.lista = function(object, ..., which = seq_along(object)) {
  lapply(object[which], CLD, ...)
}

medias<-function(x){
  medias<-emmeans(x, list(~Ciclo, ~Periodo, ~Ciclo|Periodo, ~Periodo|Ciclo, ~Ciclo|Trat, ~Periodo|Trat, ~Ciclo|Periodo|Trat, ~Periodo|Ciclo|Trat))
  cld.lista(medias, adjust="tukey", Letters=letters, reversed=T)
}

map(modelos, medias)
