### ISSUE TITLE
Support for lmPerm/aovperm object

### ISSUE THREAD

**Issue by adityabandla** [rvlenth/emmeans#70]
Is there a straight forward way to use emmeans to do pairwise comparisons for permutational ANOVA models constructed using the lmPerms package or permuco package?

For analysing a repeated measures 3-factor ANOVA, the permuco package seems to offer better options with respect to permuting the data. However, the model class isnt currently supported by emmeans

**Comment by rvlenth** [comment]
I’m not sure; I haven’t used that package. But take a look at the qdrg() function. It may be possible if you can assemble the needed components.

Sent from my iPhone

On Dec 27, 2018, at 3:10 AM, Aditya Bandla <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there a straight forward way to use emmeans to do pairwise comparisons for permutational ANOVA models constructed using the lmPerms package?

**Comment by rvlenth** [comment]
I believe this is *not* possible. Here is an example:
```
> library(lmPerm)
> data(CC164)
> mod = lmp(y ~ N * P, data = CC164)    # one of the examples in the help file
[1] "Settings:  unique SS "
> summary(mod)

Call:
lmp(formula = y ~ N * P, data = CC164)

Residuals:
ALL 9 residuals are 0: no residual degrees of freedom!

Coefficients:
        Estimate Pr(Exact)
N.L      -63.640    0.0643
N.Q        4.082    0.8929
P.L      -60.575    0.0786
P.Q        0.408    1.0000
N.L:P.L   47.000    0.4656
N.Q:P.L   42.724    0.5052
N.L:P.Q   24.249    0.7075
N.Q:P.Q   13.000    0.8524

Residual standard error: NaN on 0 degrees of freedom
Multiple R-Squared:     1,	Adjusted R-squared:   NaN 
F-statistic:   NaN on 8 and 0 DF,  p-value: NA 
```
Note that there are no SEs, p-values, etc. Indeed:
```
> vcov(mod)
            (Intercept) N.L N.Q P.L P.Q N.L:P.L N.Q:P.L N.L:P.Q N.Q:P.Q
(Intercept)         NaN NaN NaN NaN NaN     NaN     NaN     NaN     NaN
N.L                 NaN NaN NaN NaN NaN     NaN     NaN     NaN     NaN
N.Q                 NaN NaN NaN NaN NaN     NaN     NaN     NaN     NaN
P.L                 NaN NaN NaN NaN NaN     NaN     NaN     NaN     NaN
P.Q                 NaN NaN NaN NaN NaN     NaN     NaN     NaN     NaN
N.L:P.L             NaN NaN NaN NaN NaN     NaN     NaN     NaN     NaN
N.Q:P.L             NaN NaN NaN NaN NaN     NaN     NaN     NaN     NaN
N.L:P.Q             NaN NaN NaN NaN NaN     NaN     NaN     NaN     NaN
N.Q:P.Q             NaN NaN NaN NaN NaN     NaN     NaN     NaN     NaN
```
I can get a reference grid, but no useful statistical results:
```
> rg = qdrg(object = mod, data=CC164)
> emmeans(rg, ~ N | P)
P = 1:
 N emmean  SE df lower.CL upper.CL
 1    276 NaN  0      NaN      NaN
 2    339 NaN  0      NaN      NaN
 3    262 NaN  0      NaN      NaN

P = 2:
 N emmean  SE df lower.CL upper.CL
 1    314 NaN  0      NaN      NaN
 2    370 NaN  0      NaN      NaN
 3    376 NaN  0      NaN      NaN

P = 3:
 N emmean  SE df lower.CL upper.CL
 1    278 NaN  0      NaN      NaN
 2    362 NaN  0      NaN      NaN
 3    600 NaN  0      NaN      NaN

Confidence level used: 0.95
```
(Note: I previously had set the default contrasts to `"contr.sum"` which produces different coefficients than the default `"contr.treatment"`.) The EMMs are probably right because the object is basically an `lm` object. But the package is oriented to testing, not estimation.
