### ISSUE TITLE
Strange behavior with nesting

### ISSUE THREAD

**Issue by jwbenning** [rvlenth/emmeans#71]
I'm trying to get estimated marginal means (EMMs) from a logistic regression model that has a fixed, nested term. I'm looking for EMMs for combinations of two fixed factors, one of which has a nested term.

When I run emmeans on my GLM, I'm getting strange behavior that I have identified as having to do with nesting. The predicted probabilities are not consistent when I change the order of the combination specification in emmeans. Though identical probabilities result from each specification, they are not associated with the same combinations of factors. (This will be clearer below.) emmeans _is_ correctly identifying the nesting structure.

When I remove the nesting structure, emmeans behaves normally.

Example using the iris dataset:

```
iris.ex <- iris

set.seed(100)
# make binary response
iris.ex$binary <- sample(c(0,1), replace = T, size = 150)
# make factor1
iris.ex$factor1 <- sample(c("par", "moo"), replace = T, size = 150)
# make nested subspecies factor
iris.ex$ssp <- rep(c("ssp1", "ssp2"), times = 75)

iris.glm <- glm(binary ~ Species * factor1 + Species/ssp, family = "binomial"(link = "logit"), data = iris.ex)

emmeans(iris.glm, ~ Species:factor1, type = "response")
emmeans(iris.glm, ~ factor1:Species, type = "response")
```
I would expect those two emmeans calls to result in the same table of predicted probabilities for combinations of **factor1** and **Species**. They actually do result in the same probabilities, in the same listed order, but those probabilities are not associated with the same combinations of factors.

```
emmeans(iris.glm, ~ Species:factor1, type = "response")



NOTE: A nesting structure was detected in the fitted model:
    ssp %in% Species
 Species    factor1      prob         SE  df asymp.LCL asymp.UCL
 setosa     moo     0.4829111 0.09712132 Inf 0.3034992 0.6668396
 versicolor moo     0.6071125 0.10297421 Inf 0.3986860 0.7826752
 virginica  moo     0.3183634 0.09409549 Inf 0.1664290 0.5221216
 setosa     par     0.6017817 0.09899252 Inf 0.4020953 0.7725087
 versicolor par     0.3790531 0.09595448 Inf 0.2154145 0.5757750
 virginica  par     0.5476111 0.10255462 Inf 0.3497024 0.7315289



Results are averaged over the levels of: ssp 
Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 
```

**versus**

```
emmeans(iris.glm, ~ factor1:Species, type = "response")



NOTE: A nesting structure was detected in the fitted model:
    ssp %in% Species
 factor1 Species         prob         SE  df asymp.LCL asymp.UCL
 moo     setosa     0.4829111 0.09712132 Inf 0.3034992 0.6668396
 par     setosa     0.6071125 0.10297421 Inf 0.3986860 0.7826752
 moo     versicolor 0.3183634 0.09409549 Inf 0.1664290 0.5221216
 par     versicolor 0.6017817 0.09899252 Inf 0.4020953 0.7725087
 moo     virginica  0.3790531 0.09595448 Inf 0.2154145 0.5757750
 par     virginica  0.5476111 0.10255462 Inf 0.3497024 0.7315289



Results are averaged over the levels of: ssp 
Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 
```

This is very puzzling -- any ideas?

**Comment by rvlenth** [comment]
Ouch! This is not good! Thanks for reporting it. The nesting code works by calling `emmeans()` separately on different parts of the grid. Apparently, the pieces are not being put back in the right places. This may not be easy to figure out; keeping my fingers crossed, as it is obviously something that needs to be fixed.

**Comment by rvlenth** [comment]
I found the problem. The computed EMMs, don't necessarily come out in standard order (defined as is produced by `expand.grid()`). This comes back to bite because there is another call to `emmeans()` at the very end -- needed in case there are some other nesting groups not yet handled. And `emmeans()` assumes that the means are arranged in standard order. (I think I had better put-in a check for that since the user could have used the `[...]` operator to reorder them.) I'll investigate that before I push it to github. But I have fixed it at my end:
```
> emmeans(iris.glm, ~ factor1:Species)   ### the one that was right
NOTE: A nesting structure was detected in the fitted model:
    ssp %in% Species
 factor1 Species     emmean    SE  df asymp.LCL asymp.UCL
 moo     setosa     -0.0684 0.389 Inf    -0.831    0.6939
 par     setosa      0.4352 0.432 Inf    -0.411    1.2813
 moo     versicolor -0.7613 0.434 Inf    -1.611    0.0885
 par     versicolor  0.4129 0.413 Inf    -0.397    1.2225
 moo     virginica  -0.4936 0.408 Inf    -1.293    0.3055
 par     virginica   0.1910 0.414 Inf    -0.620    1.0024

Results are averaged over the levels of: ssp 
Results are given on the logit (not the response) scale. 
Confidence level used: 0.95

> emmeans(iris.glm, ~ Species:factor1)   ### the one that was wrong
NOTE: A nesting structure was detected in the fitted model:
    ssp %in% Species
 Species    factor1  emmean    SE  df asymp.LCL asymp.UCL
 setosa     moo     -0.0684 0.389 Inf    -0.831    0.6939
 versicolor moo     -0.7613 0.434 Inf    -1.611    0.0885
 virginica  moo     -0.4936 0.408 Inf    -1.293    0.3055
 setosa     par      0.4352 0.432 Inf    -0.411    1.2813
 versicolor par      0.4129 0.413 Inf    -0.397    1.2225
 virginica  par      0.1910 0.414 Inf    -0.620    1.0024

Results are averaged over the levels of: ssp 
Results are given on the logit (not the response) scale. 
Confidence level used: 0.95 
```
```

**Comment by rvlenth** [comment]
I think I have resolved this issue -- interestingly, as it turns out, by making no changes to the code for nested models, and instead, robustifying `emmeans()` so it double-checks that everything is in the right order.

I'll close this now, but let me know if any problems crop up. Thanks again for reporting it.

**Comment by jwbenning** [comment]
Thanks very much!

John
