### ISSUE TITLE
emmeans on a gls model created inside a function fails 

### ISSUE THREAD

**Issue by Natasha98764** [rvlenth/emmeans#78]
Hi,
Really appreciating the package but hit a problem which I think is a bug.  Similar to the bug reported by bengowan but there the problem was with the specification of the formula whereas here it is the passing of the data.  I have worked out a fix (model_test$call$data=mock_df) to get my code working.   

I have provided code to demonstrate the problem below.
Step 1:  construct a simulated dataset
Step 2: Fit with a gls model and extract various elements of a statistical analysis including estimated marginal means.

Step 2 works when working in global  space but not when fitting the model within a function and passing the data frame to the fitting. 

Error returned: 
Error in terms.formula(formula, data = data) : 'data' argument is of the wrong type  Error in ref_grid(object, ...) : Perhaps a 'data' or 'params' argument is needed 

Is it an issue with the model$call?  when fitting in global space this specifies the dataframe correctly but not when you are within a function.

# Step 1 - generate a mock dataset
MB_MockData <- function(NoBatches, M_veh, SD_veh, batch_SD, ES, ss_C, ss_T){
  numberBatches=c(1:NoBatches)
  BatchEffect=rnorm(n=NoBatches, mean=0, sd=batch_SD)
  #print(BatchEffect)
  ToDo=data.frame(Index=numberBatches, ImpactBatch=BatchEffect)
  results=c()          
  for (bob in numberBatches) {
    df=subset(x=ToDo, Index==bob)
    V_data=rnorm(n=ss_C, mean=(M_veh+df$ImpactBatch), sd=SD_veh)
    T_data=rnorm(n=ss_T, mean=(M_veh+df$ImpactBatch-ES), sd=SD_veh)
    GrowthData=c(V_data, T_data)
    Treatment=c(rep.int("Vehicle", times=ss_C), rep.int("Treatment", times=ss_T))
    Batch=rep.int(paste("study", bob, sep="_"), times=(ss_T+ss_C))
    ThisBatchResults=data.frame(col1=GrowthData, col2=Batch, col3=Treatment)  
    results=rbind(results, ThisBatchResults) 
  }
  names(results)=c("GrowthRate", "Study", "Treatment")
  results$Treatment=factor(results$Treatment)
  results$Study=factor(results$Study)
  results$Treatment=relevel(results$Treatment, ref="Vehicle")
  return(results)
}

mock_df=MB_MockData(NoBatches=3, M_veh=0.06502854, SD_veh=0.01177680, batch_SD=0.00235536, ES=0.03726, ss_C=6, ss_T=6) # note equivalent to a 57% inhibition 

#Step 2 fit the model - first in the global space and everything works fine
library(nlme)
library(emmeans)

model1 <- gls(GrowthRate ~ Treatment + Study + Study*Treatment, data = mock_df,   na.action="na.exclude", method="REML")
emmeans(model1,  "Treatment") 
G_m2=emmeans(model1,  "Treatment")  # returns an emmGRid object
pairs(G_m2)

#Step 2 fit the model from within a function   

statisticalOutput<-function(df, iteration){
  
    model_test <- gls(GrowthRate ~ Treatment + Study + Study*Treatment, data = df,   na.action="na.exclude", method="REML")
    Mmean_output=summary(emmeans(model_test,  "Treatment"))  # returns  df
    GR_inhibition=(100*summary(pairs(emmeans(model_test,  "Treatment")))[2])/Mmean_output$emmean[1]     
    print(GR_inhibition)
    results=c(iteration, GR_inhibition,summary(pairs(emmeans(model_test,  "Treatment")))[2],summary(pairs(emmeans(model_test,  "Treatment")))[3], anova(model_test)$'p-value'[2],anova(model_test)$'p-value'[4])
    names(results)=c("iteration", "GRinhibition", "growthRateES", "growthRateSE", "Pval_Treatment","Pval_TvI")
    return(results)			
}

statisticalOutput(mock_df, iteration=1)

**Comment by rvlenth** [comment]
Note that the error message you observed says:
```
Error in eval(predvars, data, env) : object 'Treatment' not found
Error in ref_grid(object, ...) : 
  Perhaps a 'data' or 'params' argument is needed
```
You should do exactly what it says -- add a `data` argument to all of the `emmeans()` calls. There is nothing in the `gls` object that contains the actuial data used to fit the model, so you have to provide that because `ref_grid()` and `emmeans()` need to look at the dataset. Here's the revised function:
```
statisticalOutput <- function(df, iteration){
    model_test <- gls(GrowthRate ~ Treatment + Study + Study*Treatment, 
        data = df,   na.action="na.exclude", method="REML")
    Mmean_output=summary(emmeans(model_test,  "Treatment", data = df))  # returns  df #??? No it doesn't
    GR_inhibition=(100*summary(pairs(emmeans(model_test,  "Treatment", data = df)))[2]) 
        / Mmean_output$emmean[1]     
    print(GR_inhibition)
    results=c(iteration, 
        GR_inhibition,summary(pairs(emmeans(model_test,  "Treatment", data = df)))[2],
        summary(pairs(emmeans(model_test,  "Treatment", data = df)))[3], 
        anova(model_test)$'p-value'[2],anova(model_test)$'p-value'[4])
    names(results)=c("iteration", "GR_inhibition", "growthRateES", "growthRateSE",
        "Pval_Treatment","Pval_TvI")
    return(results)			
}
```
Note that I made additional correction because you define `GR_inhibitiion` but later refer to it as `GRinhibition. After these corrections,
```
> statisticalOutput(mock_df, iteration=1)
NOTE: Results may be misleading due to involvement in interactions
NOTE: Results may be misleading due to involvement in interactions
  estimate
1 59.10802
NOTE: Results may be misleading due to involvement in interactions
NOTE: Results may be misleading due to involvement in interactions
$`iteration`
[1] 1

$GR_inhibition
[1] 59.10802

$growthRateES
[1] 0.03679779

$growthRateSE
[1] 0.004447511

$Pval_Treatment
[1] 3.098242e-09

$Pval_TvI
[1] 0.4371958
```
I suggest taking those messages about the interactions seriously. It can be misleading to average over levels of factors that interact with treatments.

**Comment by rvlenth** [comment]
If those random interactions are your assumption, then the model should reflect it. You might want to try something like
```
model <- lme(GrowthRate ~ Treatment, random = ~1 | Study/Treatment, 
        data = df,   na.action="na.exclude", method="REML")
```
