### ISSUE TITLE
emtrends: Error in data[[var]] : subscript out of bounds

### ISSUE THREAD

**Issue by toouggy** [rvlenth/emmeans#8]
Hi,

I have an issue with emtrends.  I have a model in which emmeans detects incorrectly nesting.  I updated the ref_grid with nesting = NULL and that fixed the issue with emmeans.  I tried to use the updated ref_grid with emtrends and I get the following error:  Error in data[[var]] : subscript out of bounds

As I mentioned the same updated ref_grid works just fine with emmeans, thus I presume that it would be some problem in emtrends.

On a different topic, is there a way to stop emmeans/emtrends nesting recognition?

Thank you.

Paco

**Comment by rvlenth** [comment]
You can’t run `emtrends()` on an `emmGrid` object; it has to be a model object so it can do the difference quotient. However, calling `emtrends(…, nesting = NULL)` should work. That argument is passed to `ref_grid()`, as is documented.

Usually in cases where nesting is incorrectly detected, it indicates that some shortcuts were taken in specifying the model by omitting some main effects that really should be there. I personally recommend specifying models completely; it saves confusion down the road, not just in nesting-detection issues, but in explaining what model you really fitted.

Russ

**Comment by toouggy** [comment]
Thank you Russ.  That fixed my problem.

Paco

Sent from my iPhone


On Dec 7, 2017, at 13:05, Russell V. Lenth <notifications@github.com<mailto:notifications@github.com>> wrote:

You can’t run `emtrends()` on an `emmGrid` object; it has to be a model object so it can do the difference quotient. However, calling `emtrends(…, nesting = NULL)` should work. That argument is passed to `ref_grid()`, as is documented.

Usually in cases where nesting is incorrectly detected, it indicates that some shortcuts were taken in specifying the model by omitting some main effects that really should be there. I personally recommend specifying models completely; it saves confusion down the road, not just in nesting-detection issues, but in explaining what model you really fitted.

Russ
