### ISSUE TITLE
joint_tests results mislabeled

### ISSUE THREAD

**Issue by pdixonstat** [rvlenth/emmeans#81]
I have a model for agricultural data: 2 way factorial repeated at two locations in an RCBD.  Model has location, block within location, A, B, A:B and all location interactions.  No block interactions.  Focus is on A, B and their interactions.  Block within location is a fixed effect (to get appropriate MSE when blocking was not effective).

The problem is that joint_tests() gives the appropriate set of p-values but the naming of those tests depends on the order of factors in the emmeans call.  To illustrate:
> example.emm1 <- emmeans(example.lm, c('location','A','B'))
NOTE: A nesting structure was detected in the fitted model:
    block %in% location
If this is incorrect, re-run or update with `nesting` specified
> joint_tests(example.emm1)
 model term   df1 df2 F.ratio p.value
 location       1  34   4.822  0.0350
 A              1  34   4.888  0.0339
 B              1  34  46.875  <.0001
 location:A     1  34   0.245  0.6238
 location:B     1  34   0.454  0.5052
 A:B            1  34   0.152  0.6988
 location:A:B   1  34   0.147  0.7042

> example.emm2 <- emmeans(example.lm, c('A','B','location'))
NOTE: A nesting structure was detected in the fitted model:
    block %in% location
If this is incorrect, re-run or update with `nesting` specified
> joint_tests(example.emm2)
 model term   df1 df2 F.ratio p.value
 A              1  34   4.822  0.0350
 B              1  34   4.888  0.0339
 location       1  34  46.875  <.0001
 A:B            1  34   0.245  0.6238
 A:location     1  34   0.454  0.5052
 B:location     1  34   0.152  0.6988
 A:B:location   1  34   0.147  0.7042

The correct answers are (omitting the warnings:
test(pairs(emmeans(example.lm, 'A')), joint=T)
 df1 df2 F.ratio p.value
   1  34   4.822  0.0350

> test(pairs(emmeans(example.lm, 'B')), joint=T)
 df1 df2 F.ratio p.value
   1  34   4.888  0.0339

> test(pairs(emmeans(example.lm, 'location')), joint=T)
 df1 df2 F.ratio p.value
[NIFA.zip](https://github.com/rvlenth/emmeans/files/2787411/NIFA.zip)

   1  34  46.875  <.0001

In the first emm, the p-values are assigned to A, B, and location in the wrong order.

The data set  ( a .csv file) and full code example in the attached ZIP file.

**Comment by rvlenth** [comment]
Thanks for the report. This is closely related to issue #71, and the fix for that seems to have worked for this example as well:
```
> joint_tests(example.emm1)
 model term   df1 df2 F.ratio p.value
 location       1  34  46.875 <.0001 
 A              1  34   4.822 0.0350 
 B              1  34   4.888 0.0339 
 location:A     1  34   0.454 0.5052 
 location:B     1  34   0.152 0.6988 
 A:B            1  34   0.245 0.6238 
 location:A:B   1  34   0.147 0.7042 

> joint_tests(example.emm2)
 model term   df1 df2 F.ratio p.value
 A              1  34   4.822 0.0350 
 B              1  34   4.888 0.0339 
 location       1  34  46.875 <.0001 
 A:B            1  34   0.245 0.6238 
 A:location     1  34   0.454 0.5052 
 B:location     1  34   0.152 0.6988 
 A:B:location   1  34   0.147 0.7042 
```
The CRAN version (1.3.2, updated just yesterday, Jan 22) has this fix. Thanks again. I will close this issue but let me know if anything is left hanging.

**Comment by pdixonstat** [comment]
Russ,

That does appear to fix the issue.  I ran into the issue over the weekend (with emmeans 1.3.0, but it took me a bit to put together the concise example files.

If I haven’t already told you, until lsmeans/emmeans, I refused to teach R in my intro grad stat methods class.  Now I do.  emmeans is a game changer.  Thanks for all your support.

Thanks again!
Philip

**Comment by rvlenth** [comment]
Philip,

Glad it's useful to you. The whole motivation for it at the beginning was "not having to depend on SAS" in design/anova courses.

BTW, you do know, don't you, that you had an influence on a package feature -- namely including provisions in `test()` for equivalence, non-superiority, and non-inferiority. I remember the talk you gave several years ago in a dept. colloquium at UI.

Russ

**Comment by pdixonstat** [comment]
Russ,

It is more than useful!  I now give students in 1st semester Grad methods the choice of JMP, R, or SAS.   Last semester 70% chose R.  Five years ago, everyone used SAS.  And, I taught only SAS because it was too hard to get appropriate results from R when the design was unbalanced.  I tell students that accidents happen so they need to know how to analyze unbalanced data.

I did notice the variety of tests, but did not realize I was the inspiration.  Very useful in specific situations!  Thanks!

Best,
Philip
