### ISSUE TITLE
'random effect' categories

### ISSUE THREAD

**Issue by manuelreif** [rvlenth/emmeans#84]
Thank you for this package!

I am using the `brms` package to fit some 3-level-logistic regression (with multiple random effect terms), and I try to compute conditional marginal means. 
When I use `ref_grid()` there are 2 problems:

1. The random effects are not considered in the grid (see reprex below). I would expect all unique level combinations of the random effects?
2. When I try to condition on a level of the random effects term, say: gru1 = 'b', `ref_grid()` does consider this variable. I would expect a column with this variable set to 'b' and the unique levels of `gru2` variable repeated.

How can I solve this problem?

```r
library(brms)
library(emmeans)


set.seed(123)
d <- data.frame(X0 = sample(0:1, 500, replace=TRUE),
                matrix(rnorm(150*10),500,3))

rv1 <- sample(gl(10, k = 50, labels = letters[1:10]))
rv2 <- sample(gl(20, k = 25, labels = letters[1:20]))

d <- data.frame(d, gru1 = rv1, gru2 = rv2)

mod1_priors <- c(prior(normal(0, 2), class = b))

brms_obj <- brms::brm(formula = X0 ~ X1 + X2 + X3 + (1|gru1) + (1|gru2), 
                      data = d, 
                      family="bernoulli", 
                      control = list(adapt_delta = 0.84),
                      iter = 1000,
                      chains = 4,
                      cores = 4,
                      prior = mod1_priors)

#1 ranef?
mylist1 <- list(X1 = mean(d$X1), 
                X2 = mean(d$X2),
                X3 = mean(d$X3))

res_grid <- emmeans::ref_grid(brms_obj, at = mylist1)
res_grid@grid

#          X1         X2         X3 .wgt.
# 1 0.02172068 0.02254718 0.04201589     1

#2 fixing on 1 specific category of ranef 1
mylist <- list(X1 = mean(d$X1), 
               X2 = mean(d$X2),
               X3 = mean(d$X3),
               gru1 = "b")

res_grid <- emmeans::ref_grid(brms_obj, at = mylist)
res_grid@grid
#          X1         X2         X3 .wgt.
# 1 0.02172068 0.02254718 0.04201589     1
```

Tank you!
Manuel

**Comment by rvlenth** [comment]
`ref_grid()` does not support conditioning on random effects, whether for `brms` objects or any other. It only considers the fixed-effects part of any model. I do not anticipate expanding the package in that way, as it would add tremendous complexity to the package.

When considering conditioning on random effects, that is in essence treating them like fixed effects. So my suggestion is to fit an alternative model with those random effects specified as fixed effects; then you may use `ref_grid()` and `emmeans()` on that model to obtain the results you need.

**Comment by manuelreif** [comment]
ok thank you for the quick answer.
bad news though, but now i know i don't have to dig deeper into the package. :-)
