### ISSUE TITLE
eemeans install issues

### ISSUE THREAD

**Issue by loriabendroth** [rvlenth/emmeans#85]
Hoping you can figure out the problem with my install. Initially when trying to install the package like others from CRAN, I get:
Warning in install.packages :
  package ‘eemeans’ is not available (for R version 3.5.2)

I have reviewed this (https://github.com/rvlenth/emmeans) and installed the package via
devtools::install_github("rvlenth/emmeans", dependencies = TRUE, build_opts = "")

I can see the eemeans folder in my library (C:\Users\labend\Documents\R\win-library\3.5) with this install. But when I call the library from console, I get:
library(eemeans) 
Error in library(eemeans) : there is no package called ‘eemeans’

Any ideas what is the issue? Any help would be much appreciated.

**Comment by rvlenth** [comment]
It's a double "m", not a double "e": try `library(emmeans)`; Estimated Marginal Means.

**Comment by rvlenth** [comment]
You don't need **lsmeans** at all. Its latest update is just a front-end for **emmeans**. I suggest uninstalling **lsmeans**. (Even the `lsmeans()` function itself is in **emmeans** -- it runs `emmeans()` and re-labels the results.)

**Comment by clara1989** [comment]
Hi my pc is windows, what should I do when the following error happens

 install.packages("emeans")
Installing package into ‘C:/Users/45063125/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘emeans’ is not available (for R version 3.4.4)
>

**Comment by rvlenth** [comment]
Use two ms: emmeans not emeans :-)

Russ

Sent from my iPhone

On Sep 2, 2019, at 1:49 AM, clara1989 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi my pc is windows, what should I do when the following error happens

install.packages("emeans")
Installing package into ‘C:/Users/45063125/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
package ‘emeans’ is not available (for R version 3.4.4)

**Comment by clara1989** [comment]
tried again.  Still not working
