### ISSUE TITLE
Comprehension of Emmeans output

### ISSUE THREAD

**Issue by rpmady** [rvlenth/emmeans#87]
Hello, I'm new when it comes to running models and am also new to emmeans. This package seems great! I am having trouble with understanding the output, however, and want to clarify things here since it doesn't seem to be clarified in the vignettes. 

When I run 
`summary(emm.s, type="response", infer=TRUE)`
I get a "rate."

I understand that emmeans(), pairs(), and contrast() will report a the "ratio" for level-level comparison (which is the ratio of geometric means). But I don't understand what the "rate" is.

**Comment by rvlenth** [comment]
In some places, I choose to use `rate` as the name of the estimate when back-transforming from a log. It is often correct, for example using Poisson regression with a log link. I don't know what kind of model you fitted, so I'm not sure where that comes from. If I use the pigs example, that's not the label I get:
```
> emm.s = emmeans(pigs.lm, "source")
> summary(emm.s, type = "response")
 source response   SE df lower.CL upper.CL
 fish       29.4 1.10 25     27.2     31.7
 soy        38.6 1.42 25     35.8     41.6
 skim       44.0 1.72 25     40.6     47.6

Confidence level used: 0.95 
Intervals are back-transformed from the log scale 
```
If you want something else for the label, you can use `update()` (see `? update.emmGrid`):
```
> emm.s = update(emm.s, inv.lbl = "conc_mcg/ml")
> summary(emm.s, type = "response", infer = TRUE)
 source conc_mcg/ml   SE df lower.CL upper.CL t.ratio p.value
 fish          29.4 1.10 25     27.2     31.7 90.541  <.0001 
 soy           38.6 1.42 25     35.8     41.6 98.975  <.0001 
 skim          44.0 1.72 25     40.6     47.6 96.881  <.0001 

Confidence level used: 0.95 
Intervals are back-transformed from the log scale 
Tests are performed on the log scale 
```

**Comment by rpmady** [comment]
It might be obvious, but I'm not sure what "rate" means. Is it essentially the ratio? 

I ran a zero-inflated generalized linear mixed effects model with Poisson as the family. 
Here is the model:
`zinb_bcch1 <- glmmTMB(sum.50 ~ trtmt + min_aft_sunrise2 + mintemp2 + (1|site), data = data_bcch, ziformula=~1, family = nbinom1)

Then, to get the "rate" I mentioned I do the following:
`emm.s <- emmeans(zip_bcch1, specs = "trtmt", type="response")
`
And then I got this output:
``` 
trtmt          rate    SE df lower.CL upper.CL
 control       0.207 0.106 54   0.0742    0.575
 hotspot       3.993 0.469 54   3.1561    5.052
 pulsed_food   6.443 0.867 54   4.9200    8.438
 pulsed_nofood 0.672 0.290 54   0.2828    1.598
```

**Comment by rvlenth** [comment]
The Poisson model typically involves counts, e.g., "how many highway deaths will occur in a place where deaths occur at a mean rate of 10 deaths per month?" The mean *rate* of 10 is the parameter of a Poisson distribution. In that kind of sense, the parameter of a Poisson distribution is often referred to as a rate. The same would be true of a zero-inflated Poisson, except that a certain fraction of the time, events occur at a rate of zero.

As I indicated before, if the terminology "rate" bothers you, then there is a way to change it to something else. When you do `type = "response"`, you are transforming the estimates to the same scale as your measurement, `sum.50`.

**Comment by rpmady** [comment]
Okay, I think I understand. My confusion I think stems from I didn't think of my response variable as a rate, but I suppose it could be (i.e. the number of birds I count during a 5 minute count). Very new to using using models and the Poisson distribution. And thanks for specifically addressing the zero-inflated part, that is good to know.
