### ISSUE TITLE
No adjust reported even though adjust specified

### ISSUE THREAD

**Issue by rpmady** [rvlenth/emmeans#88]
I am running the code 
`emm.c <- contrast(emm.s, list("hotspot-pulsed_food" = c(0,-1,1,0)), adjust="tukey")  
`
And the output does not indicate any adjustments have been made 

```
# contrast            estimate    SE df t.ratio p.value
# hotspot-pulsed_food    0.478 0.174 54 2.746   0.0082 
# 
# Results are averaged over the levels of: snow_cover 
# Results are given on the log (not the response) scale. 
```

**Comment by rvlenth** [comment]
I ought to add this to the FAQs vignette. You have only *one* test. There is no multiple-testing issue, hence no multiplicity adjustment.

**Comment by rpmady** [comment]
Even though this is one test, because this is a second test being run after running the model I thought I would need to adjust the p-value.
