### ISSUE TITLE
Large estimated means CIs  but significant contrasts

### ISSUE THREAD

**Issue by DominiqueMakowski** [rvlenth/emmeans#93]
Dear Russell, 

I am confronted to what seems to be a discrepancy between the estimated means and contrasts. I have fitted a Bayesian linear mixed model, and while the estimated means have very large CIs, the contrasts CIs are much smaller (looks like almost significant differences). 

Here's the [data.txt](https://github.com/rvlenth/emmeans/files/2919786/data.txt).

```r
data <- read.csv("data.txt")
model <- stan_lmer(y ~ x + (1|random), data=data)

model %>%
    emmeans::emmeans("x") 

 x  emmean lower.HPD upper.HPD
 R1     88        78       100
 R2     88        78       100
 C1     88        77       100
 C2     88        77        99
 I      88        76        98


model %>%
    emmeans::emmeans("x") %>%
    emmeans::contrast(method = "pairwise") 

 contrast estimate lower.HPD upper.HPD
 R1 - R2     -0.71     -1.42      0.03
 R1 - C1     -0.30     -0.98      0.45
 R1 - C2     -0.35     -1.05      0.39
 R1 - I       0.15     -0.57      0.89
 R2 - C1      0.42     -0.29      1.12
 R2 - C2      0.36     -0.34      1.08
 R2 - I       0.86      0.12      1.58
 C1 - C2     -0.06     -0.78      0.65
 C1 - I       0.44     -0.28      1.16
 C2 - I       0.50     -0.23      1.18


```

![image](https://user-images.githubusercontent.com/8875533/53645084-143da280-3c73-11e9-86e1-50228f767f6a.png)
I wonder if this could be related to  [re.form](https://www.rdocumentation.org/packages/lme4/versions/1.1-20/topics/predict.merMod) argument from the predict's functions for mixed models, or with the distinction between `rstanarm::posterior_linpred()` and `rstanarm::posterior_predict()`?

Anyway, is this difference of perspective expected and normal? Or is there something I can adjust in order to have more coherent estimated means and contrasts? Thanks a lot!

**Comment by rvlenth** [comment]
This, I believe, is normal, in that it is what typically happens when the means are positively correlated -- as they are, for example, when there are notable subject variations and you are looking at the levels of a within-subjects factor. The relevant theory is the formula Var(X - Y) = Var(X) + Var(Y) - 2Cov(X,Y). The larger the Cov(X,Y) (in a positive direction), the smaller the variance of the difference.

A related comment: Don't ever use overlapping CIs for means as a device for comparing them. The SEs of the means are not the same as the SEs of the differences between the means!

**Comment by DominiqueMakowski** [comment]
Thanks a lot, this is much clearer! Within this context, is there a better way of visualizing the differences between the means (i.e., the contrasts, instead of plotting the estimated means and *their* CIs)?

**Comment by rvlenth** [comment]
Somehow I thought you might ask that. 

  1. The way SAS does it is to plot each pair of means in a 2D plot, along with the identity line and CIs (scaled by sqrt(1/2)) for the differences of the means going perpendicular to the identity line, centered at each point. A difference is statistically significant if the interval does not cross the identity line. I programmed that up, but I find it very hard to label the plot effectively and don't care much for it.
  2. You can try `emmeans::plot(emm, comparisons = TRUE)` where `emm` is the result of an `emmeans()` call. This adds red arrows to the plot which indicate significant differences when the arrows don't overlap. This uses an *ad hoc* algorithm, and it is not guaranteed to be possible, especially when the SEs of the differences vary widely. Feedback from users has not been all that enthusiastic, and I'm not sure I like it so much either, but to me, when it works, it's better than the SAS approach.
  3. If you do `emmeans::CLD(emm)`, it adds a column to the summary of `emm` showing a compact letter display. Two means that share the same letter are significantly different. This works, but it is very black-and-white: with alpha = .05, *P* values slightly above or below .05 make a difference, but there's no difference between a *P* value of .051 and one of .987, or between .049 and .00001

**Comment by DominiqueMakowski** [comment]
Thanks a lot!
