### ISSUE TITLE
Possible Conflict With Variable Name (Emmeans Function)

### ISSUE THREAD

**Issue by rstockerstat** [rvlenth/emmeans#94]
Hi,

While using a one-way ANOVA model, I came across a possible naming convention conflict when working with the emmeans function.  Below is an example that analyzes a small fictional data set.  When I use the variable method as the predictor, emmeans returns an error: _match.arg(method)_.  When I use the variable new as the predictor, there is no error.  There is no difference between these variables except for their names.  The name method appears to cause an issue, but I am not 100% sure why.  Is it  possible that there is a conflict with another function in R that is named method?

``` r
library(tidyverse)
test<-tibble(method=factor(c(1,1,1,2,2,2)),new=factor(c(1,1,1,2,2,2)),response=c(5,6,8,4,2,9))
test
#> # A tibble: 6 x 3
#>   method new   response
#>   <fct>  <fct>    <dbl>
#> 1 1      1            5
#> 2 1      1            6
#> 3 1      1            8
#> 4 2      2            4
#> 5 2      2            2
#> 6 2      2            9
str(test)
#> Classes 'tbl_df', 'tbl' and 'data.frame':    6 obs. of  3 variables:
#>  $ method  : Factor w/ 2 levels "1","2": 1 1 1 2 2 2
#>  $ new     : Factor w/ 2 levels "1","2": 1 1 1 2 2 2
#>  $ response: num  5 6 8 4 2 9
test.lm1<-lm(response~method,data=test)
test.lm2<-lm(response~new,data=test)
library(emmeans)
emmeans(test.lm1,~method)
#> Error in match.arg(method): 'arg' must be NULL or a character vector
emmeans(test.lm2,~new)
#>  new emmean  SE df lower.CL upper.CL
#>  1     6.33 1.6  4    1.895    10.77
#>  2     5.00 1.6  4    0.562     9.44
#> 
#> Confidence level used: 0.95
```

<sup>Created on 2019-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by rvlenth** [comment]
Hmmm. That is bizarre, and I was able to replicate it with another example as well:
```
> library(emmeans)
> fib = transform(fiber, method = machine)
> fib.lm1 = lm(strength ~ method + diameter, data = fib)
> fib.lm2 = lm(strength ~ machine + diameter, data = fib)
> emmeans(fib.lm1, ~ method)
Error in match.arg(method) : 'arg' must be NULL or a character vector
> emmeans(fib.lm2, ~ machine)
 machine emmean    SE df lower.CL upper.CL
 A         40.4 0.724 11     38.8     42.0
 B         41.4 0.744 11     39.8     43.1
 C         38.8 0.788 11     37.1     40.5

Confidence level used: 0.95 
```
This is a subtle one. I traced it to a line of code in `emmeans()`:
``` 
    RG = ref_grid(object)
    # ...
    # Ensure object is in standard order
    ord = do.call(order, RG@grid[rev(names(RG@levels))])
```
It turns out that `method` is an optional argument in `order()`, and so if `method` is also the name of a variable to be ordered, it messes up. 

I revised the code so it removes the variable names before passing it to `order()`, and now it works. The update has been pushed up. Thanks for reporting this!

Having just 2 days ago sent a new update to CRAN, I am reluctant to send this fix in right away, as it's not an urgent bug and CRAN resists updating more often than monthly.

**Comment by rvlenth** [comment]
PS -- I now see a warning about this very issue in the help page for `order()`, where they suggest using the `unname()` function -- something I hadn't known existed. So I have actually revised my code again (eventually to be pushed up).

**Comment by rstockerstat** [comment]
Thank you for looking into this issue.  The emmeans package is great and I appreciate all of the hard work that you have put into its creation and upkeep.

**Comment by rvlenth** [comment]
Your error report has been very valuable. It has led me to fix a few other instances of `do.call(order,...)`, as well as many more of `do.call(paste, ...)`, in which having a variable named `sep` or `collapse` can really wreak havoc!
