### ISSUE TITLE
Average Over Multiple Levels

### ISSUE THREAD

**Issue by ghowoo** [rvlenth/emmeans#95]
First of all very thanks for this great package and it helps a lot in presenting predicted means. 

I am just not quite sure if I fully understand some specifications over how to get an predicted mean over a multi-level group and also perform a contrast (comparison) among multie-level averaged means.

Here is the example:
warp.lm <- lm(breaks ~ wool + tension, data = warpbreaks)
warp.emmGrid <- emmeans(warp.lm, ~ tension + wool)
LS1 <- emmeans(warp.lm, specs="wool",at = list(tension=c("L"),wool=c("A")))
LS2 <- emmeans(warp.lm, specs="wool",at = list(tension=c("M","H"),wool=c("A")))
LS2
 _wool emmean  SE df lower.CL upper.CL
 A      26.9 2.5 50     21.9     31.9

Results are averaged over the levels of: tension 
Confidence level used: 0.95_

I assume LS2 is the average over "M" and "H" on tension. However, the printed output doesn't show that.

My question is that is it possible that I could perform a contrast over the two objects, such as:

contrast(LS1,LS2)

Thanks,

**Comment by rvlenth** [comment]
Am I correct in guessing that you want the comparisons M - L and H - L for the levels of `wool`? Just do this:

```
emm = emmeans(warp.lm, "tension")
contrast(emm, "trt.vs.ctrl", ref = "L")

# contrast estimate   SE df t.ratio p.value
# M - L       -10.0 3.87 50 -2.582  0.0246 
# H - L       -14.7 3.87 50 -3.802  0.0008 
#
# Results are averaged over the levels of: wool 
# P value adjustment: dunnettx method for 2 tests
```
If you want these for a specific wool, use `at` in the call for `emm` above. However, since this is an additive model (no interaction), the comparisons at specific levels of wool are exactly the same as the overall ones:
```
> emmA = emmeans(warp.lm, "tension", at = list(wool = "A"))
> contrast(emmA, "trt.vs.ctrl", ref = "L")
 contrast estimate   SE df t.ratio p.value
 M - L       -10.0 3.87 50 -2.582  0.0246 
 H - L       -14.7 3.87 50 -3.802  0.0008 

P value adjustment: dunnettx method for 2 tests
```

**Comment by ghowoo** [comment]
Thanks a lot for explanation. It has really clarified my confusion about the syntax. I think the following code is close to what I wanted.

_> contrast(emmA, "del.eff")
 contrast estimate   SE df t.ratio p.value
 L effect    12.36 3.35 50  3.686  0.0017 
 M effect    -2.64 3.35 50 -0.787  0.4351 
 H effect    -9.72 3.35 50 -2.899  0.0083 

P value adjustment: fdr method for 3 tests_ 

However, from my reading on the help file, the "L effect" is the predicted mean of L - (M + H)/2. It would make more sense if we can get the predicted mean of L- weighted(M+H) based on the actual proportion of M and H on the data. Hopefully I have explained my intention clearly. Thanks.

**Comment by rvlenth** [comment]
I question that is what you want. However, if it is, it is possible via specifying your own contrast coefficients. See the examples at the end of the help page for `contrast` ( `? contrast`).

I think it is more likely you want each mean minus the weighted average of all three means --- that is, the difference of each mean from the grand mean. I experimented with a small example and here's a way to do that:
```
> junk = data.frame(trt = factor(c(rep("A",2), rep("B",5), rep("C", 3))),
+     y = c(3,5,  7,8,6,7,7,   11,9,10))

> junk.lm = lm(y ~ trt, data=junk)

> (emm = emmeans(junk.lm, "trt"))
 trt emmean    SE df lower.CL upper.CL
 A        4 0.655  7     2.45     5.55
 B        7 0.414  7     6.02     7.98
 C       10 0.535  7     8.74    11.26

Confidence level used: 0.95 
```
Now get the weighted mean:
```
> (emm1 = emmeans(emm, "1", weights = "prop"))
 1       emmean    SE df lower.CL upper.CL
 overall    7.3 0.293  7     6.61     7.99

Results are averaged over the levels of: trt 
Confidence level used: 0.95 
```
Now, the `+` operator (or the `rbind()` function) puts these results in one set:
```
> emm1+emm
 1       trt emmean    SE df lower.CL upper.CL
 overall .      7.3 0.293  7     6.32     8.28
 .       A      4.0 0.655  7     1.82     6.18
 .       B      7.0 0.414  7     5.62     8.38
 .       C     10.0 0.535  7     8.22    11.78

Results are averaged over some or all of the levels of: trt 
Confidence level used: 0.95 
Conf-level adjustment: bonferroni method for 4 estimates 
```
... so do contrasts comparing the first of these with the others:
```
> contrast(emm1+emm, "trt.vs.ctrl1", adjust = "none")
 contrast        estimate    SE df t.ratio p.value
 .,A - overall,.     -3.3 0.586  7 -5.636  0.0008 
 .,B - overall,.     -0.3 0.293  7 -1.025  0.3396 
 .,C - overall,.      2.7 0.447  7  6.037  0.0005 

Results are averaged over some or all of the levels of: trt
```
The labeling is kinda weird, but it does indeed compare each mean with the grand mean.

**Comment by rvlenth** [comment]
I haven't heard from you whether this is useful or not.

Anyway, in the latest commit I include enhancements that make it fairly easy to get nicer output in this example:
```
> tmp = update(emm1 + emm, levels = list(case = c("GM", "A", "B", "C")))

> contrast(tmp, "trt.vs.ctrl1", adjust = "fdr")
 contrast estimate    SE df t.ratio p.value
 A - GM       -3.3 0.586  7 -5.636  0.0012 
 B - GM       -0.3 0.293  7 -1.025  0.3396 
 C - GM        2.7 0.447  7  6.037  0.0012 

P value adjustment: fdr method for 3 tests
```

**Comment by ghowoo** [comment]
Thanks for extra demonstration. I think I have solved the problem. Here is my solution to get the weighted mean of two categories. Thanks again for you excellent work.

> ## a dummy dataset with one outcome (y), and one trt and one covariate
> junk = data.frame(
+   trt = factor(c(rep("A",2), rep("B",5), rep("C", 3)))
+   ,age = 1:10
+   ,y = c(3,5,  7,8,6,7,7,   11,9,10))
> 
> junk.lm = lm(y ~ trt + age, data=junk)
> 
> ## weighted mean of B + C
> emmeans(junk.lm, "1", weights = c(0,5/8,3/8))
 1       emmean   SE df lower.CL upper.CL
 overall   8.21 0.45  6      7.1     9.31

Results are averaged over the levels of: trt 
Confidence level used: 0.95 
> 
> ## get design matrix
> dm <- model.matrix(junk.lm)
> 
> ## weighted design matrix of "B"
> dmB <- dm
> dmB[,2] <- 1
> dmB[,3] <- 0
> dmB <- dmB*(5/8)
> 
> ## weighted design matrix of "C"
> dmC <- dm
> dmC[,2] <- 0
> dmC[,3] <- 1
> dmC <- dmC*(3/8)
> 
> ## weighted mean of B+C
> (mean((dmB + dmC) %*% coef(junk.lm)))
[1] 8.205
> ## se of the weighted mean
> sqrt(sum((dmB + dmC) %*% vcov(junk.lm) %*% t(dmB + dmC)))/10
[1] 0.4497407
