### ISSUE TITLE
Question: covariance estimate

### ISSUE THREAD

**Issue by shathab** [rvlenth/emmeans#97]
After fitting a model for data from a longitudinal study using geeglm() from the "geepack", I am trying to identify which groups are different by using emmeans pairwise comparison. According to the reference page for models used by emmeans, covariance estimates can be specified from geeglm using "vcov.method". There are two options “robust” and “naive”, the default is “robust” and changing to “naive”  seems to show more statical significant results I am not sure what does that mean or which one would be appropriate to use to identify group differences. 

Below is my example code:
```
gee_result <- geeglm(response~factor(Day)*Group, 
         id=Subject,family=gaussian("identity"),corstr="ar1",data = data)
     summary( gee_result)
     anova(gee_result)
     emmeans( gee_result,pairwise~Group|factor(Day),adjust="fdr",vcov.method ="naive")
     emmeans( gee_result,pairwise~Group|factor(Day),adjust="fdr",vcov.method ="robust") 
```
Thank you in advance for your help!

**Comment by rvlenth** [comment]
Note - I edited your question with the code reformatted so I could read it more easily.. For some reason, much of it was previously formatted as being struck out.

My understanding is that `"naive"` is very sensitive to model misspecification, whereas `"robust"` is the sandwich estimator and it is more reliable in general. I suggest you use the `"robust"` results.

**Comment by shathab** [comment]
Great! thank you so much for your help.
